### ISSUE TITLE
Testament megatest fails with Nim not found

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#10049]
```
C:\nim-devel2\testament\tester.exe c megatest
joinable specs: 458
tester.nim(591)          tester
tester.nim(559)          main
categories.nim(644)      processCategory
categories.nim(562)      runJoinedTest
tester.nim(88)           execCmdEx2
osproc.nim(586)          startProcess
oserr.nim(67)            raiseOSError
Error: unhandled exception: The system cannot find the file specified.
Additional info: "Requested command not found: \'nim\'. OS error:" [OSError]
```
Both `nim` and `nim_temp` are available in `C:\nim-devel2\bin` location.

Also `koch tests c megatest` successfully builds Nim, but it is not used by megatest

**Comment by timotheecour** [comment]
could be solved by using the new getCurrentCompilerExe, which doesnt require any PATH

**Comment by Araq** [comment]
Do not use getCurrentCompilerExe, nobody wants binaries that are machine specific!

**Comment by cooldome** [comment]
In the path I usually have release or stable version of Nim, this version of nim does not require further testing.
IMO, it is the right answer:
```
--nim:path                use a particular nim executable (default: compiler/nim)
```

**Comment by timotheecour** [comment]
so the code we have (that relies on PATH) is wrong:
`var (buf, exitCode) = execCmdEx2(command = "nim", args = args, options = {poStdErrToStdOut, poUsePath}, input = "")`
as it's inconsistent with other tests and should be fixed so that the logic used for specifying which nim compiler is used should be same for megatest as for other tests.

so a potential fix:
* add a **single** proc `findTestingNimExe()` (used everywhere relevant in testament) that:
  * uses --nim:path if specified
  * else, use `compiler/nim` 

## note
`compiler/nim` is build when you run `./koch tests` :
```nim
proc tests(args: string) =
  nimexec "cc --opt:speed testament/tester"
  # Since tests take a long time (on my machine), and we want to defy Murhpys
  # law - lets make sure the compiler really is freshly compiled!
  nimexec "c --lib:lib -d:release --opt:speed compiler/nim.nim"
  let tester = quoteShell(getCurrentDir() / "testament/tester".exe)
  let success = tryExec tester & " " & (args|"all")
  if not existsEnv("TRAVIS") and not existsEnv("APPVEYOR"):
    exec tester & " html"
  if not success:
    quit("tests failed", QuitFailure)
```

/cc @Araq
