### ISSUE TITLE
Weighted sampling from openarray - comments

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#10081]
cc @dom96 @c-blake 

### Comments on the PR

Unfortunately I couldn't have a look into the PR before it was merged. So adding my comments here instead.

`proc sample*[T, U](r: var Rand; a: openArray[T], w: openArray[U], n=1): seq[T] =`

We should use descriptive inputs instead of one letter inputs:

 `proc sample*[T, U](rng: var Rand; a: openArray[T], weights: openArray[U], num_samples=1): seq[T] =`

### Sidenotes - sampling without replacement

I'm currently studying the fastest implementation of sampling without replacement as it's a bottleneck for natural language processing and reinforcement learning and have found great potential in F+Tree ([Fenwick Trees](url) adapted to Cumulative Probability Distribution Function)
  - Link to [my research notes](https://github.com/numforge/laser/blob/553497e1193725522ab7a5540ed824509424992f/research/random_sampling_optimisation_resources.md)
  - Link to [bench](https://github.com/numforge/laser/blob/553497e1193725522ab7a5540ed824509424992f/benchmarks/random_sampling/bench_multinomial_samplers.nim#L311-L375)

```
Classic sampling via inverse CDF
Collected 1000 test samples in 9.044 seconds
Average time: 9.044 ms
Stddev  time: 1.162 ms
Min     time: 8.198 ms
Max     time: 35.947 ms
Perf:         14.154 millions samplings/s (VocabSize = 50000)

Display output[0] to make sure it's not optimized away
2

10 samplings without replacement
Collected 1000 test samples in 156.663 seconds
Average time: 156.663 ms
Stddev  time: 26.336 ms
Min     time: 147.814 ms
Max     time: 672.546 ms
Perf:         0.817 millions samplings/s (VocabSize = 50000)

Display output[0] to make sure it's not optimized away
[12913, 8020, 41233, 19747, 46496, 18194, 40084, 34881, 42615, 9536]

# Skipping a version with prefetch that is 0.5% faster (consistently)
Sampling via F+tree without prefetch
Collected 1000 test samples in 13.549 seconds
Average time: 13.548 ms
Stddev  time: 0.742 ms
Min     time: 12.792 ms
Max     time: 25.680 ms
Perf:         9.448 millions samplings/s (VocabSize = 50000)

Display output[0] to make sure it's not optimized away
39064

10 samplings without replacement without prefetch
Collected 1000 test samples in 13.680 seconds
Average time: 13.680 ms
Stddev  time: 0.583 ms
Min     time: 13.003 ms
Max     time: 22.149 ms
Perf:         9.357 millions samplings/s (VocabSize = 50000)

Display output[0] to make sure it's not optimized away
[47509, 3677, 45871, 43620, 47576, 46527, 9768, 19118, 25929, 40719]
```

 - Link to [F+tree](https://github.com/numforge/laser/blob/553497e1193725522ab7a5540ed824509424992f/benchmarks/random_sampling/fenwicktree.nim) implementation

I still have to benchmark a weighted reservoir sampling implementation though.

**Comment by c-blake** [comment]
Well, `weights` is fine.  I would say `sampleSize` is better than `num_samples`, though, being both more descriptive and style-compliant.  If @dom96 wants to just change that I say go for it.

If people want many samples against a static distribution to be more efficient, we could take a flag `alreadySummed=false` (or `weightsAreCDF=false`? ) to "if out" the sum.  Then just use `cdf[^1]` instead of `tot` in the `r.rand()` call.  Maybe best still we could change the API to instead always take the discrete CDF and provide a convenience cumsum type proc, if there isn't one already.  (And, yes, I know about parallel prefix sum with SSE/AVX and have impls of those myself..but this is just the stdlib.  People with hyper-optimized summation needs probably want Arraymancer anyway).  I can do another PR with the PDF->CDF summing lifted out and renames done, if @dom96 would like.

If you have a dynamic distribution and dynamic sampling then, yeah, a Binary-Indexed Sum Tree/Fenwick tree is the best, at least as long as you don't need too many bits.  I actually already have an impl of such with all the quantile procs and even Parzen quantile interpolation all in like 100 lines of code, and yeah, they are fast - like 30-50 cpu cycles/operation when things fit in L1.  When the number of bins starts blowing out the L3 cache, a B-Tree starts to be faster for a lot of things.

Some more advanced dynamic distro mode may make more sense outside the stdlib, though, or at least it warrants its own whole module (or even two, a `bist.nim` and `btree.nim`).  That's all a really large discussion about dynamic order statistics, though, which is all a lot more involved.  We should probably confine this issue to be about the vastly simpler static distribution case just added.

**Comment by c-blake** [comment]
Oh, and just to connect @mratsim's "without replacement" to my "dynamic order statistics" terminology, sampling without replacement is basically equivalent to querying the inverse CDF aka quantile and then decrementing the histogram count for each sampled point as you go (repeat, rinse).  By _not_ decrementing you "replace" the value.  Meanwhile, dynamic/moving order statistics (such as a median or 90th percentile over a moving window over some data) decrement one value, add another value, and then query the inverse CDF/quantile...just like the moving average, but with an order statistic like median instead.  Both problems are similarly optimized and fundamentally about rank queries on an ordered set which is dynamically updated.  You really need an insert/add for both, but sampling adds all up front while the moving order stats case "adds as it goes".  Personally, I think sampling without replacement is special enough to deserve its own API name like `select`, `randSelect`, or `randSubset` sort of thing.  Anyway, this is all far afield of the basic naming complaint of this issue.

**Comment by c-blake** [comment]
If one did do the "CDF as a parameter" change, then this function reduces to:
```Nim
for i in 0 ..< sampleSize:
  result.add(a[cdf.upperBound(r.rand(float(cdf[^1])))])
```
where then it might even make sense to not do the loop/pass `sampleSize` at all, in which case it is just `cdf.upperBound(r.rand(float(cdf[^1])))` with a user-maintained indexing convention between `a` and its `cdf`.  At that point, we aren't really saving users much effort with the proc at all.  I guess we save looking up `algorithm.upperBound` and testing that the distribution works as expected.  That is some savings, though, and maybe closer in spirit to the other procs in the random module.  I had figured the entry point for most would be a measured histogram of some kind.  Thoughts?

**Comment by c-blake** [comment]
Edit: of course, I meant `a[]` in there, too.  Maybe `sample` should become just this with a  hand-holding `cdf=weight.cumsum; sample(a,cdf)` doc comment?
```Nim
a[cdf.upperBound(r.rand(float(cdf[^1])))]
```
I can't find a `cumsum` in the stdlib.  Adding that is also probably warranted if we simplify `sample` as mentioned.  Then if somone wants to vectorize optimize it someday there is an entry point already in place.  I've seen a lot of names for `cumsum`, `cum`, `prefixSum`, etc., but `cumsum` seems the most common (Matlab, NumPy, R, Arraymancer, etc.).
