### ISSUE TITLE
`nkStmtListExpr` with typ == nil for default parameter

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#10204]
when compiling the following snippet:
```
proc f3(a: int, b = a, c = a + b) =
  echo "f3 ", a, " ", b, " ", c

10.f3()
```

the stmtlistexpr for `a+b` has `typ==nil`

d50336837dfa1a3b81c1b5338b5a9b5d41cf6221

**Comment by krux02** [comment]
Well this seems to be related to my current work here: https://github.com/nim-lang/Nim/pull/10061.
The tests are failing in this test case:

https://github.com/nim-lang/Nim/blob/8e600b78ca965117a053751f38ccaffa3e16780a/tests/generics/tlateboundgenericparams.nim#L115

Well it is good to know that it seems like I did not introduce that bug, but that bug was already there. My changes made that bug just cause problems in the test cases.

**Comment by krux02** [comment]
I probably have a fix for this in my current work mentioned above.

**Comment by ringabout** [comment]
```nim
proc f3(a: int, b = a, c = a + b) =
  echo "f3 ", a, " ", b, " ", c

10.f3()
```
This compiles and gives:
```
f3 10 10 20
```

It seems to be never introduced in stable version of Nim. I have tried from 0.19.0, 0.19.2, 1.0.0, 1.2.6 and 1.4.0.
