### ISSUE TITLE
undeclared identifier: '=-'

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#10297]
I am using
```
Nim Compiler Version 0.19.9 [Windows: amd64]
Compiled at 2018-12-13
Copyright (c) 2006-2018 by Andreas Rumpf
```

for code
```nim
proc f(a:int=1) =
    echo a

f()

f(2)
```
it can compile and run

but when I try to compile
```nim
proc f(a:int=-1) =
    echo a

f()

f(2)
```
I get `b.nim(1, 13) Error: undeclared identifier: '=-'`

I know it can work by rewriting to 
```nim
proc f(a:int = -1) =
    echo a

f()

f(2)
```

but is it inconsistent  ?

**Comment by krux02** [comment]
well, this doesn't compile as well: `let a:int=-1`. So I don't see where it is inconsistent. Since `f(a:int=-1)` wouldn't be very readable for my eyes in the first place, I actually like that the compiler rejects the non spaced version. Since this might a more common beginners mistage it might be worth though to discuss if that error messages should emit a hint like this: ``did you mean `a:int = -1`? A space is required for it.``

**Comment by Araq** [comment]
@krux02 We have special casing in the error message for other contexts.

**Comment by GULPF** [comment]
As a curiosity, it can be noted that this compiles:
```nim
template `=-`(T: type, _: int): untyped = int

proc f(a:int=-1) =
  discard
```
So improving the error message is not as simple as special casing it in the parser.

**Comment by Araq** [comment]
Sure, it has to be done in the semantic checking, no big deal.
