### ISSUE TITLE
Discardable causes issue in try finally.

### ISSUE THREAD

**Issue by solo989** [nim-lang/Nim#10440]
If the last statement in a try is discardable and it's followed by a finally an error is raised.

### Example

```nim
proc x() : int {.discardable.} = discard

try:
  x()
finally:
  echo "hi"
```

### Current Output
```
test.nim(9, 8) Error: expression 'echo ["hi"]' is of type 'int' and has to be di
scarded; start of expression here: test.nim(5, 0)
```

### This works.

```nim
try:
  x()
  discard
finally:
  echo "hi"
```

### and so does this.
```nim
try:
  x()
except:
  discard
finally:
  echo "hi"
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.2 [Windows: amd64]
```

**Comment by LemonBoy** [comment]
You have to use an explicit `discard` here otherwise the compiler is not sure about what you want to do since a `try` statement may return a value.
I do agree that the error message is (pardon my french) utter shite though.

**Comment by Araq** [comment]
I hate ``discardable``, it's stupid.

**Comment by Yardanico** [comment]
Yes, it's not really needed most of the time, but it can be useful when wrapping C/C++ libraries (because you can discard results in C/C++) or making your code more DRY (because otherwise you'll have to create two procedures where one of them will be used in case you don't need the result, and other one when you need the result).

**Comment by timotheecour** [comment]
> I hate discardable, it's stupid.

it's also overused. It might explain https://github.com/nim-lang/Nim/issues/10309

**Comment by Clyybber** [comment]
The error message is still bogus :)
