### ISSUE TITLE
Add weighted sampling procedure(s) to the `random` library

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#10740]
Proposed procedure:
```nim
proc sampleWeighted*[T, W](xs: openarray[tuple[item: T, weight: W]]): T =
  var max: W
  for x in xs: max += x.weight

  var target = rand 1.W .. max
  for x in xs:
    if target <= x.weight: return x.item
    target -= x.weight
```

**Comment by krux02** [comment]
I am sorry but I am against it. Please don't take it personal, but we are currently already 100% busy to maintain the libraries that do exist, submitting a library is great for you, but it makes us responsible to fix potential bugs in it that might have? For example are you 100% sure that it will always return? Are you 100% sure that there is no 0.00000000000001% chance that won't return an element of the input array at all because of floating point inaccuracies?

**Comment by dawkot** [comment]
The code is just an example. My main point is that weighted sampling in a standard library would be nice to have, and I didn't think that maintaining it would be much of a deal.

**Comment by Clyybber** [comment]
I don't think this procedure is a good fit for the standard library, as there are too many different ways to store a weight in elements of an array.
I for example am using a weigthed sample procedure in my code, but I store the weights in the objects/elements itself, instead of a tuple, which means I wouldn't be able to use the proposed procedure anyways.

**Comment by mratsim** [comment]
I disagree weighted random sampling is very useful but the API should be 
 arrays of values + probabilities not an array of tuples to match classic API.

In any case, this is already implemented (with a proper API):

https://github.com/nim-lang/Nim/blob/ca4b971bc81b2e751e0388d80896fde7079b1679/lib/pure/random.nim#L442-L505.

Note that this deserves a full library as depending on the situation the random sampling via cdf (cumulative distribution function) in the standard library will not be suitable for example if we want a streaming sampler or if we have constant additions and update or without replacement sampling.

See my research on [weighted random sampling](https://github.com/numforge/laser/blob/master/research/random_sampling_optimisation_resources.md) and also an [alternative implementation using a tree datastructure for online sampling without replacement.](https://github.com/numforge/laser/blob/0cb91fc2e9cb0d10f23c2fbb64aca54c160a2cc0/benchmarks/random_sampling/fenwicktree.nim)
