### ISSUE TITLE
nim grammar changes for no good reason

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#10881]
this is the PR that got merged recently: https://github.com/nim-lang/Nim/pull/10852 it should be reverted. 

The biggest problem is, it simply changes the grammer of Nim.

A bunch of other problems

 * The grammar changes are not reflected in editors for nim.
 * The new grammar is inconsistent with existing grammar rules in Nim, as it doesn't use a colon to introduce the block for the stmtListExpr
 * The new grammar was not properly reviewed if it could cause any problems.
 * The only reason for grammar change was, that the repr of a stmtListExpr created an AST that wasn't parsable by nim. That is a bad reason, because it could simply been fixed by fixing ``repr``.

Whenever the grammer changes, this needs to be discussed for a long time so that people have time to see and respond to it. To make sure that the changes are welcome to the people who use the grammer. I don't like how quickly it got merged into Nim.

```nim
if expr:
  var a = 123
  a += 3
  a

while expr:
  var ...

echo:
  var a = 123
  a += 123
  a

yield  # surprise no colon
  var a = 123
  a += 123
  a  
```

**Comment by cooldome** [comment]
Could you please mention real issues with a change except that it was not discussed with you. There are no known regressions, please mention one. 
I disagree with the fact that grammar has changed that much. Support for stmtListExpr was added to Nim long time ago with templates. stmtListExpr is supported by all parts and stages of Nim compiler, except one  till now: parser. I personally find it weird that support for stmListExpr in parser was absent that long given that everything else supports it. It also explains why change was so simple to implement and review.

I suggest extend stmtListExpr support further. IMO, it makes sense to support it after every keyword that doesn't require semicolon.

**Comment by Araq** [comment]
You both have good arguments, I'm torn. What if we introduce:

```nim

yield:
  var a = 123
  a += 123
  a  
```

**Comment by krux02** [comment]
It is not about the fact that stmtListExpr is supported now. I totally agree that it should be supported. But I don't like how it was introduced. And I don't like the result of it.

**Comment by mratsim** [comment]
Agree I would prefer the colon for consistency.

**Comment by jkaye2012** [comment]
Also agree with this. I was surprised to get bitten by something like this yesterday.

**Comment by ryukoposting** [comment]
I agree with @krux02. Consistency and stability need to be a top priority if a strong ecosystem is to develop around Nim. Not all package maintainers are going to be able to adapt their entire codebase to language-breaking changes on every single release (myself included).

Even small changes of this sort tend to pile up into a monster of a problem- there's a whole lot of mysteriously-broken packages in nimble.directory, and even on the official Nim GitHub.

**Comment by mratsim** [comment]
To be clear it's not a breaking change, it does not change what worked before but it enables new things that worked before.

**Comment by andreaferretti** [comment]
It still breaks editor parsers

**Comment by ryukoposting** [comment]
> To be clear it's not a breaking change, it does not change what worked before but it enables new things that didn't work before.

Ah, alright. Apologies for my misunderstanding (I'll save that rant for another time!). 

I think part of this issue is just a broader inconsistency in Nim. These are valid code snippets as of 0.19.4:
```Nim
return
  if someBool:
    1
  else:
    2
```

```Nim
yield
  if someBool:
    1
  else:
    2
```
`return` and `yield` here both contain a single expression, and do not require a colon. all the `if` and `else` blocks only contain a single expression as well, but still require a colon. So, if we're looking at it this way, there's already an inconsistency in the grammar, ignoring the proposed addition. Allowing for multi-statement yields/returns without a colon would just be exacerbating that.

There are a few ways to fix this inconsistency without breaking existing code. One solution would be to allow for single-expression if/else bodies without a colon. In other words, this hot mess becomes valid Nim code, probably breaking command-like procedure call syntax:
```Nim
yield if someBool 1 else 2
```
Alternatively, multi-statement return/yield blocks without a colon just wouldn't be allowed. This would align @Araq 's example. It would be more consistent with the rest of the language (excluding let/var blocks, but those have a special purpose and they don't return values).

Or, just leave the language as-is. There are plenty of ways to return a value in Nim, and they already overlap a good bit. There isn't an immediately obvious situation where yet another form of return semantics is going to be useful. These are already valid and logically equivalent:
```Nim
proc foo(x, y, z: int, ns: seq[int]): int =
  let k = x + y
  if gcd(x, y) == 3:
    result = x
    for n in ns:
      result += n
  elif k > y:
    result = z div k
  elif x > y:
    result = x
  else:
    result = y

proc foo2(x, y, z: int, ns: seq[int]): int =
  let k = x + y
  if gcd(x, y) == 3:
    result = x
    for n in ns:
      result += n
  elif k > y:
    z div k
  elif x > y:
    x
  else:
    y

proc foo3(x, y, z: int, ns: seq[int]): int =
  let k = x + y
  if gcd(x, y) == 3:
    result = x
    for n in ns:
      result += n
  else:
    return     # this could also be 'result ='
      if k > y:
        z div k
      elif x > y:
        x
      else:
        y
```
Sure, this is a contrived example, but it has all the parts of a normal procedure (mutable and immutable variables, loops, other procedure calls, etc). Where does a multi-statement `return` (or a multi-statement `yield`, for that matter) fit into the language?
```Nim
proc foo4(x, y, z: int, ns: seq[int]): int =
  let k = x + y
  if gcd(x, y) == 3:
    return:
      # why do this instead of just using the result variable?
      var res = x
      for n in ns:
        res += n
      res
  else:
    return
      if k > y:
        z div k
      elif x > y:
        x
      else:
        y

proc foo5(x, y, z: int, ns: seq[int]): int =
  return:
    # literally just foo2 but less readable
    let k = x + y
    var res = x
    if gcd(x, y) == 3:
      for n in ns:
        res += n
      res
    elif k > y:
      z div k
    elif x > y:
      x
    else:
      y
```
I think multi-statement returns/yields would just be stepping on the toes of existing features. From what I can tell, they wouldn't add enough to the language for their existence to be justified.

**Comment by b3liever** [comment]
Here are some other inconsistencies:
```nim
type
   Point = object # no colon don't act surprised
      x, y: int

let # also no colon
  p = Point()

if # this one is plain weird and could be a bug ?!
   x == y:
      echo x
```

Also to be honest I don't have a strong opinion about this, I think it's a matter of taste.

**Comment by cooldome** [comment]
I am back from vacation, I will start looking at this issue later this week.
Though, discussion may be slowed down by recently introduced regressions.

I suggest broader discussion. Identify all use cases where stmtListExpr should be supported in the parser and what syntax should be. I have identified a couple of related issues as well. I will start gathering examples.

**Comment by Araq** [comment]
I changed my mind on this one and I think it should be reverted. ``renderer.nim`` simply needs to emit ``(;;)`` where required. We cannot support an indentation based syntax for ``nkStmtListExpr`` everywhere so we might as well not change the parser at all.

**Comment by cooldome** [comment]
ok, I will update the renderer and revert the parser
