### ISSUE TITLE
Bug in C++ code generation -- fixed on devel -- need new Nim release

### ISSUE THREAD

**Issue by cdunn2001** [nim-lang/Nim#10898]
I have code which works fine with `nim c` but fails with `nim cpp`.

(This is completely separate from the problem in #10812.)

Two basic issues:

1. It seems that `$T` is only available from `typetraits` with cpp, while with c it's now available from `system`. (Weird, but probably easy to solve.)
2. With cpp, top-level templates seem to create collisions of global variables when re-used. (In other words, they seem to be non-hygienic, we guess.)

### Example
This all comes from using c-blake's **cligen** module.

* https://github.com/c-blake/cligen/issues/92
* https://github.com/c-blake/cligen/issues/94

```nim
import cligen

proc absolutize(positional: seq[string], outdir: string = "", update: bool = fal
  echo "absolutely!"
  return 0

proc filter(positional: seq[string]): int =
  echo "take a picture"
  return 0

echo "good"

when isMainModule:
  cligen.dispatchMulti(
    [absolutize,
      doc="foo",
      help={
        "positional": "infile",
        "update": "Update dataset metadata",
        "outdir": "Specify an optional output directory",
      },
    ],
    [filter,
      doc="foo",
      help={
        "positional": "infile outfile filters [filters ...]",
      },
    ],
  )
```
Everything works with `nim c`, and everything works with single "dispatch". But with `nim cpp` plus "dispatchMulti", which uses the macro 2 or more times, I get errors like below.

### Current Output
```
Error: execution of an external compiler program 'clang++ -c  -w -std=c++11 -I/Users/cdunn2001/repo/gh/pbbam/.git/PREFIX/include -I/usr/local/Cellar/htslib/1.9/include -I/usr/local/Cellar/xz/5.2.4/include   -I/Users/cdunn2001/repo/gh/Nim/lib -o /Users/cdunn2001/.cache/nim/dataset_d/top_dataset.cpp.o /Users/cdunn2001/.cache/nim/dataset_d/top_dataset.cpp' failed with exit code: 1

/Users/cdunn2001/repo/gh/Nim/lib/system/gc_common.nim:358:37: error: redefinition of 'pairs_V9csNKH9cGNJ1NFy9aftrGJlg'
tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
                                    ^
/Users/cdunn2001/repo/gh/Nim/lib/system/gc_common.nim:355:37: note: previous definition is here
tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
                                    ^
```
```
/Users/cdunn2001/.cache/nim/dataset_d/top_dataset.cpp:521:37: error: redefinition of 'pairs_V9csNKH9cGNJ1NFy9aftrGJlg'
tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
                                    ^
/Users/cdunn2001/.cache/nim/dataset_d/top_dataset.cpp:518:37: note: previous definition is here
tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
                                    ^
```
```cpp
 518 tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
 519 NI i_9anLbB4VQWiTN1JjnvHUD2g;
 520 tySequence_sM4lkSb7zS6F7OVMvW9cffQ* sugg_ebtbQutaoOj3J1ikmB8D2A_2;
 521 tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
 522 NI i_9anLbB4VQWiTN1JjnvHUD2g;
 523 STRING_LITERAL(TM_822OlwQdrJrSkbCunu8CXA_3, "good", 4);
```

There was also a warning:
```
../../bio-nim/cligen/cligen.nim(728, 7) Hint: global variable declared here [GlobalVar]
    var pairs: seq[seq[string]]
        ^
```
When we put the "pairs" code into a `block:`, that global warning disappears, but we still have the redefinition warning. And we don't think we should need a "block" anyway.

### Expected Output
Everything actually works with `nim c`. And I am not actually using any C++ code code. My code is nothing but 2 procs and the `dispatchMulti` from cligen.

### Possible Solution
I've tried several ideas with c-blake. 0.19.4, 1.19.2, `devel` (which seems to cause a problem for Nimble, so I could not try it). No luck yet.

One thing which might work is putting `dispatchMulti` inside `main()`, instead of top-level. However, we were unable to try that for various reasons (all in the long Issue thread for cligen).

### Additional Information
* Your Nim version:
  * 0.19.2, 0.19.4
* Was it working in the previous Nim releases?
  * I haven't tried earlier than 0.19.2.
* A link to a related issue or discussion.
  * https://github.com/c-blake/cligen/issues/94
  * https://github.com/c-blake/cligen/issues/92

**Comment by cdunn2001** [comment]
```
$ clang++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
```
That's on Mac. Neither problem occurs on Linux with gcc, using nim-0.19.9 (`devel`).

**Comment by pb-cdunn** [comment]
On Linx/gcc/0.19.9, the generated code looks fine:
```cpp
 438 TNimType NTI_cWnRop8dLW6UraogQ8gm8g_;
 439 tySequence_phjbYJtsbOIAYa9be34hhZg* pairs_V9csNKH9cGNJ1NFy9aftrGJlg;
 440 NI i_9anLbB4VQWiTN1JjnvHUD2g;
 441 tySequence_sM4lkSb7zS6F7OVMvW9cffQ* sugg_ebtbQutaoOj3J1ikmB8D2A_2;
 442 STRING_LITERAL(TM_822OlwQdrJrSkbCunu8CXA_3, "good", 4);
```

**Comment by pb-cdunn** [comment]
Ah. Same problem on Linux with nim-0.19.4. So I guess it's fixed on `devel`.

(I had problems with nimble and nim-devel on Mac. I'll keep working on that...)

**Comment by pb-cdunn** [comment]
I did `choosenim '#head`, re-ran, and hit this:
```
./dataset.exe absolutize --help
good
cligen.nim(730)          dataset
fatal.nim(37)            sysFatal
Error: unhandled exception: index 1 not in 0 .. 0 [IndexError]
```
Brand new error! It was working on a previous `0.19.9`.

**Comment by pb-cdunn** [comment]
It worked on b9f8528, but not on current HEAD. (It's hard to learn from `choosenim` which commit was used to build, and because it does not use symlinks, it's hard even to learn exactly how it built what is in `~/.nimble/bin/nim`.)

**Comment by pb-cdunn** [comment]
This is frustrating. The releases do not work. There is some recent commit that works, but HEAD of devel does not work.

Bisecting (and I have to rebuild the compiler each time, so this is not just a bug in library code):

* 1332f64 `(HEAD, origin/devel)` definitely fails ?
* 5c1c590 fails ?
* f1a945b fails ?
* 4181baf works
* 62ab338 works
* 939c151 works (but I had to modify cligen for `$` not in `typetraits`
* 06f2357 works
* b9f8528 works

Oh! The question marks `?` above are because those commits passed when I tried again after fixing cligen. There was churn in **cligen** because araq moved `$` out of `typetraits` and back. In order to fix that, I had to switch to a particular version of **cligen**. It tuns out that the `IndexError` crash happens for the release of **cligen** with `devel` **nim**, but not for more recent commits of either.

That explains my problems on Linux -- which seems to be working now -- but not on Mac.

**Comment by pb-cdunn** [comment]
So on Linux

* nim-0.19.4 fails with both cligen-0.9.19 and cligen-HEAD, both with redefined symbols in C++.
* nim-devel works with cligen-HEAD.

So that's good. But it means we need a new release of Nim for C++.

Now I'll try latest Nim-devel on Mac. (It seems to have big problems with Nimble, so I will build it directly.)

**Comment by pb-cdunn** [comment]
Same on Mac! It's all about the combination of nim and cligen versions.

But the main point is that the latest release of nim (`0.19.4`) is broken for C++ code generation. We need a new release!

**Comment by Araq** [comment]
@pb-cdunn can you please tell me what commit/problem 0.19.6 should solve?

**Comment by pb-cdunn** [comment]
The bug is described in c-blake/cligen#94

It's definitely fixed on `devel`, which also requires a change in **cligen**, but neither are "released". I'm broken with `master` **Nim** plus the released **cligen**.

The reason this is important to me is that Nim is starting to build more slowly. (Or maybe I just have more code now?) I work around that by putting most of my Nim code into a single executable, using sub-commands. (Separately, I'm also trying to see whether `ccache` is still getting cache-hits for nim-generated C code.)
