### ISSUE TITLE
Tuple unpacking in for loops doesnt work in templates

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#11164]
Tuple unpacking in for loops doesnt work in templates

### Example

```nim
iterator tuples: (int, int) = yield (1, 1)

template test =
  for (a, b) in tuples(): discard

test()
```

### Current Output
```
test.nim(4, 7) Error: illformed AST: (a) =
```

### Expected Output
Should compile without errors

### Additional Information
Changing `test` definition to `proc` makes example compile and run.

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-05-02
git hash: 9ad96b58e638c57ef20c22513e29cd17d18874ff
```

**Comment by mratsim** [comment]
Seems like it's not the first illformed AST when using tuples in templates https://github.com/nim-lang/Nim/issues/10854

**Comment by krux02** [comment]
The problem is, normal for looks are check via [`semFor`](https://github.com/nim-lang/Nim/blob/devel/compiler/semstmts.nim#L817), but a for loop in templates is checked with a different code path in [`semTemplBody`](https://github.com/nim-lang/Nim/blob/devel/compiler/semtempl.nim#L370). This code path has not been updated when the feature of to extract tuples via () has been added.
