### ISSUE TITLE
dynlib fails with new-style indirect .so files

### ISSUE THREAD

**Issue by jrfondren** [nim-lang/Nim#11169]
I have no idea what this feature is called, or why Fedora 30 is installing it when dlopen doesn't handle it, or if that's a bug or what, but a simple `nimble install moe; moe` now fails on Fedora 30 with this error (after recompilation with -d:nimDebugDlOpen):

```
/lib64/libncursesw.so: file too short
could not load: libncursesw.so
```

As that file contains this text, rather than .so file contents:

```
INPUT(libncursesw.so.6 -ltinfo)
```

Apparently the intent is that dlopen should fail and then dlopen-using programs should check and see if the file instead has a directive like this, after which such programs should link (in this case) libncursesw.so.6 and whatever -ltinfo resolves to.

Sorry for the low-information issue. I'm hoping that someone else will know more.

### workaround

In this case, "libncursesw.so.6" instead of "libncursesw.so" for the dynlib: parameter.

**Comment by alaviss** [comment]
Those are linker scripts and are meant for linkers such as `ld`. Typically you'd not want to `{.dynlib.}` directly to `.so` files. This is because the memory layout and ABI might change between major versions, and blindly using the latest one might results in memory corruption errors, missing symbols, etc.

While I believe it's possible for one to parse the linker script to get the target library, it'd be a overhead over just loading the library via `dlopen()`, and not to mention on what to do if commands other than `INPUT` are in these scripts.

Of course, you can link to ncurses the way C and almost everyone else do via these flags:

    --dynlibOverride:libncursesw -l:-lncursesw

And forget about `{.dynlib.}` altogether.

**Comment by jrfondren** [comment]
OK, so actually moe['s ncurses-using library] is in the wrong for referring to a ".so" instead of a ".so.X". And I agree with your other points.

I'll close this then.
