### ISSUE TITLE
Backport commit ce9815b from devel to master

### ISSUE THREAD

**Issue by PrimordialHelios** [nim-lang/Nim#11220]
### Summary
Nim commit ce9815b implements a new `normalizePath` on windows in `os.nim`. I believe this is an important commit and should be backported to master

### Description
Without this commit, some programs experience subtle bugs on Windows machines. An example is [issue #152 in Jester](https://github.com/dom96/jester/issues/152). I searched for the fix with `git bisect`, and then manually confirmed that ce9815b's parent contained the bug while ce9815b itself fixes the bug. I also merged the commit into master (with `git merge --strategy-option theirs`) and confirmed that fixed the bug as well.

Although the bug has been fixed since December of 2018, it's still present in master, and could cause issues for some users unaware of the bug's existence.

**Comment by narimiran** [comment]
We talked internally about backporting the commit you mention to our 0.19 branch (so it would then be a part of 0.19.6 version) and decided against it since it introduces breaking changes.

On the positive side, version 0.20 is around the corner and this will be a part of it, so this will be fixed soon.

**Comment by PrimordialHelios** [comment]
Oh, I didn't even realize it had breaking changes.

Glad to hear it'll be part of 0.20 though!
