### ISSUE TITLE
Support keyboard input

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#11304]
Support keyboard input better:
- support reading one (multiple-byte) keystroke at a time
- decode keystrokes (e.g. "a", F1, CTRL-SHIFT-F1, ARROW_UP)
- support blocking and non-blocking mode
- improve documentation with "`keyboard`:idx:". Right now it's difficult to find rdstdin procs in theindex.html

**Comment by data-man** [comment]
https://github.com/nim-lang/RFCs/issues/26

**Comment by zevv** [comment]
That's not something to put in the stdlib, I'd say make a nimble package for this.

**Comment by krux02** [comment]
just use [SDL2](https://github.com/Vladar4/sdl2_nim) for real scancode based keyboard input.

**Comment by FedericoCeratto** [comment]
@krux02 at the very least the existing documentation should be still updated.

**Comment by krux02** [comment]
What documentation should be updated? What do you suggest? I am aware that SDL might not be the best solution for everything, but you should also know that Nim is a programming language, not a library for platform abstractions. There are already many existing platform abstraction layers out there (like SDL), there is no reason to do all this work again just because Nim is a new programming language. When you really want to write for the terminal you might want to look for Nim wrappers of libraries such as `ncurses` or `readline`.
