### ISSUE TITLE
Can't use offsetOf on object that ends with an UncheckedArray

### ISSUE THREAD

**Issue by MortimerSnerd** [nim-lang/Nim#11320]
Get an error trying to use offsetOf on an object that has an UncheckedArray as the
last member.

### Example

```nim
type
  Payload = object
    something: int
    vals: UncheckedArray[int]

proc go() = 
  echo "Offset " & $offsetOf(Payload, vals)
```

### Compile results
```
test.nim(7, 29) template/generic instantiation of `offsetOf` from here
../home/pkelley/src/Nim/lib/system.nim(882, 9) Error: invalid type: 'UncheckedArray[int]' in this context: 'Payload' for var
```
It looks like system.offsetOf is instantiating the object as a var, and that's what's causing it to fail.

### Additional Information

```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-05-21
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: bab5e30972743d9dc343c9c4d3ad06f3645e5741
active boot switches: -d:release
```

**Comment by krux02** [comment]
I tried to see if the macros API is any better here as a workaround, and it seems like it is, but less that I though though. Here is an example.

```nim
import macros

macro useoffsetof(arg: typed) =
  var typeImpl = arg.getTypeImpl

  # get rid of peskey typedesc
  while typeImpl.kind == nnkBracketEXpr and typeImpl[0].eqIdent("typeDesc"):
    typeImpl = typeImpl[1].getTypeImpl

  for identDefs in typeImpl[2]:
    let sym = identDefs[0]
    echo sym, ": ", getOffset(sym)

type
  Payload = object
    something1, something2: int
    vals: UncheckedArray[int]

useoffsetof(Payload)
```

output:

```
something1: 0
something2: 8
vals: -3
```

The output is correct until you hit the ``UncheckedArray``, which returns ``-3``. This ``-3`` is an internal magic number that represents in this context "unknown offset".  This i of course wrong, because the offset is known by the compiler. But at least you can get the offsets of all the other fields in this object.
