### ISSUE TITLE
sets use non-optimized countBits32

### ISSUE THREAD

**Issue by data-man** [nim-lang/Nim#11330]
![countbits32](https://user-images.githubusercontent.com/1754269/58369629-7d515100-7f16-11e9-873b-76b7c5124825.png)

/cc @krux02 

related #10617

**Comment by krux02** [comment]
I am aware of this. Unfortunately I can't do a lot about it. 

https://github.com/nim-lang/Nim/blob/f7744260959bbdaefdc5172aaf7ff4770f8f8c03/lib/system/sets.nim#L15

This is the problem:

 * The fast countSetBits is implemented in ``bitops.nim``
 * Slow but compatible ``countBits32`` and ``countBits64`` is implemented in ``sets.nim``
 * `system.nim` includes `sets.nim`
 * `bitops` defines a macro, ``setBits`` (it is a macro, because we don't have proper varargs forwarding like in c++).
 * macros may not be imported from ``system.nim``.

Therefore,  sets need to be implemented with the slow ``countBits32/64``.  The solution that I see possible is the following: Fix varargs in nim templates with proper varargs forwarding that isn't based on macros (like in c++). Then the macros in bitops can be implemented as pure templates and bitops can be imported from ``sets.nim`` (and therefore also from system.nim).

**Comment by data-man** [comment]
@krux02 
I don't know all details, but can be bitops added to implicit imports?
Something like ```conf.implicitImports.add ...```.
And call countBits there:
https://github.com/nim-lang/Nim/blob/devel/compiler/ccgexprs.nim#L1855-L1857

**Comment by krux02** [comment]
No don't use implicitImports at all. It only causes harm. That would be worse than importing bitops in system.nim which I just explained isn't possible because of its macros.

**Comment by Clyybber** [comment]
@krux02 Isn't it possible to use `from bitops import countBits32/64` ?

**Comment by Araq** [comment]
Move countBit32/64 to system, import it from bitops, problem solved.
