### ISSUE TITLE
Error: usage of 'isNil' is a user-defined error

### ISSUE THREAD

**Issue by Arnaz87** [nim-lang/Nim#11440]
test.nim
```nim
var a: string = "foo"
echo a.isNil
```

```
$ nim -r c test.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
test.nim(2, 8) Error: usage of 'isNil' is a user-defined error
```

OS: Manjaro (Arch Linux)

```
$ nim -v
Nim Compiler Version 0.19.6 [Linux: amd64]
Compiled at 2019-05-14
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace
```

I can't understand how is it that a function as common as that doesn't work. Am I doing something wrong?

btw I noticed the version says it's compiled for an amd, but I'm running an x86-64

**Comment by kaushalmodi** [comment]
It's because a **string** cannot be *nil*. You need to compare with `"" ` or look into using `options` stdlib module.

**Comment by Arnaz87** [comment]
I suggest removing the function on strings from the standard library since it doesn't make sense. Also on seqs which also seem to not work anymore.

**Comment by Arnaz87** [comment]
Works with ref

~~~
type Obj = ref object
  v: string

var a: Obj = Obj(v: "foo")
echo a.isNil
~~~

Doesn't work with seq

~~~
var a: seq[int] = @[1]
echo a.isNil
~~~

**Comment by kaushalmodi** [comment]
Looks like the `isNil` procs for strings and seqs still exist so that `--nilseqs:on` works during the transition period of this deprecation:

https://github.com/nim-lang/Nim/blob/bce908f6ee9f24346641310d8f7f8971e92ffe01/changelogs/changelog_0_19_0.md#L180-L181

https://github.com/nim-lang/Nim/blob/bce908f6ee9f24346641310d8f7f8971e92ffe01/lib/system.nim#L2828-L2838
