### ISSUE TITLE
Selective disabling of hints/warnings does not work.

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#1167]
According to the manual,

```
{.warning[LineTooLong]: off.}
```

should be able to turn off the `LineTooLong` warning selectively, but generates an invalid pragma error instead. Hint pragmas appear to have the same problem.

**Comment by dctucker** [comment]
I have this code that ignores the pragma:
```
  {.warning[CaseTransition]:off.}
  if final_kind in dkIntegerKinds:
    result.kind = final_kind
  {.warning[CaseTransition]:on.}
```

The potential object case transition is already mitigated by the conditional since all kinds in the set have the same value field. I don't expect the compiler to prove this, so I want to disable the warning just in this specific case. I can make the warnings to away by telling the compiler `--warning:CaseTransition:off` but I don't want to turn off the warning everywhere.

Incidentally, when I use `{.push warning[CaseTransition]: off.}` (and later `{.pop.}`) it properly squelches the warning.

**Comment by Araq** [comment]
Use push/pop
