### ISSUE TITLE
make better run smarter [feature] (#11709)

### ISSUE THREAD

**Issue by AdrianV** [nim-lang/Nim#11719]
IMHO the new better run behavior with `nim c -r` feature is too optimistic now. 

For example there is no recompile when I change from `-d:debug` to `-d:release` or when I change the compiler or cpu target or compiler parameters. 

I would suggest that these parameters should be tracked too.

**Comment by timotheecour** [comment]
* that's indeed more on the line of what I was  suggesting in https://github.com/nim-lang/RFCs/issues/107:
```
A1: when nim c -cache foo.nim foo bar gets run, nim creates a hash string hashid of all compiler flags (including cmd line ones and implicit ones from nim.cfg, config.nims, but excluding program arguments given after foo.nim, these are not cached so we can rerun with different such arguments)
... etc
# then see if hash exists otherwise create new one and garbage collect via LRU to keep disk usage low
```
this prevents `nim c -d:foo --stacktrace:on bar.nim` to invalidate what was cached by `nim c -d:baz bar.nim` for example; both are kept, until garbage collection kicks in

also I'd prefer this cache to be triggered by a separate `--cache` flag, not by the existing `-r` flag, for several reasons:
* separate of concerns
* the new `-r` (as shown above) is still too optimistic, and using `nim c -r -f` is **not** equivalent to the old `nim c -r` since `-f` will do more work
* sometimes, `nim c -r foo` is not equivalent to `nim c foo` followed by `./foo`  so users may want to run these separately, which would prevent them from using the `smarter run` feature; eg if nim is installed by choosenim, it actually calls a wrapper program that itself calls nim (not sure why symbolic links arent used to implement choosenim on posix?), and results differ in some cases
