### ISSUE TITLE
int128 Undocumented

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#11847]
- `int128` is Undocumented.
- `int128` is missing from TheIndex.

Should be nice to have it documented, even as Experimental.
:slightly_smiling_face:

**Comment by alaviss** [comment]
`int128` is a big number library exclusively used by the compiler to process `(u)int64` in case statements, so I don't think it's designed for general consumption.

**Comment by juancarlospaco** [comment]
It is exported with a `*`, and it didnt warning anywhere is internal-only (comment or warning pragma),
I was thinking it was some kind of Experimental feature.

Feel free to close if its internal-only.

**Comment by krux02** [comment]
Well, I wrote int128, and I can tell you for sure that it is compiler internal usage for sure. That is also the reason why it is in ``compiler/int128``. The ``*`` for symbol export is required though. Otherwise ``import int128`` in the compiler is a bit pointless. But I can add a documentation comment to int128, if that makes you happy.

**Comment by juancarlospaco** [comment]
@krux02 Thanks for the work!, code looks good, I didnt know it was internal-only,
I was thinking it was kinda experimental or similar thing to tinker with, 
yeah just a line of documentation comment on top of module will do and Close this.
Sorry for the noise.
