### ISSUE TITLE
Clever error message wrong on var parameter syntax

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#11890]
With the following wrong syntax, `;` instead of `:` we get a clever but wrong error message, it still gives the correct solution from the wrong assumptions though.

```Nim
proc foo(x; var int) =
  discard
```
```
Error: the syntax is 'parameter: var T', not 'var parameter: T'
```

**Comment by disruptek** [comment]
You'd think that reproducing the incorrect syntax would the least of the challenges here.  :laughing:

**Comment by krux02** [comment]
Well, this is funny. But is it really an issue that needs attention to be fixed?

**Comment by mratsim** [comment]
I can't tag it lower than low priority ;). I think it's a good intro bug for those who wants to give a go at Nim's parser.

**Comment by krux02** [comment]
I don.t think this is a good intro bug for anyone, because the syntax is just wrong. There is no right way to interpret wrong syntax. If you fix this by making the parser smart you will break other error messages for incorrect syntax. Therefore as long as there is no observable problem with this way of parsing the incorrect syntax, I would like to treat it as a non-issue.

**Comment by dom96** [comment]
This is low priority, but it's certainly not a non-issue. We should strive to make error messages as human friendly as possible.

**Comment by Araq** [comment]
Harder to fix than reasonable.
