### ISSUE TITLE
Documentation, Testament missing from "Tools available with Nim"

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#12251]
- *" testament is generally available as a tool to run Nim tests automatically. "*
- https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_1_0_0.md#tool-changes
- https://nim-lang.github.io/Nim/tools.html

:slightly_smiling_face:

**Comment by JJ** [comment]
Does this mean it's available with the common nim installation? Or how can I install it?

**Comment by ringabout** [comment]
`testament` is shipped with Nim.
You should be able to use directly
type `testament` on the command line

Related docs
https://dev.to/xflywind/how-to-use-testament-in-nim-1l0h
http://nim-lang.github.io/Nim/testament.html

**Comment by JJ** [comment]
I think that the problem is that, while it's in the default distribution,
the default installation procedure with install.sh or the one that's hosted
in the distribution repositories (Ubuntu, for instance), does not install
testament to the default PATH. You need to copy it by hand, or, even better
use choosenim, which *does* install it by default.
