### ISSUE TITLE
compiler as a library: findNimStdLibCompileTime fails to find system.nim

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12293]
When trying the compiler as library API, findNimStdLibCompileTime does not find system.nim when the compiler is installed through nimble.

Test case:

nimble install compiler

And then compile:
```Nim
import compiler/[nimeval, llstream]

proc evalString(code: string, moduleName = "script.nim") =
  let stream = llStreamOpen(code)
  let std = findNimStdLibCompileTime()
  var intr = createInterpreter(moduleName, [std])
  intr.evalScript(stream)
  destroyInterpreter(intr)
  llStreamClose(stream)

let runtimeString = "echo \"Hello World\""
evalString(runtimeString)
```
Error:
```
/home/beta/Programming/Nim/Arraymancer/build/ceval.nim(13) ceval
/home/beta/Programming/Nim/Arraymancer/build/ceval.nim(5) evalString
/home/beta/.nimble/pkgs/compiler-1.0.0/compiler/nimeval.nim(98) findNimStdLibCompileTime
/home/beta/.choosenim/toolchains/nim-1.0.0/lib/system/assertions.nim(27) failedAssertImpl
/home/beta/.choosenim/toolchains/nim-1.0.0/lib/system/assertions.nim(20) raiseAssert
/home/beta/.choosenim/toolchains/nim-1.0.0/lib/system/fatal.nim(39) sysFatal
Error: unhandled exception: /home/beta/.nimble/pkgs/compiler-1.0.0/compiler/nimeval.nim(98, 12) `fileExists(result / "system.nim")` result:/home/beta/.nimble/pkgs/compiler-1.0.0/lib [AssertionError]
```

from:
https://github.com/nim-lang/Nim/blob/af6539b0c3b6958251737d5bc140cbcc8652eb8b/compiler/nimeval.nim#L93-L98

**Comment by Araq** [comment]
``findNimStdLibCompileTime`` is a bad idea. I wonder why we have it.

**Comment by PMunch** [comment]
Because `findNimStdLib` doesn't work with `choosenim`? It could try to run `nim dump` and find the folder from that, that would probably be the most reliable, or it could at least re-use whatever logic that calls. Right now it is less a `findNimStdLib` and more of a `guessWhereNimStdLibMightBeDependingOnWhereTheCompilerBinaryIs`..

**Comment by Araq** [comment]
The standard library is relative to ``nim.exe`` but it's a better idea to ship your own version of the required Nim files. Really, it is, I made the same mistake with NimEdit. The Nim stdlib evolves so fast that it gets outdated with the NimScript version that you ship your program with.

**Comment by timotheecour** [comment]
there are a few issues going on here:
- [ ] `findNimStdLib` will not work with choosenim-installed nim; this is in part due to choosenim shims (https://github.com/dom96/choosenim/issues/189); it could use `nim dump --dump.format:json` at runtime
- [ ] `nimble install compiler` is misleading and this seems like a bug:
it installs under:
`/Users/timothee/.nimble/pkgs/compiler-1.3.5/compiler.nimble`
yet uses the latest release tag, 1.2, so the 1.3.5 is really misleading
- [x] `findNimStdLibCompileTime` currently fails with `nimble install compiler`, but after a PR I'm about to submit, it'll work for `nimble install compiler@#head` (or any recent enough version of compiler pkg that will have that patch), semantics can be discussed in PR; EDIT: fixed in https://github.com/nim-lang/Nim/pull/14334
