### ISSUE TITLE
const cstring incorrectly cgen'd (pointer is copied, pointing to garbage)

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#12334]
```nim
type O = object
  a: cstring

proc test(o: var O) =
  const foo = "Hello"
  const fooc: cstring = foo
  o.a = fooc

var o: O
test(o)
echo o.a
```
Actual output: empty
Expected output:
```
Hello
```
Offending commit: 85db42ad8c1a19ea47bd5826d8639e8974cc9042
The issue can be worked around with the following pattern: `o.a = static(cstring(foo))`

**Comment by Clyybber** [comment]
I think this may be related to https://github.com/nim-lang/Nim/issues/12282 (EDIT(timotheecour): probably not, this doesn't involve `distinct`), since with https://github.com/nim-lang/Nim/commit/85db42ad8c1a19ea47bd5826d8639e8974cc9042 there should now be an implicit conversion in `const fooc: cstring = foo`.

**Comment by timotheecour** [comment]
reduced:
```nim
when true: # D20201024T083352
  const a = "foo"
  const b: cstring = a
  # const b: cstring = "foo" # would work
  var c = b
  echo (a.repr, b.repr, c.repr, a, b, $b, c, c.len, cast[int](c), cast[int](b))
```
prints:
("0x105df7f98\"foo\"", "0x105df7f98\"foo\"", "0x105df7f88\"\\3\"\n", "foo", "\x03", "foo", "\x03", 1, 4393500552, 4393500552)

so the title is wrong, the cstring is not empty, it's just that the cstring is being copied incorrectly (the pointer is copied directly instead of copying the content it points to) when crossing the VM => RT boundary

## note
another unrelated issue I found is:
```nim
when true: # D20201024T085220:here
  const a = "foo"
  var b: cstring = a
  echo (a.repr, b.repr)
```
("0x10d7dff98\"foo\"", "0x10d7df518\"foo\"\n")
=> repr gives different results for VM cstring vs RT cstring; this is likely due to how cstring's are represented in VM so might not be a real bug, but it's still an inconsistency
