### ISSUE TITLE
Some part of the compiler uses `sizeOf` instead of `sizeof`

### ISSUE THREAD

**Issue by ridho9** [nim-lang/Nim#12342]
Some parts of the compiler and stdlib uses `sizeOf` instead of `sizeof`. A few notable place is in https://github.com/nim-lang/Nim/blob/devel/lib/pure/strutils.nim#L957 and in a test file.

Can I just create a pr renaming all instance of `sizeOf` to `sizeof`?

And also, the naming isn't consistent with `offsetOf` which uses capital O.

**Comment by awr1** [comment]
Since `sizeof` [isn't a keyword](https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords) but in fact [a nonoverloadable buitlin](https://nim-lang.org/docs/manual.html#procedures-nonoverloadable-builtins), should we not opt to use `sizeOf` instead, since we only prefer all-lowercase for keywords (e.g. `isnot`)?

I get the feeling `sizeof` being typed the way it is is more of a C-ism than anything...

**Comment by awr1** [comment]
(Also, do `alignOf` and `offsetOf` need to be added to the list of builtins?)

**Comment by Araq** [comment]
Yeah, it's a C-ism but it's good enough and I'm more used to ``sizeof`` than to ``sizeOf``.
