### ISSUE TITLE
float types are not distinct

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#1252]
``` nimrod
assert float32 isnot float64 # fails
assert float32 isnot float # fails
var x: float32 = 10e308f64 # x is inf
```

**Comment by ziotom78** [comment]
This happens not only with floats, but also with integers:

`````nim
assert int32 isnot int64 # fails
assert int32 isnot int # fails
`````

However, the following statement causes a compilation error ("Error: type mismatch: got (int64) but expected 'int32'") as expected:

`````nim
var x : int32 = 5000000000i64
`````

Is this bug trivial to solve? I'm asking this because I would love to try to create a PR for fixing this.

**Comment by andreaferretti** [comment]
This prints four times `true` as of today, so I guess this can be closed

```nim
echo float32 isnot float64
echo float32 isnot float
echo int32 isnot int64
echo int32 isnot int
```

**Comment by Yardanico** [comment]
@Araq, @ephja - close?
