### ISSUE TITLE
Include complex path inside template gives error

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#12539]
**Test**
```nim
template includePath(n: untyped) = include ../test/n # But `include n` works
includePath(Foo)
``` 
**Result**
```nim
Error: unhandled exception: 'ident' is not accessible
using discriminant 'kind' of type 'TNode' [FieldError]
```
This used to work.
***
```nim
>nim -v
Nim Compiler Version 1.1.0 [Linux: i386]
Compiled at 2019-10-28
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 5ed99f8d3fc67d6f02172ab9cbcc67c17eeee5c9
active boot switches: -d:release
```

**Comment by metagn** [comment]
Now the error message is `Error: unhandled exception: field 'ident' is not accessible for type 'TNode' using 'kind = nkOpenSymChoice' `

The open symchoice in question is `/`, the failure is in [evalInclude](https://github.com/nim-lang/Nim/blob/da7670c8e0aff740a66783e83134d212383f9dd1/compiler/semstmts.nim#L2741) (which also wasn't updated for #21636), `import` is also vulnerable to the same issue with `as` [here](https://github.com/nim-lang/Nim/blob/da7670c8e0aff740a66783e83134d212383f9dd1/compiler/importer.nim#L354) but this is less important since `as` usually isn't overloaded. Should be fixed by just using `getPIdent`
