### ISSUE TITLE
StaticRead does force a recompile if static file changes.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#12663]
Have a nim file:
```nim
const msg = staticRead("test.txt")
echo msg
```

Put some thing in `test.txt`, compile it. Change some thing in test.txt and compile again. It will not recompile and display old message. Only `nim c -f` will force a recompile.

It really annoying when working with shaders always having to wait with `nim c -f` while just a single nim file needs a recompile.

**Comment by alehander92** [comment]
i guess one can generate some kind of dependency list in the nimcache (nim file => other files)

**Comment by zah** [comment]
In theory, this should also work for `staticExec`.

Most build systems are relying on the fact that a build tool can report the list of dependencies that must be tracked in order to see where a re-compile is necessary.  The `-M` option of gcc is an example for this:

> Instead of outputting the result of preprocessing, output a rule suitable for make describing the dependencies of the main source file. The preprocessor outputs one make rule containing the object file name for that source file, a colon, and the names of all the included files, including those coming from -include or -imacros command line options.
>
> Unless specified explicitly (with -MT or -MQ), the object file name consists of the basename of the source file with any suffix replaced with object file suffix. If there are many included files then the rule is split into several lines using `\'-newline. The rule has no commands.
>
> This option does not suppress the preprocessor's debug output, such as -dM. To avoid mixing such debug output with the dependency rules you should explicitly specify the dependency output file with -MF, or use an environment variable like DEPENDENCIES_OUTPUT (see Environment Variables). Debug output will still be sent to the regular output stream as normal.
>
> Passing -M to the driver implies -E, and suppresses warnings with an implicit -w. 

If Nim has minimal support for checking such dependencies, I can imagine how the community will be able to develop wrapper scripts calling various 3-rd party build tools and describing their dependencies to Nim. One can even develop an automated generic wrapper tool that can discover the dependencies of any external build tool through file I/O instrumentation. My favorite build system [tup](http://gittup.org/tup/) is able to do just that.
