### ISSUE TITLE
Arrays are passed by copy to iterators, causing crashes, unnecessary allocations and slowdowns

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/Nim#12747]
```nim
type
    ABC = ref object
        arr: array[0x40000, pointer]

let a = ABC()

for a in a.arr:
    assert a == nil
```
This code crashes with an unspecified error:
```
Error: execution of an external program failed: 'c:\Users\Kemal\Desktop\workframe\arg.exe '
```

If I interpret the C code correctly, the reason for this that the whole array is copied onto the stack, which can't hold the 2mb object.

**Comment by krux02** [comment]
It looks like the parameter to the for loop is passed by value instead of reference.

```C
void* a_2;
tyArray__gE9cBpmaYdCnQyUIB49bPnkg colontmp_;
NI i;
a_2 = (void*)0;
nimZeroMem((void*)colontmp_, sizeof(tyArray__gE9cBpmaYdCnQyUIB49bPnkg));
nimln_(18, "/tmp/scratch.nim");
nimCopyMem((void*)colontmp_, (NIM_CONST void*)(*a).arr, sizeof(tyArray__gE9cBpmaYdCnQyUIB49bPnkg)); // HERE expensive copy
nimln_(17, "/home/arne/proj/nim/Nim/lib/system/iterators.nim");
i = ((NI) 0);
nimln_(18, "/home/arne/proj/nim/Nim/lib/system/iterators.nim");
```

I tested if this is a general problem that parameters are passed by value, but this doesn't seem to be the case, it seems to be an array problem only. Then I tested what happens when the internal type is something more complex than a POD type, and I realized that the array parameter is a full deep copy of the argument:

```nim

type
  MyObject = object
    data: int
    subdata: seq[int]


  ABC = object
    arr: array[0x800, MyObject]

let a = ABC()

for a in a.arr:
  assert a.data == 0
```

generated C code
```C
tyArray__fw4Xqb4g3J57B176sXAsWg colontmp_;
NI i;
nimZeroMem((void*)colontmp_, sizeof(tyArray__fw4Xqb4g3J57B176sXAsWg));
nimln_(24, "/tmp/scratch.nim");
genericAssign((void*)colontmp_, (void*)a__5XsYCtwp8oCm9cIIRL3Taeg.arr, (&NTI__fw4Xqb4g3J57B176sXAsWg_));
```

ABC being a value, ref or ptr type doesn't affect the code generation here. It is just that in ref/ptr types heap memory is copied to the stack. Value types would crash earlier.

This is not what Nim claims to do in parameter passing.

**Comment by Araq** [comment]
> This is not what Nim claims to do in parameter passing.

Well it has nothing to do with parameter passing either because iterators are inlined...

**Comment by narimiran** [comment]
> This code crashes with an unspecified error:

I couldn't reproduce the crash with Nim devel 1.1.1. @RSDuck, can you confirm?

**Comment by RSDuck** [comment]
@narimiran you seem to have a larger stacks on your system, with the current revision (b20d7e2110d3d8ab406d44f2231120847e6fea05) it crashes for me. The code responsible for this is still generated:
```c
tyArray__csEBLl709aLlauoKYkyd9cew colontmp_;
NI i;
nimZeroMem((void*)colontmp_, sizeof(tyArray__csEBLl709aLlauoKYkyd9cew));
nimln_(7, "c:\\Users\\Kemal\\Desktop\\psquare3ds\\test.nim");
nimCopyMem((void*)colontmp_, (NIM_CONST void*)(*a__rzPnqgxKTArAY31mYN1Y3A).arr, sizeof(tyArray__csEBLl709aLlauoKYkyd9cew));
```
