### ISSUE TITLE
new $nimbleDir path substitution yields unexpected search paths

### ISSUE THREAD

**Issue by disruptek** [nim-lang/Nim#12767]
Given the following `nim.cfg` in an otherwise empty directory:

```
--clearNimblePath
--path="$nimbledir/foo"
```
`nim dump` now yields

```
#...
/home/adavidoff/.nimble/pkgs/foo
/opt/nimble/pkgs/foo
#...
```

Because I don't actually have any `nimblePaths` (due to `--clearNimblePath`), I expected no substitution, ie:
```
#...
$nimbledir/foo
#...
```
I tried adding `--noNimblePath`:
```
--noNimblePath
--clearNimblePath
--path="$nimbledir/foo"
```
and the output did not change.  Then I tried adding a `--nimblePath`:
```
--clearNimblePath
--nimblePath="$config/goats"
--path="$nimbledir/foo"
```
and now my search paths (not lazy paths) include the following:
```
/home/adavidoff/git/t/goats/foo
/home/adavidoff/.nimble/pkgs/foo
/opt/nimble/pkgs/foo
```
and lazy paths includes `/home/adavidoff/git/t/goats`.

So it seems that there are two breaking changes introduced in #12750:
- we cannot remove these global paths at all
- paths (below the target) that do not exist are added via `--nimblePath`

nimph will just add `--excludePath` to the `nim.cfg` to exclude missing paths, but I feel a better solution would be to fix the compiler.

**Comment by genotrance** [comment]
> we cannot remove these global paths at all

`--clearNimblePath` and `--noNimblePath`, only clear `lazyPaths` today. They do not affect what is being stored into `conf.nimblePaths`.

Here is what I propose: both `--clearNimblePath` and `--noNimblePath` will set `conf.nimblePaths = @[]`. If you then add a `--path:"$nimbleDir/xyz-1.0.0"` without adding a `--nimblePath`, it will fail since there's no `$nimbleDir` available to substitute with.

The error isn't pretty though: `Error: unhandled exception: invalid format string [ValueError]`

`--nimblePath` after a `--noNimblePath` won't get added at all so `$nimbleDir` will always fail. `--clearNimblePath` is more forgiving though and provides the behavior expected.
