### ISSUE TITLE
Incorrect error when setting transformed lambda to a variable

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#1288]
``` nimrod
macro test(n: stmt): stmt =
  result = n

let x =
  proc (): int {.test.} = 5

echo x()
```

```
Error: value of type 'proc (): int' has to be discarded
```

**Comment by andreaferretti** [comment]
`stmt` is deprecated. Changing it to `untyped` works just fine. Changing it to `typed` gives a different error, `Error: illformed AST: proc (): int = result = 5`.

This is about shadowing `result` from the proc inside the macro; as far as I can tell this is the same issue as https://github.com/nim-lang/Nim/issues/7323.

Can we then close this?

**Comment by andreaferretti** [comment]
Since `stmt` is finally `gone`, `untyped` works and `typed` gives a different error which is already tracked, I am closing this

**Comment by dom96** [comment]
The errors output by the examples in #7323 are different to this error, what makes you think these are duplicates?

Either way, this issue is older and offers a more "to the point" example. I'm reopening this.

**Comment by andreaferretti** [comment]
The example in this issue is not even valid Nim anymore. I guess you mean the variant

```nim
macro test(n: typed): typed =
  result = n

let x =
  proc (): int {.test.} = 5

echo x()
```

which gives `Error: illformed AST: proc (): int = result = 5`

This is a completely different issue than the one you opened. On a second thought, I am not even sure this example should compile, given that the output is typed and `result` is not hygienic in this context

**Comment by Araq** [comment]
Agreed.
