### ISSUE TITLE
Exceptions can't escape macros

### ISSUE THREAD

**Issue by sealmove** [nim-lang/Nim#12923]
Not sure if this is known behavior:
```Nim
import unittest

macro myMacro() =
  raise newException(OSError, "message")

try:
  myMacro()
except:
  echo "catch"
```

```
stack trace: (most recent call last)
/usercode/in.nim(4, 3)   myMacro
/usercode/in.nim(7, 10) template/generic instantiation of `myMacro` from here
/usercode/in.nim(4, 3) Error: unhandled exception: message [OSError]
```

**Comment by dumjyl** [comment]
If you just want the exception to escape, wrap the raise in a `quote do:`, otherwise read on.

Exceptions raised within macros are for exception handling within macros. 
If an exception is not caught in the macro it means the macro failed to generate proper code, triggering a compilation error.

If it wasn't a compilation error, one of two things happens:
- The program always fails with unhandled exception at runtime when it could have failed during compilation.
- Or worse, the program handles the exception. Macros are hard enough to reason about without stealthily failing.

**Comment by Araq** [comment]
Not a real bug, code shows a misunderstanding of macros.
