### ISSUE TITLE
nim-gdb is missing from all released packages

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#13104]
File is present in Nim repo but not in released xz or zip files.

**Comment by Araq** [comment]
Ouch.

**Comment by genotrance** [comment]
`tools/nim-gdb.py` is present whereas `bin/nim-gdb` is missing. Sorry, I should have been more accurate.

**Comment by HymanZHAN** [comment]
@Araq As the author mentioned, the fix is not complete... There's no `nim-gdb` executable shell script in the bin folder.

Notice how the timestamp is different as I need to copy and create `nim-gdb` myself:

![Screenshot from 2020-03-16 10-24-59](https://user-images.githubusercontent.com/26806995/76767756-78dd7980-6770-11ea-9860-fd98827d55f2.png)

**Comment by tobimensch** [comment]
I hit on this bug today with Nim 1.2.0.

**Comment by HymanZHAN** [comment]
@Araq This issue hasn't been fully fixed yet. I just tried to install nim with choosenim today and the nim-gdb is still missing from there.

![Screenshot from 2020-08-21 16-23-54](https://user-images.githubusercontent.com/26806995/90931736-409b3080-e3cb-11ea-83d7-d7a99cba3551.png)

**Comment by ErikSchierboom** [comment]
I've hit the same issue today.

**Comment by narimiran** [comment]
> I've hit the same issue today.

What is your Nim version? (Check by running `nim -v`)

**Comment by ErikSchierboom** [comment]
```
Nim Compiler Version 1.2.6 [Linux: amd64]
Compiled at 2020-07-29
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by dom96** [comment]
Choosenim also needs to shim this: https://github.com/dom96/choosenim/issues/140
