### ISSUE TITLE
Rephrase "Garbage Collection" on website and documentation

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#13331]
Problem: people on online forums frequently dismiss Nim as being garbage collected and unfit for games and microcontrollers, often assuming it is implementing a stop-the-world gc. [example](https://news.ycombinator.com/item?id=22399416)

Proposed solution: 1) describe the memory management as multi-paradigm on https://nim-lang.org/ and link to https://nim-lang.org/features.html and https://nim-lang.org/docs/gc.html
2) clarify that the current GC implementation is not Java-like stop-the-world

Update https://nim-lang.org/docs/gc.html with a list of the existing memory managers and hint at the upcoming ARC

**Comment by treeform** [comment]
Maybe also deprecate --gc: to rename it to --mm: for memory management.  Instead of gc.html have mm.html that starts with "Nim's Memory Management" and list other GCs as one of Memory Management Modes along with none and arc...

Describe arc as not as a "GC" but a cleaver compiler trick that figures out statically where allocations and frees go ... and in rare cases where a logic is too complex it falls back on reference counting ... but it still stays extremely deterministic and fast.

In even rare case in very complex code where cycles are possible, you can use a cycle detector called --mm:orc. But only if you choose/require it for your use case.

But maybe this is going too far... and would scare people way from GC based languages that want safety of the GC?

**Comment by andreaferretti** [comment]
> But maybe this is going too far... and would scare people way from GC based languages that want safety of the GC?

Yes

> Describe arc as not as a "GC" but a cleaver compiler trick that figures out statically where allocations and frees go

The thing is, in general it cannot. The information is just not there. Rust can do it at the price of making the type system much more complicated. Let us not sell what is not there

**Comment by Araq** [comment]
> The thing is, in general it cannot. The information is just not there. Rust can do it at the price of making the type system much more complicated. Let us not sell what is not there

Nah, Rust cannot do it either, in Rust too it's mostly a marketing gag. It uses 1 bit reference counts under the hood, for example.

**Comment by andreaferretti** [comment]
> It uses 1 bit reference counts under the hood, for example.

Wow, I did not know that! Do you have a reference?

**Comment by Araq** [comment]
https://doc.rust-lang.org/nomicon/drop-flags.html

**Comment by Varriount** [comment]
As an anecdote, one of the big things that drew me to Nim was that it has a GC. I wanted a compiled language that had automatic memory management and didn't look like the top row of my keyboard had been stepped on by a cat.

**Comment by FedericoCeratto** [comment]
https://nim-lang.org/docs/gc.html has been updated - thanks.
Closing the issue.
