### ISSUE TITLE
htmlgen does not support `data-*` attributes

### ISSUE THREAD

**Issue by sveri** [nim-lang/Nim#13444]
When using htmlgen and using any data- attribute I get a compile error.

### Example
```nim
import htmlgen

td(data-label ="foobar")
```

### Current Output
Typemismatch error

### Possible Solution

In htmlgen.nim change the `proc delete` to check for data attributes like this:
```nim
proc delete[T](s: var seq[T], attr: T): bool =
  # data-* attributes are user defined, so it would not make sense to
  # define each single one statically.
  if attr.startsWith("data-"):
    return true

  var idx = find(s, attr)
  if idx >= 0:
    var L = s.len
    s[idx] = s[L-1]
    setLen(s, L-1)
    result = true
```

```
$ nim -v
Nim Compiler Version 1.0.6
```

**Comment by metagn** [comment]
Your example will not work because `data-label` is parsed as the expression `data - label`. You have to quote it with backticks. That will make your possible solution work, except it will allow duplicate attributes starting with `data-`.

**Comment by Vindaar** [comment]
> Your example will not work because `data-label` is parsed as the expression `data - label`. 

That's not really a problem. The input is handed to `getIdent` beforehand. So adding a case for `nnkInfix` makes it work. E.g.:

```nim
proc getIdent(e: NimNode): string {.compileTime.} =
  case e.kind
  of nnkIdent:
    result = e.strVal.normalize
  of nnkAccQuoted:
    result = getIdent(e[0])
    for i in 1 .. e.len-1:
      result.add getIdent(e[i])
  of nnkInfix:
    doAssert toStrLit(e[0]).strVal == "-"
    result = toStrLit(e[1]).strVal & toStrLit(e[0]).strVal & toStrLit(e[2]).strVal
  else: error("cannot extract identifier from node: " & toStrLit(e).strVal)
```
where we just build the expected string from the infix.

Also the `delete` proc in `htmlgen.nim` really shouldn't be generic as far as I can tell. It's only used in `xmlCheckedTag` and only using `string`.

Finally, maybe just replace the line here:
https://github.com/nim-lang/Nim/blob/devel/lib/pure/htmlgen.nim#L92
by one including your suggestion:
```nim
      if delete(req, name) or delete(opt, name) or name.startsWith("data-"):
```

This will make it work anyways. I'm not all that familiar with HTML, so I won't open a PR, because I don't know if "data-" is special or if there's other tags with similar user defined behavior etc.

**Comment by sveri** [comment]
> This will make it work anyways. I'm not all that familiar with HTML, so I won't open a PR, because I don't know if "data-" is special or if there's other tags with similar user defined behavior etc.

I am not sure what exactly you mean when you say if there are other tags with similar user defined behaviour. I just spent some time looking around, data-* is a global attribute according to: https://www.w3schools.com/tags/ref_standardattributes.asp whatever that means.
The spec itself states clearly that data-* is a custom attribute that can be applied to every html element: https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#custom-data-attribute.

For a PR would you need a test? I took a look at testament/htmlgen.nim but did not understand where and how to add one for the data-* attribute.

**Comment by Vindaar** [comment]
> > This will make it work anyways. I'm not all that familiar with HTML, so I won't open a PR, because I don't know if "data-" is special or if there's other tags with similar user defined behavior etc.
> 
> I am not sure what exactly you mean when you say if there are other tags with similar user defined behaviour. I just spent some time looking around, data-* is a global attribute according to: https://www.w3schools.com/tags/ref_standardattributes.asp whatever that means.
> The spec itself states clearly that data-* is a custom attribute that can be applied to every html element: https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#custom-data-attribute.

Yes, what I mean is if there's other attributes which can have variable names to an extent. The link doesn't seem to imply that's the case. I just mention it, because if there was it wouldn't be a nice solution to add a hardcoded `if ... or name.startsWith("data-")` into the code. But if it's the only one of a kind then that may be acceptable.

> For a PR would you need a test? I took a look at testament/htmlgen.nim but did not understand where and how to add one for the data-* attribute.

Yes, a test should be added. 
The file you mention isn't actually a test file for `htmlgen`. It's a file to generate html output for testament, as far as I can tell.
The actual tests are found here: https://github.com/nim-lang/Nim/tree/devel/tests

I'm not on a computer with the Nim source and a terminal, so I can't grep through the tests to find the ones (if they exist?) for `htmlgen`. Somewhere in there.

**Comment by Vindaar** [comment]
It seems like the only test cases using stuff from `htmlgen` is at the bottom of this file:

https://github.com/nim-lang/Nim/blob/devel/tests/stdlib/tstdlib_various.nim#L227
