### ISSUE TITLE
[minor] `nimgrep --word` doesn't work with operators (eg misses  `1 +% 2`)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13528]
I'm not 100% sure this is a bug since ripgrep has same issue (eg rg ''\b\+%\b' also won't find `1 +% 2`), however this is definitely not desirable; it makes it just a bit harder to search for operators in code.

### Example
```
bin/nimgrep --find -r --ext:nim --word '\+%' lib
```

### Current Output
it returns a single entry
```
lib/pure/uri.nim:721:     doAssert encodeQuery({"foo": "bar & baz"}) == "foo=bar+%26+baz"
```

without --word it returns 104 entries, eg:
```
lib/system/gc_common.nim:402:           sp = sp +% sizeof(pointer)
```

### Expected Output
these should be listed when we pass `--word`
```
lib/system/gc_common.nim:402:           sp = sp +% sizeof(pointer)
```

### Additional Information
* built nimgrep from nim devel 1056f9ecff60f624522f24e508d0976994bcef80 ; but probably never worked

**Comment by BurntSushi** [comment]
> since ripgrep has same issue

It does not. While this

```
$ echo '1 +% 2' | rg '\b\+%\b'
$
```

yields nothing, this is correct behavior. `\b` generally means "match a word character on one side and a non-word character on the other." Neither spaces nor `+` are word characters, so it doesn't match here. However, this

```
$ echo '1 +% 2' | rg -w '\+%'
1 +% 2
```

does work, because ripgrep does not implement `-w` by surrounding the regex with `\b`. Instead, it translates the regex to `(^|\W)(\+%)($|\W)`, which ends up being more generally useful, as you've found.

GNU grep behaves the same way. And indeed, ripgrep's behavior is inspired by GNU grep's here. ripgrep used to have the same bug many moons ago. See https://github.com/BurntSushi/ripgrep/issues/389 and https://github.com/BurntSushi/ripgrep/issues/938

**Comment by timotheecour** [comment]
wow good thing you're monitoring for `ripgrep` in github :-) BurntSushi is the author of the awesome https://github.com/BurntSushi/ripgrep
Thanks for this super useful answer, see https://github.com/nim-lang/Nim/pull/13537 which also shows an edge-case that ripgrep also has; let's move the discussion there (if you care)
