### ISSUE TITLE
Better detection of threading issues

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#13623]
### Problem

* `{.threadvar.}` is just a normal var when `--threads:on` isn't supplied during compilation, even when the Nim code gets called by an external piece of code from different threads.
* Many internal data structures and libraries depend on the semantics of `{.threadvar.}`
* When these semantics don't hold you get all sorts of fun segfaults

### Solutions

* In debug mode, introduce some way to detect when a `threadvar` is accessed from a different thread and fail with a descriptive error message.
* Implement threadvar support even when threads are disabled?

**Comment by Araq** [comment]
Unclear what you mean. With --threads:off means you don't need thread local storage at runtime. At compiletime the semantics do change as can be seen in the behaviour for e.g. gcsafety.

**Comment by mratsim** [comment]
In C thread-aware code must be compiled with -pthread (or the Windows equivalent).

Either we generate no `__thread`/threadvar like what is done today when no `--threads:on` flag is passed, or we compile by default with `--threads:on` implying pthread.

Implementing threadvar when there is no thread support means implementing and supporting TLSEmulation which is already a source of significant threading bugs. In Weave I explicitly prevent compilation with tlsEmulation because [I can't assign an integer ID](https://github.com/mratsim/weave/blob/82b21690e85c9db05ff90d92f6966182fd275e17/weave/scheduler.nim#L254) to my worker threads for example and it's also [abysmally slow](https://github.com/mratsim/weave/issues/61) which completely defeats the purpose of multithreading (3x perf improvement by disabling TLS)

**Comment by dom96** [comment]
> Either we generate no __thread/threadvar like what is done today when no --threads:on flag is passed

Yeah, why don't we do this?

> With --threads:off means you don't need thread local storage at runtime. 

You do if your code is running on Android and JNI calls your function from another thread. Then you'll get segfaults which are tough to debug (and it might not always be obvious that a library you're using is using a threadvar, it wasn't clear in my case).

**Comment by Araq** [comment]
> Yeah, why don't we do this?

Performance. If you're on Android with JNI calls that use threads you must compile with ``--threads:on``, everything else is madness.

**Comment by dom96** [comment]
> Performance

Can you explain why this would degrade performance?

> If you're on Android with JNI calls that use threads you must compile with --threads:on, everything else is madness.

Fair enough. It's just such a PITA to do this though :(

**Comment by Araq** [comment]
> Can you explain why this would degrade performance?

Depending on the C compiler and architecture access to thread local storage is slower than accessing globals.

**Comment by Araq** [comment]
`--threads:on` is now the default.
