### ISSUE TITLE
Cannot retrieve the default paramater value of a proc from inside a macro

### ISSUE THREAD

**Issue by rayman22201** [nim-lang/Nim#13688]
For idents that resolve to procs via `bindSym`, The AST returned from `getTypeImpl` "forgets" the default parameter value of the proc arguments. It shows as an empty nim node.

### Example
```nim
import macros
{.experimental: "dynamicBindSym".}

macro testMacro(op: untyped): untyped =
  let formalProcDef = op.bindSym.getTypeImpl
  # where did all the default params go?
  # it should be an intLitNode(42)
  assert formalProcDef[0][2][2].kind != nnkEmpty
  result = nnkCall.newTree(op, newLit(1), newLit(2))

proc testProc(a, b: int; default: int = 42) : bool =
  return a < b

echo testMacro(testProc)
```

### Current Output
```
Error: unhandled exception: /usercode/in.nim(7, 10) `formalProcDef[0][2][2].kind != nnkEmpty`  [AssertionError]
```

```
$ nim -v
Nim Compiler Version 1.0.6
```

**Comment by ghost** [comment]
Workaround: use `getImpl` instead, it is a more familiar form anyway.
For someone wanting to contribute, here is the relevant line: 
https://github.com/nim-lang/Nim/blob/15ba765ebd83e44d18a0a2c23016bdf3b4bbecca/compiler/vmdeps.nim#L237

**Comment by timotheecour** [comment]
this bug is invalid, can we close this?

default value isn't part of the type (as returned by getTypeImpl)

this modified snippet (without bindSym, which is not relevant) should explain everything
```nim
when true:
  import macros
  macro testMacro2(s: typed): untyped =
    let s = s[0][0]
    let s2 = s.getImpl
    echo s2.treeRepr # would show default value but not the type of `default` (not in this examples's AST)
    let formalProcDef = s.getTypeImpl
    echo formalProcDef.treeRepr # would not show the default value but would show the resolved type for `default`
    assert formalProcDef[0][2][2].kind != nnkEmpty
  testMacro2:
    proc testProc(a, b: int; default = 42) : bool =
      return a < b
```


> Workaround

not a workaround, there is no bug

## note
a more interesting example would be:
```nim
when true:
  macro testMacro2(s: typed): untyped = ...

  const foo = 42
  proc testProc(a, b: int; default = foo) : bool =
    return a < b
```

in this example, `getImpl` resolves `foo` as `Ident "foo"`; to resolve to a symbol, you need https://github.com/nim-lang/Nim/pull/11754 (which I just rebased to keep it green /cc @araq)

**Comment by rayman22201** [comment]
@timotheecour your example explains the behavior, but not why the behavior is this way.

Maybe the real bug is the lack of documentation that explains the difference between `getImpl` and `getTypeImpl` It's not clear to me what difference is between the two.

I haven't been following too closely, but it seems like the behavior between `getImpl` and `getTypeImpl` has changed a few times. (Also, Maybe my knowledge of the docs is out of date)

This part is just my opinion (In other words, feel free to ignore :-P):
I guess I see how the default value is not part of the formal type...
but, in practice, I almost always want both the type and the value of the default.
I'm not writing Haskell, I'm writing Nim...

**Comment by timotheecour** [comment]
under the hood:
getImpl represents a symbol, ie a PNode of kind PSym (symbol, here, of kind nkProcDef)
getTypeImpl represents a typedec as AST, ie a PNode rendering PType as AST (see code: `regs[ra].node = opMapTypeToAst(c.cache, regs[rb].node.typ, c.debug[pc])`)

getImpl is easy to understand as it maps 1:1 to an entity known by compiler.
getTypeImpl is trickier because it doesn't map 1:1, it's generated to represent a type as AST (taking care of cycles) via mapTypeToAstX

Note that getTypeXXX apis are not as intuitive as could be, eg see @mratsim 's posts https://github.com/nim-lang/RFCs/issues/44 + elsewhere. IMO this stems from impedance mismatch between PType and PNode, where macros.nim tries to shoe-horn PType to a PNode (constructing AST on the fly), even though it's internally not represented as a PType
(a PNode's sons are PNode's, and a PType's sons as PType's)

I'm actually now wondering whether we could simply expose PType (so we'd have NimNode and NimType in macros.nim); there would be no transformation involved, the compiler would simply expose the PType object as is.
