### ISSUE TITLE
`=destroy` ran twice?

### ISSUE THREAD

**Issue by jxy** [nim-lang/Nim#13768]
`=destroy` ran twice for the first variable `I(i:0)` in the following example.

### Example
```nim
type I = object
  i: int
proc `=destroy`(x:var I) =
  echo "destroy ",x

for i in 0..2:
  echo i
  var x = I(i:i)
  echo x
```

### Current Output
```
0
destroy (i: 0)
(i: 0)
1
destroy (i: 0)
(i: 1)
2
destroy (i: 1)
(i: 2)
destroy (i: 2)
```

### Expected Output
I don't know what should be the expected order in the output.

### Possible Solution

no

### Additional Information

no

```
$ nim -v
Nim Compiler Version 1.2.0 [MacOSX: amd64]
Compiled at 2020-03-26
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8f1ac3fa89250c66290cb065aed717bcde240ba
active boot switches: -d:release
```

**Comment by sheerluck** [comment]
if you iterate `for i in 10..12:` you'll see
```
10
destroy (i: 0)
(i: 10)
11
destroy (i: 10)
(i: 11)
12
destroy (i: 11)
(i: 12)
destroy (i: 12)
```
so it is not "twice" but "fantom `=destroy` for unintialized var"

**Comment by jxy** [comment]
So is this expected behavior?

**Comment by Clyybber** [comment]
Yeah. Because `var x = I(i: i)` gets transformed to `=sink(x, I(i: i)` and `=sink` calls `=destroy` on the first parameter.
This is optimized away in most cases via the firstWrite analysis, but in this case we are in a loop, so we must `=sink`, so as to destroy the value of the previous iteration.
In general `=destroy` should check for its parameter to be nil/someOtherUninitState.
