### ISSUE TITLE
arc: codegen or inject destructor error 

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#13780]
Appears on nim compiler itself when compiled with `--gc:arc --sinkInference:on`
```nim
type
  TPassContext = object of RootObj
  PPassContext = ref TPassContext

  PCtx = ref object of TPassContext
    a: int

  ModuleGraph = object
    vm: RootRef

proc myOpen(g: sink ModuleGraph): PPassContext = 
  result = PCtx g.vm

var g = ModuleGraph(vm: new(PCtx))

let vm = myOpen(g)
```

Generated C doesn't compile, error:
```
nimcache_z3/@mz3.nim.c:235:3: error: assignment to cast is illegal, lvalue cast are not supported:
        ((tyObject_PCtxcolonObjectType___crveL78K5XzCmJYqrRnx2g*) (g.vm)) = 0;
```

**Comment by cooldome** [comment]
Not sure if it codegen error or move should not be allow if type conversion is involved 
So far error seems in genWasMoved()

**Comment by Clyybber** [comment]
So far the issue seems to be that `genWasMoved()` does `genWasMoved(skipConv(n))`.
`n` is a `nkObjDownConv(nkObjUpConv(g.vm))`; skipConv will only skip the first nkObjDownConv so then we generate `wasMoved(PCtx(g.vm))`.  The backend can't handle that.
I have an example here:
```
type
  TPassContext = object of RootObj
  PPassContext = ref TPassContext

  PCtx = ref object of TPassContext
    a: int

  ModuleGraph = object
    vm: RootRef

proc main() =
  var g = ModuleGraph(vm: new(Pctx))
  PPassContext(PCtx(g.vm)) = nil #This compiles, but crashes at runtime with gc:arc
  #PCtx(g.vm) = nil #This generates invalid C code

main()
```
The version that compiles crashes at runtime only with `gc:arc`, as the backend generates temporaries for the conversions, so `g.vm` doesn't actually get assigned to nil, so we get a double free. So even when removing that skipConv call or adapting it it will still fail.

So IMO the issue is twofold, first we probably shouldn't be skipping the `nkObjDownConv` and second (and thats the actual issue here I think) the backend either generates incorrect code or too many temporaries that cause incorrect behaviour.

**Comment by elcritch** [comment]
I'm getting a very similar issue that I think is due to the same problem/code path. I'm using the latest `devel` (see below). 

A project I'm testing with C++ & C output is giving me this issue, but only with `gc:arc`: 

```
third-party/spryvm/spryvm/sprycore.nim:67:58: error: assignment to cast is illegal, lvalue casts are not supported
"ctType|RootObj|")){ raiseObjectConversionError(); }                            ((tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw*) (blk)) = 0;
                                                                                ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~
```

This is the Nim code: 

```nim
    let act = evalArgInfix(spry)
    let blk = evalArg(spry)
    if act of Activation:
      if blk of Blok:
        Activation(act).catcher = Blok(blk)
```

Resulting in this block of C++ code: 

```c++
#line 65 "third-party/spryvm/spryvm/sprycore.nim"
				if (blk && !isObj((*blk).m_type, "|spryvm.spryvm.Blok:ObjectType|spryvm.spryvm.SeqComposite:Objec"
"tType|spryvm.spryvm.Composite:ObjectType|spryvm.spryvm.Node:Obje"
"ctType|RootObj|")){ raiseObjectConversionError(); }				((tyObject_BlokcolonObjectType___UIJsSh2kxAc9acGwoSYj4xw*) (blk)) = 0;
#line 461 "third-party/spryvm/spryvm/spryvm.nim"
				nimln_(461, "third-party/spryvm/spryvm/spryvm"
".nim");				eqsink___ZEC0qfeEseAEXIkmgFHZTQ_2((*((tyObject_ActivationcolonObjectType___jwMMFyLWVLpBU9ca5Dr6Vrw*) (act))).catcher, blitTmp);
}			}
			LA10_: ;
}		}
		LA6_: ;
	
```

My nim version: 

```
Nim Compiler Version 1.3.1 [MacOSX: amd64]
Compiled at 2020-05-06
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 6dba06f9e63083d4cbcd09b10aaf2342b70821b0
active boot switches: -d:release
```

It looks like the ccgexprs.nim file is casting the source, and setting it to 0. Clang doesn't appear to like that.

**Comment by elcritch** [comment]
Tracing which branch the compiler takes show in my case that it's using line 2477:

```nim
      putIntoDest(p, d, n,
                "(($1) ($2))/* d */" % [getTypeDesc(p.module, n.typ), rdLoc(a)], a.storage)
 ```

It looks like in my case, that the code is still generating an lvalue. One last bit, if I change the Nim code that triggers this to avoid the assignment error: 

```
    if act of Activation:
      if blk of Blok:
        var act1 = Activation(act)
        var blk1 = Blok(blk)
        act1.catcher = blk1
        return act1
```

I then get a runtime error: 

```
Traceback (most recent call last)
third-party/spryvm/tests/spryunittest.nim(5) spryvmtest
third-party/spryvm/spryvm/spryvm.nim(792) parse
third-party/spryvm/spryvm/spryvm.nim(595) pop
third-party/spryvm/spryvm/spryvm.nim(589) closeKeyword
third-party/spryvm/spryvm/spryvm.nim(574) produceNodes
$HOME/.asdf/installs/nim/devel/lib/system/repr_v2.nim(115) add
$HOME/.asdf/installs/nim/devel/lib/system/refs_v2.nim(65) nimIncRef
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: 'third-party/spryvm/tests/all '
```

Hope that helps you all figure out this issue!

**Comment by cooldome** [comment]
@Clyybber can we close it now? It seems to work fine after your codegen fix and fix had a test case.

**Comment by Clyybber** [comment]
Ok, I'll open a seperate issue for this then:
```
type
  TPassContext = object of RootObj
  PPassContext = ref TPassContext

  PCtx = ref object of TPassContext
    a: int

  ModuleGraph = object
    vm: RootRef

proc main() =
  var g = ModuleGraph(vm: new(Pctx))
  PPassContext(PCtx(g.vm)) = nil #This compiles, but crashes at runtime with gc:arc

main()
```

**Comment by Clyybber** [comment]
Actually, @elcritch's issue seems to be on a devel after https://github.com/nim-lang/Nim/commit/d6e1b5c070bf58449bf4af210ec099418d496aa5.

**Comment by elcritch** [comment]
@Clyybber unfortunately yes, it's still present on the latest dev as of this morning. 

I've forked the library and created two branches that exhibit this  double free error and a C generation lvalue error. They are at my fork of [SpryVM](https://github.com/elcritch/spryvm) on branches `runtime-double-free` and `compile-error-lvalue`. 

To run the code:
```sh
cd spryvm/tests/
./run.sh 
```

My Nim version: 
```
Nim Compiler Version 1.3.3 [Linux: amd64]
Compiled at 2020-05-12
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: de74362213baeb28d52c05c71cd9b8389ae69060
active boot switches: -d:release
```
I'm hoping to get this running on an embedded device! That's why ARC is important to me. It's the only Nim GC that works on embedded that I've tried.
