### ISSUE TITLE
`sequtils.foldl` doesn't work in generic context

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#13852]
### Example
```nim
import sequtils

proc test(xs: auto) =
  discard xs.foldl(a & $b, "")

test "abc"
```

### Current Output
```
template/generic instantiation of `test` from here
type mismatch: got <macro (e: varargs[untyped]): untyped{.noSideEffect, gcsafe, locks: <unknown>.}>

but expected one of:
proc `$`(httpMethod: HttpMethod): string
first type mismatch at position: 1
required type for httpMethod: HttpMethod
but expression 'b' is of type: macro (e: varargs[untyped]): untyped{.noSideEffect, gcsafe, locks: <unknown>.}
...
```

### Additional Information

* Tested on 1.0.6 and 1.1.1
* Applies to procs other than `$`

**Comment by timotheecour** [comment]
should we close this issue?

@dawkot I cannot reproduce this, and I'm suspecting the example provided isn't correct since it shows `HttpMethod` which isn't exposed with imports you have; maybe you had other code, or `--import:xxx` in you config.nims? 

(i tried with devel 03271593446f72cb99ebe8b68121999ba7ea8021 and 1.0.6)

**Comment by dawkot** [comment]
I can't reproduce it either at this point.
