### ISSUE TITLE
crash in nimDestroyAndDispose

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#13864]
The following code works with default gc, but not with `--gc:arc`.
```nim
type Variant* = object
    refval: ref RootObj

proc newVariant*[T](val: T): Variant =
    let pt = T.new()
    pt[] = val
    result = Variant(refval: cast[ref RootObj](pt))

var v = newVariant(@[1, 2, 3])
```
```
nim c -r --gc:arc test.nim
```
```
Traceback (most recent call last)
~/test.nim(7) test
~/nim/lib/system/refs_v2.nim(119) nimDestroyAndDispose
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
**Nim version**: 1.2

**Comment by cooldome** [comment]
It is caused by the fact that `seq` doesn't inherit from `RootObj`. This is more of ref in arc design question. In principal it is illegal cast, but I understand it is a common trick in old runtime.

@Araq: do we plan to support such use case?

**Comment by yglukhov** [comment]
I am happy to work this around. If there any other type erasure technique for seq?

**Comment by Araq** [comment]
> do we plan to support such use case?

Uh, no...

**Comment by cooldome** [comment]
As a discussion point. 

Looks like with `gc:arc` there is no way to have a ref to anything anymore, it only ptr to anything left. Sounds like a limitation. I understand we have reference to final objects and non final objects. Reference to final objects are more efficient because they don't have to keep runtime type info. Possibly we can have a procedure to promote/convert ref on final object to ref on non final object, it will not be free but it will exist. Something like automatic packing into another object with NTI as first element.  Problem with alignment might appear though.

@Araq, What do you think?

**Comment by Araq** [comment]
I don't see the point. With ``move`` it's easy to now code this without hacks:

```nim

type
  Base[T] = object of RootObj
    val: T

proc newVariant*[T](val: sink T): Variant =
    let pt = Base[T](val: val)
    result = Variant(refval: pt)

```

**Comment by cooldome** [comment]
make sense
