### ISSUE TITLE
os.lastPathPart always returns full path on windows, works fine on *nix

### ISSUE THREAD

**Issue by faulander** [nim-lang/Nim#13969]
### Example
![image](https://user-images.githubusercontent.com/38588197/79113781-f7363700-7d81-11ea-8be4-7f06ff3a236c.png)

Above is what it should return, but it returns:
![image](https://user-images.githubusercontent.com/38588197/79113971-5a27ce00-7d82-11ea-875c-27952f0873ec.png)

i tried with an r-string and with a normal string. Always the same.

**Comment by timotheecour** [comment]
can't reproduce. works on 1.2.0, 1.0.6 and on latest devel c2699648604cc57cd55ecd7d88ccd55ed38099fb   (using windows 10)

* @faulander please don't post images, use code and expected output in plain test as in all other issues
* @faulander as mentioned in https://github.com/nim-lang/Nim/issues/13971#issuecomment-613140405 please always mention which version of nim (either git tag or git hash) you're using, otherwise it's not actionable; can this be closed?

**Comment by Araq** [comment]
Can't reproduce.
