### ISSUE TITLE
nim -r option must be valid only when compiling

### ISSUE THREAD

**Issue by pmetras** [nim-lang/Nim#13974]
Nim compiler `-r` option can be used with `doc` command, for example, and will produce an error message.

### Example
```sh
$ nim doc -r tutu
...
Hint: 16297 LOC; 0.202 sec; 15.918MiB peakmem; Debug build; proj: ./tutu; out: ./tutu.html [SuccessX]
Hint: ./tutu.html  [Exec]
sh: 1: ./tutu.html: Permission denied
Error: execution of an external program failed: './tutu.html '
```

### Expected Output
```sh
$ nim doc -r tutu
Invalid option `-r`. Can be used only with commands `c`, `compile`, `js`, `cc`...
TO BE COMPLETED WHERE VALID.
```

### Possible Solution

* Don't write anything!
* Don't use `-r`.

```
$ nim -version
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by metagn** [comment]
[Relevant if/else block](https://github.com/nim-lang/Nim/blob/c2699648604cc57cd55ecd7d88ccd55ed38099fb/compiler/nim.nim#L104)

Could use [browsers.openDefaultBrowser](https://nim-lang.org/docs/browsers.html#openDefaultBrowser%2Cstring) too. The valid command line options for running a binary seem to be `{cmdCompileToC, cmdCompileToOC, cmdCompileToCpp}` and i guess also `cmdCompileToLLVM`, and if browsers are going to be used then you can group `cmdRst2html`  with `cmdDoc`.

**Comment by timotheecour** [comment]
I agree, it should work and use browsers.openDefaultBrowser. I have another branch ( no PR yet) where `nim js -r -d:nimbrowser main` works by opening browser instead of running node (which is via `nim js -r -d:nodejs main`) ; it does a few more things like opening a template html that links the js and displays the output etc.

but for `nim doc -r main` it should be as simple as opening the browser

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/14285
