### ISSUE TITLE
Documentation nonexistent quitprocs module

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#14331]
- https://nim-lang.org/docs/quitprocs.html 
- Listed on TheIndex https://nim-lang.org/docs/theindex.html
- Theres no `quitprocs.nim` on Nim git repo.
- This is a reoccurring bug  https://github.com/nim-lang/Nim/issues/12279#issue-499195707 Something is necromancing this bug.

**Comment by timotheecour** [comment]
my guess is that this was never committed to nim repo, according to `git log -SaddQuitClosure`, and that @araq probably has this implemented in one of this branches (and committed the docs https://nim-lang.org/docs/quitprocs.html) but it never made it to Nim.
@araq maybe you can have luck with `git log -SaddQuitClosure --all` in your local Nim repo?

**Comment by timotheecour** [comment]
* new modules should be under std => lib/std/quitprocs.nim instead of lib/pure/quitprocs.nim

* this is useful but also a bit buggy:
```nim
import std/quitprocs

proc fun1() {.noconv.} = echo "ok1"
proc fun2() = echo "ok2"
proc fun3() {.noconv.} = echo "ok3"
proc fun4() = echo "ok4"

addQuitProc(fun1)
addQuitClosure(fun2)
addQuitProc(fun3)
addQuitClosure(fun4)
```

prints

ok3
ok4
ok2
ok1

instead of what a user would expect:
ok4
ok3
ok2
ok1

why not instead overload `addQuitProc` and user can pass a closure or proc with same API, but more importantly order would be preserved (reverse order)?

**Comment by Araq** [comment]
Well, it's a start....

**Comment by juancarlospaco** [comment]
Thanks, awesome. :slightly_smiling_face:
