### ISSUE TITLE
[Regression] karax events are not firing 

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#14350]
Regression caused by https://github.com/nim-lang/Nim/pull/14158

Test case
```nim
proc render(): VNode =
  result = buildHtml(tdiv(class="normalDiv")):
    label(`for`=comboID):
      text "default should be C"
      br()
      select(id=comboID):
        for p in ["A", "B", "C", "D"]:
          if p=="C":
            option(selected="true"): text p.kstring
          else:
            option: text p.kstring
```
Combobox should be in position `C` but after https://github.com/nim-lang/Nim/commit/707367e1ca231d964ba82a92b642eb5efdc1aa7c, it remains in position A.

**Comment by cooldome** [comment]
@hlaaftana, could you please have a look. PR was far too big to easily nail down the problematic part. Thank you.

**Comment by metagn** [comment]
Without PR:

```html
<select id="comboID">
  <option>A</option>
  <option>B</option>
  <option selected="true">C</option>
  <option>D</option>
</select>
```

With PR:

```html
<select id="comboID" class="">
  <option value="" id="" class="">A</option>
  <option value="" id="" class="">B</option>
  <option value="" id="" class="" selected="true">C</option>
  <option value="" id="" class="">D</option>
</select>
```

#14158 made it so uninitialized seqs/strings weren't `null` anymore. This is a pretty important change that probably should have been communicated better. Karax doesn't seem to generate tag attributes when the value is `null` (uninitialized strings before PR) and generates them when they are an empty ~~string (uninitialized strings after PR). So something somewhere should be a `Option[string]` in Karax, though I understand this sacrifices performance, which could be fixed with a rewrite of the `options` module for JS that treats `null` as `None`.~~ The `id` and `class` attributes and I'm guessing also the `value` attribute in Karax are `cstring`s which can be `null` with the PR, but are initalized as empty cstrings which is inconsistent with C backend.

```nim
var s: cstring
echo s == cstring"" # true with PR, false without PR or on C backend
echo s == cstring(nil) # false with PR, true without PR or on C backend
```

It's a [one line change](https://github.com/nim-lang/Nim/blob/278b4582f5c7cc3471bccc4ba587030edf7a50e2/compiler/jsgen.nim#L1693-L1694) to fix this, instead of generating `""` we generate `null`.
