### ISSUE TITLE
`nim doc` recursive should allow specifying a directory and flattened structure

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#14376]
Currently using the nim doc for the global project via

nim doc --project --index:on --git.url:<url> --git.commit:<tag> <main_filename>.nim
nim buildIndex -o:htmldocs/theindex.html htmldocs

will recursively generate doc for each Nim file of the project and put them next to the Nim files.

Providing the options to:
- Put all the docs in a target directory (keeping the original hierarchy)
- Put all the docs in a target directory (using a flattened hierarchy)

would help automating doc generation and their publication.

**Comment by timotheecour** [comment]
did you see https://github.com/nim-lang/Nim/pull/13223#issuecomment-582688394 ?
this works:
```nim
nim doc --project --index:on --outdir:htmldocs compiler/nim.nim
nim buildIndex -o:htmldocs/theindex.html htmldocs
```

https://github.com/nim-lang/Nim/pull/13223 made `--project` more reliable, as well as introducing `--docroot` but there are more things that need to be fixed:
- [x] `nim buildIndex -o:htmldocs/theindex.html htmldocs` extra step shouldn't be needed and be implied by `--index:on` (or at least have option for that since it's what you'll often want to have and it's more DRY)
- [x] fix a recent regression introduced sometime after https://github.com/nim-lang/Nim/pull/13223 where `--docroot` would cause `nimdoc.out.css` to be misplaced
- [x] `dochack.js` should be installed by default when you use `--project` so that search works by default
- [ ] I can't think of a valid use case for `recursively generate doc for each Nim file of the project and put them next to the Nim files` so IMO we should make `--outdir:htmldocs` be implied as a default (unless overridden by some flag, eg `--outdir:xxx`); in fact it's downright harmful to do so as it clobbers your sources (or worse, could potentially overwrite some files in your sources) and may be hard to gitignore if you have other html files etc; if really needed we can add an option (off by default) to output each generated file next to its source
- [x] likewise https://github.com/nim-lang/Nim/issues/6583 regression is related (outputs to `$pwd`, which has similar drawbacks) ; I'm fixing that in a PR, where it'll probably default to htmldocs (like it did at some point in nim history IIRC)
- [x] (EDIT) update https://nim-lang.github.io/Nim/docgen.html to reflect reality

`nim doc` is special because it installs other things (eg nimdoc.out.css, idx files, html files, and subdirs) so it really should be encapsulated inside htmldocs (by default) to avoid clobbering either pwd or source files


> Put all the docs in a target directory (using a flattened hierarchy)

I had originally suggested that to deal with design issues with the old `--project` semantics (relative imports + module name clashes) but see discussion here https://github.com/nim-lang/Nim/issues/13150#issuecomment-575401029 which led to the new semantics in https://github.com/nim-lang/Nim/pull/13223

**Comment by mratsim** [comment]
Ah the docgen documentation is lagging behind

**Comment by timotheecour** [comment]
@mratsim https://github.com/nim-lang/Nim/pull/14324 should fix this (in particular all points mentioned in https://github.com/nim-lang/Nim/issues/14376#issuecomment-630006752); see that comment for why we don't have a `flattened structure` option.
feel free to chime in
