### ISSUE TITLE
`foldr` raises IndexError when called on sequence

### ISSUE THREAD

**Issue by refracted** [nim-lang/Nim#14404]
### Example
```nim
echo toSeq(1..10).foldr(a + b)
```

### Current Output
```
Error: unhandled exception: index 10 not in 0 .. 9 [IndexError]
```

### Expected Output
```
55
```

### What works

The following all work as expected.

```nim
echo foldr(toSeq(1..10), a + b)

echo foldl(toSeq(1..10), a + b)

echo toSeq(1..10).foldl(a + b)
```

### nim version
```
$ nim -v
Nim Compiler Version 1.2.0 [Linux: amd64]
```

**Comment by timotheecour** [comment]
woks at proc scope, fails at module and block scope (as of 16003bffe1ceef0b57ecccef23be31f760120f89 1.3.5)
```nim
import sequtils
template fun = echo toSeq(1..10).foldr(a + b)
proc main=fun()
main() # works
block: fun() # fails
fun() # fails
```

@refracted always check against latest devel when reporting issues (in this case it does fail in devel, but oftentimes it's a bug that was recently fixed in devel); also make sure example is self contained (i had to add `import sequtils`); other than that it's a good, valid bug report
