### ISSUE TITLE
Documentation needed for re.split behavior regarding zero-width chars

### ISSUE THREAD

**Issue by capocasa** [nim-lang/Nim#14469]
re.split [behaves in an unexpected way](https://github.com/nim-lang/Nim/issues/14468) which [won't be changed](https://github.com/nim-lang/Nim/issues/14468#issuecomment-634603421_), so the behavior needs to be documented.

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/issues/14468#issuecomment-635191438

> PRs are welcome

PR sounds more productive than documenting something odd; since there is some reasonable disagreement amongst libraries (see https://github.com/nim-lang/Nim/issues/14468#issuecomment-635189566) I suggest starting with non-controversial fixes first; @capocasa do you want to close this and instead open a PR to fix https://github.com/nim-lang/Nim/issues/14468 ?

**Comment by capocasa** [comment]
@timotheecour 

> PR sounds more productive than documenting something odd

Agreed.

> close this and instead open a PR to fix #14468

Maybe- would it be feasible to reopen it? And could possible issues have a target to select "1.x" or "dev"?

**Comment by timotheecour** [comment]
> Maybe- would it be feasible to reopen it? 

i reopened

> And could possible issues have a target to select "1.x" or "dev"?

easiest is to target devel and backport on a best effort basis to 1.x
