### ISSUE TITLE
`typed` resolves to `nkSym` instead of `nkClosedSymChoice` if symbol is in system

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#14605]
The intent was to pass a user defined proc to a macro to investigate if a parameter of that proc is a var parameter. Works fine when there is only one proc with that name. But

```nim
import macros
import math

macro inspect*(p: typed): untyped =
  echo $p
  echo p.getImpl().toStrLit

proc p1(i: int) =
  echo i * i

proc len(s: string): int =
  13

proc sin(i: int): int =
  0

inspect(p1)
inspect(len)
inspect(sin)
```

```
$ nim c t.nim 
Hint: used config file '/home/stefan/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/stefan/Nim/config/config.nims' [Conf]
.......
p1
proc p1(i: int) =
  echo [i * i]

len
proc len[U; V](x: HSlice[U, V]): int {.noSideEffect, inline.} =
  ## Length of ordinal slice. When x.b < x.a returns zero length.
  ## 
  ## .. code-block:: Nim
  ##   assert((0..5).len == 6)
  ##   assert((5..2).len == 0)
  result = max(0, ord(x.b) - ord(x.a) + 1)

sin
stack trace: (most recent call last)
/tmp/examples/gtk3/t.nim(6, 9) inspect
/tmp/examples/gtk3/t.nim(19, 8) template/generic instantiation of `inspect` from here
/tmp/examples/gtk3/t.nim(6, 9) Error: node is not a symbol
stefan@nuc /tmp/examples/gtk3 $ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-06-08
```

Output for p1 is fine, for len it is strange that we seems to get a system proc, and for sin we get "node is not a symbol" which is not a very helpful error message.

**Comment by timotheecour** [comment]
using p.treeRepr explains why:

```nim
ClosedSymChoice
  Sym "sin"
  Sym "sin"
  Sym "sin"
```

I really wish the compiler code would start using custom assert macros to provide helpful diagnostics:
instead of this (which is the code triggering your error message):
```nim
      if a.kind == nkSym:
        someImpl
      else:
        stackTrace(c, tos, pc, "node is not a symbol")
```
which generates a fixed error strings (eg `"node is not a symbol"`) without telling you what node kind was used, a custom assert macro would provide helpful contextual runtime information, eg: 
```
      myassert a.kind == nkSym
      # myassert a.kind == nkSym, $("node is not a symbol", typ.kind, otherVariable == nil) # in case other relevant context is needed
      someImpl
```
would show: stacktrace + expression that failed + values, just like in `unittest.check`
* simpler, shorter code and control flow
* and yet, it gives better diagnostic as it shows the relevant runtime information

I doubt this would increase compile times at all, and even if it did, a simple flag could turn on/off extended diagnostics.

if unittest.check is overkill, than a a 90% solution can be used, that would at least handle the common case of `a == b`, and show the values of `a` and `b`

**Comment by Araq** [comment]
Huh? assertions for compiler error messages is non-sense. We can improve the compiler's error messages without relying on hacks.

**Comment by timotheecour** [comment]
custom assertions is not the same as calling assert and crashing on error, i meant a custom assert that calls `liMessage` when condition fails, see https://github.com/nim-lang/Nim/pull/14613

**Comment by StefanSalewski** [comment]
Note that this issue is not about error messages only, it is more about the len proc. See

https://irclogs.nim-lang.org/08-06-2020.html#15:04:58

```
Salewski: For the sin() procs echo p[0].getImpl().toStrLit seems to work at least.
Salewski:But len() seems to be bound by system module already.
Araq: you macro needs to handle nkSymChoice
Araq: never mind, it's a bug
Araq: cannot get it to produce a sym choice either
```

**Comment by timotheecour** [comment]
i see...

interestingly, bindSym doesn't have this bug:
```nim
when defined case2:
  import macros
  type Foo = object
  proc len(s: Foo): int = 13
  {.push experimental:"dynamicBindSym".}
  macro inspect2*(): untyped =
    let p2 = bindSym"len"
    echo p2.treeRepr
    for ai in p2: echo ai.owner.repr
  macro inspect3*(s: static string): untyped =
    let p2 = bindSym(s)
    echo p2.treeRepr
    for ai in p2: echo ai.owner.repr

  inspect2()
  inspect3("len")
```
=> will show the correct sym in the list
