### ISSUE TITLE
Create a Complex[T] from polar coordinates

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#14731]
### Summary
Add a function to the `complex` module, that allows to easily create a `Complex[T]` from polar coordinates. There already is the `polar` proc, to convert a complex number **to** polar coordinates and this would complement it nicely.

### Description
```nim
proc fromPolar*[T](rho, theta: T): Complex[T] =
  ## Create a complex number from polar coordinates
  result.re = rho * cos(theta)
  result.im = rho * sin(theta)
```

### Alternatives
Provide no such function.

### Additional Information
[Wikipedia](https://en.wikipedia.org/wiki/Polar_coordinate_system#Complex_numbers)

**Comment by timotheecour** [comment]
there's already `rect` that does that but I don't like it because it sticks out like a sore thumb:
* the name is not so good, `fromPolar` as you suggest is better and more discoverable as inverse of `polar`
* it should take its input as a tuple, which would match the output of `proc polar*[T](z: Complex[T]): tuple[r, phi: T] =`

so +1 for me for the following:
* add fromPolar as follows:
```nim
proc fromPolar*[T](a: tuple[r, phi: T]): Complex[T] = ...
```
* cross fromPolar and polar in their doc-comments
* deprecate `rect`

**Comment by b3liever** [comment]
Tuple as input? but why?

**Comment by konsumlamm** [comment]
Closing, see https://github.com/nim-lang/Nim/pull/14740#issuecomment-647016556.
