### ISSUE TITLE
Typo in sumKbn (from sums)

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#14734]
Given that [`sumKbn`](https://nim-lang.github.io/Nim/sums.html#sumKbn%2CopenArray%5BT%5D) implements Ka**h**an summation, this is likely a typo and should be `sumKhn`. I don't know if fixing this would be considered a  breaking change, but it is worth mentioning.

EDIT: I assume the solution is to deprecate `sumKbn` and make it an alias for `sumKhn`.

**Comment by timotheecour** [comment]
@konsumlamm 
~~was a typo introduced in https://github.com/nim-lang/Nim/pull/9284~~
please send PR as follows:
* rename to `sumKahan` (no need for abbreviation `sumKhn`) and change the 4 usages in nim repo to the new name
* and simply add this: `{.deprecated: [sumKbn: sumKahan].}`~~

EDIT: see next comment...

**Comment by timotheecour** [comment]
EDIT: actually, it's not a typo, it's an acronym for Kahan-Babuška-Neumaier summation http://support.hfm.io/1.3/api/math-functions-0.1.7.0/Numeric-Sum.html#t:KBNSum

**Comment by konsumlamm** [comment]
Interesting, though the doc comment only mentions Kahan. I guess I should close my PR then?

**Comment by timotheecour** [comment]
@konsumlamm instead of closing it let's improve things.

from http://blog.zachbjornson.com/2019/08/11/fast-float-summation.html

>  Kahan summation is the most famous algorithm; it's simple and effective. Neumaier's improved version ("Kahan-Babuška Algorithm") is correct in some cases where Kahan is not, but is significantly slower.

sumKbn is indeed implementing https://en.wikipedia.org/wiki/Kahan_summation_algorithm#Further_enhancements, not the original kahan algorithm, but the next question is: since it's significantly slower, we may want to:
* clarify all this in doc comments for `sumKbn` (maybe just make your PR do just that for starters)
* introduce `sumKahan` which implements the original Kahan summation, after writing a small benchmark to test for accuracy + speed
* explain speed vs accuracy tradeoff in doc comments; linking to http://blog.zachbjornson.com/2019/08/11/fast-float-summation.html or relevant resource is always a good idea as well

**Comment by planetis-m** [comment]
I think it is a exaggeration to add kahan algorithm (which also has problems with optimizing compilers), since faster method of pairwise summation is also provided. Also [see](https://rosettacode.org/wiki/Kahan_summation)

**Comment by jibal** [comment]
> Given that sumKbn implements Kahan summation, this is likely a typo and should be sumKhn.

I think this warranted _a lot_ more investigation before running off and making a change.

**Comment by Clyybber** [comment]
It wasn't renamed.

**Comment by jibal** [comment]
> It wasn't renamed.

Yes, I can read. That's not the point.

**Comment by konsumlamm** [comment]
> I think this warranted _a lot_ more investigation before running off and making a change.

It isn't obvious at all that `sumKbn` refers to Kahan-Babuška-Neumaier summation, as both the docs and the PR that added it just call it Kahan summation.

**Comment by jibal** [comment]
> 
> 
> > I think this warranted _a lot_ more investigation before running off and making a change.
> 
> It isn't obvious at all that `sumKbn` refers to Kahan-Babuška-Neumaier summation, as both the docs and the PR that added it just call it Kahan summation.

Who said anything about obvious? Like I said ... "a lot more investigation". What was even less obvious was that sumKbn was a typo for sumKhn ... that was extremely unlikely, and even considering such a change was unwarranted. My comment stands, and I'm unsubscribing.
