### ISSUE TITLE
Iterator for heapqueue

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#14809]
I noticed that there doesn't seem to be a method to iterate over a `HeapQueue`. Is there something I'm missing?

One way I could imagine this should look like is this:
```nim
iterator items[T](var heap: HeapQueue[T]): T =
  while heap.len != 0:
    yield heap.pop()
```

**Comment by Araq** [comment]
Why do you need it? And the proposed implementation is non-idiomatic, iteration shall not be destructive.

**Comment by konsumlamm** [comment]
> Why do you need it?

I just thought it would be nice to be able to iterate over a `HeapQueue`. Maybe one wants to convert it to a `seq`.

> And the proposed implementation is non-idiomatic, iteration shall not be destructive.

In that case, I think just doing the iteration manually (i.e. by calling `pop` repeatedly) is fine there.

What about a function to iterate over it in an unspecified order, i.e. something like this:
```nim
iterator items[T](heap: HeapQueue[T]): T =
  for i in 0 .. heap.len - 1:
    yield heap[i]
```

**Comment by jibal** [comment]
[Priority queues](https://en.wikipedia.org/wiki/Priority_queue) don't normally have an enumeration operation. If someone needs that, they are probably misusing the data structure. But if they really need it, they can pop each item and add it to another queue, and then replace the old queue with the new queue. that would give them the items in the correct order. A non-destructive iterator that returned items in random order would be a trap for the unwary.

Adding such things to the API doesn't come free, and "would be nice" is the road to bloat.  I suggest that there are better uses of resources.

```nim
iterator items[T](heap: HeapQueue[T]): T =
  for i in 0 .. heap.len - 1:
    yield heap[i]
```

Yes, you can do that because `HeapQueue` exposes `[]`, which strikes me as a mistake in the API--it makes it impossible to replace the implementation of `HeapQueue` with one that isn't based on an array. Then again, the stdlib `HeapQueue` just guarantees that a priority queue is available out of the box. More performant queues (e.g., ranked pairing) can be added to nimble.

**Comment by konsumlamm** [comment]
Ok, fair.
