### ISSUE TITLE
Please revert my commit

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14930]
Hello,

due to the recent events in the Nim-lang community, I don't want to be associated with the project anymore. 
As a small request, I would like the commit 3e843ab335817cd4a111b56574575c2c841b40ed, which I contributed, to be reverted.

Thanks in advance and have a nice day

**Comment by HugoP707** [comment]
imho, having problems with some people of the community should not depend on wether you collaborate in a GitHub project like this, it’s a ahem you want to do it 😕

**Comment by ghost** [comment]
A former Nim-lang contributor was harrassed and attacked by community members. They were misgendered and deadnamed intentionally, which can hurt a lot. 

Because of this, they asked politely for cosmetic changes they contributed to be removed from the project (reverted), which is their personal right according to section 6 of the berne convention. This started more hateful moves. The project lead reverted the commit and sent them an invoice for the supposed work it created.

The project lead supported this behaviour and helped to erase evidence of what was happening. Discussions on IRC/Discord were deleted, the user was banned from Discord without a real reason.

**Comment by Yardanico** [comment]
@petabyteboy I'd like to correct you on something - discussions on IRC/Discord were not deleted at all, they're all still there.

**Comment by ghost** [comment]
Thanks for the correction @Yardanico, I thought I had seen something on IRC discussions in the distant past being deleted from the irc logs server.
However, many comments from the GitHub pull request were definitely removed by the nim-lang GitHub account, which seemed really shady to me.

**Comment by dom96** [comment]
I am really sorry that you do not wish to be a part of this community anymore. I am happy to revert the commits you have referenced and will do so now.

Some things that I would like to clarify with regards to your points.

> They were misgendered and deadnamed intentionally, which can hurt a lot.

I have looked at the IRC logs and could not find any evidence of anyone intentionally misgendering or deadnaming Simula or other transgendered members of our community (I searched in the time period where Simula and BornInWinter were active, +- 2 hours). I do realise that there was some confusion, some members of our community did indeed default to masculine pronouns. Myself and trans members of the community have spoken with these individuals about the importance of pronouns and they are trying to be better on this. I'm sorry for any pain it would understandably have caused.

> This started more hateful moves. The project lead reverted the commit and sent them an invoice for the supposed work it created.

I've just been made aware of this email and haven't had a chance to properly discuss it yet. From what I can see it's a poor joke and not something I approve of.

> The project lead supported this behaviour and helped to erase evidence of what was happening. Discussions on IRC/Discord were deleted, the user was banned from Discord without a real reason.

> Thanks for the correction @Yardanico, I thought I had seen something on IRC discussions in the distant past being deleted from the irc logs server.

Funnily enough I have actually asked @Yardanico to remove the comment that you are responding to. The reason I asked Yardanico to remove it is because I wanted a chance to confirm that no Discord/IRC messages have been removed. I have looked at the Discord audit logs and see no message deletions there:

![Annotation 2020-07-07 184805](https://user-images.githubusercontent.com/246651/86823328-a1bdad80-c084-11ea-9e80-1d689c2c895c.png)

Furthermore, IRC logs are only accessible by a select few (and would require logging into our servers) so it's very unlikely they would have been removed. But you can cross check them against Discord as these chat rooms are bridged.

> However, many comments from the GitHub pull request were definitely removed by the nim-lang GitHub account, which seemed really shady to me.

I'm looking into all aspects of this. Would you mind linking me to the GitHub pull requests where this occurred?

I want to reiterate and emphasise that I personally care a lot about this, I have reached out to Simula separately and opened a channel to discuss what happened. Just like I have done with other trans members of our community. Please feel free to get in touch with me (email at picheta.me) if you (or anyone reading this) has something to say regarding this and I will take it on board.

**Comment by planetis-m** [comment]
I have not taken any part in the brawl but I am hanging at the channel and read some of the exchanges.

...And I have completely different recollections of what happened. First of no one attacked that person! NO ONE.

Instead that person harassed another person in the community and started spamming. He who was attacked by them asked to ban them from discord. Rightfully so. Irc logs prove that.

Then went on at a twitter clone and started spreading lies that people was intolerant towards them. (Frankly when someone causes trouble and has antisocial behavior people get irritated.)

That person also attacked someone who tried to have a conversation with them (another member of nim community) and also swore at them.

Not to mention opening issues to revert a commit that just recapitalizes identifiers (and threatened with lawsuits)!

This behavior is uncivilized and shows weak character.

**Comment by b3liever** [comment]
I just want to add that we are all humans and sometimes we get pissed of at various things. Sometimes our anger is justified, sometimes we misjudge a situation. I have got into fights over nothing and accepted I was wrong. However I really dislike people who take it too far and are vengeful.

Disengage, forgive and forget is my advise to you and everyone else.

Bless your heart!
