### ISSUE TITLE
OrderedTable del and pop are slow

### ISSUE THREAD

**Issue by hashbackup** [nim-lang/Nim#14971]
Below are some small test programs that add items to an ordered hash table then delete them in the same order as added, to understand a performance problem that was noticed while experimenting with tiny_sqlite's statement cache based on OrderedTable.

Compiles are with Nim 1.3.5 using --gc:arc.  With Nim 1.2, results will be very different & somewhat confusing because 1.2 used an identity hash function while 1.3 uses a real hash function.  1.2 is sometimes faster, sometimes slower, but is unpredictable because of collision clustering, whereas 1.3 is more consistent.  

The test programs are:
* Nim's OrderedTable
* Python 3 dicts (ordered since 3.7)
* Nim package https://github.com/jackhftang/lrucache.nim
* Nim package https://github.com/Lemonboy/compactdict

Nim's OrderedTable:
```
import tables
import times

const
  els = 50_000

var
  ot = initOrderedTable[int, int](els)

var t0 = cpuTime()
for i in 0 ..< els:
  ot[i] = i
echo "len = ", len(ot), ", seconds to create table: ", cpuTime() - t0

t0 = cpuTime()
for i in 0 ..< els:
  ot.del(i)
echo "Seconds to delete table: ", cpuTime() - t0

ms:nx jim$ nim c -d:danger --gc:arc ordtable1
Hint: 41563 lines; 0.859s; 49.367MiB peakmem; Dangerous Release build; proj: /Users/jim/nx/ordtable1; out: /Users/jim/nx/ordtable1 [SuccessX]
```
OrderedTable with 50K items:
```
ms:nx jim$ /usr/bin/time -l ./ordtable1
len = 50000, seconds to create table: 0.0006670000000000001
Seconds to delete table: 13.850194
       13.85 real        13.83 user         0.02 sys
   8978432  maximum resident set size
```
OrderedTable with 100K items to see how it scales (quadratic):
```
ms:nx jim$ /usr/bin/time -l ./ordtable1
len = 100000, seconds to create table: 0.001153
Seconds to delete table: 59.89174999999999
       59.90 real        59.83 user         0.06 sys
  17375232  maximum resident set size
```
Python 3 built-in dict:
```
import time

els = 100000
map = {}
t0 = time.time()
for i in range(els):
  map[i] = i
t1 = time.time()
print('Created %d item dict in %.2f secs' % (len(map), t1 - t0))

t0 = t1
for i in range(els):
  del map[i]
print ('Deleted items in %.2f secs' % (time.time() - t0))
```
Python 3 with 100K items:
```
ms:nx jim$ /usr/bin/time -l py3 ordtable3.py
Created 100000 item dict in 0.02 secs
Deleted items in 0.02 secs
        0.08 real         0.04 user         0.00 sys
  18411520  maximum resident set size
```
Python 3 with 1M items to see how it scales:
```
ms:nx jim$ /usr/bin/time -l py3 ordtable3.py
Created 1000000 item dict in 0.20 secs
Deleted items in 0.17 secs
        0.45 real         0.35 user         0.05 sys
 121114624  maximum resident set size
```
Nim package LruCache
```
import lrucache
import times

const
  els = 100_000

var
  lru = newLruCache[int, int](els)

var t0 = cpuTime()
for i in 0 ..< els:
  lru[i] = i
echo "len = ", len(lru), ", seconds to create table: ", cpuTime() - t0

t0 = cpuTime()
for i in 0 ..< els:
  lru.del(i)
echo "Seconds to delete table: ", cpuTime() - t0
```
LruCache with 100K items:
```
ms:nx jim$ /usr/bin/time -l ./ordtable2
len = 100000, seconds to create table: 0.018195
Seconds to delete table: 0.011533
        0.04 real         0.02 user         0.00 sys
  11767808  maximum resident set size
```
LruCache with 1M items to see how it scales:
```
ms:nx jim$ /usr/bin/time -l ./ordtable2
len = 1000000, seconds to create table: 0.208906
Seconds to delete table: 0.154687
        0.40 real         0.36 user         0.03 sys
  99672064  maximum resident set size
```
Nim package compactdict
```
import compactdict
import times

const
  els = 100_000

var
  map = initDict[int, int](els)

var t0 = cpuTime()
for i in 0 ..< els:
  map[i] = i
echo "len = ", len(map), ", seconds to create table: ", cpuTime() - t0

t0 = cpuTime()
for i in 0 ..< els:
  map.del(i)
echo "Seconds to delete table: ", cpuTime() - t0
```
Nim package compactdict 100K items:
```
ms:nx jim$ /usr/bin/time -l ./comptable
len = 100000, seconds to create table: 0.007076000000000001
Seconds to delete table: 0.003003
        0.01 real         0.00 user         0.00 sys
   6864896  maximum resident set size
```
Compactdict with 1M items, to see how it scales:
```
ms:nx jim$ /usr/bin/time -l ./comptable
len = 1000000, seconds to create table: 0.168201
Seconds to delete table: 0.09213499999999999
        0.28 real         0.24 user         0.02 sys
  51707904  maximum resident set size
```
I didn't check, but believe OrderedTable.pop() is also affected by this since it uses del().  From what I can tell (take this with a grain of salt!) OrderedTable creates a hash table with each item having an extra field for a singly-linked list that preserves ordering.  Every call to del() builds an new hash table by traversing the entire list looking for matching items, ignoring them, and adding all non-matching items to the new table it is building.

Since it is already traversing the whole list, a simple improvement would be to delete matching items from the hash table and adjust the list by keeping track of the previous entry and setting its next pointer to bypass the deleted item.  This would avoid creating a new hash table but would still be O(n) and not recommended.

Python dicts have been ordered since 3.7, even across deletes, using the new "compact dict" data structure.

The LruCache version is faster because: a) it doesn't create a new data structure on every delete; and b) it uses a doubly-linked list, finds the item to delete via the hash table, deletes it from the hash table, then only has to update a couple of pointers to remove an item from the list.  This is O(1) rather than O(n).

The Nim compactdict package provides the Python 3 compact dict struct to Nim.

I did not do any serious testing of any of these packages to check their scalability, check edge cases, etc.   There may also be issues with Nim (sometimes?) allowing duplicate hash table entries, a feature I find rather odd and unexpected.

Based on the limited testing I have done, I'd recommend replacing OrderedTable with either compactdict or a modified version of LruCache w/o the LRU code:
* compactdict uses less memory (half as much as LruCache for 1M items)
* it runs faster
* it would be nice to provide Python users with a data structure with a similar performance profile to the built-in Python dict
* ~~but compactdict appears to have a scaling problem that Python3 and LruCache do not: 1M deletes with compactdict is 30x slower than 100K deletes instead of 10x slower.~~

EDIT: compactdict does not have a scaling problem.  I think it is just very fast and CPU cache efficient at small sizes so not possible to compare with larger sizes.  See scaling tests below.

**Comment by hashbackup** [comment]
I made the simple modification mentioned above to OrderedTable:
```
proc del*[A, B](t: var OrderedTable[A, B], key: A) =
  ## Deletes ``key`` from hash table ``t``. Does nothing if the key does not exist.
  ##
  ## O(n) complexity.
  ##
  ## See also:
  ## * `pop proc<#pop,OrderedTable[A,B],A,B>`_
  ## * `clear proc<#clear,OrderedTable[A,B]>`_ to empty the whole table
  runnableExamples:
    var a = {'a': 5, 'b': 9, 'c': 13}.toOrderedTable
    a.del('a')
    doAssert a == {'b': 9, 'c': 13}.toOrderedTable
    a.del('z')
    doAssert a == {'b': 9, 'c': 13}.toOrderedTable

  if t.counter == 0: return
  var
    h = t.first
    p = -1
  let hc = genHash(key)
  while h >= 0:
    var nxt = t.data[h].next
    if isFilled(t.data[h].hcode) and t.data[h].hcode == hc and t.data[h].key == key:
      if p >= 0:
        t.data[p].next = t.data[h].next
      else:
        t.first = t.data[h].next
      if t.data[h].next == -1:
        t.last = p
      delImplIdx(t, h)
    else:
      p = h
    h = nxt
```
It does reduce the test runtime for 100K items from 60s to 21s and reduces memory from 17M to 9M, but is still O(n) and nowhere near the better implementations' performance.

EDIT: removed ` dec t.counter` because `delImplIdx` does that.

**Comment by hashbackup** [comment]
The non-linear behavior of compactdict was bothering me, so I ran tests with 1M, 2M, 4M and 8M items for both compactdict and LruCache:
|Type|Items|Time|Ratio|Memory|Ratio|
|-|-|-|-|-|-|
|Compact|1M|0.25s||52M||
||2M|0.60|2.4|116|2.2|
||4M|1.24|2|238|2|
||8M|2.74|2.2|396|1.6|
|LRU|1M|0.40s||100M||
||2M|0.82|2|199|2|
||4M|1.64|2|397|2|
||8M|3.42|2.1|793|2|

I thought compactdict had a scalability problem, but based on this test, it doesn't.  What I think may have been happening is that at the smaller sizes, compactdict is very CPU cache efficient and fast,  so when comparing 100K vs 1M, there is a point where cache is not as effective as it was for smaller sizes and the two can't be compared.

Compactdict is faster and uses less memory than LruCache at all sizes.  It is also more complex, with 295 LOC vs 136 for LRU (and some of those LRU lines would be unnecessary), so that may also be a consideration. LemonBoy, the author, has archived compactdict.

Another possibility is to use the simpler design of LruCache for OrderedTable now, to keep short-term risk low, then later either add a new DictTable to collections based on compactdict or replace OrderedTable again with compactdict.  I would not advocate replacing Table with compactdict because at large sizes (10M items) compactdict uses 40% more memory and is 2.7x slower than Table.

Either LruCache or compactdict would be a huge improvement over the existing OrderedTable, where del and pop are so slow that they should never be used, or at least should have a note in the documentation that they have an extremely high cost and should be avoided if possible.

**Comment by c-blake** [comment]
First I would say that these observations seem sound.  It indeed seems that the current stdlib impls of those removes are documented as inefficient.  That is likely only about allocating core dev work hours than any kind of opinion that it should be slow.

The compact dict from @LemonBoy  uses a suboptimal probe sequence for out of L3 cache tables.  I implemented one of these using linear probing with optional Robin Hood re-org in https://github.com/c-blake/adix/tree/master/adix called `OLSet` and `OLTab`.  That should be a bit faster.  The LRU from @jackhftang uses the regular stdlib Table.  That should be fast except for two things A) iterating will always be slower compared to the compact/indexed style since hopping a linked list in hash order obviously cannot compete with iterating through a dense `seq` from a memory system perspective and B) that specific impl duplicates storage for keys & values while the stdlib only has an extra link field and so is much more memory efficient.

Since which approach is best - DLL+Table or compact/indexed - depends upon workload (iteration heavy vs random point edits), really one needs both for a fully general system.  Given that the delete functionality itself is very new, this was maybe not in high demand for stdlib until recently.

I think the best approach would be to add an "intrusive" doubly linked list to the stdlib (probably singly linked as well) that allows easy inclusion/mixin of links in some other data structure.  These are much more flexibly re-used and I know @Araq has expressed interest in adding them in the past, though I do not recall where & when..maybe IRC.  With said intrusive linked lists in hand, using the approach of @jackhftang's LRU would use much less memory especially for large `K` and/or `V`.  Then as a totally separate new table type we could call `CompactTable` we can also do the fast-iteration "two level" variant like the `adix` `diset` or `olset`.

Together these changes would also enable moving to optional Robin Hood re-organization of the hash-part of both this new DLL-OrderedTable and `CompactTable` and the main `Table` as well.  Right now one cannot even RH Table since it shares its impl with OrderedTable and the latter has special needs to keep even just insert fast while doing RH re-org (EDITed for clarity).  I think with DLLs we could do a "somewhat" expensive re-ordering to fixup that stuff, but I have never exactly done it before.  So, I might be wrong.

As is well known, that re-org can substantially improve memory density (66% -> 95% is not an crazy expectation, though 90% is more conservative).  Now, re-org is not "free" and sometimes does not "pay off".  Robin Hood works ***really*** well with a high fraction of "miss" searches (like inserts of novel keys or other failed lookups) or if that memory density really helps (iteration, near memory hierarchy cliffs).  The example I always use for a best case for RH is an intersection of two sets expected to be nearly empty.  For that RH can be almost 2x faster due to an "incidental" property of occupied slots being "sorted by distance from their home locations" (so you can stop a failed search 1/2-way through, on average).   Anyway, that "not always useful" property of RH would create a kind of "optionality" we would need to add to all the sets/tables `init` APIs/objects.

I think all these changes could be great and could also be backward compatible, but it's definitely a chunk of work to be done.  Maybe this can be a first PR for @hashbackup?  I can try to help, too if there is interest in these features in the stdlib.

**Comment by hashbackup** [comment]
The simple modification I wrote above to avoid creating a new table doesn't work: if a delete causes Table to do a backshift, it breaks the linked list that OT uses.  That's the reason OT.del was creating a new table.

The LruCache module doesn't have this problem because it stores its data outside the hash table and stores hash(node) in the hash table.  It also uses more memory because of this.

**Comment by jackhftang** [comment]
> B) that specific impl duplicates storage for keys & values while the stdlib only has an extra link field and so is much more memory efficient.

The values are **not** duplicated. The keys is duplicated in a sense that it is kept inside both Table and LruCache internal node. 
The key kept inside LruCache Node is used to remove the corresponding entry in table, when the cache overflow or shrink. In theory, I can store the hash of key and make the space usage independent of sizeof(key)

For your reference, here is the full list of types

```nim
type
  Node[K,T] = object
    key: K
    val: T

  LruCache*[K, T] = ref object 
    capacity: int
    list: DoublyLinkedList[Node[K,T]]
    table: Table[K, DoublyLinkedNode[Node[K,T]]]

  KeyValuePair[A, B] = tuple[hcode: Hash, key: A, val: B]

  KeyValuePairSeq[A, B] = seq[KeyValuePair[A, B]]

  Table*[A, B] = object
    data: KeyValuePairSeq[A, B]
    counter: int

  DoublyLinkedNodeObj*[T] = object
    next*: ref DoublyLinkedNodeObj[T]
    prev*: ref DoublyLinkedNodeObj[T]
    value*: T

  DoublyLinkedNode*[T] = ref DoublyLinkedNodeObj[T]

  DoublyLinkedList*[T] = object
    head*: DoublyLinkedNode[T]
    tail*: DoublyLinkedNode[T]
```

Direct memory usage of LruCache should be

```
let sInt = size of int = size of pointer
let sK = size of Key
let sV = size of Value
let x = number of element
from tables import rightSize

direct_memory_usage = x*(2*sInt+sK+sV) + rightSize(x)*(2*sInt+sK) + constant
```

In your case, sInt = sK = sV = 8

```nim
for i in [1,2,4,8]:
  let x = 1_000_000 * i
  let size = rightSize(x)*24 + 40*x
  echo i, " ", size, " ", size / x

#[ output:
1 82331648 82.331648
2 164663296 82.331648
4 329326592 82.331648
8 658653184 82.331648
]#
```

The memory usage should be 82.3*x bytes and your test showed that the actual multiplier is slightly less than 100. 
I am not sure where the extra 18 bytes per element come from, but I would guess it comes from some housekeepings or allocation alignments inside GC.

**Comment by c-blake** [comment]
Sorry if I misspoke to keys & values instead of just values.  Keys can also be big, though.  You can't, in theory, store just the hash since that could collide for two keys and you would not know which to remove.  Right?  You can't quite store the slot numbers or a pointers to the slots unless you are sure to update them when things get moved around like during delete.  As long as collision clusters are small the updates should be pretty small, I think.  I think @hashbackup has some ideas for solving that aspect.

Just to expand upon my comment, this kind of general purpose `TwoLinks[T] = tuple[prev, next: T]` intrusive field to be added/manipulated could be useful for other things..when you want to maintain "several orders" on some nodes, for example.  It's usually easy to convert from intrusive to external by adding a wrapper `LinkedOb[T, V] = tuple[dll: TwoLinks[T], ob: V]` but not vice versa.  So, intrusive is more general purpose.  Of course, it only works when nodes are kind of free floating not an allocation arena unto themselves the way hash tables are.

**Comment by jackhftang** [comment]
FYI, LruCache 1.0.3 released, which is now storing the hashes of keys instead of keys. 

Space usage become
```
let sInt = size of int = size of pointer
let sV = size of Value
let x = number of element

from tables import rightSize
direct_memory_usage = x*(3*sInt+sV) + 3*rightSize(x)*sInt + constant
```

**Comment by jackhftang** [comment]
right... forget key collision... then need another hash table for enumerating keys and use that ID in both table and list...
