### ISSUE TITLE
Flutter bindings for Nim

### ISSUE THREAD

**Issue by JordyScript** [nim-lang/Nim#15121]
The development of Flutter bindings for Nim would in my opinion be a great boon for the Nim community and ecosystem, as Flutter is fast becoming the most widely supported, and most developer friendly framework for cross-platform GUI application development.

I am not sure if it's technically feasible, but from my limited newbie understanding of Nim and Dart, they have some similarities which would make Nim an excellent candidate for a(n) alternative/replacement for Dart for developing Flutter apps, perhaps increasing performance.

A quick comparison of features that make Dart and Flutter such a suitable combination, which I think also apply to nim: 
- Dart compiles to JavaScript, which enables targetting the web platform, as does Nim
- Dart can be interpreted, thus enabling stateful hot reload for application development, as well as compiled to native binaries, suitable for deployment/production. I understand work has been underway to make Nim capable of stateful hot reloading, while it's already a compiled language.
- Both Dart and Nim are statically typed, making it easier to substitute one for the other.

There may be more similarities that are relevant here, as well as some dissimilarities that i'm not aware of, which may impact the feasibility of this idea. 

I am not familiar with the implementation of Nim, Dart, or Flutter, so this is just a suggestion I make because I'm not aware that anyone has explored this possibility yet. It may not be possible, but if it were possible I expect it would be very good for Nim.

Thank you for your consideration.

**Comment by ghost** [comment]
It's really not possible to actually create real high-level Flutter bindings for Nim because all of Flutter is implemented in Dart. Of course you can make some kind of a Dart -> Nim converter, but that would be a major work.

Even moreso, Dart is mostly using OOP paradigm - "Dart is an object-oriented language with classes and mixin-based inheritance. ", so it would be hard mapping that to Nim's style (even if you can still use methods with inheritance).

The only way you could use Nim with Flutter is via Dart's FFI which is still in beta - https://dart.dev/guides/libraries/c-interop

And really, even if languages have similarities, Dart has a runtime. Also about Dart's "static typing" - it has the "dynamic" type, which really kills the point of static typing IMO.

**Comment by Araq** [comment]
This is the wrong issue tracker, please see https://github.com/nim-lang/needed-libraries/issues
