### ISSUE TITLE
Documentation regression jsre module missing

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#15183]
- https://nim-lang.github.io/Nim/jsre.html
- https://github.com/nim-lang/Nim/blob/devel/lib/js/jsre.nim
- I can confirm it was there some time ago, but it is 404 now.

**Comment by C-NERD** [comment]
You can generate the documentation by typing "Nim doc fullpath to the module"

**Comment by Jjp137** [comment]
Seems to be caused by 4b93c61f0d783cbc1ce35d4494b533186595cdbd. For some reason, jsre was added to the list of modules to be ignored in an attempt to fix a problem with nightly builds. Removing the added line at line 163 of tools/kochdocs.nim and recompiling koch works for me locally, though. I'm not sure what the problem exactly was, though.

**Comment by juancarlospaco** [comment]
Thanks @Jjp137 !; Maybe @narimiran knows best the reason, 
is Ok to disable if it was a Blocker, but should be Fixed on the long run anyways.
:)

**Comment by narimiran** [comment]
Yes, it was causing problems and we have disabled it on purpose.
