### ISSUE TITLE
backticks : Using reserved keywords as identifiers is not documented

### ISSUE THREAD

**Issue by jprochazk** [nim-lang/Nim#15806]
I'm talking about this:
```nim
type MyType = object
  `type`: string
```
Where reserved keywords can be enclosed in backticks to enable their use as identifiers. I tried googling for it, but couldn't find it explicitly documented anywhere.

**Comment by jrfondren** [comment]
Nim in Action specifically highlights it and calls it 'stropping', but the only references to that on nim-lang.org are from IRC logs of people discussing it. If you read through the manual or tutorial you'll run into it frequently, but it's only described as a "common backticks notation".

**Comment by jprochazk** [comment]
I've personally never heard of "Stropping". When I tried searching for "nim stropping", a [wikipedia article](https://en.wikipedia.org/wiki/Stropping_(syntax)#Modern_use) popped up. 
Wouldn't it be worth it add a section/highlight to the manual or tutorial? E.g. rust has [raw identifiers](https://doc.rust-lang.org/edition-guide/rust-2018/module-system/raw-identifiers.html), c# doesn't have a name for it, [but still documents it](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/).

**Comment by metagn** [comment]
Accented identifiers have some weird behavior, like `` `2d` `` translates to the identifier `2.0` instead of `2d`, because `2d` parses as a double precision float and then that float is stringified. The way to make it named `2d` is to do `` `"2d"` ``, which is ugly and you have to use the same syntax every time you invoke that symbol. There is a bit on [identifier construction](https://nim-lang.org/docs/manual.html#templates-identifier-construction) in the manual which is fine for now, to document the specific usage of the accent syntax to strop keywords then you should simply mention it in the [identifiers & keywords](https://nim-lang.org/docs/manual.html#lexical-analysis-identifiers-amp-keywords) section of the manual.

**Comment by timotheecour** [comment]
> Accented identifiers have some weird behavior

https://github.com/nim-lang/Nim/issues/11810 + some other existing issue I couldn't find

**Comment by ringabout** [comment]
> > Accented identifiers have some weird behavior
> 
> #11810 + some other existing issue I couldn't find

https://github.com/nim-lang/Nim/issues/14407

**Comment by Araq** [comment]
This has to be documented and the ``2d`` bug has to be fixed.
