### ISSUE TITLE
Nimsuggest misleads, but newcomers use it by default

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#16001]
Nimsuggest is [infamous for creating error messages](https://twitter.com/lzsthw/status/1326940752597938180) which are confusing. There are plenty of examples of this and newcomers do not realise that it's far more reliable to use `nim` directly to get better error messages. Since fixing Nimsuggest is non-trivial, can we make it clear to newcomers to use nim directly for their error messages? Perhaps we could have nimsuggest focus on just giving the same error that nim would give?

**Comment by PMunch** [comment]
What is the actual issue with nimsuggest in a case like this? After all it is running the same code as the compiler, so why are the error messages different? Does it have something to do with running it without failing early and not knowing which error message out of all possible ones to display?

**Comment by RSDuck** [comment]
I'm not sure if that's related but I've experienced something similar several times with `nim check`. I try to throw together an example.

**Comment by zetashift** [comment]
Nimsuggest surely has it faults, but a lot of the current editor support rely on nimsuggest. Is it really beginner/user friendly if we tell them to ignore it? Can we maybe find a middle ground in fixing nimsuggest to a good enough state?

Other language-servers from other programming languages, have faults too, yet I don't see them advicing to switch a more manual way of development.

**Comment by RSDuck** [comment]
like I said to my knowledge a lot of plugins don't use nimsuggest's chk command, but instead they rely on `nim check` for diagnostics. It's really weird that `nim check` can report different errors (or rather additional ones) than the Nim compiler, because shouldn't it be a normal compilation with fewer steps?

```nim
import
    dom, bitops

let x = bitor(0'u32, 0)
```

Compiling this with the nim compiler results in this error:
```
.....
C:\Nim\lib\js\dom.nim(14, 10) Error: This module only works on the JavaScript platform
```
short and concise.

This is what `nim check` outputs:
```
.....
C:\Nim\lib\js\dom.nim(14, 10) Error: This module only works on the JavaScript platform
..
...\main.nim(4, 14) Error: expression '' has no type (or is ambiguous)
...\main.nim(4, 5) Error: 'let' symbol requires an initialization
...\main.nim(4, 5) Hint: 'x' is declared but not used [XDeclaredButNotUsed]
...\main.nim(2, 5) Warning: imported and not used: 'dom' [UnusedImport]
```
The proper error is included, but there are a lot more errors and warnings which distract from what's the actual problem. When the file is compiled with the js backend, the first error disappears and all other errors with it.

Another example inspired by the one in the tweet:
```nim
import
    dom

let main = document.getElementById('main')
```

If we compile this, this time with the proper JS command (nim js file.nim) we get this error: 

```
...\main.nim(4, 38) Error: missing closing ' for character literal
```

But what does `nim check` say (`nim --backend:js check file.nim`)?

```
...\main.nim(4, 38) Error: missing closing ' for character literal
...\main.nim(4, 43) Error: missing closing ' for character literal
...\main.nim(4, 44) Error: expected: ')', but got: '[EOF]'
...\main.nim(4, 39) Error: type mismatch: got <char, char>
but expected one of:
proc contains(c: ClassList; class: cstring): bool
  first type mismatch at position: 1
  required type for c: ClassList
  but expression '')'' is of type: char
proc contains(n: Node): bool
  first type mismatch at position: 1
  required type for n: Node
  but expression '')'' is of type: char
proc contains[T](a: openArray[T]; item: T): bool
  first type mismatch at position: 1
  required type for a: openArray[T]
  but expression '')'' is of type: char
proc contains[T](x: set[T]; y: T): bool
  first type mismatch at position: 1
  required type for x: set[T]
  but expression '')'' is of type: char
proc contains[U, V, W](s: HSlice[U, V]; value: W): bool
  first type mismatch at position: 1
  required type for s: HSlice[contains.U, contains.V]
  but expression '')'' is of type: char

expression: contains(')', 'm')
```

Again, much more confusing. In fact, I've had cases where a single error (which was properly reported by running the nim compiler normally) could cascade into hundreds of errors reported by `nim check`.

So while I definitely agree that nimsuggest could be improved, I think in this particular case, it seems to be `nim check` which is faulty.

**Comment by bung87** [comment]
in the compiler related files, I've seen atleast  two places do `when nimssugest ` doing extra check, and commented as only  affected to nimsuggest, seems to be related to this issue.

**Comment by timotheecour** [comment]
> It's really weird that nim check can report different errors (or rather additional ones) than the Nim compiler, because shouldn't it be a normal compilation with fewer steps?

the main difference you're observing is `--errormax` is set differently for `nim c` vs `nim check`.

`nim r --errormax:10 main` shows the same errors as `nim check main.nim` in your example(s)
`nim check --errormax:1 main` shows the same errors as `nim r main.nim` in your example(s)

reporting several errors at a time is a feature though, that can be useful at times:
* when compilation is expensive and you want to catch multiple errors at once
* in testament this is used a lot

Note that nim is already smart about deduping certain kinds of errors, eg:
```nim
when true:
  proc fn1 =
    echo a1 # error
    echo a1+1 # error gagged, bc symbol is skUnknown
    echo b1 # error
```

some things can be improved though
- [ ] report at most 1 error per line would go a long way and is easy to implement

**Comment by bung87** [comment]
in msgs.nim `writeContext` has `if context.info != lastinfo and context.info != info:`  execute `structuredErrorHook`. well ,in nimsuggest `runCmd` proc  has
`conf.writelnHook = proc (line: string) =
      retval.add(Suggest(section: ideMsg, doc: line))`

`conf.writelnHook = proc (s: string) =
      stderr.write s & "\n"`
you will see duplicated messages if there are.   
I dont know why assign `conf.writelnHook ` twice, and why should write to stderr if I use it as library.

**Comment by timotheecour** [comment]
- [ ] @bung87 that's a bug you've found, PR welcome
```nim
    conf.writelnHook = proc (line: string) =
      retval.add(Suggest(section: ideMsg, doc: line))
    conf.suggestionResultHook = proc (s: Suggest) =
      retval.add(s)
    conf.writelnHook = proc (s: string) =
      stderr.write s & "\n"
```

**Comment by PMunch** [comment]
Yes a lot of the issue is the fact that `nimsuggest` asks for more than a single error (instead of the compiler which fails early) but doesn't have any mechanism to track cause of an error. You do get used to it after a while, but it's certainly not great.

As timotheecour mentioned, this is intended behaviour as it means that multiple _unrelated_ issues can be reported at the same time saving the user time when working with their code (e.g. if they restructure an object and need to change every access to a field). The "one error per line" solution might help hide some of these superfluous errors (although it might show the wrong one, not sure if they are weighted somehow). But this isn't a great solution. As we can see from the error messages posted by RSDuck these related error messages aren't always on the same line, some of them (like the notorious `Error: expression '' has no type (or is ambiguous)`) are caused by a previous error that has rendered something completely invalid.

I have considered adding some kind of filtering to NimLSP, however I wasn't entirely sure if that would be a good idea or not. As I mentioned a solution like that might end up hiding the real error.

**Comment by timotheecour** [comment]
here's D's strategy, which does a good job in practice at removing spurious cascade errors:
https://forum.dlang.org/thread/k0bb3t$ad4$1@digitalmars.com?page=2

>> On 8/13/2012 9:47 AM, Dmitry Olshansky wrote:
>> I seriously consider writing a simple postprocessor for dmd's output.
>> Once dmd became able to recover from errors and crawl on it started to produce
>> horrific amounts of redundant text on failure.

>The current strategy the compiler uses on detecting a bug is it marks whatever >symbol/expression/statement caused the bug as "poisoned". Then, every dependency on that poisoned >symbol/expression/statement is also marked as "poisoned" and error messages for them are suppressed.
>This has been extremely successful at reducing cascaded, duplicated, and nonsense error messages.
>However, it is not completely implemented throughout the compiler.

as I mentioned earlier in this thread, nim has some form of this (eg `skUknown` symbols won't re-generate undefined identifier for same symbol in above example) but IIRC it's currently limited.

I think what's missing is a new `nkError` (node kind) instead of `nkEmpty` that's used IIRC, to represent error nodes that should be gagged.


=> [add `nkError` / `nkPoison` for poisoned nodes that contain errors instead of re-using nkEmpty · Issue #381 · timotheecour/Nim](https://github.com/timotheecour/Nim/issues/381)

**Comment by PMunch** [comment]
I have seen something like `nkError` show up in type mismatch errors, or it just displays it as `Error` in the type signature at least. But that kind of "poisoned" symbols would likely clear up most if not all the superfluous errors if implemented correctly.

**Comment by timotheecour** [comment]
> I have seen something like nkError

no, that's `tyError`. I think `nkError` is also needed.

**Comment by Araq** [comment]
> I think what's missing is a new nkError (node kind) instead of nkEmpty that's used IIRC, to represent error nodes that should be gagged.

I want ``nkError`` for other reasons, for nimsuggest ``nkEmpty`` (or the unused ``nkNone``) would work just as well.

**Comment by moigagoo** [comment]
My biggest issue with nimsuggest is that it won't work with Karax or Jester because it fails to process their macros. Not only do I get false negatives all the time, the suggestion functionality is lost too.

To me, it's the suggestions and code navigation that really matter. I guess I personally would be happier if nimsuggest didn't check for errors at all leaving it to nim check and focused only on code assistance necessary for comfortable IDE experience.

**Comment by disruptek** [comment]
Please change the title of this issue and, ideally, move it to the RFC repo.  I think it's too incendiary and, coming from me, that really says something.  The product was no less successful before someone with 10,000 followers tweeted about it, so let's not pretend that we suddenly developed compassion for newbies.  If you're really that embarrassed, maybe pick up a keyboard and fix it instead of merely insulting the product and distancing yourself.

With regard to `nimsuggest` itself, the program is ripe for rethink in light of new IC artifacts which could help it run more quickly and with less memory use.  To me, it's more important that I have working navigation and syntax highlighting regardless of how broken my code is, and I'd gladly give up a lot of `check` functionality for more robust behavior in, for example, the compiler or macro-heavy code.  So I'm :+1: to @moigagoo's comment.

I'll support whatever @alaviss thinks we should do. :wink:

**Comment by Araq** [comment]
Not actionable, nimsuggest will improve with IC which we're working on.

**Comment by dom96** [comment]
Title updated. FWIW my suggestion would be to make it clear to users and code editor extension developers to use `nim c` for error messages instead of nimsuggest/nim check while this is fixed (which right now could take anywhere from 6 months to many years).

**Comment by RSDuck** [comment]
`nim check --errormax:1` would do the trick as well, though that would also bring some disadvantages with it, as discussed here.

**Comment by nc-x** [comment]
> make it clear to users and code editor extension developers to use "nim c" for error messages 

Definitely no!

1) Compiling the whole code takes time, and is the reason why every "good" compiler ide plugin does "not" do so.
2) Most developers want to see more than 1 error message at a time.

**Comment by dom96** [comment]
> Compiling the whole code takes time, and is the reason why every "good" compiler ide plugin does "not" do so.

Sure, that's a good point. I wouldn't want the extension to build my code every time I save, of course. So we would need yet another switch for `nim c` I suppose, meh.

> Most developers want to see more than 1 error message at a time.

Yes, they likely do, but in Nim's case these errors can be incredibly unreliable and misleading. 

Anyway, just a suggestion, this is a real problem right now and has been for many years. I've learned that error messages given by VS Code/nim check/nimsuggest are not reliable and know to use `nim c` but many newcomers will get caught out by this and think Nim's error messages are poor.

But since there isn't a will to implement a short-term solution we can leave this closed.

**Comment by timotheecour** [comment]
> But since there isn't a will to implement a short-term solution we can leave this closed.

I gave an actionable point here: https://github.com/nim-lang/Nim/issues/16001#issuecomment-730118098
>  report at most 1 error per line would go a long way and is easy to implement
