### ISSUE TITLE
Small tutorial error

### ISSUE THREAD

**Issue by Hazarre** [nim-lang/Nim#16047]
Hi,

I'm recenly learning Nim and I think there might be an error in the tutorial at this
[link](https://nim-lang.org/docs/tut1.html). 

In the sample code of Break Statement, the last echo says   [echo "still in block" ] but I think the program should've left the block at that point. It's a small one but let me know if I'm wrong. Thanks

**Comment by timotheecour** [comment]
@Hazarre good catch.
* please always reference devel docs (https://nim-lang.github.io/Nim/lib.html) not latest release docs, in case bug already got fixed in devel.

* as you can see in same page in devel docs (https://nim-lang.github.io/Nim/tut1.html) there is now a Source + Edit button, so please use the Edit button (or just your favorite workflow) to make a PR!

**Comment by narimiran** [comment]
It is the same echo in both examples. And in both examples it is part of the block. The only difference is that in the second example it won't be printed.

So the example is **not** wrong. We might want just to add comment there `# this is not printed`
