### ISSUE TITLE
The views feature is broken.

### ISSUE THREAD

**Issue by bobeff** [nim-lang/Nim#16132]
I have trouble trying the [views](https://nim-lang.github.io/Nim/manual_experimental.html#view-types) feature. I have tried three variants and every one of them is broken in some way.

### Example
```nim
{.experimental: "views".}

proc foo(): var int =
  var x {.global.}: int
  once: x = 42
  return x

var y: var int = foo()
y = 15
echo foo()
```

### Current Output
```
Error: 'result' must borrow from the first parameter
```

### Expected Output
```
15
```

### Example
```nim
{.experimental: "views".}

var x: int

proc foo(): var int =
  once: x = 42
  return x

var y: var int = foo()
y = 15
echo foo()
```

### Current output
```
Error: cannot borrow from x, it is not a path expression; see https://nim-lang.github.io/Nim/manual_experimental.html#view-types-algorithm-path-expressions for details
```

### Expected output
```
15
```

### Example
```nim
{.experimental: "views".}

var x: int

proc foo(x: var int): var int =
  once: x = 42
  return x

var y: var int = foo(x)
y = 15
echo foo(x)
```

### Current output
```
Traceback (most recent call last)
/some/path/nimtest/test.nim(13) test
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/some/path/nimtest/test '
```

### Expected output
```
15
```

## Compiler version
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-11-25
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 0472526d9023467bb1e29ad8c90c03f1f1347eea
active boot switches: -d:danger
```

**Comment by Araq** [comment]
Only the third variant should work, everything else works as documented.

**Comment by bobeff** [comment]
> Only the third variant should work, everything else works as documented.

I think that it would be useful, the first two variants to be also allowed. Especially the first one. In C++ it is a classical pattern for implementing singletons.

**Comment by Araq** [comment]
A singleton is simply a global variable, it's always there, there is never a reason to return its address.

**Comment by zah** [comment]
The `{.global.}` pragma is often used a way to "generate" unique global variables corresponding to types or other symbols in the program. For example, in script binding or a serialization library, each type may have a custom user-generated RTTI table associated with it. In the Chronicles logging library, I use this feature to generate an unique state variable for each "logging topic" used in the program. By modifying this variable, you enable or disable the logging statements associated with the topic at run-time.

If you want to provide a mutable access to your generated variable, you'll have to return its address in one form or another (either as a `ptr` value or preferably as `var`). Since the lifetime of globals encompasses the lifetime of any local variable, there is no reason to now allow this. In fact the manual already states that it should be possible:

> A local variable of a view type can borrow from a location derived from a parameter, another local variable, a global const or let symbol or a thread-local var or let.
>
> Let p the proc that is analysed for the correctness of the borrow operation.
>
> Let source be one of:
>
>    A formal parameter of p. Note that this does not cover parameters of inner procs.
>    The result symbol of p.
>    A local var or let or const of p. Note that this does not cover locals of inner procs.
>    A thread-local var or let.
>    A global let or const.
>    A constant array/seq/object/tuple constructor.
