### ISSUE TITLE
{.inheritable.} not working for generic types

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#16653]
For C++ interop, I need to have generic inheritable objects.
Those are refused with `Error: inheritance only works with non-final objects; for Foo to be inheritable it must be 'object of RootObj' instead of 'object'`

Example
```Nim

when true: # not working
  type
    Foo {.pure, inheritable.} [T] = object


    Bar[T] = object of Foo
else: # working
  type
    Foo {.pure, inheritable.} = object


    Bar = object of Foo
```

**Comment by jcosborn** [comment]
I ran into this too recently.  Moving ``inheritable`` makes it work, but gets a warning about pragmas there being depracated.  Note that ``pure`` apparently has to stay where it is to have effect.  I realize that deprecating pragmas on the object was intentional (I think to avoid redundancy), but it seems that ``pure`` and ``inheritable`` logically belong as part of the object more so than the symbol. 
```Nim
type  # works
  Foo {.pure.} [T] = object {.inheritable.}
  Bar[T] = object of Foo
```

**Comment by metagn** [comment]
The workaround shown above gives a parser error on 2.0, so here is an example of a macro to do it on all versions: https://github.com/metagn/genericinheritablefix
