### ISSUE TITLE
HashSet output wrong with non-arc/orc gc

### ISSUE THREAD

**Issue by Clyybber** [nim-lang/Nim#16958]
This outputs a wrong result.

### Example
```nim
import sets

proc main =
  var potLastReads = toHashSet([13, 15])
  var lastReadsA = toHashSet([13])
  var lastReadsB = initHashSet[int]()
  var potLastReadsA = toHashSet([20, 21])
  var potLastReadsB = toHashSet([13, 15])

  echo potLastReads
  let oldPotLastReads = potLastReads
  potLastReads.clear()
  when true: # Disabling/enabling this line also changes result
    potLastReads.incl lastReadsA + lastReadsB

  potLastReads = (potLastReadsA + potLastReadsB) - oldPotLastReads
  potLastReads.incl potLastReadsA * potLastReadsB
  echo potLastReads # Correct would be {20, 21}

main()
```
Works correctly with `gc:arc/orc` :) , fails with every other gc option, including `gc:none`.
Also works correctly in a top level statement/block instead of a proc.

### Expected Output
```
{20, 21}
```

### Additional Information

latest devel: c548f97241c9f0da8f9442c07b99dd9d6adf225a

**Comment by konsumlamm** [comment]
The issue is apparently that `let oldPotLastReads = potLastReads` doesn't copy the `HashSet` (so that `oldPotLastReads` and `potLastReads` refer to the same set), as made clear when inserting a debug `echo oldPotLastReads` (which prints `{}` for non-arc/orc) after the assignment.

Interestingly enough, when changing the `let` to `var`, it works.

**Comment by ringabout** [comment]
Related https://github.com/nim-lang/Nim/issues/16312

**Comment by Clyybber** [comment]
Closing as duplicate of #16312
