### ISSUE TITLE
Unittest does not notice JS errors

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#16978]
In JS:

### Example
```nim
import unittest

test "Bad test":
  var x: cstring = nil
  discard x[0]
```

### Current Output
```
[OK] Bad test
<test file path>.js:4787       
var eTypeDesc_13450001 = (makeNimstrLit("[") || []).concat(cstrToNimstr(e_13445602.name) || [],makeNimstrLit("]") 
|| []);


       ^

TypeError: Cannot read property 'name' of null
    at Object.<anonymous> (<test file path>.js:4787:84)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)        
    at Function.executeUserEntryPoint 
[as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

### Expected Output
Test fails with stack trace of TypeError from JS.

### Possible Solution

The issue is that the current exception in JS is nil if it's from JS. There could be a `JsException` type or something that wraps these exceptions.

```
$ nim -v
Nim Compiler Version 1.4.2
```

**Comment by juancarlospaco** [comment]
I dont think unittest is prepared for JS target, but it has bold top recommendation about using testament instead.

**Comment by metagn** [comment]
> I dont think unittest is prepared for JS target, but it has bold top recommendation about using testament instead.

I don't think unittest is deprecated yet, and if it is, I'm not sure testament is ready for general use, nor is supported enough. This isn't really unittest's problem as much as it is a general ergonomic problem with JS errors, it just could be specifically handled for unittest.

**Comment by Araq** [comment]
Testament is more ready for "general use" than unittest.nim is, IMHO. Also, I'm willing to support testament but I'm unwilling to support unittest.

**Comment by timotheecour** [comment]
fixing this in https://github.com/nim-lang/Nim/pull/16998

unittest is just a tool, it's not a replacement of testament and in fact can be used in testament (lots of tests use it in fact); testament manages running individual tests out of process and has lots of features/scope whereas unittest is much smaller in scope than testament so should be easier to maintain (to wit, testament keeps getting bug fixes (by me and many others) and many many more are left, due to its broader scope).

IMO the main problem with unittest isn't the API (check, require in particular as the most useful procs), but the implementation that's overly complicated, making excessive use of templates. 
A much simpler unittest (with more useful functionality) could be devised, maintaining the key features of `check`:
* delayed failure
* show runtime values on failure

testament isn't really replacing those features (not without a stretch).

**Comment by Araq** [comment]
> testament isn't really replacing those features (not without a stretch).

I beg to differ. 

> A much simpler unittest (with more useful functionality) could be devised

Yeah, but we don't have it and I would prefer if we all worked on more important things. However, if a simplified unittest.nim comes along, I don't mind too much.
