### ISSUE TITLE
csources generation broken after #16764

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#17078]
Demonstrated by nightlies

### Build log
Full log at: https://github.com/nim-lang/nightlies/pull/51/checks?check_run_id=1922863521#step:11:284
```
nim compile -f --symbolfiles:off --compileonly --gen_mapping --cc:gcc --skipUserCfg --os:solaris --cpu:i386 -d:danger -d:gitHash:4c568734f426052a43693772cf12301d7b457060 compiler/nim.nim
Hint: used config file '/home/runner/work/nightlies/nightlies/nim/config/nim.cfg' [Conf]
Hint: used config file '/home/runner/work/nightlies/nightlies/nim/config/config.nims' [Conf]
Hint: used config file '/home/runner/work/nightlies/nightlies/nim/compiler/nim.cfg' [Conf]
.............................................
/home/runner/work/nightlies/nightlies/nim/lib/pure/concurrency/cpuinfo.nim(100, 14) Error: undeclared identifier: 'sysconf'
Error: call to nim compiler failed
Error: execution of an external program failed: '/home/runner/work/nightlies/nightlies/nim/tools/niminst/niminst --var:version=1.5.1 --var:mingw=none csource --main:compiler/nim.nim compiler/installer.ini -d:danger -d:gitHash:4c568734f426052a43693772cf12301d7b457060'
FAILURE
```

Commit 4c568734f426052a43693772cf12301d7b457060

Caused by https://github.com/nim-lang/Nim/commit/31bb67a309ae4bfdc1909c0a7c6748a534a0b00e#diff-3951d345226b809e9d95884f6c5d550de903ce8113e6f971115483ba1872dde0L18

**Comment by alaviss** [comment]
@timotheecour

**Comment by timotheecour** [comment]
@alaviss thanks for the ping, see https://github.com/nim-lang/Nim/pull/17079

- [ ] I can run locally `nim compile -f --symbolfiles:off --compileonly --gen_mapping --cc:gcc --skipUserCfg --os:solaris --cpu:i386 -d:danger -d:gitHash:4c568734f426052a43693772cf12301d7b457060 compiler/nim.nim` but how can I run this more generally to ensure nightlies passes?

- [ ] more generally (refs https://github.com/timotheecour/Nim/issues/594), can we add something to nim's CI so that it runs, if not all what nightlies runs, at least a representative subset to catch as many regressions as possible before a merge? what's the command to run nigthtlies, and how long does it take to run in nightlies' CI?

refs https://github.com/timotheecour/Nim/issues/610
