### ISSUE TITLE
deprecate `initDateTime` which has has unintuitive parameter order, introduce new set of inits

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#17072]
https://github.com/nim-lang/Nim/blob/f49d148a918cf8becec91f7d06f9b72e2bf4c4a2/lib/pure/times.nim#L1326

It turns out that `initDateTime` expects day of month first, which is of course a local convention in some regions of the world, but quite.. unusual in engineering - https://www.iso.org/iso-8601-date-and-time-format.html is generally used to avoid ambiguity, retain trivial lexicographic sorting and to maintain sanity in general when switching from pretty much any language out there where year-month-date really is an established canonical order for these parameters - also, thinking about it from a logical simplicity point of view, it's way easier to remember that it goes from least granular to most granular: `yyyy-mm-dd hh:mm:ss` - switching order in the middle of the parameters is quite confusing.

The request here is to deprecate the existing functions and replacing them with a new set of functions that adhere to relevant standards, are logically consistent and aren't just unique for uniqueness' sake.

**Comment by gcaplan** [comment]
Please give this serious consideration. As the OP states, the ISO is the canonical order in other languages. "Unusual" is quite a charitable way to describe the current API.

On the plus side, the strong Ada-style typing should prevent hard-to-track bugs, but the current API still violates the principle of least surprise.

**Comment by timotheecour** [comment]
> Please give this serious consideration

it starts with a PR

**Comment by gcaplan** [comment]
> it starts with a PR

Are you saying that's the _only_ way that this community will consider even a minor request??

**Comment by Varriount** [comment]
> 
> 
> > it starts with a PR
> 
> Are you saying that's the _only_ way that this community will consider even a minor request??

No, however this issue is a relatively minor one - minor enough that it hasn't been picked up by anyone else. I would recommend interpreting the lack of feedback as implicit approval to go ahead and make a proposed change. More discussion tends to happen in PRs, as all the details about a proposed fix are known.

Personally, I agree with the idea that date-time functions should accept parameters in `year/month/day` order, however I'm unsure if the issue is severe enough to warrant a whole new set of initialization functions. I would need to see an actual implementation first.

**Comment by gcaplan** [comment]
Fair enough. Thanks for the clarification!

**Comment by timotheecour** [comment]
=> PR https://github.com/nim-lang/Nim/pull/18590

**Comment by Varriount** [comment]
> 
> 
> => PR #18590

You don't need to add a comment - GitHub automatically makes a history note in an issue when it is mentioned in a PR.
