### ISSUE TITLE
`math.gamma` and `math.lgamma` always return 0.0 in VM

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#17118]
### Example
```nim
import std/math

static:
  echo gamma(5.0)
  echo lgamma(5.0)
```

### Current Output
```
0.0
0.0
```

### Expected Output
```
24.0
3.178053830347946
```

### Additional Information
This doesn't compile on current stable (1.4.2), giving
```
Error: cannot 'importc' variable at compile time
```

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-02-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: da52e81327594ac65c80ddc8d2c7cb152f4b1b24
```

**Comment by metagn** [comment]
The reason is these procs have empty bodies now presumably because of runnableExamples (gamma has runnableExamples but not lgamma). Are `importc` procs supposed to fallback on bodies for VM? Is this used anywhere in the standard library?

**Comment by ringabout** [comment]
Most of `cbrt, arcsinh, arccosh, arctanh, erf, erfc, gamma,
  lgamma` procs will suffer from this issue, I will make a PR to register them in vmops.

**Comment by ringabout** [comment]
> Is this used anywhere in the standard library?

I haven't found other modules suffer from this issue.

This is partial regression(never worked but the situation is worse namely silently failed)

**Comment by timotheecour** [comment]
root cause is https://github.com/nim-lang/Nim/issues/17121 ; note that both this issue and https://github.com/nim-lang/Nim/issues/17121 are regressions, but for different reasons: 
* https://github.com/nim-lang/Nim/issues/17121 is a regression because it gave CT error in 0.19
* this issue is a (partial) regression because `gamma` + friends returning 0 is worse than giving CT error (it started returning 0 since some doc comment or runnableExamples were added)
