### ISSUE TITLE
SIGSEGV when trying to compile template

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#17157]
Fails to compile template below, tested in latest playground

[playground](https://play.nim-lang.org/#ix=2Qx7)

```nim
template something(op: proc (v: untyped): void): void =
  discard
```

### Current Output

```
....SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by ghost** [comment]
This is a valid compiler crash, but I don't think that this code is valid because a proc can't have one of its arguments as untyped. If you try to compile something like `proc a(x: untyped) = discard` the compiler correctly states `Error: 'untyped' is only allowed in templates and macros or magic procs`

**Comment by ringabout** [comment]
crash at Nim 1.4.4, but CT error at devel.

> Error: 'untyped' is only allowed in templates and macros or magic procs
