### ISSUE TITLE
The sqrt(2) does not work with integers literals.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#17201]
Function `sqrt` does not work with integers literals.

### Example

https://play.nim-lang.org/#ix=2RdE
```nim
import math
echo sqrt(2)
```

### Current Output

```
/usercode/in.nim(2, 10) Error: ambiguous call; 
both math.sqrt(x: float32) [declared in /playground/nim/lib/pure/math.nim(256, 8)] 
and math.sqrt(x: float64) [declared in /playground/nim/lib/pure/math.nim(257, 8)] 
match for: (int literal(2))
```

### Expected Output

It just works like `sqrt(2.0)`.

### Possible Solution

Two `math.sqrt` are defined. One for `float32` and one for `float64`. For some reason it can't pick which one it should do when you give it an integer. One could create a 3rd that deals with some integer and converts it to float64. Or maybe do some thing with converters?

**Comment by timotheecour** [comment]
reduced:
this works:
```nim
proc fn(a: float) = discard
fn(2)
```
this gives CT error:
```nim
proc fn(a: float32) = discard
proc fn(a: float) = discard
fn(2)
```
This works by design according to the spec, but IMO this is a design problem.
suppose you have a module containing:
```nim
proc f*n(a: float) = discard
```
3rd party code then starts using it via:
```nim
fn(2)
```
which is legal, work, passes code review, etc


then later that module adds an overload `proc fn(a: float32) = discard`, which is legitimate, passes its own tests etc.

The problem is this breaks code that used `fn(2)`


> Or maybe do some thing with converters?

that would be the worst option IMO, converters cause other issues.

## note 1
(using https://nim-lang.github.io/Nim/manual_experimental.html#term-rewriting-macros-parameter-constraints)
this works:
```nim
when true:
  proc fn(a: float32): auto = (a,)
  proc fn(a: float): auto = (a,)
  template fn(a: int{lit}): untyped = fn(a.float)
  doAssert fn(2) == (2.0,)
```

which suggests a potential solution:
* when adding a first overload to a proc that previously accepted a int literal, we can add:

```nim
when defined nimLegacyFnLit:
  template fn*(a: int{lit}): untyped = fn(a.float)
```

whether it's a good solution or not is unclear though

## note 2
this doesn't work:
`proc fn(a: int{lit} | float): auto = (a,)`

> Error: type expected, but got: int{lit}

**Comment by treeform** [comment]
As I see it, `2` in the `sqrt` is a literal and has no type. The literal-to-typed conversion should be able to figure out if `2` should be `float64` or `float32` when being passed.

**Comment by timotheecour** [comment]
> The literal-to-typed conversion should be able to figure out if 2 should be float64 or float32 when being passed.

by picking one of those 2 arbitrarily?  what about this case:

```nim
proc fn(a: int8)=discard
proc fn(a: uint16)=discard
fn(2) # ??
```

**Comment by metagn** [comment]
> The literal-to-typed conversion should be able to figure out if 2 should be float64 or float32 when being passed.

#20852 is an example implementation of this, but it might not be worth it for such an inconvenience.

**Comment by Araq** [comment]
Sorry, but there is no bug here, the compiler doesn't guess and pick arbitrarily between float32 and float64.
