### ISSUE TITLE
js should ignore threads:on

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#17267]
```nim
echo "Hello"
```

nim js -r --threads:on app.nim

```
Error: 'getCurrentException' is not GC-safe as it accesses 'lastJSError' which is a global using GC'ed memory
```

Nim v1.4.2
Nim devel

**Comment by timotheecour** [comment]
ok.
* in future we can introduce `--webworkers` for js threads (https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) instead of reusing --threads
* see also https://github.com/nim-lang/RFCs/issues/349 which would prevent running redundant compilations/runs when using js and c backends with options.
