### ISSUE TITLE
double free 

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#17298]
https://gist.github.com/xflywind/dd2f86cbf4602a8d6bb0d45ed66c93a6

The codes don't use `sink` parameters(I removed them), it seems to be related with `=destroy` being used twice.

```nim
import channel
import std/[httpclient]


var ch = initChan[seq[string]]()


proc worker =
  var url: seq[string]
  ch.recv(url)
  if url.len == 0:
    return
  var client = newHttpClient()

  let response = client.get(url[0])
  echo response.body[0 .. 20]
  client.close()


proc spawnCrawlers =
  ch.send(@["https://nim-lang.org"])


var thr2: Thread[void]
createThread(thr2, worker)

spawnCrawlers()
joinThread(thr2)
```

compile it with `nim c -r --gc:orc --d:ssl --threads:on -d:useMalloc app.nim`, 

```
<!doctype html>
<html
double free or corruption (fasttop)
Traceback (most recent call last)
/root/.choosenim/toolchains/nim-#devel/lib/system.nim(2247) worker
SIGABRT: Abnormal termination.
Aborted
```

compile it with `nim c -r --gc:orc --d:ssl --threads:on app.nim`

```
/root/play/app.nim(20)   worker
/root/.choosenim/toolchains/nim-#devel/lib/pure/httpclient.nim(1155) get
/root/.choosenim/toolchains/nim-#devel/lib/pure/httpclient.nim(1054) request
/root/.choosenim/toolchains/nim-#devel/lib/pure/strutils.nim(2036) contains
/root/.choosenim/toolchains/nim-#devel/lib/pure/strutils.nim(1875) find
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
```

it works with `refc`

Nim devel + Linux
https://github.com/nim-lang/Nim/commit/dd8383b10acfc7242a1b60080866c5dc95179246

**Comment by ghost** [comment]
I reduced it a bit and I'm wondering - is this actually an ARC/ORC issue? Maybe I'm wrong, but from my point of view it seems that the code passes the seq by the raw pointer (`unsafeAddr`) to another thread and uses it. With `refc` that doesn't crash, probably because `refc` doesn't collect stuff right away or some other reason. With ARC/ORC it crashes because the compiler will inject the destroy call for the seq right after the `ch.send`.

Again: this is just my opinion, I might be wrong

**Comment by ghost** [comment]
Basically with
```nim
import channel
var ch = initChan[seq[string]]()

proc test(data: string) = 
  echo data.len

proc worker =
  var url: seq[string]
  ch.recv(url)
  if url.len == 0:
    return

  test(url[0])

proc spawnCrawlers =
  var tmp = @["https://nim-lang.org"]
  ch.send(tmp)

var thr2: Thread[void]
createThread(thr2, worker)

spawnCrawlers()
joinThread(thr2)
```

Nim injects destructor calls for `tmp` both in `spawnCrawlers` and `worker` (because it doesn't know that the object was moved to another thread). 

Works with
```nim
proc spawnCrawlers =
  var tmp = @["https://nim-lang.org"]
  ch.send(tmp)
  wasMoved(tmp)
```

because then Nim knows that the object was moved to another thread and it doesn't need to inject the destructor in the current proc.

I checked and the channels module from stdlib actually does the same for sending stuff to another thread when `gcDestructors` is defined.

**Comment by ringabout** [comment]
@Yardanico 
thanks!

**Comment by timotheecour** [comment]
@xflywind can we make this safer? eg:
can't `wasMoved` be called by `send` ?

**Comment by ringabout** [comment]
that's what i did
