### ISSUE TITLE
type checking bug 

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/Nim#17498]
the nim compiler doesn't detect the type mismatch and it causes the runtime error 

### Example
```nim
type 
  List* = seq[int]
  Matrix* = seq[List]

proc toMatrix*(m: seq[seq[int]]): Matrix=
  for y in 0..<m.len:
    result.add newSeq[List]() # note that the correct form is newSeq[int]
    echo "result.len: ", result.len # also this is very intresting!
    for x in 0..<m[y].len:
      # the nim compiler doesn't detect the above 
      # type mismatch and it causes the runtime error 
      result[^1].add m[y][x]

echo @[
  @[12,4],
  @[23,14]
].toMatrix
```

### Current Output
```
result.len: 0
/usercode/in.nim(17)     in
/usercode/in.nim(12)     toMatrix
/playground/nim/lib/system.nim(2593) []
/playground/nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```

### Expected Output
compile time error: 
> type mismatch: expected `seq[int]` but given `seq[seq[int]]`

### Additional Information
nim version: 1.4.4
reproduced on windows 10 and play.nim-lang.org

**Comment by Vindaar** [comment]
There is no type checking bug here.

```nim
result.add newSeq[List]() # note that the correct form is newSeq[int]
```
is valid, because of:
https://nim-lang.github.io/Nim/system.html#add%2Cseq%5BT%5D%2CopenArray%5BT%5D
i.e. you end up with still an empty seq. `result` is mutable, hence the argument can be added, but the argument is an empty list.

```nim
    echo "result.len: ", result.len # also this is very intresting!
```
no, it's expected because of the above.

```nim
      # the nim compiler doesn't detect the above 
      # type mismatch and it causes the runtime error 
      result[^1].add m[y][x]
```

- `result[^1]` is a `List`. 
- `List` is simply a `seq[int]`
- `m[y]` is a `seq[int]`. 
- `m[y][x]` thus is an `int`. 
-> since `result[^1]` is a `seq[int]` , the `add`  call adds the element `x` (no compile time error is what I'm referring to, i.e. this add: https://nim-lang.github.io/Nim/system.html#add%2Cseq%5BT%5D%2CsinkT)

So what's the runtime error? Simply that `result` is still empty after adding an empty `newSeq[List]`. So accessing the last element is an out of bounds access.
