### ISSUE TITLE
Better error messages for proc signature mismatches [$12]

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#1761]
``` nimrod
type
  TypeOne = object
  TypeTwo = object
  TypeThree = object
  TypeFour = object
  TypeFive = object
  TypeSix = object
  TypeSeven = object
  TypeEight = object

proc doSomething(
      param1: TypeOne,
      param2: TypeTwo,
      param3: TypeThree,
      param4: TypeFour,
      param5: TypeFive,
      param6: TypeSix,
      param7: TypeSeven,
      param8: TypeEight) =
  discard

doSomething(
  TypeOne(),
  TypeTwo(),
  TypeThree(),
  TypeTwo(),
  TypeFive(),
  TypeSix(),
  TypeSeven(),
  TypeEight())
```

The compiler outputs this:

```
test.nim(22, 11) Error: type mismatch: got (TypeOne, TypeTwo, TypeThree, TypeTwo, TypeFive, TypeSix, TypeSeven, TypeEight)
but expected one of: 
test.doSomething(param1: TypeOne, param2: TypeTwo, param3: TypeThree, param4: TypeFour, param5: TypeFive, param6: TypeSix, param7: TypeSeven, param8: TypeEight)
```

And it can take some time to figure out what's wrong, especially when some of the parameters match, but differ by type name (aliases).

One might argue that having 8 parameters is excessive, but I've found that it incurs some mental overhead with as few as 4 arguments.

One way to mitigate this might be to display each parameter on a separate line or display some kind of diff, perhaps with colors.

**Comment by josephduchesne** [comment]
I looked into this issue a bit, and there should probably be some discussion about the design of this before any implementation is done. It's a simple problem, but there are a wide variety of possible enhancements  available of varying quality and performance impact. 

Some questions:
- Should we only show a diff if the argument count is the same? (assume correct arg length). This would make matching parameters dramatically easier because you could assume that inputArg[n] should be candidateArg[n]. Otherwise this turns into a real [diff](https://neil.fraser.name/writing/diff/) exercise with insertions, omissions, substitutions etc.
- Should #4416 's request be implemented first or as part of the system (show converted types as their "final" value) or should that be annotated as such
- Is a line-per-arg output too verbose? It might get silly in cases like the 8 arg example. 
- In cases where there are mismatching argument lengths should that be noted? (e.g. "3 arguments passed, 4 arguments expected" or similar)

**Comment by Araq** [comment]
I would try this:

- Output the first mismatching argument for the best matching proc(s). Include the argument number.
- That's it. :-)

**Comment by data-man** [comment]
Nim-devel now outputs:

<pre><font color="#DC322F">Error: </font>type mismatch: got &lt;TypeOne, TypeTwo, TypeThree, TypeTwo, TypeFive, TypeSix, TypeSeven, TypeEight&gt;
but expected one of: 
proc doSomething(param1: TypeOne; param2: TypeTwo; param3: TypeThree; param4: TypeFour;
                param5: TypeFive; param6: TypeSix; param7: TypeSeven;
                param8: TypeEight)
  first type mismatch at position: 4
  required type: TypeFour
  but expression &apos;TypeTwo()&apos; is of type: TypeTwo

expression: doSomething(TypeOne(), TypeTwo(), TypeThree(), TypeTwo(), TypeFive(), TypeSix(),
            TypeSeven(), TypeEight())
</pre>

**Comment by dom96** [comment]
But who gets bounty? :)

**Comment by data-man** [comment]
@dom96 I guess Araq fixed it for free. :-)
