### ISSUE TITLE
Confusing error messages for constructors

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#17793]
#### 1
```nim
type Test = object
  x: int

echo Test(42)
```
#### 2
```nim
type Test[T] = object
  x: T

echo Test(42)
```
#### 3
```nim
type Test[T] = object
  x: T

echo Test(x: 42)
```

#### 1
```
Error: type mismatch: got 'int literal(42)' for '42' but expected 'Test = object'
```
#### 2
```
Error: type mismatch: got 'int literal(42)' for '42' but expected 'Test = CompositeTypeClass'
```
#### 3
```
Error: object constructor needs an object type
```

#### 1
```
Error: expected object constructor
```
#### 2
```
Error: expected object constructor
```
#### 3
No error, `T` should be inferred to `int`. The same works with procs:
```nim
proc test[T](x: T): T = x

echo test(42) # compiles
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-04-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 3b80f0dc8ef2bc9d2a981a7c92a6355dfc72b7ef
active boot switches: -d:release
```

**Comment by metagn** [comment]
1 and 2 should not be "expected object constructor". You use `Test()` for type conversion, same for objects as any other type. Maybe it should try to point out that it sees it as a conversion. 3 would be a new feature, and has been addressed in other issues, for an error message you can say "expected concrete object type for object constructor" and maybe specialize it to "expected generic parameters for object type" when it just needs generic parameters.

**Comment by timotheecour** [comment]
> 3 would be a new feature, and has been addressed in other issues

indeed, see https://github.com/nim-lang/Nim/issues/11799

**Comment by timotheecour** [comment]
see https://github.com/nim-lang/Nim/pull/17806 which improves msg for case3 (and https://github.com/nim-lang/Nim/pull/17777 which improves other cases of bad ctor calls)

good enough to close this, given that #11799 tracks the `T should be inferred to int` part?

the other suggestions in this issue are not good IMO:
`Error: expected object constructor` is worse than existing msg because it shows less context (users should know how call an object ctor) and because of what @hlaaftana also mentioned.
