### ISSUE TITLE
Docgen issue with runnableExamples on specific usage of anyIt template.

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#17835]
### Example
```nim
import std/sequtils

proc foo*(n: seq[int]): bool =
  result = anyIt(n, it == 0)
```

### Current Output
```
$ nim doc test.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
Hint: used config file '/etc/nim/nimdoc.cfg' [Conf]
......
sequtils.nim(721, 3) Error: runnableExamples must appear before the first non-comment statement
```

### Additional Information
Any statement before `result =` will make the bug disappear.

This is causing disruptek/cps docs to not build.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-04-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: b667e288e27a09ce4f65166fc66a6b713350a9b6
active boot switches: -d:release -d:nimUseLinenoise -d:nativeStackTrace
```

Bisect shows that a807233aebcd3759bc3e21b450ed89e1eb6ddace is the first bad commit.

/cc @timotheecour @xflywind

**Comment by timotheecour** [comment]
yes, it's a regression, but the real cause is https://github.com/nim-lang/Nim/issues/16993 (which is a regression itself)
2 options:
* turn the error into a warning (temporarily), and fix https://github.com/nim-lang/Nim/issues/16993 later
* or just fix https://github.com/nim-lang/Nim/issues/16993 directly
