### ISSUE TITLE
regression: rendering of strings has bad syntax highlighting

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17890]
### Example
```nim
proc fn*() =
  runnableExamples:
    let a = "ok1\nok2\nok3"
    let b = "ok1\nok2 alt\nok3"
```
nim doc main

### Current Output
![image](https://user-images.githubusercontent.com/2194784/116511146-d9e3e600-a87a-11eb-8986-10afbe984cd2.png)

### Expected Output
output with 1.2 was better:
![image](https://user-images.githubusercontent.com/2194784/116511073-bde04480-a87a-11eb-9e7a-6bd2a4dd7cc8.png)

### Additional Information
1.5.1 01bca8cd4fad857124794144bff09ae0326895bd
/cc @a-mr if you have any ideas?

**Comment by a-mr** [comment]
the same bug is in 1.4 and it's a bug in `highlite.nim`.

I was not able to determine the origin of regression: checking git log showed that no essential change was done in `highlite.nim` between 1.2 and 1.4. I thought for a moment that it's escape sequences being highlighted with the same color as string literals, but it seems `doc/nimdoc.css` already had the dedicated color for `--escape` in 1.2. :-/

Anyway output for 1.2 is not correct because `\n` is not highlighted.

**Comment by timotheecour** [comment]
> I was not able to determine the origin of regression

git bisect should work (comparing presence of a bad string in the html or css), but maybe in this case we don't need to figure out which commit introduced this change and it can be fixed directly

> Anyway output for 1.2 is not correct because \n is not highlighted.

hmm, it's subjective though; should it highlight it? i don't mind if it does but at least shouldn't be highlighted as above

**Comment by a-mr** [comment]
@timotheecour 
git bisect showed that the first "bad" commit is e013ebc91a22eeccc9546498994b0c561e438599.
