### ISSUE TITLE
Broken example on hot code reloading

### ISSUE THREAD

**Issue by gavr123456789** [nim-lang/Nim#17998]
Compile error on line 51 in [hcr example](https://nim-lang.org/docs/hcr.html)
```nim
var rect = Rect(x: posX - 25, y: posY - 25, w: 50.cint, h: 50.cint) # object constructor needs an object type
```

```
nim -v
Nim Compiler Version 1.4.6 [Linux: amd64]
Compiled at 2021-04-26
Copyright (c) 2006-2020 by Andreas Rumpf
```
https://github.com/nim-lang/Nim/issues/14380

**Comment by ringabout** [comment]
Hello

I cannot reproduce it on windows with `nim c --hotcodereloading:on`

Is it related to hot code reloading? If not can you minify the example? If possible, please also try the devel version and other Nim versions.

**Comment by gavr123456789** [comment]
@xflywind   
```nim
type
  Rect* = tuple[x, y: cint, w, h: cint]
var rect = Rect(x: posX - 25, y: posY - 25, w: 50.cint, h: 50.cint) # object constructor needs an object type

```
Also you can try it from my repo https://github.com/gavr123456789/NimTests/tree/main/hot_code_reload

**Comment by ghost** [comment]
@xflywind maybe you have sdl2_nim installed? The thing is that with sdl2 (the one by nim-lang org) `Rect` is declared as a tuple, but with sdl2_nim (a package by Vladar) it's an object.

And in Nim you can't really declare a tuple with the syntax described in the HCR example, since that syntax is only used for objects.

**Comment by ringabout** [comment]
I see, thanks, maybe we could get some kinds of tests in the future for tutorials.
