### ISSUE TITLE
nim js: parseJson("0.0").kind returns JInt instead of JFloat

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18009]
### Example
```nim
when true: # D20210513T215227
  import std/json
  var a = 0.0
  let j = %a
  let j2 = $j
  echo j2
  let j3 = j2.parseJson
  echo (j3, j3.kind)
```

### Current Output
c:
0.0
(0.0, JFloat)
js:
0.0
(0, JInt)

### Expected Output
c:
0.0
(0.0, JFloat)
js:
0.0
(0.0, JFloat)

### Possible Solution
use isInteger from lib/std/private/jsutils.nim
(or maybe isSafeInteger)

### Additional Information
1.5.1 1e080eb9b4e0759b8b3f87406cd58bb7a615902f

**Comment by ringabout** [comment]
It is hard to mimic the behavior which can be achieved in C backend using JS backend. Because 0.0 and 0 are the same for JS. `parseJson(0.0)`  returns 0 instead of 0.0 in JS. We cannot differentiate them easily in JS unless we rewrite our own `parseJson` instead of the native one. I cannot think of any good idea.

https://stackoverflow.com/questions/56537993/converting-0-0-string-to-0-0-float-number/56538032
