### ISSUE TITLE
Instantiating default(sum type) in Nim 1.4 creates internal error: getTypeDescAux(tyOr)

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#18096]
Instantiating default(sum type) in Nim 1.4 creates internal error: getTypeDescAux(tyOr).

### Example
```nim
type A = int | string
discard(default(A))
```

### Current Output
On Nim 1.2.12, 1.4.2 and 1.4.6:
```
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
....
Error: internal error: getTypeDescAux(tyOr)
No stack traceback available
To create a stacktrace, rerun compilation with './koch temp c <file>', see https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler for details
```

This is fixed in Nim head, but meanwhile on current release versions, 1.2 and 1.4, it creates an internal error.

### Expected Output
An error message more along the lines of Nim 1.5.x:
```
z.nim(2, 16) template/generic instantiation of `default` from here
Nim/lib/system.nim(978, 15) Error: cannot instantiate: 'T'
```

**Comment by timotheecour** [comment]
there are a ton of bugs fixed in devel that haven't been backported, I don't see why this particular bug should be backported as it doesn't seem critical/security related/etc (bugfixes can cause regressions too)

IMO we should close this as won't fix since it works in devel.
(otherwise we'd end up with endless similar bug reports for things already fixed in devel)

**Comment by tersec** [comment]
Fair enough.
