### ISSUE TITLE
&"{1.236:<.2}" doesn't work in VM.

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#18134]
format float with strformat.& is not available in VM.

### Example
```nim
import strformat
static:
  echo &"{1.236:<.2}"
```

### Current Output

```
d:\Tool\Nim\lib\pure\strutils.nim(2375, 11) Error: cannot 'importc' variable at compile time; c_sprintf
```

```
$ nim -v
Nim Compiler Version 1.5.1 [Windows: i386]
Compiled at 2021-05-30
Copyright (c) 2006-2021 by Andreas Rumpf
active boot switches: -d:release
```

**Comment by ringabout** [comment]
This is due to that `formatBiggestFloat` procs haven't supported VM.

```nim
import strutils


static:
  let x = 123.456
  echo x.formatBiggestFloat()
```
Error: cannot 'importc' variable at compile time; c_sprintf

**Comment by slangmgh** [comment]
> This is due to that `formatBiggestFloat` procs haven't supported VM.
> 
> ```nim
> import strutils
> 
> 
> static:
>   let x = 123.456
>   echo x.formatBiggestFloat()
> ```
> 
> Error: cannot 'importc' variable at compile time; c_sprintf

Yes, I know the cause, but I think VM should support this function.

**Comment by slangmgh** [comment]
Now with dragonbox algorithm merged, we can fix this.

**Comment by konsumlamm** [comment]
Would it be possible to simply add a `formatBiggestFloat` VM callback? There are already callbacks for `formatfloat.addFloatRoundtrip` and `formatfloat.addFloatSprintf` (which are used in the `$` implementation for floats). Alternatively, we could reimplement it in pure Nim, but the first option would be easier and less error prone.

IMO it should be a high priority to make `strformat` work with the VM. It puts Nim in a bad light if we say that we don't need builtin format strings because we can implement them as macros, but then they don't work at compile time (which is one of the advertised strengths of Nim).
