### ISSUE TITLE
nim doc doesn't work across windows partitions

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#18142]
nim doc output following message for any file.

```
Error: unhandled exception: globs.nim(48, 3) `not path.isAbsolute`  [AssertionDefect]
```

```
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-06-01
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c0e8199acc9f49caa36bae34d103600d112b66f3
active boot switches: -d:release
```

**Comment by khchen** [comment]
`git bisect`: 64e6670de45f8f5a470e5cc3ad9ed2cb85f0b57c is the first bad commit

**Comment by timotheecour** [comment]
can you show a full stacktrace ? (refs https://nim-lang.github.io/Nim/intern.html)

and ideally instrument code to show what `path` points to?

**Comment by khchen** [comment]
```
Hint: used config file 'd:\nim\config\nim.cfg' [Conf]
Hint: used config file 'd:\nim\config\config.nims' [Conf]
Hint: used config file 'd:\nim\config\nimdoc.cfg' [Conf]
................D:\nim\compiler\nim.nim(125) nim
D:\nim\compiler\nim.nim(84) handleCmdLine
D:\nim\compiler\main.nim(292) mainCommand
D:\nim\compiler\main.nim(81) commandDoc2
D:\nim\compiler\modules.nim(178) compileProject
D:\nim\compiler\modules.nim(97) compileModule
D:\nim\compiler\passes.nim(189) processModule
D:\nim\compiler\passes.nim(65) closePasses
D:\nim\compiler\docgen2.nim(42) close
D:\nim\compiler\docgen.nim(1273) writeOutput
D:\nim\compiler\docgen.nim(1219) genOutFile
D:\nim\compiler\options.nim(918) canonicalImport
D:\nim\lib\std\private\globs.nim(48) nativeToUnixPath
D:\nim\lib\system\assertions.nim(68) failedAssertImpl
D:\nim\lib\system\assertions.nim(58) raiseAssert
D:\nim\lib\system\fatal.nim(53) sysFatal
Error: unhandled exception: D:\nim\lib\std\private\globs.nim(48, 3) `not path.isAbsolute`  [AssertionDefect]
```

I believe there was a same bug before: https://github.com/nim-lang/Nim/issues/13986

`that regression seems to happen when nim is installed in some drive eg D:\ and nim doc foo is called with foo being on another drive (eg C:\)`

**Comment by timotheecour** [comment]
IMO the correct way to fix it would be https://github.com/nim-lang/Nim/pull/13265 but there's pushback here: https://github.com/nim-lang/Nim/pull/13265#issuecomment-674700064

**Comment by Varriount** [comment]
@timotheecour My question would be why nativeToUnixPath is in globs.nim in the first place. It has no relation to file globbing.

Looking through the entire Nim repository source code and the actual usage of `nativeToUnixPath`, my general question is "why should it be used anywhere?". Rather than convert all input paths to Unix, it's generally more robust (not to mention user friendly!) to convert constant paths to the native system format.

These are the examples I could find:

  - [kochdocs.nim, lines 197 & 198](https://github.com/nim-lang/Nim/blob/8ccde68f132be4dba330eb6ec50f4679e564efac/tools/kochdocs.nim#L197) - Can be removed by converting paths in the referenced constants to native paths (and they should be sequences too).
  - [trunner.nim, line 120](https://github.com/nim-lang/Nim/blob/b59dc3b255d778cefdbef2c0c3ff55d43892c11c/tests/misc/trunner.nim#L120) - Can be removed by doing roughly the same thing as point 1.
  - [compiler/options.nim, line 918](https://github.com/nim-lang/Nim/blob/97970d9dccb24bb290cdba14275acae62602c832/compiler/options.nim#L918) - Only used by the documentation generator, should probably just return a native path, or a higher-level abstraction.
  - [docgen.nim, line 1215](https://github.com/nim-lang/Nim/blob/1568ae23c66c572891207f2c1d330d246b3144ac/compiler/docgen.nim#L1215) - Ok, I can see needing a function like that here, for the titles, however it could just be a simple "split the path into pieces and rejoin using `/`" function.

So we have 5 uses, 4 of which can be easily solved by fairly minor modifications.

**Comment by timotheecour** [comment]
/cc @khchen see PR https://github.com/nim-lang/Nim/pull/18501

> My question would be why nativeToUnixPath is in globs.nim in the first place. It has no relation to file globbing.

it's under `lib/std/private/`, it can be moved around as needed in future work
