### ISSUE TITLE
`moveDir()` not able to move files between partitions on Windows

### ISSUE THREAD

**Issue by maradotwebp** [nim-lang/Nim#18216]
The `moveDir()` command is not able to move folders between partitions on Windows.

### Example
- Use Windows 
- Create C:\\testdir\
- Create D:\\testdestdir\
```nim
import os

moveDir("C:\\testdir", "D:\\testdestdir")
```

### Current Output
```
D:\Projects\mc\pax\test.nim(3) test
C:\Users\Alexander\nim\nim-1.4.8\lib\pure\os.nim(2407) moveDir
C:\Users\Alexander\nim\nim-1.4.8\lib\pure\os.nim(1828) tryMoveFSObject
C:\Users\Alexander\nim\nim-1.4.8\lib\pure\includes\oserr.nim(94) raiseOSError
Error: unhandled exception: Zugriff verweigert
Additional info: "(\"C:\\\\testdir\", \"D:\\\\testdestdir\")" [OSError]
Error: execution of an external program failed: 'D:\Projects\mc\pax\test.exe '
```

### Additional Information
Bug present since at least V1.2.0.

**Comment by timotheecour** [comment]
> Zugriff verweigert

access denied? do you have proper permissions to write to this dir?

**Comment by maradotwebp** [comment]
I'm able to create files on both partitions manually, am marked as owner in the security settings and am otherwise on an administrator account.

**Comment by timotheecour** [comment]
besides this bug, `tryMoveFSObject` is a confusing API (private proc, so can and should be improved):
* on windows it raises on error
* on non-windows, it returns false on error
(and then the code uses `  if not tryMoveFSObject(source, dest): when not defined(windows):` to compensate for this, but it seems kludgey)

and in fact here lies the bug:
> When moving a directory, the destination must be on the same drive.

(refs https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexa)

so the fix is to use the same algorithm on windows as for posix for moveDir:
```nim
  if not tryMoveFSObject(source, dest):
    when not defined(windows):
      # Fallback to copy & del
      copyDir(source, dest)
      removeDir(source)
```
=> fix `tryMoveFSObject` and then change this to:
```nim
  if not tryMoveFSObject(source, dest):
    # Fallback to copy & del
    copyDir(source, dest)
    removeDir(source)
```

@froehlichA, PR welcome

**Comment by maradotwebp** [comment]
Will do, thanks for looking into this :+1:

**Comment by froehlichA** [comment]
Wait a second, both the `MoveFileExA` and `MoveFileExW` Windows functions have a flag `MOVEFILE_COPY_ALLOWED` that does the following:

> If the file is to be moved to a different volume, the function simulates the move by using the CopyFile and DeleteFile functions. If the  file is successfully copied to a different volume and the original file is unable to be deleted, the function succeeds leaving the source file intact. This value cannot be used with MOVEFILE_DELAY_UNTIL_REBOOT.

Curiously enough, `tryMoveFSObject` already uses the `moveFileExA` and `moveFileExW` commands with that flag.

..I'm not THAT experienced with system level programming, but to me it seems like the current code should already work since windows will automatically copy & delete if move doesn't work. I'm not really sure what is going wrong in my case.
