### ISSUE TITLE
regression (1.4=>devel) compiling `proc fn3(n) = discard` gives SIGSEGV instead of CT error

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18327]
### Example
```nim
proc fn3(n) = discard
```

### Current Output
SIGSEGV

### Expected Output
t12453.nim(5, 10) Error: typeless parameters are obsolete

### Additional Information
SIGSEGV in 1.5.1 40ec8184ad51ccdaa6042132dc9b37b6f242c362
worked in 1.4 (ie gave CT error)

**Comment by ringabout** [comment]
Well, it seems to be caused by https://github.com/nim-lang/Nim/commit/e12597589f2a8cdaabe09e8b2b92ff0fbe3727ef#diff-67ade5e03602588f80d76f0ba86b7ea4d16306d7a6a9b47e05784366b96a083c


How could it work in the beginning?

![image](https://user-images.githubusercontent.com/43030857/122904557-08fe6b80-d383-11eb-9b14-5254ec901b13.png)

**Comment by timotheecour** [comment]
guess that's what happens when no tests are added to a PR... sounds like an easy bug to fix though

**Comment by ringabout** [comment]
> guess that's what happens when no tests are added to a PR... sounds like an easy bug to fix though

I will make a PR.
