### ISSUE TITLE
Bug using nested loops in closure iterators

### ISSUE THREAD

**Issue by Hi02hi** [nim-lang/Nim#18474]
When I have a nested loop in a closure iterator, `i` only goes through 1 iteration

Example:
```nim
iterator products(): int {.closure.} = 
  for i in 10..99:
    for j in 10..99:
      yield i*j
  

for i in products():
  echo i
```

Current Output: 100 110 ... 980 990
Expected Output: 100 110 ... 980 990 110 (11 * 10) 121 ... 1078 1089 (11 * 99) ... 9801 (99 * 99)

It works fine with an inline iterator

Additional Information
It seems this is a very old bug, as in the playground, the first version that doesn't crash (0.17.0) has this bug

Note: my first issue, did I do fine?

**Comment by Araq** [comment]
> Note: my first issue, did I do fine?

You're doing exceptionally well, thanks!

**Comment by Hi02hi** [comment]
Update:

Interestingly, 

```nim
iterator nested(): (int, int) {.closure.} = 
  # its easier to see the bug by returning (int, int)
  for i in countup(10, 99):
    for j in 10 .. 99:
      yield (i, j)
  
for i in nested():
  echo i
```

```nim
iterator nested(): (int, int) {.closure.} = 
  for i in 10..99:
    for j in countup(10, 99):
      yield (i, j)
  
for i in nested():
  echo i
```

```nim
iterator `....`(start, finish: int): int = 
  for i in start..finish:
    yield i

iterator nested(): (int, int) {.closure.} = 
  for i in 10..99:
    for j in 10....99:
      yield (i, j)
  
for i in nested():
  echo i
```

all work. It seems that nesting the same iterator is broken, but using an alias fixes it.

**Comment by nick8325** [comment]
I did some digging and might have an idea what goes wrong - effectively, both loops end up using the same variable for their loop counter.

Here is the test program:

```nim
iterator iter(): (int, int) {.closure.} =
  for i in 0..<5:
    for j in 0..<10:
      yield (i, j)

for i in iter(): echo i
```

Here is how `iter` looks by the time it gets passed in as input to `closureiters.transformClosureIterator` (this is what I get if I add an `echo n` to the top of that function):

```nim
block :tmp:
  var :envP.i1
  mixin inc
  var :envP.i3 = 0
  block :tmp:
    while :envP.i3 < 5:
      :envP.i1 = :envP.i3
      block :tmp:
        var :envP.j2
        mixin inc
        var :envP.i3 = 0
        block :tmp:
          while :envP.i3 < 10:
            :envP.j2 = :envP.i3
            yield (:envP.i1, :envP.j2)
            inc :envP.i3, 1
      inc :envP.i3, 1
```

The for-loop has been lowered to a while-loop. Notice though that both loops use the same name `:envP.i3` for their loop variable, so the outer loop does `while :envP.i3 < 5` and the inner loop does `while :envP.i3 < 10`. These are different variables - `:envP.i3` is declared twice, once in the outer scope and once in the inner scope.

After `transformClosureIterator` we get this:

```nim
while true:
  block :stateLoop:
    goto :envP.`:state`5
    state 0:
    block :tmp:
      var :envP.i1
      mixin inc
      var :envP.i3 = 0
      block :tmp:
        :envP.`:state` = 1
        break :stateLoop
    state 1:
    if :envP.i3 < 5:
      :envP.i1 = :envP.i3
      block :tmp:
        var :envP.j2
        mixin inc
        var :envP.i3 = 0
        block :tmp:
          :envP.`:state` = 2
          break :stateLoop
    else:
      :envP.`:state` = 5
      break :stateLoop
    state 2:
    if :envP.i3 < 10:
      :envP.j2 = :envP.i3
      :envP.`:state` = 3
      return (:envP.i1, :envP.j2)
    else:
      :envP.`:state` = 4
      break :stateLoop
    state 3:
    inc :envP.i3, 1
    :envP.`:state` = 2
    break :stateLoop
    state 4:
    inc :envP.i3, 1
    :envP.`:state` = 1
    break :stateLoop
    state 5:
    :envP.`:state` = -1
    break :stateLoop
```

At this point, since the block structure of `iter` is gone, it does not seem possible to tell which references to `:envP.i3` are the variable from the outer loop and which are the variable from the inner loop. And indeed in the generated C code, the environment for `iter` only has one `i3` field.

**Comment by nick8325** [comment]
OK, I did a bit more digging, and have a fix! However, I don't know if it's the right fix :)

Here's what's happening. First the inner iterator `0..<10` is expanded (in `transformFor`) to:

```nim
  mixin inc
  var i = a
  while i < b:
    yield i
    inc i
```

* Then `freshVar` is called on `i`, which in turn calls `freshVarForClosureIter`.
* Later, the outer iterator `0..<5` is expanded and `freshVarForClosureIter` is called on its version of `i`.

So we get two calls for `freshVarForClosureIter` for the same symbol `i`. But there is a bug: both calls return the same symbol `i3`!

I think the bug is here:

```nim
proc freshVarForClosureIter*(g: ModuleGraph; s: PSym; idgen: IdGenerator; owner: PSym): PNode =
  ...
  addField(obj, s, g.cache, idgen)
  ...
  let field = getFieldFromObj(obj, s)
```

There is a comment in `addField` explaining that it mangles the name with its ID, so indeed the first call to `freshVarForClosureIter` adds a field `i3` and the second call adds another one `i4`. However, `getFieldFromObj` is only passed `i`, so I don't think it has any way to know whether `i3` or `i4` is wanted. It seems to return the first matching symbol in this case, so both for-loops end up using `i3`.

I fixed this by making `addField` return the `PSym` that it creates. Then `freshVarForClosureIter` just does `let field = addField(obj, s, g.cache, idgen)` rather than calling `getFieldFromObj`. And the iterator is then compiled correctly :) However:

1. This is also my first Nim issue so I've absolutely no idea if this is the right solution :)
2. I don't know if any of the other calls to `addField` and `getFieldFromObj` in `lambdalifting.nim` should be checked.

I could make a pull request though if this is a reasonable fix. @Araq, do you have any thoughts/hints?

**Comment by Araq** [comment]
Sounds good. Please create a PR.
