### ISSUE TITLE
Importing winlean module forces {.passC: "-DWIN32_LEAN_AND_MEAN".}

### ISSUE THREAD

**Issue by veksha** [nim-lang/Nim#18680]
Importing `winlean` module forces `{.passC: "-DWIN32_LEAN_AND_MEAN".}`
This might not be desirable by all developers.
WIN32_LEAN_AND_MEAN is a macro that must be controlled by developer in user code, not by stdlib.

I believe that lib that expects this macro to be defined by stdlib is poorly designed project.
but I will be happy with it not being removed but to make it optional so developer decides what is best for him.

### Example (not a real world example! minified for simplicity)
```nim
#[
nim c -r --app:gui sometest
]#

import os

type HDROP {.importc.} = object
var hDrop: HDROP
```

### Current Output
```
error: unknown type name 'HDROP'
```

### What is happening

1. `--app:gui` includes <windows.h>
2. `import os` imports winlean.nim (which forces WIN32_LEAN_AND_MEAN, therefore windows.h includes only minimal set of header files)
3. developer can't do importc `HDROP`, for example.

### Workaround
underfine WIN32_LEAN_AND_MEAN right after import.
```nim
import os
{.passC: "-UWIN32_LEAN_AND_MEAN".}
```
... BUT this will create a LOT of warnings by vcc compiler (and they can't be disabled)!

### Possible Solution

* remove `{.passc: "-DWIN32_LEAN_AND_MEAN".}` line from winlean.nim
or
* make it optional adding `when defined(Win32LeanAndMean)` just before.

### 

### Additional Information

* Issue #3879 is related

```
$ nim -v
Nim Compiler Version 1.5.1 [Windows: amd64]
Compiled at 2021-08-09
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 8ce782d463b0bca091be5a34db190dc441c23ce4
active boot switches: -d:release
```

**Comment by demotomohiro** [comment]
`winlean` exists just for implementing stdlib and it imports only functions Nim's stdlib uses.
It is not for a generic windows API programming.
Winim module provides much more windows APIs:
https://github.com/khchen/winim

When I compiled following code, nim still calls gcc with `-DWIN32_LEAN_AND_MEAN` options.
But it compiled without errors because winim defines `HDROP` type and `DragFinish` proc without using windows.h file.

```nim
import std/os
import winim/shell

var hDrop: HDROP
DragFinish(hDrop)
```

**Comment by veksha** [comment]
> `winlean` exists just for implementing stdlib and it imports only functions Nim's stdlib uses.
> It is not for a generic windows API programming.

why restrict?

> Winim module provides much more windows APIs:
> [khchen/winim](https://github.com/khchen/winim)

that was just a small example with "HDROP". The real application like mine might want to mix nim and cpp code by including third-party SDK with {.emit:#include..}. And that SDK includes windows.h assuming that it is full and not LEAN. it will not include it second time, because it was already included by importing `os` that is useful too. by importing `os` you're also importing `winlean` and changing compiler command line by defining lean_and_mean! that is ugly, in my opinion.

So SDK depends on full windows.h, otherwise it fails with a lot of errors like undefined far/near, undefined "HDROP", "interface", "IDataObject", "IUnknown", and a lot of errors like "unexpected token(s) preceding ';'"
without LEAN_AND_MEAN it just works like a charm. but that means that I need to comment out that forced define in nim library sources everytime.

I just don't know why lean_and_mean is forced in 2021. what are the reasons? it was useful in windows 95 times, i think, but not today.

> When I compiled following code, nim still calls gcc with `-DWIN32_LEAN_AND_MEAN` options.
> But it compiled without errors because winim defines `HDROP` type and `DragFinish` proc without using windows.h file.

I'm aware about winim module. as you can see above, that is not useful to my application. anyways, thank you for trying to help me.

**Comment by Araq** [comment]
PRs are welcome.

**Comment by demotomohiro** [comment]
> > `winlean` exists just for implementing stdlib and it imports only functions Nim's stdlib uses.
> > It is not for a generic windows API programming.
> 
> why restrict?

I think that is because windows API is very large compared to a set of windows API Nim's stdlib uses.
If `winlean` contained most of windows API, compiling it on windows would be slow even if you don't directly use windows API.

`-DWIN32_LEAN_AND_MEAN` does not means you cannot use some of windows APIs, it just reduce a number of header files windows.h includes.
You can still use other windows APIs by including specific header file.

For example:

```C
#include <windows.h>
#include <shellapi.h>

int main() {
  HDROP a;
  return 0;
}
```
This code can be compiled without error even if gcc called with `-DWIN32_LEAN_AND_MEAN` option.
Windows API reference tells with header file should be included.
https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-dragqueryfilea

I compared compile time with/without `WIN32_LEAN_AND_MEAN`.

winleantest.c:
```c
#include <windows.h>
#ifdef WIN32_LEAN_AND_MEAN
#  include <shellapi.h>
#endif

int main() {
  HDROP a;
  return 0;
}
```

winleantest.nim:
```nim
import std/[monotimes, times, osproc, strformat]

proc measure(command: string) =
  const numLoop = 20
  let start = getMonoTime()
  block:
    for i in 0 ..< numLoop:
      doAssert execCmd(command) == 0
  let delta {.inject.} = getMonoTime() - start
  echo &"{command}: {delta.inMilliseconds.float / 1_000.0 / numLoop} sec"

proc main =
  measure("gcc winleantest.c")
  measure("gcc -DWIN32_LEAN_AND_MEAN winleantest.c")

main()
```

Output:
```
f:\>nim c -d:danger winleantest.nim
f:\>winleantest.exe
gcc winleantest.c: 1.39365 sec
gcc -DWIN32_LEAN_AND_MEAN winleantest.c: 0.8519500000000001 sec
```

When I create a new Win32 project on Visual Studio 2015, it generates a `stdafx.h` with `#define WIN32_LEAN_AND_MEAN` before `#include <windows.h>`.
I think that means most of cpp projects on windows works with `WIN32_LEAN_AND_MEAN`.

**Comment by veksha** [comment]
> When I create a new Win32 project on Visual Studio 2015, it generates a `stdafx.h` with `#define WIN32_LEAN_AND_MEAN` before `#include <windows.h>`.
> I think that means most of cpp projects on windows works with `WIN32_LEAN_AND_MEAN`.

maybe "most" but not all. SDK that I'm using is not in this list.
also micro$oft includes it in user code so you can remove it in your app. (and with precompiled headers it's not an issue for VS.)
anyways, thank you. nice test. :)

**Comment by cheatfate** [comment]
I can confirm that `WIN32_LEAN_AND_MEAN` directive is normal practice and default setting for Visual Studio 2017 project too.

@veksha sorry, but even reproducible source you have used in this issue exploits the knowledge that something imports `winlean.nim` and you do not import it directly.

When you using Windows API or types you should not assume that `winlean.nim` or any other module imports everything you need. For this purposes use `winim` package. But if you do not want to import `winim` - declare your types and procedures properly.

So if you need to use `HDROP` type, declare it properly:
```nim
  import os
  type HDROP {.importc, header: """#include <windows.h>
                                   #include <shellapi.h>""".} = object
  var hDrop: HDROP 
```
And this code will work whatever `define` has been declared, because you explicitly defined headers you need.
And this is actually how you should do, you can check how it is done in `stdlib` https://github.com/nim-lang/Nim/blob/devel/lib/pure/ioselects/ioselectors_select.nim

**Comment by veksha** [comment]
@cheatfate
WIN32_LEAN_AND_MEAN directive is not my normal practice and not default setting for my project.
because I can't modify 3rd-party SDK's that are responsible for including windows headers and declaring types/methods. I just want to emit-include sdk.h and not waste hours of wandering why I can't undefine a simple macro that is generating errors without editing stdlib.

"normal practice" and "default" != "can't be disabled"
in VS this macro is explicitly defined (you can remove it), why in Nim we don't even have an option to disable it?

**Comment by cheatfate** [comment]
So `why the need of one should be higher than the need of many`? Just because you are using unnamed 3rd party SDK and you have troubles which can be workarounded?
So maybe its time to create an issue inside 3rd party SDK repository and ask for support there?

You have not presented enough arguments in this issue to change stdlib behavior which is used by many other people and projects.

**Comment by veksha** [comment]
> So `why the need of one should be higher than the need of many`? Just because you are using unnamed 3rd party SDK and you have troubles which can be workarounded?

option will be enough.
workaround generate warnings, you should've read this thread more carefully.

> So maybe its time to create an issue inside 3rd party SDK repository and ask for support there?

I don't think that optional macro will hurt anyone, but forced macro is already hurting me :)

> You have not presented enough arguments in this issue to change stdlib behavior which is used by many other people and projects.

OK. I just think that Nim can be more versatile and allow users to take control of their compiler command line.
I am people too :-)

**Comment by cheatfate** [comment]
This is real bug in 3rd party SDK if it uses types and function declarations without proper `#include` directive.

**Comment by cheatfate** [comment]
For example this code
```nim
import winlean
{.passC: "-UWIN32_LEAN_AND_MEAN".}
var VS_VERSION_INFO {.importc: "VS_VERSION_INFO", header: "<windows.h>".}: cint
var FIONBIO {.importc: "FIONBIO", header: "<winsock2.h>"}: cint
when isMainModule:
  echo VS_VERSION_INFO
  echo FIONBIO
```
is working for `mingw64` but did not work for `vcc`. So Nim CI is green because it doesn't test `vcc` compiler.

But on Windows its the only way to get some debugging support is to use `vcc` compiler instead of `mingw64`.

**Comment by veksha** [comment]
> This is real bug in 3rd party SDK if it uses types and function declarations without proper `#include` directive.

1. there is no bug. you just want to put your macro on everyone.
2. MFC project template is not what all programmers choose when they use VS.
3. please, read here, similar problem, nice answer: https://github.com/SergiusTheBest/plog/issues/13
i.e. developer is responsible for defining this macro. developer takes full control and responsibility on this.
not libs, not stdlibs.

**Comment by veksha** [comment]
> For example this code
> 
> ```nim
> import winlean
> {.passC: "-UWIN32_LEAN_AND_MEAN".}
> var VS_VERSION_INFO {.importc: "VS_VERSION_INFO", header: "<windows.h>".}: cint
> var FIONBIO {.importc: "FIONBIO", header: "<winsock2.h>"}: cint
> when isMainModule:
>   echo VS_VERSION_INFO
>   echo FIONBIO
> ```
> 
> is working for `mingw64` but did not work for `vcc`. So Nim CI is green because it doesn't test `vcc` compiler.
> 
> But on Windows its the only way to get some debugging support is to use `vcc` compiler instead of `mingw64`.

you just replace -U with -D. but here, in your code. not in stdlib.

**Comment by veksha** [comment]
closing. isn't very popular.
