### ISSUE TITLE
chinese words on windows command line Garbled code

### ISSUE THREAD

**Issue by appemit** [nim-lang/Nim#19022]
OS: Windows 7 x64
![image](https://user-images.githubusercontent.com/65663182/138089057-628e7086-a0b0-4ed7-a54c-63b9151a7838.png)

```nim
# app.nim, saved as UTF8
import encodings
echo "chinese 中文"
var s = "Nim中的字符串编码转换"
echo getCurrentEncoding()                            

var convencoding: EncodingConverter
convencoding = open("GB2312","UTF-8")
echo convert(convencoding,s)

convencoding.close()

echo convert(s,"GB2312","UTF-8")
```

![image](https://user-images.githubusercontent.com/65663182/138089273-6e300ffe-f4fa-4396-8843-14af9d163e29.png)

 
How do I solve the issue?

**Comment by ghost** [comment]
But why are you using the `encodings` module if your text is already UTF-8? Can you try with

```nim
echo "chinese 中文"
echo "Nim中的字符串编码转换"
```

**Comment by ghost** [comment]
@appemit did my comment help you with the issue?

**Comment by appemit** [comment]
> But why are you using the `encodings` module if your text is already UTF-8? Can you try with
> 
> ```nim
> echo "chinese 中文"
> echo "Nim中的字符串编码转换"
> ```

# app.nim, saved as UTF8
import encodings
echo "chinese 中文"

I have saved the file as  UTF8.

echo "chinese 中文"     just  Garbled code , which you can see in the picture above.

**Comment by DMI-1407** [comment]
the problem is not the code, its the cmd.exe from windows 7.
you can e.g. write the chinese text to a file or use mintty (with charset GBK) which ships with the setup from git.
`writeFile("test.txt", s)`
![image](https://user-images.githubusercontent.com/53574099/138506144-08663bb7-99a6-4d43-b0b4-aba6809f5946.png)

**Comment by appemit** [comment]
thanks.
the problem is the cmd.exe in windows 7_64. Others is ok but mine is not.
and I cann't solve it as well.

**Comment by demotomohiro** [comment]
I'm sorry but I don't have chinese windows 7 machine.
I wrote this based on my japanese 64bit windows 8.1.

Nim code that echo japanese text on `cmd.exe` in default setting doesn't display japanese text in utf8 correctly.
I fixed it in following way:
1. Run `cmd.exe`
   - Code page must not be 65001
2. Push Alt + space key then push 'p' key to open property window
3. In font tab, change font to any font that can display japanese except Raster font(Raster font is selected in default that cannot display japanese text in code page 65001)
4. Running Nim code that output japanese text like `echo "こんにちは"` work correclty.

I can't choose the font that can display japanese correctly when the console is in code page 65001.

Quote from
https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_1_0_0.md

> On Windows console applications the code-page is set at program startup to UTF-8. Use the new switch -d:nimDontSetUtf8CodePage to disable this feature.

Related code:
https://github.com/nim-lang/Nim/blob/62701cd3b92677c2014cf70b1cf5a5ba6e0468bf/lib/system/io.nim#L829

On windows, when you open the command prompt (`cmd.exe`), it is in the code page that supports only specific language.
If you run a program that is supposed to be run in that code page, it can output text correctly.
But when you run a Nim program, it changes the code page to Utf8 65001.
Then, in default `cmd.exe` setting, the console font is changed and japanese output text on the console are displayed incorrectly.

Problems in default setting `cmd.exe` console in UTF-8 code page 65001:
1. Cannot type japanese because cannot turn on Windows IME (I can use Windows IME in default code page)
2. Dos command displays message in english (they displays message in japanese in default code page)
3. After changing code page to 65001 from default code page, japanese text output before changing code page are garbled and the console font is changed 
4. Localized program (For example, cl.exe in VisualStudio 2015) that output japanese message doesn't output message
5. Simple Nim code like `echo "こんにちは"` (encoded with UTF-8) cannot display japanese.

Changing `cmd.exe` font fixes only 4 and 5.

So using Nim console program with localized console application might annoying for people who don't know english unless you compile the Nim program with `-d:nimDontSetUtf8CodePage` and write stdout/stderr with the encoding corresponding to your code page.

This is what happans on `cmd.exe` in default setting when running Nim program in japanese Windows 8.1:

I ran `cmd.exe` and ran `chcp` and `chcp /?`.
It starts with code page 932 and `chcp /?` displays help message in japanese.
It displays path separator as yen (Tradition of Windows/Dos in japan).

![before](https://user-images.githubusercontent.com/1882512/138576084-fcb3c6e0-b751-41a2-a16d-52cc210f161e.png)

Then, I ran `nim -v`.
Console font and window size are changed. And it displays path separator as back slash.
Japanese text outputs from `chcp` and `chcp /?` are broken.

![rightafter](https://user-images.githubusercontent.com/1882512/138576113-5adcf6b2-f66f-469b-bbac-4359c9fc4f36.png)

After `nim -v`, `chcp` and `chcp /?` displays message in english.

![after](https://user-images.githubusercontent.com/1882512/138576127-4c3dac71-aa0c-41e0-839e-6a972058f9f8.png)

I ran VS2015 x86 Native Tools command prompt.
Code page is 932.
`cl /?` displays help message in japanese.

![clbefore](https://user-images.githubusercontent.com/1882512/138576165-4c57fa74-ad6d-47dd-bd8e-557833a2d07e.png)

Running `cl /?` after `nim -v`.  It displays nothing.

![clafter](https://user-images.githubusercontent.com/1882512/138576174-44a2daa9-0060-4629-938a-979bb822afaa.png)


## Other workaround

Saving following nim code in shift jis encoding that corresponding to my default code page 932 worked correcly in my `cmd.exe` in code page 932.
```nim
echo "こんにちは"
```

Compile with following command:
```
nim c -d:nimDontSetUtf8CodePage testechoSjis.nim
```

But saving non-alphabet charactor in non-unicode encoding can be a problem when you want to support linux or other OS.
Most of modern linux use UTF-8.

Following Nim code checks console's code page and output japanese text only when code page 932:

testenc.nim (save in utf-8 encoding)
```nim
import std/encodings

when defined(windows):
  #echo getCurrentEncoding()
  # "shift_jis" is a encoding for japanese windows (codepage 932)
  let isLocalize = getCurrentEncoding() == "shift_jis"
  let encodingConverter = if isLocalize: open("shift_jis", "UTF-8") else: EncodingConverter()

  proc enc(srcLocal, srcEnglish: string): string =
    if isLocalize:
      encodingConverter.convert(srcLocal)
    else:
      srcEnglish

else:
  proc enc(srcLocal, srcEnglish: string): string = srcLocal

echo enc("こんにちは", "Hello")
```

Compile:
```
nim c -d:nimDontSetUtf8CodePage testenc.nim
```

Another workaround is run `cmd.exe` from [Neovim](https://neovim.io)'s terminal buffer.
Running command `:terminal cmd.exe /k chcp 65001` opens new terminal in code page 65001.
Or put dos commands you want to run before using console in .bat file and run `:terminal cmd.exe /k yourbatfile.bat`
Nim code that output utf-8 japanese workds and I can type japanese on console in code page 65001.
`cl.exe` output japanese text correctly.
I can copy & paste texts on console, move cursor, scroll, etc in the vim way.
But dos commands still output message in english.

How to reset the looks of the Command Prompt window, in Windows?
https://superuser.com/questions/609470/how-to-reset-the-looks-of-the-command-prompt-window-in-windows

**Comment by Varriount** [comment]
Just to note, the reason this isn't a problem in some other languages (such as Python) is because calls like `print`, `echo`, etc. automatically encode strings using the console's current encoding.
