### ISSUE TITLE
std/os createDir with Windows URL erring

### ISSUE THREAD

**Issue by gwque** [nim-lang/Nim#19103]
The std/os import is failing when using createDir on Windows using a URL:

```
import std/os
# this path doesn't work
let newFldr = "\\\\myserver\\myshare\\test1"
# this works when X: maps to \\\\myserver\\myshare
# let newFldr = "X:\\test1"
createDir(newFldr)
```
The error:
```
C:\Apps\nim-1.6.0\lib\pure\os.nim(2552) createDir
C:\Apps\nim-1.6.0\lib\pure\os.nim(2522) existsOrCreateDir
C:\Apps\nim-1.6.0\lib\pure\os.nim(2507) rawCreateDir
C:\Apps\nim-1.6.0\lib\pure\includes\oserr.nim(95) raiseOSError
Error: unhandled exception: The specified path is invalid.
```

Using std/winlean, createDirectoryW works with the same path:
```
let ws = newWideCString(newFldr)
let r = createDirectoryW(ws,nil)
```

see forum issue https://forum.nim-lang.org/t/8595 for discussion

**Comment by MegaIng** [comment]
The problem here is that `createDir` is incorrectly implemented. The implementation tries to adjust for the windows weirdness of the first part of the absolute path being something that shouldn't be passed to `rawCreateDir`, but for UNC paths this is actually the first three segments that should be skipped: `//<server name>/<share name>`. Currently the implementation only skips the empty segment before the server name and then tries to do `existsOrCreateDir("//<server name>")` which fails.

I think most other functions in `std/os` are broken in a similar way. Despite looking like two path components, the entire `//server/share/` should be treated as a drive like `C:`. Compare the behavior to python's `os.path.split`:

```
>>> os.path.split(r"\\wsl.localhost\Ubuntu")
('\\\\wsl.localhost\\Ubuntu\\', '')
```

Vs nim's `splitPath`:

```
>>> echo splitPath(r"\\wsl.localhost\Ubuntu")
(head: "\\\\wsl.localhost", tail: "Ubuntu")
```

**Comment by havardjohn** [comment]
@MegaIng That's great research. The Python function `makedirs` does the same as `createDir` in Nim, but handles UNC paths correctly. It calls the `os.path.split` function you mention. That seems to account for UNC paths by first splitting away the drive/UNC part of the path with a Windows-specific `splitdrive` function, so that the UNC path is kept as is. I think `splitdrive` should be copied to Nim to fix this issue.

Are you working on fixing this, @MegaIng, or anyone else? This issue affects me, so I'd like to work on this.

**Comment by MegaIng** [comment]
@havardjohn I am currently not working on this, but might do so in a few days if noone else says they will do it.

**Comment by havardjohn** [comment]
> @havardjohn I am currently not working on this, but might do so in a few days if noone else says they will do it.

Alright. I'm working on this now.
