### ISSUE TITLE
colors.isColor and colors.parseColor do not recognize "LightGrey"

### ISSUE THREAD

**Issue by orthoplex** [nim-lang/Nim#19124]
### Example
```nim
import colors
echo colors.isColor("LightGrey")
echo colors.parseColor("LightGrey")
```

### Current Output
```
false
/home/orthoplex/nimbug/bug.nim(3) bug
/usr/lib/nim/pure/colors.nim(456) parseColor
Error: unhandled exception: unknown color: LightGrey [ValueError]
```

### Expected Output
```
true
#D3D3D3
```

### Solution

Both procedures perform a binary search on colorNames, which is not sorted correctly.
To fix this, "lightgrey" and "lightgreen" need to be swapped.

**Comment by orthoplex** [comment]
Pull Request: #19125

**Comment by GrayJoKing** [comment]
This technically "fixes" the issue, but it probably should have instead been renamed to the American spelling "lightgray" in order to match with the rest of the gray colours. This module as a whole should also be updated to fully follow the CSS colours standard, which includes both spellings as aliases (additionally, a couple of the colour codes are incorrect, with `8`s swapped out for `B`s)

**Comment by Araq** [comment]
Please produce a follow-up PR.

**Comment by orthoplex** [comment]
I deliberately did not rename the color to "lightgray" since that would also involve changing the corresponding constant name to `colLightGray`, which could break existing code. I think the most reasonable way to fix the naming inconsistency would be to introduce all variations of "grey" and "gray".
