### ISSUE TITLE
When expression evaluation of booleans too eager

### ISSUE THREAD

**Issue by JorySchossau** [nim-lang/Nim#19140]
I expected conditional short-circuiting, but was surprised when it didn't happen.
Possibly related to #2002 and #12188.
The workaround is obvious, but this was unexpected.

```nim
template f(x:auto) =
  when
    x is (int,int): # expectedly does not trigger
      discard
  elif
    x is (int,int) and x[0] == 0: # unexpectedly triggers w/ error
      discard
  elif
    x is string: # expected trigger
      echo "got string"

f "hello"
```
```
Error: type mismatch: got <char, int literal(0)>
but expected one of:
proc `==`(x, y: char): bool
  first type mismatch at position: 2
  required type for y: char
  but expression '0' is of type: int literal(0)
```

**Comment by konsumlamm** [comment]
The problem is that `x is (int,int) and x[0] == 0` is a single expression, so imo it makes sense that this doesn't work (`when` doesn't special case `and`). A solution would be to special case `and` (and `or`, for consistency) in `when` conditions, but i don't think that's a great idea (it just special cases specific syntax, what if someone defined their own short-circuit operator, does that need to be special cased as well then?).

Either way,  your example code doesn't make much sense, since the first condition already is true when the type of `x` is `(int, int)`, so the second condition will never be checked. (And even if it would be, `x[0] == 0` would only work if `x` can be evaluated at compile time.)

**Comment by Araq** [comment]
"Unexpected" is bad, but it's not a bug.
