### ISSUE TITLE
Wrong GC-safe Warning for recursive procs.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#19339]
Compile this code:
```nim
proc outer()

proc inner() =
  outer()

proc outer() =
  inner()

proc main() {.gcsafe.} =
  outer()

main()
```

Produces warnings:
```
/p/try/gccrap2.nim(7, 6) Warning: 'outer' is not GC-safe as it calls 'inner' [GcUnsafe2]
/p/try/gccrap2.nim(10, 6) Warning: 'main' is not GC-safe as it calls 'outer' [GcUnsafe2]
```

I feel should not produce this warning and this is a bug. This recursion should be gc safe.

```
Nim Compiler Version 1.6.0 [Linux: amd64]
Compiled at 2021-10-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 727c6378d2464090564dbcd9bc8b9ac648467e38
active boot switches: -d:release -d:danger
```

**Comment by Araq** [comment]
https://nim-lang.org/docs/manual.html#effect-system-gc-safety-effect 

"The GC safety property is usually inferred. The inference for GC safety is analogous to the inference for exception tracking."

--> https://nim-lang.org/docs/manual.html#effect-system-exception-tracking

"Every call to a proc q which has an unknown body (due to a forward declaration)"
