### ISSUE TITLE
isValidFilename is unreliable on Linux

### ISSUE THREAD

**Issue by vercingetorx** [nim-lang/Nim#19574]
isValidFilename on Linux ignores the one restricted character '/'. This is because isValidFilename handles filenames as filepaths.

ex:
```nim
let filename = "my/filename.ext"
echo filename.isValidFilename()
```

This IS an invalid filename and should return false, but returns true. Because filenames are handled as filepaths, it will by definition never catch forward slashes. A real world example where this issue crops up is my youtube downloader where video titles are used as the filenames and isValidFilename fails to catch forward slashes.

Consider not handling filenames as full filepaths or split into seperate isValidFilename / isValidFilepath procs.

**Comment by juancarlospaco** [comment]
`"/"` is os sep in Linux,
therefore `"my/filename.ext"` is a folder `"my"` and a file `"filename.ext"` by definition, therefore must be `true`.

`isValidFilepath` is not possible to implement cheaply,
basically because anything can be mounted as a path in Linux and its 3584390850392 supported filesystems.


![2022-03-05_08-20](https://user-images.githubusercontent.com/1189414/156891601-69c83b10-e1a0-48b7-b2e1-9a5953501547.png)


> **func only checks filenames.**

**Comment by vercingetorx** [comment]
"/" is os sep in Linux,
    therefore "my/filename.ext" is a folder "my" and a file "filename.ext" by definition, therefore must be true.

This is true only if you treat the string as an implicit filepath, which is an arbitrary choice. The way I view it is you have some string, any string and you don't necessarily know what the string contains but you want to see if that string can be used as a filename, hence calling isValidFilename. In other words, treating it as strictly the file name portion of a path, not the entire path itself which is the way it's done now.

Anyway, I will close this as i'm confident this is a won't fix scenario.
