### ISSUE TITLE
improved db_postgres docs.

### ISSUE THREAD

**Issue by sdmcallister** [nim-lang/Nim#19606]
### Summary
Using db_postgres can have a bad first impression on windows. Say you have a dev database on your windows system. You try to connect using the db_postgres docs examples and you likely get the error "could not load: libpq.dll".  Depending on your experience or background you may be used to things 'just working'. For example, db_sqlite just works. At this point you may go back to the inferior language or continue to search for answers.  

If you continue to search, you might discover you need to include the shared lib / dll and where it should be located. So, you download the latest version of postgresql and copy the libpq.dll over.  You then get the same error as before.  At this point, you may again give up or persist by searching again for more information. I just copied all of the dlls over which seemed to do the trick. I suppose there is some type of additional windows utility to check for specific dependencies. I'll mention that with db_mysql just copying the 1 required dll was sufficient.

**Comment by Araq** [comment]
Usually, for databases, you don't copy the DLLs around, you ensure they are in your %PATH%. That we ship sqlite.dll with the Nim distribution is partly a historical accident and partly because it's an **embedded** database.

There is nothing to fix here, at some point when you develop for Windows, you have to learn some basics about Windows. If you don't want to learn how things work and never try to get your program to actually run on a different computer, then yes, the "inferior" language that happens to ship `libbq.dll` (but then what happens when you need `mongodb.dll`?) might be better for you.

**Comment by sdmcallister** [comment]
@Araq  
`ensure they are in your %PATH%`

I'm not suggesting ship the postgres dlls or that anything is broken. But why not just add that comment or something similar to the docs for db_postgres and db_mysql?

**Comment by Araq** [comment]
> But why not just add that comment or something similar to the docs for db_postgres and db_mysql?

Oh, that's a good idea. Sorry for the misunderstandings.
