### ISSUE TITLE
Can't check if stderr is static

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#19680]
While working on Futhark I wanted to decide whether or not to put something into a `const` or a `let`. Basically it tries to read out macros which can resolve to simple numbers and I want those to be consts, but it can also be other stuff which can't go into a const. I came if with a solution of using `when x is static: const y = x else: let y = x` which works fine for most identifiers. But certain built-ins like `stdout` and `stderr` makes the compiler crash.

### Example
```nim
when stderr is static:
  echo "whoops"
else:
  echo "works"
```

### Current Output
```
fatal.nim(53)            sysFatal
Error: unhandled exception: index -1 not in 0 .. 0 [IndexDefect]
```

### Expected Output
```
works
```

### Possible Solution
Not really sure what a possible solution would be, but building a debug compiler gives a lot more output to work with.

**Comment by Cloudperry** [comment]
Your code might be triggering the same underlying compiler bug that I hit with nim-regex. The last 6 lines of the debug compiler stack trace are the same as with the code here: https://github.com/nitely/nim-regex/issues/107. Idk if this is helpful at all, because it seems your code is a simpler way to trigger the same bug.

**Comment by beef331** [comment]
Seems it's an issue with `x is static` it attempts to check the `[^1]` element of `static` which is empty given you did give a type and as such it crashes. Since `static` is not a typeclass I dont think it should work either you need a macro which checks the `symKind` or `typeKind` to see if it's static.

**Comment by ringabout** [comment]
built-ins like stdout and stderr are importc symbols

see https://github.com/nim-lang/Nim/pull/19709

It is a regression since 1.2.0 caused by https://github.com/nim-lang/Nim/pull/12877
