### ISSUE TITLE
Request: Make using-a-variable-after-move an error (or warning)

### ISSUE THREAD

**Issue by singularperturbation** [nim-lang/Nim#19768]
### Summary

If I understand the current behavior, a moved object is reset to its 'zero value' after being moved.  This can result in [unintuitive behavior](https://www.reddit.com/r/nim/comments/ufy1a7/is_move_of_a_ref_object_and_accessing_later_to/) and I think that accessing an object after it's moved is usually a mistake - a non-ref object could be even worse, because then reading a field would give the zero value for that field, sillently continuing to run with wrong data.

### Description

Would it be possible to make this

```nim
type
  data = ref object
    id : string

var testData = data(id:"zone-5")
var zone = move testData
# error/warn here
echo testData.id
```

a compile-time error?

### Alternatives

Could be a run-time error, like Rust's [RefCell](https://doc.rust-lang.org/std/cell/index.html), or maybe something that a linter would catch.  Could opt into it as a compiler setting?

**Comment by Araq** [comment]
If the compiler can prove it's the last access you don't have to write `move`. If it cannot prove that it usually cannot warn about it either. Don't write `move` if it produces errors for you... What we will add instead is an `ensureMove` call so that you can see if your idea aligns with the compiler's.
