### ISSUE TITLE
Disallow private types used in public functions

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#19793]
```nim
type
  Foo = object
    x: int

proc bar*(): Foo =
  Foo(x: 42)

```

Notice how `Foo` will not be accessible outside this module. We should make this kind of code an error to ensure library authors don't accidentally forget to make a type public when it is used in a public proc.

**Comment by ghost** [comment]
Is there a reason this is a feature request and not an RFC? I thought all similar requests should go through an RFC first.

**Comment by dom96** [comment]
I didn't think this merited much of a discussion, but can be transferred to the RFCs repo easily if it does.

**Comment by ghost** [comment]
@dom96 personally I don't have such a strong opinion on this as on case-insensitivity, but there are actual valid use-cases for this, for example if you want to let users use your type as an "opaque" type without actually knowing its structure. The alternative would be to do this, which is more ugly:
```nim

type
  MyInternalType = object
    stuff: string
    otherstuff: int
  MyType* = object
    internal: MyInternalType
```

Is there a reason for making it an error except for correcting possible mistakes of library authors? I really always thought Nim is about freedom, and freedom can and will be misused and there's nothing wrong with that. There are a lot of features that can be misused by library authors or users, but using them is not an error either.

At max this should be a hint.

EDIT: Thinking about it for more, there is indeed not much difference since you can have the fields private anyway, so I guess I'm neutral to this change. But I'm still not sure what exact problem this will solve. Ability to create new variables of the type returned by public procs?

**Comment by bluenote10** [comment]
@Yardanico Your work-around seems unnecessary. All fields of the type are private, so from the outside, the object already is opaque, isn't it?

For reference in Rust this is checked

![image](https://user-images.githubusercontent.com/3620703/168462859-bbb6a793-4b32-44c1-b660-775168405d9f.png)

![image](https://user-images.githubusercontent.com/3620703/168462889-91417832-65a5-4bd2-8b24-fd4c681e8de6.png)

which makes total sense. What's the value of this kind of freedom if you accidentally make your library unusable from the outside? Happened several times to me.

**Comment by Araq** [comment]
> What's the value of this kind of freedom if you accidentally make your library unusable from the outside?

Totally wrong question. Every feature, including "linting" features start as "not implemented" and cause on-going costs for good.

Why not test your code before publishing? A `runnableExample` ensures that the example is run outside of the current module.

**Comment by bluenote10** [comment]
> Why not test your code before publishing?

Exactly, the freedom costs time either on library maintainer or library consumer site, perhaps not Nim maintainer site.

Just saying that I lost time because there is no check, and I'm happy that in Rust this is checked.
