### ISSUE TITLE
Replace SHA-1 and MD5 with non-deprecated hashing functions

### ISSUE THREAD

**Issue by WeebNetsu** [nim-lang/Nim#19863]
### Summary
Both the SHA-1 and MD5 methods are deprecated, and should no longer be used for hashing.

### Description

The sha1 and md5 std modules in Nim should be deprecated (because those hashing methods themselves are deprecated) and replaced with sha2 and/or other newer hashing methods instead 

### Additional Information

Nim hashing modules: https://nim-lang.org/docs/lib.html#pure-libraries-hashing
Nim MD5 hashing: https://nim-lang.org/docs/md5.html
Nim SHA-1 hashing: https://nim-lang.org/docs/sha1.html

**Comment by juancarlospaco** [comment]
I think thats up to the purpose, latest Git uses SHA1 for example,
and for checksum like purposes still Ok, I agree with adding more algos.

**Comment by tersec** [comment]
Git is migrating away from SHA-1(https://git-scm.com/docs/hash-function-transition/) as is Mercurial (https://www.mercurial-scm.org/wiki/SHA1TransitionPlan).

They're not well-suited for non-legacy applications for checksum purposes either, they don't lie on any particular Pareto curve of speed/security. If one wants fast, mostly-cryptographic-quality hashes, there are faster hashes than either. If one wants genuine speed, they were never a good choice. If one wants actual cryptographic collision resistance, well, collisions are known and can be generated for both.

**Comment by Araq** [comment]
These checksums can be part of protocols etc and they are correctly implemented to the best of my knowledge. We should add documentation for discouraging their usage, but not deprecate them. Encryption is an ever moving target so anything we would add today would be deprecated in 5-10 years.

**Comment by tersec** [comment]
That's convenient, since Nim's standard library doesn't include any cryptographic encryption, only cryptographic hashing.

SHA-1 as part HMAC-SHA1 does continue to see use, and the widely used TOTP frequently uses SHA-1 (though it can also use SHA-2: https://datatracker.ietf.org/doc/html/rfc6238), but in general, it's not necessarily worth supporting protocols that depend still on MD5.

For example, https://www.ietf.org/rfc/rfc9155.html notes:
> 2. Signature Algorithms
>
> Clients MUST include the signature_algorithms extension. Clients MUST NOT include MD5 and SHA-1 in this extension.
> 3. Certificate Request
>
> Servers SHOULD NOT include MD5 and SHA-1 in CertificateRequest messages.
> 4. Server Key Exchange
>
> Servers MUST NOT include MD5 and SHA-1 in ServerKeyExchange messages. If the client receives a ServerKeyExchange  message indicating MD5 or SHA-1, then it MUST abort the connection with an illegal_parameter alert.
> 5. Certificate Verify
>
> Clients MUST NOT include MD5 and SHA-1 in CertificateVerify messages. If a server receives a CertificateVerify message with > MD5 or SHA-1, it MUST abort the connection with an illegal_parameter alert.

The same RFC explicitly states that HMAC-SHA1 is fine for now.

One proposal:
- deprecate `md5` with the genuine intent at some point to remove;
- clearly document the limitations of `sha1`. "Deprecation" might be too strong, but it should not be something people just reach for casually; and
- since currently having some cryptographic hashing algorithm, but not a more generally secure one, creates a kind of attractive nuisance in Nim, if one's going to keep SHA-1, add SHA-2 (the 256 and maybe 512-bit version), to avoid funneling people into using SHA-1 in new applications where they shouldn't, by virtue of minor convenience.

It would have been reasonable to simply not have any of these in Nim's stdlib. But once they're there, it is a hazard to the ecosystem as a whole not to update them at least once every decade or so.

**Comment by Araq** [comment]
> But once they're there, it is a hazard to the ecosystem as a whole not to update them at least once every decade or so.

For version 2 we're trimming down the stdlib so it might make sense to remove these modules indeed.

**Comment by dlesnoff** [comment]
Is this issue only concerning the documentation?

If the issue is about adding a hashing algorithm, is SHA-2 the best option? We've got many different options for hashing functions with basic implementations in [nimcrypto](https://github.com/cheatfate/nimcrypto).

I consider all round 3 candidates for the SHA-3 NIST competition good alternatives. While they are more recent than old SHA-2 hashing algorithms, many research papers have studied their security, for more than ten years long.
[The most recent variant of the Blake hash function family Blake3](https://github.com/BLAKE3-team/BLAKE3) is 1.3x faster than SHA-256 and 3x faster than SHA-512.

These crypto StackExchange forum posts explain well the consequences of using hashing algorithms with known collisions and could serve as a basis for our own documentation.

[Understanding why hash collisions are problematic](https://crypto.stackexchange.com/questions/98954/understanding-hash-collisions-why-bad)
[Examples of technical problems arising from signature forgery](https://crypto.stackexchange.com/questions/87104/what-are-other-good-attack-examples-that-use-the-hash-collision)

I would like to add a comment on cryptographic design: If cryptographic concerns seem particularly high to the general public, it is to ensure security over time even if a change of paradigm (like the apparition of distributed algorithms, Internet, etc ...) increases the hardware/software performance, and bridge the gap to the lowest known generic attack.

> Encryption is an ever-moving target so anything we would add today would be deprecated in 5-10 years.

I am tempted to say that breaches in security mostly stem from protocol errors, implementation issues and physical attacks for embedded devices, rather than mathematical discoveries.

I do not think that the hash algorithm itself is going to be so quickly broken.

**Comment by dlesnoff** [comment]
Can the title of the issue be changed to "non-deprecated hashing functions"?
Hashing functions serves to preserve authenticity with signing protocols, or data integrity.
These are not related (directly) to ciphers and encryption purposes.

**Comment by tersec** [comment]
I'm not particularly opinionated on SHA-2 (SHA2-256, SHA2-384, SHA2-512, or any of the other truncated variations of SHA2-512), it's just a reasonable default. Widely supported in general in hardware and seems solid enough.

But sure, if the goal is to have a cryptographic hashing algorithm which is faster, then some of the SHA-3 finalists and their subsequent evolutions are fine, as well.

My very specific objection is that right now, Nim's stdlib has two long-since-broken cryptographic hashing algorithms, https://nim-lang.org/docs/md5.html and https://nim-lang.org/docs/sha1.html

Two reasonable options are:

- more aggressively deprecate and remove at least `md5` from being used by people who are unaware of its weaknesses (there are algorithms both faster and more secure by now); and

- accept that Nim's stdlib does, in fact, contain cryptographic hashes and could do so more responsibly, by including more modern, secure functions, and pointing people to them instead of the existing `md5` and `sha1` modules.

Right now, the status quo in Nim's stdlib is that people fishing for some cryptographic hash function, if they're not that picky, have a choice of exactly two, broken, functions, and nothing else. They can use `nimcrypto` , but it's not there by default, creating a language environment with actively insecure defaults.

Beyond that, exactly which potential new hash functions are supported I'm not that opinionated regarding. Lots of good options, depending on priorities (speed, standards-compatibility, ecosystem support, inclusion in specific protocols worth supporting via the stdlib, cryptographic considerations such as length extension attack vulnerabilities, et cetera).

**Comment by Araq** [comment]
"inclusion in specific protocols worth supporting via the stdlib" is the criterion we should pursuit.

**Comment by dlesnoff** [comment]
Then we should not keep neither md5 nor sha1 to the very least.

I guess we need at least one hash function in the stdlib. So either a SHA-3 candidate or a SHA-2 member. Or both. Any good documentation should highlight that these hash functions *should not be used for password verification*.
Only argon2 or other password hashes should be used for these purposes.

**Comment by Araq** [comment]
No, we should add SHA-3 and Argon2 or similar and call it a day. PRs are welcome. As I said, the existing MD5 and SHA1 implementations are correct and stay correct. The docs should discourage their usage but there is no reason to deprecate working code.

**Comment by chmod222** [comment]
I would be willing to tackle this and implement sha2, sha3 and maybe argon2 if there is still a need for this despite the existence of the pretty mature nimcrypto project.

**Comment by dlesnoff** [comment]
There is still a need for this in the standard library!
Please focus on a SHA-3 implementation and documenting MD5 and SHA1 weaknesses.
About Nimcrypto:
> They can use Nimcrypto, but it's not there by default, creating a language environment with actively insecure defaults.

**Comment by ringabout** [comment]
For simplicity, It can start with documenting MD5 and SHA1 weaknesses.

**Comment by chmod222** [comment]
Update: I have implemented SHA-2 (SHA-224, SHA-256, SHA-384 and SHA-512) as well as SHA-3 (SHA3-224, SHA3-256, SHA3-384, SHA3-512, SHAKE128, SHAKE256 and SHAKE512) for both the C (and likely C++) and JavaScript backend targets. As for password hashing, I'm eyeing bcrypt as well as Argon2. Even though bcrypt is on the older side, it's still widely used and secure.

I'm now busy shoving them through the NIST CSRC test suite and then I'll follow up with a draft merge request probably around the weekend.
