### ISSUE TITLE
Can't tell return value of programs with staticExec

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#1994]
Using `staticExec` the return value of the executed program can't be checked. Even the manual's example of `git rev-parse HEAD` can fail if you're not inside a git repo, which you can't catch nicely. I think `staticExec` should either return an empty string if the return value isn't 0, or have a way to get back the return value as well as stdout.

**Comment by hildjj** [comment]
Throw an exception if the return code is non-zero?

**Comment by Varriount** [comment]
It's not quite as simple as that (besides, exceptions should be used for unexpected, exceptional cases). Different platforms have different ideas on what a error return code is.

**Comment by kirbyfan64** [comment]
There are three ways I've seen:

1. Return a tuple.

2. Return a custom object. This is what Python does.

3. Use var parameters. This seems very ugly to me.

Personally, I think 2 would be the best, since platform-specific error codes might not matter; it could just have a `succeeded` boolean attribute.

**Comment by Araq** [comment]
*2* is by far the hardest to implement and *1* affects backwards compatibility. What should be done is that the proc grows an "onErrorRaise= true" flag and then an OSError exception is raised. If set to false the empty string is returned instead.

**Comment by dom96** [comment]
Wouldn't it make sense to force users to check the return code of the process? Therefore breaking backwards compatibility should be acceptable in this case.

**Comment by Araq** [comment]
@dom96 Returning a tuple is quite hard to do in the VM though.

**Comment by dom96** [comment]
@Araq Why is it hard?

**Comment by Araq** [comment]
Now at least it produces "" instead of crashing, I think.

**Comment by dom96** [comment]
That sounds like it will lead to some ambiguities.

**Comment by dom96** [comment]
Bah, so a ``staticExecEx`` was added. This just caused a bug in Nimble:

```
~ » nimble -v
nimble v0.8.8 compiled at 2017-09-07 20:23:12
git hash: fatal: Not a git repository (or any of the parent directories): .git
```

Silently accepting output when the command fails is as bad as JavaScript's ``undefined``. I vote to make this a breaking change and throw an exception when the command fails.

**Comment by skellock** [comment]
I'm with @dom96 and [php ceo](https://twitter.com/php_ceo/status/629652685231390721?lang=en) on this one. If i can't `staticExec`, I want the build to burn to the ground.

However, if this ship has sailed, so be it.  At least we have `gorgeEx`'s exit code.

```nim
const goods = gorgeEx("exit 69")

echo goods.output # ""
echo goods.exitCode # 69
```

My question is this:  what's a guy gotta do to get a t-shirt around here?  

Should we be adding a `staticExecEx` alias, documentation and call it a day?  Should we check the `exitCode` and raise?

I'm up for doing the work if you can tell me which direction you'd like.

**Comment by dom96** [comment]
I still want what I asked for initially. But best wait for @Araq to give his okay, of course if you've got a PR ready it'll be harder to say "no" ;)

**Comment by dom96** [comment]
IMO this is a breaking change that needs to happen before v1.0 so I'm adding this to the 1.0 milestone.

**Comment by Araq** [comment]
Seriously? Ok then, do what you think is best.

**Comment by skellock** [comment]
I had a look. With a handful of small changes to the [gorge](https://github.com/nim-lang/Nim/blob/devel/compiler/gorgeimpl.nim#L25) implementation we could die gloriously with a well placed `localError()`.

However...

My concern is, doing this would mean we won't be returning our tuple (output, exitcode). This would be the type of breaking change where we remove capabilities entirely (e.g. what if someone had a `gorgeEx` call with another `gorgeEx` call as a fallback?).

Seems like we could "configure" our way out of this (e.g. yet another param to govern whether we `localError` or return the `tuple`), but I'm not really liking how [my implementation](https://github.com/nim-lang/Nim/compare/devel...skellock:static-executioner) is turning out.

I do believe the default should blow up, but do y'all have any advice to do that along with keeping exitcode/output on the table?

I'd love to see this feature through as I'm in way over head and learning tonnes.

**Comment by genotrance** [comment]
Let the user decide if it needs to blow up. I'm using gorgeEx() in many .nimble files and looking at return values works just fine.

**Comment by narimiran** [comment]
The original issue ("Can't tell return value of programs with staticExec") has been solved by the addition of `gorgeEx` ([link](https://nim-lang.github.io/Nim/system.html#gorgeEx%2Cstring%2Cstring%2Cstring)), which returns a tuple with, I'm quoting, "the precious exit code". :)

Since this is one of the issues marked with "v1.0 milestone", my question is: is the above enough and this can be closed, or is there some more (breaking) work that remains to be done (soon-ish)?

**Comment by Araq** [comment]
Use ``gorgeEx`` or **look at** ``gorge``'s return value. Not worth breaking somebody's code at this point.

**Comment by saemideluxe** [comment]
Sorry to open this up again, but could we reflect this in the documentation a bit clearer? I was a bit confused by reading the docs because staticExec only mentions george as an alias but not georgeEx and there is nothing about return codes.

But glad we have a solution.
Also, Nim is great, thanks for all the people that work on it!
Also, I can write a PR for this in case PRs are welcome.
