### ISSUE TITLE
Compiler's infinite recursion in generic resolution

### ISSUE THREAD

**Issue by Leu-Gim** [nim-lang/Nim#2006]
This code brings compiler into infinite recursion, I think should check for it and report an error instead.

```nim
type I = generic x
  x.p
var x = 7
proc p(x: I) = discard
x.p
```

**Comment by Varriount** [comment]
While their should definitely be a fix for the infinite recursion aspects the bug, I'm not sure if this kind of code would cause an error in and of itself.

**Comment by Leu-Gim** [comment]
Varriount: ``x.p`` call makes the compiler check if ``x`` conforms to generic ``I``, this generic checking calls ``x.p`` again, hence another check if ``x.p`` is ``I``, and so on. As I see this code shouldn't compile anyhow, and compiler should just report an error, like "unresolvable generic parameter".

**Comment by Varriount** [comment]
Yes, I can see that. In this case, however, the bug is largely self inflicted.

I suppose semantic checking could throw an error under the following conditions:
 - The body of a typeclass contains a call to a procedure with that typeclass as an argument
 - The procedure with the typeclass argument is passed the typeclass 'subject' (the type being tested)

However there are so many corner cases involved in this process. What if the subject is converted/casted? What about overloaded procedures?

**Comment by flaviut** [comment]
This doesn't involve the VM: There is no compile-time code evaluation going on.

**Comment by Varriount** [comment]
Not quite true - can't a type class use a procedure to evaluate it's subject?
