### ISSUE TITLE
`x < 1 (and|or) b` generates temp variables in js output

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/Nim#20219]
### What happened?

```nim
proc f(x: int): int {.exportc.} =
  if result > 5 and result < 10:
    discard
```
`nim js -d:danger`
```js
function f(x_0) {
  var temporary_1;
  var result_0 = 0;

  if (!(5 < result_0)) {
    temporary_1 = false;
  } else {
    temporary_1 = (result_0 < 10);
  }
  if (temporary_1) {}

  return result_0;
}
```
it should generate:
```js
function f(x_0) {
  var result_0 = 0;

  if (((result_0 > 5) && (result_0 < 10))) {}

  return result_0;
}
```
https://github.com/nim-lang/Nim/blob/d2318d9ccfe69e21d0517f0448a6469a18b69513/compiler/jsgen.nim#L335
```nim
p.isSimpleExpr(a) == false  # result > 5 also with >= and != infix or call syntax
p.isSimpleExpr(b) == true  # result < 10
```

### Nim Version

1.7.1

**Comment by hamidb80** [comment]
> ```js
>   if (!(5 < result_0)) { // 1
>     temporary_1 = false;
>   } else {
>     temporary_1 = (result_0 < 10);
>   }
> ```

truth table:

**nim code**
|result_0  |  temporary_1 |
|----------|---------|
| 4 | false |
| 5 | false |
| 6 | true |
| 10 | false |
| 11 | false |


**js code**
|result_0  |  temporary_1 |
|----------|---------|
| 4 | false |
| 5 | false |
| 6 | true |
| 10 | false |
| 11 | false |

-----------------------

the result is correct, please explain clearly what you expect, I guess you wanted a **simpler** generated code

**Comment by hamidb80** [comment]
as mentioned before, the goal is not to generate perfect `js` code
https://github.com/nim-lang/Nim/issues/20190

**Comment by metagn** [comment]
[Benchmark](https://jsben.ch/iaTRd)

For me with temporary is faster by a tiny bit. My guess is it's because the `&&` operator adds some slowness because it also has behaviors for non-booleans in JS. `if` does too but `&&`'s behavior is more complicated, `if` just checks for truth and moves on.

Not that it matters which is faster, there are little languages that don't optimize this.

**Comment by AmjadHD** [comment]
But the behaviour is inconsistent, why is `x < 5` considered a simple expr yet `x > 5` isn't and thus produces different JS outputs ?

**Comment by hamidb80** [comment]
> But the behaviour is inconsistent, why is `x < 5` considered a simple expr yet `x > 5` isn't and thus produces different JS outputs ?

Well if you really wanna know, read the codes of js backend

**Comment by metagn** [comment]
In Nim, `!=`, `>` and `>=` are implemented as templates over `==`, `<` and `<=` ([see here](https://github.com/nim-lang/Nim/blob/65e0906e690bdbfa98197463fb1d452be9142618/lib/system/comparisons.nim#L123-L138)). Maybe Nim thinks the template body is a statement list with 1 expression rather than just that expression itself, and that's why it's not considered simple. I believe this is the reason why `!=` output is [indented in rendered Nim](https://github.com/nim-lang/Nim/blob/c0b25f33c70b48e73d66b959429fdf99a6cbce72/tests/arc/tcursorloop.nim#L12-L19). Unsure what should be done about this behavior, it could be breaking to change it.

**Comment by AmjadHD** [comment]
It's an `nkStmtListExpr` with `nkEmpty` and `nkInfix` as children.

**Comment by AmjadHD** [comment]
> In Nim, !=, > and >= are implemented as templates over ==, < and <= ([see here](https://github.com/nim-lang/Nim/blob/65e0906e690bdbfa98197463fb1d452be9142618/lib/system/comparisons.nim#L123-L138)).

I suspected that so I overrided the `>` definition in system:
```nim
template `>`(x, y: untyped): untyped =
  y < x

proc f(): int {.exportc.} =
  if result > 5 and result < 10:
    discard
```
now it generates the right code. Is this some compiler magic ?

**Comment by metagn** [comment]
The version in system has a doc comment (nkCommentStmt) which gets deleted and becomes nkEmpty. That must be causing it.

**Comment by AmjadHD** [comment]
Indeed, adding a doc comment to the override makes it generate the "wrong" code, and does have an `nkEmpty` node.
