### ISSUE TITLE
{.push hint[Name]: off.} does not work

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#20243]
### What happened?

I am talking about examples from https://github.com/khchen/winim/tree/master/examples/clr
 
when I compile `winim-master\examples\clr\simple_gui.nim` with nim 1.7.1, the message says
```bash
C:\Users\USER\.nimble\pkgs\winim-3.9.0\winim\clr.nim(737, 7) Hint: 'RuntimeHelp' should be: 'runtimeHelp' [Name]
``` 
however
there is `{.push hint[Name]: off.}` in C:\Users\USER\.nimble\pkgs\winim-3.9.0\winim\clr.nim as you can read on line https://github.com/khchen/winim/blob/master/winim/clr.nim#L18

### Nim Version

latest cloned-and-compiled nim 1.7.1

$ nim -v
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2022-08-16
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 9f408ea9430b104eb6c14a84d7a1650bf115b6a0
active boot switches: -d:release

### Expected Standard Output Logs

```shell
do not show

C:\Users\USER\.nimble\pkgs\winim-3.9.0\winim\clr.nim(737, 7) Hint: 'RuntimeHelp' should be: 'runtimeHelp' [Name]
```

### Possible Solution

I don't know

**Comment by retsyo** [comment]
btw, when I compile `winim-master\examples\clr\simple_gui.nim`, there is more `Hint: xxx [Name]` in `simple_gui.nim`:
```bash
C:\tmp\winim-master\examples\clr\simple_gui.nim(43, 5) Hint: 'Size' should be: 'size' [Name]
C:\tmp\winim-master\examples\clr\simple_gui.nim(44, 5) Hint: 'Point' should be: 'point' [Name]
```

Now I know I can add `{.push hint[Name]: off.}` at the very begining of `simple_gui.nim` to eliminate these hints, but it is an annoying solution.

So there are 2 extra questions:
1. Why doe this kind of `hints` come to birth? I did not met it if I use nim 1.6.6. Why new nim need it?

2. What is the nice way to avoid this kind of naughty `Hints` information? 
No, I think it is a very bad way to use variant name according to the hint's lower/upper case. I mean it is good to say
```nim
var Size = drawing.GetType("System.Drawing.Size")
```

but the hint suggests to use
```nim
var size = drawing.GetType("System.Drawing.Size") 
```

thank you in advance

**Comment by metagn** [comment]
To get rid of the hint globally you can use `--hint[Name]:off` in the command line, or `--hint:"[Name]:off"` in a nimscript configuration file (not sure if these are documented, they are files with the same name as the module name except `.nims` instead of `.nim`)

The `Name` hint seems to be part of `--stylecheck`, which you can turn off with `--stylecheck:off`. For FFI-type libraries like winim, it is probably a good idea to use `--stylecheck:off`/`{.push styleChecks: off.}`.

You only need the `push` version if you only want it for specific parts of code. You can also just do `{.styleChecks: off.}` where you don't need to use `{.pop.}`.

Related: #4044

**Comment by retsyo** [comment]
Well ` --styleCheck:off` does not erase `Hint`, however `--hint[Name]:off` erase annoying `Hint`

**Comment by ringabout** [comment]
fixed by https://github.com/nim-lang/Nim/pull/20398
