### ISSUE TITLE
Type Mismatch in table when used as non ref object field

### ISSUE THREAD

**Issue by ChanderG** [nim-lang/Nim#20779]
### What happened?

When a Table is used as a field in a non ref object, like the example below, 

```
import std/tables

type Owner = object
  name*: string
  rooms: Table[string, int]

proc addRooms(self: Owner) =
  self.rooms["living"] = 1
  self.rooms["bed"] = 2

proc printRooms(self: Owner) =
  echo self.name & " owns:"
  echo self.rooms

var alice = Owner(name: "Alice")
alice.addRooms()
alice.printRooms()
```

a type mismatch error is thrown during compilation.

### Nim Version

Nim Compiler Version 1.6.8 [Linux: amd64]
Compiled at 2022-09-27
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c9f46ca8c9eeca8b5f68591b1abe14b962f80a4c
active boot switches: -d:release

### Current Standard Output Logs

```shell
/home/..../table.nim(8, 13) Error: type mismatch: got <Table[system.string, system.int], string, int literal(1)>
but expected one of:
proc `[]=`(s: var string; i: BackwardsIndex; x: char)
  first type mismatch at position: 0
proc `[]=`[A, B](t: OrderedTableRef[A, B]; key: A; val: sink B)
  first type mismatch at position: 0
proc `[]=`[A, B](t: TableRef[A, B]; key: A; val: sink B)
  first type mismatch at position: 0
proc `[]=`[A, B](t: var OrderedTable[A, B]; key: A; val: sink B)
  first type mismatch at position: 0
proc `[]=`[A, B](t: var Table[A, B]; key: A; val: sink B)
  first type mismatch at position: 0
proc `[]=`[A](t: CountTableRef[A]; key: A; val: int)
  first type mismatch at position: 0
proc `[]=`[A](t: var CountTable[A]; key: A; val: int)
  first type mismatch at position: 0
proc `[]=`[I: Ordinal; T, S](a: T; i: I; x: sink S)
  first type mismatch at position: 0
proc `[]=`[Idx, T; U, V: Ordinal](a: var array[Idx, T]; x: HSlice[U, V];
                                  b: openArray[T])
  first type mismatch at position: 0
proc `[]=`[Idx, T](a: var array[Idx, T]; i: BackwardsIndex; x: T)
  first type mismatch at position: 0
proc `[]=`[T, U: Ordinal](s: var string; x: HSlice[T, U]; b: string)
  first type mismatch at position: 0
proc `[]=`[T; U, V: Ordinal](s: var seq[T]; x: HSlice[U, V]; b: openArray[T])
  first type mismatch at position: 0
proc `[]=`[T](s: var openArray[T]; i: BackwardsIndex; x: T)
  first type mismatch at position: 0
template `[]=`(s: string; i: int; val: char)
  first type mismatch at position: 0

expression: `[]=`(self.rooms, "living", 1)
```

### Expected Standard Output Logs

```shell
Compilation should succeed without errors.
```

### Possible Solution

The program works as expected if:
```
type Owner = ref object
```

I am new to Nim and maybe I am holding this wrong and tables are not supposed to be used with non ref objects. I don't think that is the case between what is written in the docs and this error message.

### Additional Information

I tried switching to older versions of nim (1.4.0 and 1.6.0) and devel, but the same error persists.

**Comment by Vindaar** [comment]
This is not a bug, but a problem in your code. In a non ref object, the fields of an argument of a procedure (as in `addRooms`) are _not_ mutable. That means in order to change the `rooms` field of the `Owner`, you need to modify the procedure signature to:

```nim
proc addRooms(self: var Owner) =
```
which then will make it work. 

It seems that for tables the error message does not print information about the table being immutable. That makes it a bit misleading here, so improving the error message would certainly be nice.

Note: in a `ref object` it only works, because by default the "mutability" part of a ref object refers to the instance (so you cannot do `self = Owner()` in that `addRooms` as it would change the instance itself; i.e. mutability applies to the implicit pointer underlying the `ref`), but not the field itself. 
On Nim devel one can now use `{.experimental: "strictFuncs".}` combined with `func` to make sure field mutations do not happen with ref objects without `var` either, similar to what you see with the regular object.

**Comment by ChanderG** [comment]
@Vindaar Oops. Ok - that makes sense. Thanks for the clarification. The error message for a simple field is much clearer:
```
Error: 'self.name' cannot be assigned to
```

Now that I know what to look for, this line makes more sense:
```
proc `[]=`[A, B](t: var Table[A, B]; key: A; val: sink B)
  first type mismatch at position: 0
```

A clearer error message would definitely be better, but I can see that this is a proc call and technically everything is working as intended.
