### ISSUE TITLE
Add stew to important_packages

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#20798]
### What happened?

looks like `nim-stew` is broken in latest devel - it contains foundational utilities for many of the other packages in important_packages, so it should probably be added also:

https://github.com/status-im/nim-stew/actions/runs/3385076960/jobs/5622805817

### Nim Version

devel

**Comment by ringabout** [comment]
Sure thing when it passes tests.

It is broken because the algorithm for type names are different for refc and ORC. The devel branch has already switched to ORC. Type names were used for subtype checking in ORC (recently ARC/ORC switched to display based type checking which no longer needs the types names, but the type names are still not compatible between refc and ARC/ORC). It is better to fix tests of https://github.com/status-im/nim-stew instead since stew relies on internal implementation details of type names.


```nim
proc baseType*(obj: RootObj): cstring =
  when not defined(nimTypeNames):
    raiseAssert("you need to compile this with '-d:nimTypeNames'")
  else:
    {.emit: "result = `obj`->m_type->name;".}
```
