### ISSUE TITLE
More examples in the stdlib docs [$15]

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#2089]
We need far more examples in the standard library documentation.

**Comment by reactormonk** [comment]
Maybe something like doctest to go with it so we can directly test the examples?

**Comment by oderwat** [comment]
It would be cool to have something similar to rust-playpen at the same time.

**Comment by reactormonk** [comment]
@oderwat how does that relate?

**Comment by oderwat** [comment]
You brought up the doctest which is (?) testing the code in the examples for validity. I think it is cool to have executable examples in the documentation or tutorials. So that you can see how stuff executes and try modifications while reading the documentation. Maybe playpen was not the right example. The Rust documentation has inline code execution. Another site using this is FPComplete (Haskell). I enjoyed that a lot while learning. There could be a little "icon" which opens the code in an online playground and run it.

**Comment by reactormonk** [comment]
Ok, now I see what you mean. But the javascript backend isn't stable enough to compile the compiler IIRC.

**Comment by oderwat** [comment]
Those systems do not use javascript but a "real" compiler. Send some code. Let it run in a shell / vm report it back. There is also "http://rust.godbolt.org/" which I guess could be adopted for Nim too.

**Comment by reactormonk** [comment]
> Killed - processing time exceeded
> Compilation failed

We already have the IRC bot, shouldn't be too difficult to adapt it.

**Comment by dom96** [comment]
I would love to see a Nim compilation and execution website. I think @ekarlso was trying to write one.

**Comment by ekarlso** [comment]
I got the code on my laptop and will post it once a am back home in a few days. (3 days.) so I can handle this

**Comment by Araq** [comment]
This is far too generic for a "high priority" bug report. Please open concrete issues for underdocumented stdlib modules.

**Comment by dom96** [comment]
So far all of them need more examples. Do you want me to open an issue for every module in the stdlib?

**Comment by reactormonk** [comment]
You could make a list here which modules need more examples and start ticking them off.

**Comment by FedericoCeratto** [comment]
The docs already contain "Source" links to GitHub, but I think we could encourage docs contribution by adding a page header "Help us improving <this page link_to_source_on_github>"
