### ISSUE TITLE
Add 'clock' as a parameter to getTime

### ISSUE THREAD

**Issue by pkve** [nim-lang/Nim#21491]
### Summary

The "getTime" function uses "clock_gettime" with "CLOCK_REALTIME" for POSIX.

``` nim
proc getTime*(): Time {.tags: [TimeEffect], benign.} =
...
elif defined(posix):
    var ts {.noinit.}: Timespec
    discard clock_gettime(CLOCK_REALTIME, ts)
    result = initTime(ts.tv_sec.int64, ts.tv_nsec.int)
```

But I need to use "CLOCK_REALTIME_COARSE" instead.

https://www.man7.org/linux/man-pages/man3/clock_gettime.3.html
> CLOCK_REALTIME_COARSE (since Linux 2.6.32; Linux-specific)
>               A faster but less precise version of CLOCK_REALTIME.  This
>               clock is not settable.  Use when you need very fast, but not
>               fine-grained timestamps.  Requires per-architecture support,
>               and probably also architecture support for this flag in the
>               [vdso(7)](https://www.man7.org/linux/man-pages/man7/vdso.7.html).

### Description

Could we add "clock" as a parameter to "getTime()" with "CLOCK_REALTIME" as default value?
Or create a new "getTimeCoarse()" function?
And add "const CLOCK_REALTIME_COARSE* = cint(5)" to "posix_linux_amd64_consts.nim".

### Alternatives

Create my own getTimeCoarse function (but I also have to copy clock_gettime proc, ClockId, Time and Timespec types and create the new constant "CLOCK_REALTIME_COARSE").

### Links

https://github.com/nim-lang/Nim/issues/10494

**Comment by ghost** [comment]
Personally I don't think this is a good idea since `getTime`  is supposed to be as cross-platform as possible, and to actually support this argument `std/times` will have to define an overload of `getTime` or an alternative procedure specifically for that different type of time resolution.

About implementing the feature yourself - you can just import `std/posix` to not re-define all those types (except `CLOCK_REALTIME_COARSE` since it's not defined in `std/posix`), and then you can copy the posix part of the `getTime` procedure:

```nim
import std/[times]
# too many symbols, so we don't cause collisions
from std/posix import clock_gettime, Timespec

var CLOCK_REALTIME_COARSE* {.importc, header: "<time.h>".}: cint

proc getCoarseTime*(): Time {.tags: [TimeEffect].} =
  var ts {.noinit.}: Timespec
  discard clock_gettime(CLOCK_REALTIME_COARSE, ts)
  result = initTime(ts.tv_sec.int64, ts.tv_nsec.int)

echo getCoarseTime()
```
