### ISSUE TITLE
Standard library hints about long lines

### ISSUE THREAD

**Issue by dhasenan** [nim-lang/Nim#2158]
lib/system.nim(2946, 85) Hint: line too long [LineTooLong]
lib/system.nim(2949, 85) Hint: line too long [LineTooLong]
lib/system.nim(2952, 81) Hint: line too long [LineTooLong]

Barring a means to restrict hints to the current project, it's ideal for the standard library to produce no hints. While the LineTooLong hint is turned off by default, some people might want to use it.

**Comment by oderwat** [comment]
I was looking into this because I wanted to enable line length checks for our projects. It is not practicable to fix the lens in the standard libraries as there are a lot of them and some for documentation would become a pain to edit after reformatting them (imho).

So I looked where the hint is produced and found that it would be relatively easy to modify by telling the lexer for which files lexer those hints are not wanted. 

What I don't know yet is how I can extend the config options to contain a list of prefixes. At the same time it may be cool to make the hard coded 80 cols margin configurable. I guess I have to learn about the config file :)

P.S.: Another idea would be to suppress the checks for all "added path" sources (nimble packages) too. But that again could be a path prefix anyway.

**Comment by Varriount** [comment]
@oderwat 
> What I don't know yet is how I can extend the config options to contain a list of prefixes.

I'm assuming you mean path prefixes? 

The config files are meant purely for holding options that would otherwise be passed via command line. If you want to add something to a config file, first look into adding it as a command line option. The main file that deals with this is ['compiler/commands.nim'](https://github.com/Araq/Nim/blob/devel/compiler/commands.nim) - Look at how '--passc' is implemented.

**Comment by oderwat** [comment]
@Varriount Thank you for the hint! Will look into that!

**Comment by Araq** [comment]
Closing since Nim now only outputs hints and warnings for the main package that is built.
