### ISSUE TITLE
Changes to allow/deny "alias syntax" break alias-free code

### ISSUE THREAD

**Issue by disruptek** [nim-lang/Nim#21727]
### Description

The PR nim-lang/Nim#21671 which constrains the use of so-called "alias syntax" broke the following CPS code:

```nim
template debugAnnotation*(s: typed; n: NimNode; body: untyped) {.dirty.} =
  debug(astToStr s, n, Original)
  result = rewriteIt n:
    body
  debug(astToStr s, result, Transformed, n)

macro cpsJump(cont, contType: typed; name: static[string];
              call, n: typed): untyped =
  ## Rewrite `n` into a tail call via `call` where `cont` is the symbol of
  ## the continuation and `fn` is the identifier/symbol of the function
  ## field.
  ##
  ## All AST rewritten by cpsJump should end in a control-flow statement.
  let
    call = normalizeCall call
    name = genProcName(name, "jump " & $call.name & "()",
                       info=n.NormNode)
    cont = cont.asName
    contType = contType.asName
  debugAnnotation cpsJump, n:
    it = newStmtList:
      makeContProc(name, cont, contType, n)
    it.add:
      jumperCall(cont, contType, name, call)
```
A minimal reproduction:
```nim
import pkg/cps
```

### Nim Version

```
Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-04-24
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 380dafcc32abed83148f5da78a2aaef608831f8a
active boot switches: -d:release
```

### Current Output

```text
cps/transform.nim(70, 19) Error: recursive dependency: 'cpsJump'
```

### Possible Solution

Be more accurate in determining whether a naked macro symbol is an instance of "alias syntax".

**Comment by ringabout** [comment]
cc @metagn

**Comment by metagn** [comment]
Did not realize `semProcAux` compiles the macro body because templates don't have the same problem 

`sfNoalias` has to be set in `semProcAux`, first immediately after the symbol is created if the symbol kind is macro and there are generic params, then in `semProcTypeNode` if macro or template and any parameters are required, I'll do it in like 2-3 hours when I get home

(Alternatively, just set `sfNoalias` for  macros unconditionally in `semProcAux`, then unset it)
