### ISSUE TITLE
type binding fails for type alias with extra generic parameter

### ISSUE THREAD

**Issue by shirleyquirk** [nim-lang/Nim#21742]
### Description

```nim
type
  Foo[T] = object
    x:T
  Bar[T,R] = Foo[T]
  Baz = Bar[int,float]

proc qux[T,R](x: Bar[T,R]) = discard

var b:Baz
b.qux()
```

### Nim Version

Nim Compiler Version 1.9.3 [Linux: amd64]
Compiled at 2023-04-27
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 220b45048983998675df761d4f33cd31128f10d5
active boot switches: -d:release

### Current Output

```text
Error: cannot instantiate: 'R'
```

### Expected Output

```text
compiles
```

### Possible Solution

a workaround is to use distinct

```nim
type
  Foo[T] = object
    x:T
  Bar[T,R] = distinct Foo[T]
  Baz = Bar[int,float]

proc qux[T,R](x: Bar[T,R]) = discard

var b:Baz
b.qux()
```

### Additional Information

I struggled to find a related issue, which surprised me.  maybe https://forum.nim-lang.org/t/5008#31415 https://github.com/nim-lang/RFCs/issues/153 and https://github.com/nim-lang/Nim/issues/12863 ?

i'm starting to wonder if this is expected behaviour?

**Comment by metagn** [comment]
Kind of related https://github.com/nim-lang/RFCs/issues/450

Which is weird because the code in the first comment also uses a "deleted" generic parameter with an alias type but works

**Comment by SirOlaf** [comment]
Cause of the error is [here](https://github.com/nim-lang/Nim/blob/faf1c91e6a418e21d56ac6e45e1dbc851f9ffd22/compiler/sigmatch.nim#L1468-L1469) because [skipGenericAlias](https://github.com/nim-lang/Nim/blob/faf1c91e6a418e21d56ac6e45e1dbc851f9ffd22/compiler/types.nim#L1179) doesn't care about the generic params you added.

Does seem like a bug to me.
