### ISSUE TITLE
`invalid pragma: stacktrace:false` on macro-generated proc

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#22198]
### Description

```nim
import std/macros

macro async2(prc: untyped): untyped =
  echo prc.kind
  prc.addPragma(newColonExpr(ident "stackTrace", ident "off"))

  prc

func recurse(tree: NimNode): NimNode {.compileTime.}=
  tree.expectKind {nnkProcDef, nnkIteratorDef, nnkStmtList}
  if tree.kind == nnkStmtList:
    for i, child in tree:
      tree[i] = child.recurse
    tree
  else:
    let name = tree[0]
    quote do:
      proc `name` {.async2.} = discard

macro turnIntoProc(tree: untyped) =
  tree.recurse


proc test0 {.turnIntoProc.}
# OK

iterator test1 {.turnIntoProc.}
# Error: invalid pragma: stackTrace: false

turnIntoProc:
  iterator test2
```

based on https://github.com/status-im/nim-chronos/issues/367

### Nim Version

1.6.12

### Current Output

```text
$ nim c -r "testit.nim"
nnkProcDef
nnkProcDef
testit.nim(63, 5) Error: invalid pragma: stackTrace: false
```
```


### Expected Output

_No response_

### Possible Solution

_No response_

### Additional Information

_No response_

**Comment by Araq** [comment]
Works on devel.

**Comment by juancarlospaco** [comment]
!nim c

```nim
import std/macros
macro async2(f: untyped): untyped =
  doAssert f.kind == nnkProcDef
  f.addPragma(newColonExpr(ident "stackTrace", ident "off"))
  f
func recurse(tree: NimNode): NimNode {.compileTime.}=
  doAssert tree.kind in {nnkProcDef, nnkIteratorDef, nnkStmtList}
  if tree.kind == nnkStmtList:
    for i, child in tree: tree[i] = child.recurse
    tree
  else:
    let name = tree[0]
    quote do:
      proc `name` {.async2.} = discard
macro turnIntoProc(tree: untyped) = tree.recurse
proc test0 {.turnIntoProc.}
turnIntoProc: 
  iterator test2
iterator test1 {.turnIntoProc.}
```

**Comment by juancarlospaco** [comment]
@araq Yep fixed on devel.

**Comment by arnetheduck** [comment]
can the fix be found via the bisect tool, ie which commit fixed it so it can be backported?

**Comment by arnetheduck** [comment]
also, the bug is reported against 1.6.12 meaning it should not really be closed ideally

**Comment by juancarlospaco** [comment]
> can the fix be found via the bisect tool

@arnetheduck DIY
Need smallest as possible but assertive (no `echo` but `doAssert`) bug repro code sample:

![temp](https://github.com/nim-lang/Nim/assets/1189414/94b00146-961f-451a-81d8-4159a209bec4)

Ideally users can bisect their own bugs by themselves.

Sometimes the specific commit that has the bug can not be found,
because Nim can not be re-built commit-by-commit on that specific commit to bisect,
but then it gives you the "commits near" where the bug hides (and for context), 
likely the commit with the bug arrived in pack with other commits in a PR:

![temp](https://github.com/nim-lang/Nim/assets/1189414/1aad06c6-449f-476c-94cb-4d7c5ea5578b)

**Comment by arnetheduck** [comment]
ping for reopening / backport
