### ISSUE TITLE
Expands `codegenDecl` to work in function params.

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/Nim#22306]
### Summary

By allowing the user to specify `condegenDecl` the interop can be improved further, we could do for instance:

```nim
{.emit:"""/*TYPESECTION*/
  int operate(int x, int y, int (*func)(const int&, const int&)){
    return func(x, y);
  };
""".}

proc operate(x, y: int32, fn: proc(x, y: int32 ): int32 {.cdecl.}): int32 {.importcpp:"$1(@)".}
proc add(a {.codegenDecl:"const $#& $#".}, b {.codegenDecl:"const $# $#", byref.}: int32): int32  {.cdecl.} = a + b
echo operate(1, 2, add)
``` 

### Description

See the code sample above

**Comment by arnetheduck** [comment]
A point of order here is that `codegenDecl` is difficult to maintain compatibility around - ie the C++ output is not part of the language specification and increasing reliance on open-ended text substitution means increasing the cost of introducing any changes to the generated code when there is no corresponding primitive in nim itself - it seems prudent to explicitly note that codegenDecl-based code is best-effort for which no backwards-compatibility is offered so that it doesn't unduly limit the design space of future native Nim features and improvements.

The `add` declaration is a good example of this point: Nim does not specify an ABI for "simple" parameter passing - ie if `a` were an object, the size of it would determine if it's passed by value or pointer - the language is currently free to decide how `a` should be passed but the `codegenDecl` declaration imposes a new constraint (must be passed by reference or value, not pointer) that previously did not exist and that Nim does not know about / understand (because it cannot parse the contents of `codegenDecl`).

**Comment by jmgomez** [comment]
@arnetheduck thanks for the comments. I think anyone that use `emit` or `codegenDecl` in its general form, know that is using low level APIs and they are on their own. The whole point of them is to be able to workaround the backend edges, especially the C++ never endings features, without polluting the backend itself. 

On this concrete case, there are two things worth noticing: 
1. `codeGenDecl` was already there, so expanding it it's a matter of completeness. At this point I think the only thing missing besides params is type fields. 
2. The substitution happens at the very end. Meaning high degree of backwards compatibility. 

I think your point makes more sense for things like `virtual`, `member` or `constructor` (we are looking into unifying them). But it was string substitution/parsing or polluting the frontend with an insane amount of pragmas (i.e. see previous RFC for `virtual`). 
Anywais, it isnt so different from `importc` or `exportc`, which arguably can be a bit "hacky" but without them interop would be pretty much impossible in its current form (which is one of the biggest strengths of Nim)
