### ISSUE TITLE
Nim cannot detect proper overload without importing the used generic module in wrapper module

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/Nim#22543]
### Description

compile `wrapper.nim`.

wrapper.nim
```nim
# import std/lists # XXX if uncommented, code complies!!!
import inside

bug 1, @[1]
```

inside.nim
```nim
import std/lists

proc bug*[L](
  val: L, # XXX without generics code compiles. 
  arr: seq[int]
) = 
  discard toDoublyLinkedList arr
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-23
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 6b04d0395ab1d6d8efa7d287c73da2c7230800c9
active boot switches: -d:release

### Current Output

```text
/home/hamidb80/.choosenim/toolchains/nim-#devel/lib/pure/collections/lists.nim(188, 11) Error: type mismatch
Expression: add(result, elem)
  [1] result: DoublyLinkedList[system.int]
  [2] elem: int

Expected one of (first mismatch at [position]):
[1] proc add(x: var string; y: char)
[1] proc add(x: var string; y: cstring)
[1] proc add(x: var string; y: string)
[1] proc add[T](x: var seq[T]; y: openArray[T])
[1] proc add[T](x: var seq[T]; y: sink T)
```

### Expected Output

```text
nothing - just compiles successfully
```

### Possible Solution

seems like the generic call is tied to the caller module?

**Comment by juancarlospaco** [comment]
!nim c

```nim
import temp1
bug(1, @[1])
```

```nim
import std/lists
proc bug*[L](v: L; a: seq[int]) = discard toDoublyLinkedList(a)
```

**Comment by Araq** [comment]
Use a `bind` or `mixin` statement.

**Comment by metagn** [comment]
I think the issue is that [`toDoublyLinkedList`/`toSinglyLinkedList`](https://github.com/nim-lang/Nim/blob/2e7c8a339f654ebd6fe178f4c81aa89c14851f22/lib/pure/collections/lists.nim#L168-L188) in `lists` are declared before `add` for lists ([single](https://github.com/nim-lang/Nim/blob/2e7c8a339f654ebd6fe178f4c81aa89c14851f22/lib/pure/collections/lists.nim#L434-L446)/[double](https://github.com/nim-lang/Nim/blob/2e7c8a339f654ebd6fe178f4c81aa89c14851f22/lib/pure/collections/lists.nim#L567-L584))
