### ISSUE TITLE
Overloaded Enum value names generate wrong results

### ISSUE THREAD

**Issue by ConformalMapping** [nim-lang/Nim#22598]
### Description

Original question: https://forum.nim-lang.org/t/10448
```nim
import std/macros
type
    A = enum
        red
    B = enum
        red

let a = @[red]
let b = @[red]

echo typeof a #seq[A]
echo typeof b #seq[B]
```
When I commented out the first line, the result was different: both a and b are of the same type `seq[A]` !

### Nim Version

Nim Compiler Version 2.0.0 [Windows: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release

### Current Output

```text
seq[A]
seq[B]
```

**Comment by SolitudeSF** [comment]
```nim
type
  A = enum red
  B = enum red

let a = red

echo typeof a # A
echo typeof red # None (??????????????????????)
```

**Comment by metagn** [comment]
#20457 + #20932 (semexprs diff)

To not break old code we don't error on these and just pick the first symbol in the symchoice which can be effectively random if they're ambiguous. This was the behavior before overloadable enums for imported enum fields in some contexts, hence not breaking old code.

We can check the local scope for the enum name again, see if the symbol the local scope gives is ambiguous, and the symbol is inside the symchoice, and error only then. But I can't justify this too much. The first solution was also me not being able to come up with anything.

`typeof red` is `None` because `red` is a symchoice, same as `typeof add`.

**Comment by SolitudeSF** [comment]
how can it break old code if the code like this didnt compile before overloaded enums? what contexts was this allowed in?
and why is the warning isnt enabled by default? this is absolutely not intuitive.

**Comment by metagn** [comment]
Sorry, I should be clear, this isn't good behavior. What I am trying to say is the design of overloadable enums doesn't account for scope, and this is the result of a bandaid solution to make it do so. I'll try to think of something else.

**Comment by SolitudeSF** [comment]
At least having hint enabled by default would alert the user to the ambiguity and the results wouldnt be as surprising.
