### ISSUE TITLE
Forward declarations do not work well with templates

### ISSUE THREAD

**Issue by fsh** [nim-lang/Nim#22725]
### Problem

Having either the forward declaration or the implementation of a function in a template (or genAst/quote/etc.) leads to a compile error.

### Minimal Reproduction

```nim

proc test(n: int) # Error: implementation of 'xxx.test(n: int)' expected

template define_test(): untyped =
  proc test(n: int) = echo n

define_test()

test(n=69) # works fine (if forw. decl. is commented out to make it compile).
```

### Notes & Solutions

1. The last line (`test(n=69)`) indicates there are some (which?) workarounds/conveniences in place to make the hygienic renaming unobtrusive, I think there is a good argument to be made for saying that the `` `gensymN `` stuff should be ignored also during forward declaration matching.

2. It can also be argued that the error is quite confusing, as it is very hard to tell why or what it is complaining about by merely "looking at the code." The two declarations can be identical in the source, so it requires conscious reflection on the hygienic renaming and how it's applied to argument names (even though it's not applied to the function name). Note also that if the functions don't have parameters, there would be no errors with the forward declaration until one day an argument was added. The "implementation expected" should probably list the functions it found with the same name, showing the mismatch in types/argument names?

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-12
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8f5b90f886501862bd27d4e0e8244e2f7f0ebc2a
active boot switches: -d:release

**Comment by metagn** [comment]
> The last line (test(n=69)) indicates there are some (which?) workarounds/conveniences in place to make the hygienic renaming unobtrusive

[Here](https://github.com/nim-lang/Nim/blob/b542be1e7de067573370a3159b0812396309ef8b/compiler/astalgo.nim#L238)

Relevant line is [here](https://github.com/nim-lang/Nim/blob/f7c203fb6c89b5cef83c4f326aeb23ef8c4a2c40/compiler/types.nim#L1015) but copying that code gives `ambiguous call; both template_various.test(n: int) and template_various.test(n`gensym134: int) match for: (int literal(69))`, presumably because [the forward declaration replacement code is too intrusive](https://github.com/nim-lang/Nim/blob/f7c203fb6c89b5cef83c4f326aeb23ef8c4a2c40/compiler/semstmts.nim#L2109-L2111)

You can make the template `{.dirty.}` or add `{.inject.}` to `n`.

**Comment by Araq** [comment]
I don't see a bug here, just an unfortunate interaction of features, but totally understandable behavior. I prefer fewer language rules that lead to surprising behavior over more language rules that also lead to surprising behavior, eventually.
