### ISSUE TITLE
Nimsuggest segfault with invalid assignment to table

### ISSUE THREAD

**Issue by SirOlaf** [nim-lang/Nim#22753]
### Description

Examples below show code that segfaults nimsuggest during `track` in sempass2. Not sure the second case is minimal, but haven't been able to get it smaller yet. Either way both are very disruptive during actual usage of nimsuggest, vscode extension gives up completely and must be restarted.

A real location that also causes the crash in nimsuggest can be found in `compiler/semstmts.nim` which causes a crash at this location [semstmts.nim](https://github.com/nim-lang/Nim/blob/devel/compiler/semstmts.nim#L57), but reducing that seems pretty tough.

Immutable case:
```nim
import std/tables
proc myProc(x: Table[int, int]) =
  x[0] = 0
```

Mutable case:
```nim
import std/tables

type
  OuterType = object
    inner: InnerType

  InnerType = object
    table: Table[int, int]

proc myProc(self: var OuterType) =
  self.inner.table[0] = self.inner
```

### Nim Version

Tested 1.6.14 and latest devel 1b0447c208a8ec03c1abf5c511b3949a882a8996

### Current Output

```text
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

```text
Reports an error/works
```

**Comment by ire4ever1190** [comment]
Running through GDB I get the segfault happening in [sempass2](https://github.com/nim-lang/Nim/blob/devel/compiler/sempass2.nim#L1159) instead (Using latest devel).
Looks similar to a bug I found recently (That I tried to solve, failed, then forgot to report) since they both segfault in same spot
```nim
var x: array[3]
x[0] = 9
```

Is the solution just adding a check `n[0].typ != nil` or should `n[0].typ` be assigned something in these cases?

**Comment by SirOlaf** [comment]
Same location I got, I just didn't make it clear, sorry for that. Segfault happens when it tries to access `.kind` of typ where typ is nil. Adding a check there is definitely not a "real" fix because it shouldn't be nil in the first place but I did patch it like that on my local build.
