### ISSUE TITLE
Challenges installing nim + tooling on M1 Mac

### ISSUE THREAD

**Issue by bbbscarter** [nim-lang/Nim#22808]
### Description

Apologies - this is a slightly wide-ranging bug report, which touches on a number of different things. But the overview is 'as a newcomer, installing Nim on an M1 Mac hit some unexpected challenges.'

I ended up with a working setup, so I'm very happy. However, I'm conscious that it took me a while; there was some friction with getting it working, which others might hit, and for which there might be some easy wins. (Or maybe I read the wrong docs!)

Thanks!

Full report:

1. homebrew
- I started out using homebrew, with `brew install nim`
- This worked until I wanted to use other tools, like nimsuggest and nim-lsp. Running `nimble install nimlsp`  threw up errors about nim source not being available.

2. choosenim
- Guessing that I needed to install nim outside of brew, I uninstalled the brew version and went with `choosenim`, as per the website instructions. https://nim-lang.org/install_unix.html. This worked, and allowed me to get nim-lsp working.
- Installed `nim sdl` and got a toy app building. This ended up with an error message about using an arm64 library in an amd64 app.
- Running `file myapp` indeed showed that the nim app had compiled as an amd64 application on my M1 mac. Compiling the app with `--cpu:arm64` didn't seem to change anything - still had an amd64 executable.
- Eventually realised that `choosenim` had installed an amd64 version of nim.

3. `choosenim` + custom build
- Followed the instructions on github for compiling from source, which worked fine. I used `choosenim ~/nim-source` to point `choosenim` at my build of nim. Building with nim then produced the correct binaries.
- Deciding to expand the project I moved on to using `nimble` for builds. Strangely, this seemed to result, again, in an amd64 binary. 
- Running directly `~/nim-source/bin/nimble build` produced an arm64 binary.

4. remove `choosenim` - just use custom build
- Removed `choosenim`, and pointed my path at the `~/nim-source/bin`. 
- Everything now works fine - next time will jump to this step directly!

### Nim Version

Nim Compiler Version 2.0.1 [MacOSX: arm64]
Compiled at 2023-10-09
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: d30565f810ba5165ea2e5bcd91ea3dee9950051f
active boot switches: -d:release

### Possible Solution

Some potential suggestions:
- Get choosenim to provide arm builds on M1/M2 Macs.
- Failing that - on the website, recommend users of M1/M2 Macs build themselves, rather than using choosenim for now.
- Consider distributing core tooling, like nim-lsp, alongside nim in homebrew.
- Potentially - identify why choosenim + custom build doesn't use the right nimble.
- Potentially - identify why `--cpu:<xx>` silently doesn't seem to work (or maybe I'm using it wrong!)

**Comment by Araq** [comment]
Website has been updated since then.

**Comment by lewisl** [comment]
What is the resolution of this 9 months later.  The documentation content that was fixed doesn't address arm64 anywhere that I can see in the download page.  Where else should I look?

**Comment by lewisl** [comment]
Would building from source using instructions from the website result in arm64 output when building on arm64 machine?

```
sh build.sh
bin/nim c koch
./koch boot -d:release
./koch tools
```

Answering own question:  Yes!

This is the most reliable way to build from source while choosenim remains broken on arm64.  Better than all the advice one can find across the internet and even araq's own answers on the forum.  Must be a reason it's the recommendation on the web site.

Probably would add tip on the website to delete the directory "c-code" (did I already forget what it's really called?) to get rid of 1.87 gb of code.  Then you end up with a completely correct, functional build for the platform on which the build was done--which is exactly what we'd expect.   

Probably would also suggest to run nimble and add some innocuous package (I use "nimlangserver") so that nimble sets itself up nicely.

**Comment by theAkito** [comment]
> Would building from source using instructions from the website result in arm64 output when building on arm64 machine?
> 
> ```
> sh build.sh
> bin/nim c koch
> ./koch boot -d:release
> ./koch tools
> ```

https://github.com/theAkito/docker-nim

**Comment by lewisl** [comment]
Yes!  Just tried it and updated my original post.

Couple tips:
Delete directory c-code when done
Run nimble to install an package so that nimble directory gets created.
Add path to nimble and to the finished nim build.

From: Akito ***@***.***>
Reply-To: nim-lang/Nim ***@***.***>
Date: Friday, August 30, 2024 at 10:57 AM
To: nim-lang/Nim ***@***.***>
Cc: Lewis Levin ***@***.***>, Comment ***@***.***>
Subject: Re: [nim-lang/Nim] Challenges installing nim + tooling on M1 Mac (Issue #22808)


Would building from source using instructions from the website result in arm64 output when building on arm64 machine?

sh build.sh

bin/nim c koch

./koch boot -d:release

./koch tools

https://github.com/theAkito/docker-nim
