### ISSUE TITLE
Unittest breaks if proc name on/off defined in same module

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#22841]
### Description

There is an error if a proc named `on` or `off` is defined in the same module as `unittest` is used.

```nim
import unittest

proc on() =
    discard

suite "some suite":
    test "some test":
        discard
```

### Nim Version

`Nim Compiler Version 2.1.1 [Windows: amd64]`

0d4b3ed18edff5ae098be842a986cb32de651fbf

This occurs in 2.0.0 as well.

### Current Output

```text
test_on.nim(6, 1) template/generic instantiation of `suite` from here
nim_tui\test_on.nim(7, 5) template/generic instantiation of `test` from here 
nim-#devel\lib\pure\unittest.nim(555, 34) Error: type mismatch: got 'None' for 'on' but expected 'bool'
```

**Comment by metagn** [comment]
Caused by [`test` template being `dirty`](https://github.com/nim-lang/Nim/blob/0d4b3ed18edff5ae098be842a986cb32de651fbf/lib/pure/unittest.nim#L527), we could add `on` and `off` to the `bind` list but that would be kind of ridiculous, in general maybe the compiler should just special case `on` and `off` in pragmas and not rely on the `system.on` and `system.off` constants

**Comment by juancarlospaco** [comment]
Different solution, have some kind of `strictBool` that disables `on` and `off` alias?. 🤔

**Comment by beef331** [comment]
> Different solution, have some kind of `strictBool` that disables `on` and `off` alias?. 🤔

Soon there will be more Nim dialects than spoken dialects.
