### ISSUE TITLE
Strings aren't copied in parallel loop

### ISSUE THREAD

**Issue by PhilipWitte** [nim-lang/Nim#2286]
Apparently this code should copy strings accessed from multiple threads, but it does not when used with 'parallel':

``` nimrod
import math, threadPool

# ---

type
  Person = ref object
    name: string
    friend: Person

var
  people: seq[Person] = @[]

proc newPerson(name:string): Person =
  result.new()
  result.name = name

proc greet(p:Person) =
  #p.friend.name &= "-MUT" # this line crashes the program
  echo "Person {",
    " name:", p.name, "(", cast[int](addr p.name),"),",
    " friend:", p.friend.name, "(", cast[int](addr p.friend.name),") }"

# ---

proc setup =
  for i in 0 .. <20:
    people.add newPerson("Person" & $(i + 1))
  for i in 0 .. <20:
    people[i].friend = people[random(20)]

proc update =
  parallel:
    for i in 0 .. people.high:
      spawn people[i].greet()

# ---

when isMainModule:
  randomize()
  setup()
  update()
```

Note that if I replace `parallel` with `spawn`/`sync` then strings are correctly copied and I can mutate friend's name from within `greet` without error.

**Comment by krux02** [comment]
I am reopening this, maybe I am wrong and everything is ok, but the test for this issue is not executed properly.  in [tmissing_deepcopy](https://github.com/nim-lang/Nim/blob/devel/tests/parallel/tmissing_deepcopy.nim) there is a ``ccodeCheck: "\\i @'deepCopy(' .*"``, I don't fully understand this pattern yet, but the generated csources do not contain 'deepCopy(' literally. There is a lot of 'deepcopy' in the generated source file, but those lower case versions come from the name of the test file not from a proc called literally 'deepCopy'.

**Comment by krux02** [comment]
I fixed the test on my current development branch. Since it has nothing to do with this original issue, I close it now again.
