### ISSUE TITLE
Ambiguous identifier in pragma

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#23002]
### Description

testit2.nim:
```nim
proc on*(): void = discard
```

testit.nim
```nim
import testit2

proc test() =
  {.warning[ProveInit]: on.}

test()
```

inside the pragma, the evaluation should be looking for a `bool`, not a `proc` - yet, the proc is matched (which in the real world example has more arguments)

### Nim Version

1.6.16, devel

### Current Output

```text
testit.nim(4, 25) Error: ambiguous identifier: 'on' -- use one of the following:
  system.on: bool
  testit2.on: proc (){.noSideEffect, gcsafe, locks: 0.}
```

**Comment by ringabout** [comment]
!nim c
```nim
proc on(): void = discard

proc test() =
  {.warning[ProveInit]:on.}

test()
```

**Comment by ringabout** [comment]
```nim
proc on = discard
const s: bool = on
```
I image it to be similar with this case, viz, values are not be overloadable except enums etc.

**Comment by metagn** [comment]
In #22841 I suggested special casing on/off for pragmas.

We would not have a problem like this if we used true and false instead of on and off, because we know the expected type is a bool which is an enum containing true and false, but on and off are just random constants in system. There also wouldn't be a problem if on and off were defined as `type PragmaOption = enum on, off` and this was the expected type instead of bool. 

Instead of doing this though we can just interpret `on` and `off` at the AST level for pragmas and not let the user override their meaning.

**Comment by arnetheduck** [comment]
> but on and off are just random constants in system

they're random constants with a type though and since the pragma expects "something with the bool type", it should reasonably be possible to narrow down the matching options.

hardcoding seems like a loss - I'd rather see that "anything that evaluates to a bool" gets done, and then we can even have computed pragma values, ie full expressions.

**Comment by metagn** [comment]
We would still be able to compute arbitrary expressions, `on` and `off` would just get an early pass (the logic is [here](https://github.com/nim-lang/Nim/blob/5dfa1345fa2c046a42730a6357b12245e5ee3f06/compiler/pragmas.nim#L285)).

The type inference logic is there for overloaded symbols (so unfortunately not const), but even with type inference the problem remains if the other module defines another `const on: bool`. Unlikely, but still interfering with what is always expected to work in the language. [Type sections have something similar](https://github.com/nim-lang/Nim/blob/5dfa1345fa2c046a42730a6357b12245e5ee3f06/compiler/semtypes.nim#L2015-L2025).
