### ISSUE TITLE
Mozilla and bitdefender report malware in the Windows installer

### ISSUE THREAD

**Issue by edreamleo** [nim-lang/Nim#23151]
### Description

Both Mozilla and bit defender warn of malware in https://nim-lang.org/download/nim-2.0.2_x64.zip.

bitdefender removed two files after downloading. Here is the log:

```console
nim-2.0.2_x64.zip=>nim-2.0.2/bin/nimgrab.exe
Trojan.GenericKD.70907822 Deleted
 Gen:Variant.Tedy.472027 Deleted
```

[Araq](https://forum.nim-lang.org/profile/Araq) claims these warnings are false positives.

That may be true, but Nim should make these warnings go away: they make a bad first impression!

### Nim Version

nim-2.0.2_x64.zip

### Current Output

```text
bitdefender log:

nim-2.0.2_x64.zip=>nim-2.0.2/bin/nimgrab.exe
Trojan.GenericKD.70907822 Deleted
 Gen:Variant.Tedy.472027 Deleted
```

### Expected Output

```text
No warnings about malware.
```

**Comment by ringabout** [comment]
It's a common issue for less known programming languages https://github.com/nim-lang/Nim/issues/17820; even Golang suffers these problems https://go.dev/doc/faq#virus

We have done everything possible to fight these issues https://github.com/nim-lang/virus_checker  I don't suppose we could do better unless these virus scanners learn some Nim code. 

You might report false positives to these virus scanners so that they might whitelist it.

**Comment by Araq** [comment]
Report antivir bugs to your antivir software vendors.

**Comment by edreamleo** [comment]
Thanks for your quick response. I'll do as you suggest.

**Comment by mystica555** [comment]
Funny enough Edward, your Leo Editor google groups post messages with the link to the installer were quarantined by Gmail as "potential phishing" because

```
"This message seems dangerous
It contains a suspicious link that was used to steal people's personal information. Avoid clicking links or replying with personal information."
```

 Lol. 
Everything thinks this is a virus or malware.  I've flagged both emails as "not phishing".

**Comment by edreamleo** [comment]
@mystica555 Hehe. Now I am *really* sharing your pain!
