### ISSUE TITLE
Symbols in `when false` section affect lookup

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#23326]
### Description

A follow-up on https://github.com/nim-lang/Nim/pull/23091 - real code is here: https://github.com/arnetheduck/nim-results/pull/35/ (error happens with `resultsGenericBindingWorkaround=false`).

The `error` symbol inside `when false` should obviously have no effect on compiling the sample.

`testit.nim`:

```nim
type Result*[E] = object
  e*: E

proc error*[E](v: Result[E]): E = discard

template valueOr*[E](self: Result[E], def: untyped): int =
  when E isnot void:
    when false:
      # Comment line below to make it work
      template error(): E {.used, gensym.} = s.e
      discard
    else:
      template error(): E {.used, inject.} =
        self.e

      def
  else:
    def


block:
  let rErr = Result[string](e: "a")
  let rErrV = rErr.valueOr:
    ord(error[0])

```

### Nim Version

nim -v
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-02-20
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 773c066634d831a968bb464eab35b25a00026525
active boot switches: -d:release

(same error on 1.6)

### Current Output

```text
$ nim c /tmp/testit
.....................................................................
/tmp/testit.nim(23, 19) template/generic instantiation of `valueOr` from here
/tmp/testit.nim(24, 8) Error: type mismatch
Expression: ord(error)
  [1] error: proc (v: Result[system.int]): int{.noSideEffect, gcsafe.}

Expected one of (first mismatch at [position]):
[1] func ord[T: Ordinal | enum](x: T): int
```

**Comment by litlighilit** [comment]
A clearer demo:
```Nim
template valueOr*(def: untyped): int =
  when false:
    # Comment line below to make it work
    template error(): int {.gensym.} = discard
    discard
  else:
    template error(): int {.inject.} = 1
  def

let rErrV = valueOr error
```

It seems the symbol capture doesn't cover edge cases, when it comes to `gensym`

**Comment by litlighilit** [comment]
In addition,

maybe there is another factor:
```Nim
template valueOr*(def: untyped): int =
  template error(): int {.gensym.} = 1
  def

let rErrV = valueOr error
```
`gensym` is not considered when lookup

**Comment by metagn** [comment]
Culprit is maybe this?

https://github.com/nim-lang/Nim/blob/94c599687796f4ee3872c8aa866827b9ed33f52b/compiler/semtempl.nim#L264

The gensym template is added to scope [here](https://github.com/nim-lang/Nim/blob/94c599687796f4ee3872c8aa866827b9ed33f52b/compiler/semtempl.nim#L282) and the injected template declaration finds it and reuses the symbol? Presumably to allow overloading the gensym'd symbol since adding `gensym` again defines a different symbol, even though omitting `gensym` implies `inject` for routines. Then again why does `gensym` again define a different symbol when we only get to use one at a time in the template?

We could move the gensym reuse logic inside the [logic for when `gensym` is given](https://github.com/nim-lang/Nim/blob/94c599687796f4ee3872c8aa866827b9ed33f52b/compiler/semtempl.nim#L277), if this  breaks code we could allow opting out of the symbol reuse on an explicit `inject`.

This is all letting alone the logic of actually using `error` inside the template after the when block, also I'm speculating about all this from my phone so I might be wrong.
