### ISSUE TITLE
Error: type mismatch: got <typedesc[A]>, but expected one of: A = proc (){.closure.}

### ISSUE THREAD

**Issue by haoyu234** [nim-lang/Nim#23587]
### Description

[https://play.nim-lang.org/#pasty=cVWRkhXTOfpv](https://play.nim-lang.org/#pasty=cVWRkhXTOfpv)

Compiles normally on 'play.nim-lang.org' without uncommenting.
Compiling locally will report an error, just like the title says.

```nim
import std/tables

# After uncommenting and compiling on 'play.nim-lang.org', an error will be reported (killed by system)
# import std/asyncnet
# import std/asyncdispatch

type
  A = proc ()

proc main =
  let repo = initTable[uint32, A]()

  let c1 = repo.getOrDefault(uint32(1), nil)
  echo "c1.isNil: ", c1.isNil

  let c2 = repo.getOrDefault(uint32(1), A(nil))
  echo "c2.isNil: ", c2.isNil

main()

```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-05-05
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 1ef4d04a1e56f67d85559a7964e9467df06bc2d7
active boot switches: -d:release

### Current Output

```text
/root/repos/spaces2/a.nim(13, 16) template/generic instantiation of `getOrDefault` from here
/root/.choosenim/toolchains/nim-#devel/lib/pure/collections/tables.nim(437, 19) Error: type mismatch: got <typedesc[A]>
but expected one of:
A = proc (){.closure.}
```

### Expected Output

```text
no error
```

**Comment by drkameleon** [comment]
Also spotted: https://forum.nim-lang.org/t/12547

@haoyu234 Have you found any workaround to this?

**Comment by metagn** [comment]
Took me a second to figure it out, the issue is this call:

https://github.com/nim-lang/Nim/blob/f73e03b1323cf3ed65d6996f43c8e6891c40f924/lib/pure/collections/tables.nim#L437

It tries to call the parameter `default` with `B` rather than the magic `default`, which [gets overriden](https://github.com/nim-lang/Nim/blob/f73e03b1323cf3ed65d6996f43c8e6891c40f924/compiler/semexprs.nim#L1203) because `default` has a proc type in this case. A minimization is:

```nim
proc foo(default: proc ()) =
  echo default(int)

foo(123)
```

which seems to fail in all versions, ~~likely it also started consistently happening for generic procs at some point~~ nevermind, the call was just added in #22365. Doesn't happen if `default` doesn't have a proc type.

Very easily worked around by just removing this call from `tables` but it is an interesting issue and the error message isn't good.

**Comment by c-blake** [comment]
This workaround seems ok, but for non-`proc` value types it worked before when called with a keyword parameter.  E.g., this worked fine but with this fix it obviously will not:

```Nim
import std/tables
var t: Table[int, int]
echo t.getOrDefault(0, default=2)
```

A preliminary search of Nimble packages makes that seems *very* rare.  As a (probably already known) simple meta-rule, if you must change call sites in / uses by the compiler, you should likely put in a changelog.  Some dark/non-nimble-published code might like the self-documenting/more explicit kw param calls => changelog, even if the compile error in that case might be clear.

**Comment by c-blake** [comment]
(and I know both @Araq & @metagn noticed my above point (sans changelog idea) already from the code review discussion on the PR - but maybe more people read Issue threads??  ¯\\_(ツ)_/¯ )
