### ISSUE TITLE
Enum Overloading Regression?

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#23596]
### Description

```Nim
import std/heapqueue
type Algo = enum heapqueue, quick
proc bar*(algo=quick) =
  var x: HeapQueue[int]
  case algo
  of heapqueue: echo 1 # `Algo.heapqueue` works on devel
  of quick: echo 2
  echo x.len
```

### Nim Version

nim-devel c91b33aaba4234d8abdf04af102d71b86e285c58

### Current Output

```text
foo.nim(6, 6) Error: expression 'heapqueue' has no type (or is ambiguous)
```

### Expected Output

```text
Nim compilers only a couple weeks older work without needing the `Algo.` qualification.
```

### Possible Solution

I expect but do not know that this relates to @ringabout's recent enum work.  It's probably an easy git bisect.  It worked in nim-devel 6cb2dca41dde3498a065c9cfb2e484d2104dd11c which I only kept around for [backend portability-performance investigation](https://github.com/nim-lang/Nim/pull/23488#issuecomment-2098054212).

### Additional Information

I think this is distinct from https://github.com/nim-lang/Nim/issues/23579 .  I'm also not sure if it's exactly unintended behavior.  Maybe nim core wants the qualification to be required in this case.  It seemed worth reporting while the work is fresh.

**Comment by juancarlospaco** [comment]
!nim c

```nim
import std/heapqueue
type Algo = enum heapqueue, quick
proc bar*(algo=quick) =
  var x: HeapQueue[int]
  case algo
  of heapqueue: echo 1
  of quick: echo 2
  echo x.len
```

**Comment by juancarlospaco** [comment]
@metagn See Bisect.

**Comment by metagn** [comment]
Pre-existing in general:

```nim
import std/heapqueue
proc heapqueue(x: int) = discard
# or type Algo = enum heapqueue
let x = heapqueue
```

A non-pre-existing version would be:

```nim
import std/heapqueue
type Algo = enum heapqueue, quick
let x: Algo = heapqueue # note type annotation
```

We could disable module symbols in any context where a value is expected but in `foo.bar` the compiler expects `foo` to have a type. Maybe `foo.bar` should be a specific context where module symbols are allowed? But this could break code like:

```nim
macro foo(x: typed) = discard

import math
foo(math)
```

Something that has a better chance of working is not giving module symbols "priority" in symbol lookup (don't break in `searchInScopesFilterBy`) because they don't check for overloads so they would be treated as ambiguous and get resolved away but this isn't reliable because the order in which the symbols are imported/declared would affect it.
