### ISSUE TITLE
[Regression] compiler is not inferring the type of an `enum` marked with the `pure` pragma when there is a type with the same identifier as a value of this enum

### ISSUE THREAD

**Issue by rockcavera** [nim-lang/Nim#23689]
### Description

Until recently the compiler was able to correctly infer the code below, however, in the current devel the compiler reports an error

```nim
type
  MyEnum {.pure.} = enum
    A, B, C, D

  B = object
    field: int

let x: MyEnum = B # the type is explicit as `MyEnum`, therefore `B` should be inferred as `MyEnum.B`

echo typeof(x)

let y = MyEnum.A

if y in {A, B}: # `B` should be inferred as `MyEnum.B`, as `A` can only be `MyEnum.A`
  echo true
```

### Nim Version

Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2024-06-06
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 8f5ae28fab113c425d22e5abc230f456fa627744
active boot switches: -d:release

### Current Output

```text
nim r bug
Hint: used config file 'E:\Nim\config\nim.cfg' [Conf]
Hint: used config file 'E:\Nim\config\config.nims' [Conf]
.......................................................................
C:\Users\josep\desktop\bug.nim(8, 17) Error: type mismatch: got 'typedesc[B]' for 'B' but expected 'MyEnum = enum'
```

### Expected Output

```text
MyEnum
true
```

### Additional Information

compiles correctly in version 2.0.4 and with 1.6.20

**Comment by juancarlospaco** [comment]
!nim c

```nim
type
  MyEnum {.pure.} = enum
    A, B, C, D

  B = object
    field: int

let x: MyEnum = B # the type is explicit as `MyEnum`, therefore `B` should be inferred as `MyEnum.B`

echo typeof(x)

let y = MyEnum.A

if y in {A, B}: # `B` should be inferred as `MyEnum.B`, as `A` can only be `MyEnum.A`
  echo true
```

**Comment by juancarlospaco** [comment]
@metagn Bisect.

**Comment by metagn** [comment]
Can't check right now, does it work if the enum isn't pure? There was functionality that bypassed symbol lookup for enum identifiers based on the inferred type which was removed because it ignores existing local symbols. Pure enums have a lower priority in symbol lookup, if another symbol is found before them it's used instead.

**Comment by juancarlospaco** [comment]
I mean check this bisect https://github.com/nim-lang/Nim/issues/23689#issuecomment-2153568605 🙂 
[It is one of your commits](https://github.com/nim-lang/Nim/commit/c101490a0) maybe you have an idea about what happens.

**Comment by rockcavera** [comment]
> Can't check right now, does it work if the enum isn't pure? There was functionality that bypassed symbol lookup for enum identifiers based on the inferred type which was removed because it ignores existing local symbols. Pure enums have a lower priority in symbol lookup, if another symbol is found before them it's used instead.

does not work without marking with the pure pragma, either in devel, 2.0.4 or 1.6.20

**Comment by metagn** [comment]
> I mean check this bisect 

I know what commit caused it, I was just explaining what the commit did.

The reason this worked since 1.6.14 is functionality that was not good, which was removed in #23588. Doing the removed functionality in a proper way is very hard. Whenever the inferred type of an identifier expression was an enum, it would immediately check the enum member list to check if the enum has a member with the same name as the identifier. This skipped local symbols with the same name, i.e. this happened:

```nim
type Foo = enum a, b
block:
  let b = a
  let c: Foo = b
  echo c # b
```

I've been trying to think of ways to bring the intended behavior back since the "regressions" started popping up but there's nothing that's simple and covers every case.

1. We can only trigger it for undeclared identifiers (#23614), but that doesn't fix this issue.
2. We can trigger it when the expected type of an identifier is an enum but lookup fails OR the lookup succeeds but the type doesn't match, this can cause a performance hit to the compiler because it's a type comparison every single time we look up an identifier with an expected enum type.
3. We can disable type symbols in lookup when an enum type is expected similar to #23597, maybe combined with #23614 to deal with #23611. This really only fixes this issue and it's pretty arbitrary, the question of "why just enum types, which other types can type symbols never be" pops up. I'll open a PR with this but I don't know if it'll even work. (#23694)

Another thing is the fact that this only works with pure enums, normal enums give a redefinition error instead like a proc would (unless you spread the 2 types across different modules in which case normal enums work). To fix this we would probably have to make types overloadable which would be a big effort (there's no way to disambiguate type symbols in the same module), so we can't merge pure enums with normal enums yet.
