### ISSUE TITLE
Regression from 1.6 to 2.0/devel with templates with `gensym` `proc`

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#23813]
### Description

```nim
template r(body: untyped) =
  proc x() {.gensym.} =
    body

template g() =
  r:
    let y = 0

  r:
    proc y() = discard
    y()

g()
```

### Nim Version

Builds in Nim 1.6:
```
Nim Compiler Version 1.6.21 [Linux: amd64]
Compiled at 2024-07-09
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 786bbff1ae0c1f124fc0848948c0fd7dfd30225c
active boot switches: -d:release
```

Does not build in 2.0 and devel:
```
Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-07-08
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-07-09
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 732f7752a954bb33a92e839304006ba5d865400a
active boot switches: -d:release
```

### Current Output

```text
/tmp/m.nim(7, 9) Hint: 'y`gensym0' is declared but not used [XDeclaredButNotUsed]
/tmp/m.nim(13, 2) template/generic instantiation of `g` from here
/tmp/m.nim(11, 5) Error: undeclared identifier: 'y`gensym0'; if declared in a template, this identifier may be inconsistently marked inject or gensym
candidates (edit distance, scope distance); see '--spellSuggest': 
 (2, 2): 'x`gensym1'
 (2, 2): 'x`gensym2'
```

### Expected Output

```text
Builds
```

**Comment by metagn** [comment]
This is #23392 hence the special error message. The `let y` marks `y` as gensym but `proc y` injects it, previously the previous `y` being gensym'd also made the `proc y` gensym for some reason. But only the previous gensym'd `y` is in the template scope, injected procs don't track their identifiers as injected internally (not added to `toInject`) so it just uses the `let y` instead in `y()`. So a workaround is marking `let y` as `inject` or `proc y` as `gensym` (the old behavior) or making the template dirty.

I had a PR that added injected procs to `toInject` but it ended up not going through, I don't remember what it broke. Edit: It was #20003 but then I tried adding to `toMixin` instead which passed CI I believe, but I don't know if that would be too weird or breaks stuff that isn't in CI.

**Comment by metagn** [comment]
Sorry, `toMixin` doesn't fix this issue since a gensym'd `y` still exists, so I don't think there's an easy fix. The workaround of adding `{.gensym.}` to the `proc y` mirrors exactly the previous behavior but I understand it might look ugly, maybe we can add a pragma to templates that changes the default for routine symbols to gensym and not inject since it's completely a frontend issue.

I'm going to open a PR that implements the idea mentioned [here](https://github.com/nim-lang/Nim/pull/23392#issuecomment-1989314924) where the old behavior is kept unless the proc has an explicit `inject`. It might be nice to mention this in the documentation though.
