### ISSUE TITLE
bisecting 2.2.0 rc1

### ISSUE THREAD

**Issue by ringabout** [nim-lang/Nim#23836]
!nim c
```nim
type p = ptr UncheckedArray[char]
doAssert p is ptr UncheckedArray
```

**Comment by ringabout** [comment]
!nim c
```nim
proc test(): (int, int) {.discardable.} =
  discard

if true:
  test()

else:
  quit()
```

**Comment by ringabout** [comment]
!nim c --warningAsError:UnreachableCode
```nim
proc test(): bool =
  
  block okay:
    if true: break okay
    return false
  
  return true # Line 7 is here

echo test()
```

**Comment by ringabout** [comment]
!nim c
```nim
type
  Object = object
    a: int
    b: ref int

template bug(body: untyped) =
  proc fn(): auto {.cdecl.} =
    body
  
  discard fn()

var x = 0
bug:
  inc x
  return Object()

# import std/assertions
doAssert x == 1
```

**Comment by ringabout** [comment]
ref https://forum.nim-lang.org/t/11987

**Comment by ringabout** [comment]
!nim c
```nim
type p = ptr UncheckedArray[char]
doAssert p is ptr UncheckedArray
```

**Comment by ringabout** [comment]
I'm working on unreachable code

**Comment by metagn** [comment]
The one with `cdecl` has nothing to do with templates, simplified:

```nim
type Object = object
  a: int
  b: ref int
var x = 0
proc fn(): auto {.cdecl.} =
  inc x
  return Object()
discard fn()
doAssert x == 1
```

Both `a: int` and `b: ref int` need to exist for some reason.

Locally this seems caused by #23409, not sure if there's a reason the bisect bot couldn't figure it out.

Also thanks for fixing the regressions from #23681, I didn't have time to look at them.

**Comment by alex65536** [comment]
> Locally this seems caused by https://github.com/nim-lang/Nim/pull/23409, not sure if there's a reason the bisect bot couldn't figure it out.

I am unsure, though, whether the PR above is the real cause of the bug, or the bug was just hidden deep inside codegen, and the PR just revealed it by returning the struct from a C function instead of passing it by reference as an extra argument.

See the generated code:
```nim
 nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Object__VgM2mdSfwS3kJw14mu7dcQ));
 colontmpD_.a = fn__temp_u7().a;
 colontmpD_.b = fn__temp_u7().b;
```

It looks clearly that somehow codegen managed to duplicate the function call.

**Comment by SirOlaf** [comment]
> !nim c
> 
> ```nim
> type p = ptr UncheckedArray[char]
> doAssert p is ptr UncheckedArray
> ```

Culprit here seems to be https://github.com/nim-lang/Nim/pull/23055 which switched to `elementType` from `base`, probably only worked by chance before.

**Comment by ringabout** [comment]
>> Locally this seems caused by https://github.com/nim-lang/Nim/pull/23409, not sure if there's a reason the bisect bot couldn't figure it out.

> I am unsure, though, whether the PR above is the real cause of the bug, or the bug was just hidden deep inside codegen, and the PR just revealed it by returning the struct from a C function instead of passing it by reference as an extra argument.

Yeah, I have found the culprit, I'm trying to reason with its original design

**Comment by ringabout** [comment]
All solved one way or another!

**Comment by metagn** [comment]
Was the `ptr UncheckedArray` one solved?

**Comment by SirOlaf** [comment]
> Was the `ptr UncheckedArray` one solved?

Will be if this fix makes sense
