### ISSUE TITLE
Compiling with Nim v2.2.0 gives SIGSEGV for yaml loading code

### ISSUE THREAD

**Issue by jfilby** [nim-lang/Nim#24526]
### Description

Using Nim v2.2.0, when I compile code that loads yaml (standard library) into an object that contains a ref object, the compiler crashes with a sigsegv.

### Nim Version

2.2.0

### Current Output

```text
nexus/src/nexus/cmd$ nim --path:../.. -d:ssl c programs/nexus.nim
Hint: used config file '/home/user/.choosenim/toolchains/nim-2.2.0/config/nim.cfg' [Conf]
Hint: used config file '/home/user/.choosenim/toolchains/nim-2.2.0/config/config.nims' [Conf]
......................................................................................................................................................................................................................................................................
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output

```text
Best case is that the code compiles without any problem. But in the worst case it should give a valid error message and not crash.
```

### Known Workarounds

For the object trying to be loaded, convert any ref objects to objects.

### Additional Information

Test case:

```nim
import streams, yaml


type
  Item* = ref object of RootObj
    name*: string


# Load YAML
var
  item: Item
  s = newFileStream("test.yaml")

load(s, item)
s.close()
```

**Comment by metagn** [comment]
First of all the segfault is from calling `kind` on a nil node which the compiler [doesn't check](https://github.com/nim-lang/Nim/blob/aeb3fe9505f7d1ef3efcd0001541a64ca8382b01/compiler/vm.nim#L1800), maybe we could add stacktraces for nil accesses in these magics but straight up `nil` nodes aren't supposed to be encountered in macro code AFAIK.

The issue seems to be a weird interaction in `hasCustomPragma` caused by #23101, the `getImpl` call [here](https://github.com/nim-lang/Nim/blob/aeb3fe9505f7d1ef3efcd0001541a64ca8382b01/lib/core/macros.nim#L1587) returns the `nnkTypeDef` node of the type symbol, and when there are no pragmas in the typedef the first node (the name) is returned for some reason. This returned node can be an `nnkPostfix` node since #23101. Then this node is iterated over [here](https://github.com/nim-lang/Nim/blob/aeb3fe9505f7d1ef3efcd0001541a64ca8382b01/lib/core/macros.nim#L1676) which yields a `nil` node that causes the segfault? It's weird that `hasCustomPragma` was doing it like this in the first place (it could just return `nil` instead of the name node) but I guess there shouldn't be a postfix node with a nil child either. Edit: Yes, the compiler is at fault for generating a nil node.

**Comment by jfilby** [comment]
Thanks!
