### ISSUE TITLE
Add hint for unused imports

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#251]
Add an optional switch to the compiler where it hints which imported modules are not being used at all, so the programmer can remove them.

**Comment by BigBoneDaddy** [comment]
@gradha I have many likes for this idea! Good to throw in garbage module that is not used!

**Comment by Varriount** [comment]
@BigBoneDaddy Unless you have something constructive and noteworthy to say, please refrain from commenting on old issues. Merely stating your favor for a feature/change does not merit updating an old issue.

**Comment by BigBoneDaddy** [comment]
@Varriount GitHub is social development. If you not want social then maybe you unsubscribe from issues? There Unsubscribe button at right side in right column. Scroll and you see it.

**Comment by Varriount** [comment]
@BigBoneDaddy Even on forums (which are arguably more social than the comments section of a GitHub issue page) it's poor etiquette to update an old thread without a good (read: constructive) reason.

**Comment by BigBoneDaddy** [comment]
@Varriount The issue is still open! It is still an active issue! It matters not when it was created. It matters not what its age is. If it is still open then it is still active. Like I say there is Unsubscribe button to the right. If notices bother you then click Unsubscribe button to right and you get no more of the notices that so bother you greatly!

**Comment by Araq** [comment]
Note that Nim's ``export`` feature makes this internally quite complex to support properly.

**Comment by GULPF** [comment]
This has been implemented.
