### ISSUE TITLE
Automatically cycling between code samples on front page makes them hard to read

### ISSUE THREAD

**Issue by kentonv** [nim-lang/Nim#2635]
The top part of the front page at http://nim-lang.org/ shows some code samples. This is great! A programming language home page should _always_ start with code samples, as this is the fastest way to communicate the basics feel of the language.

Unfortunately, these samples are impossible to read, because after a few seconds, the sample fades out and a new one replaces it.

While this cycling may seem snazzy from a web designer's perspective, as a new visitor and reader I actually find it frustrating. Even if I click on the little circles at the right (which many people might not even notice, or realize control the cycling), this only seems to pause the cycling temporarily -- not long enough to absorb the information displayed.

I would argue that the samples should be shown non-overlapping, so I can see all three at once and scroll at my leisure. If they must be overlapping, it would help to have a clear and obvious way to manually navigate between them, and either don't auto-cycle at all or stop auto-cycling when I first click on the manual controls.

**Comment by reactormonk** [comment]
There are actually buttons to the right of the orange text column - gotta move them closer.

**Comment by dom96** [comment]
:+1:

**Comment by kirbyfan64** [comment]
+1. Also, IMO, the second slide should be the primary one, and the one about the parallel block should have something less cheesy than "Why should I be excited?"

**Comment by ozra** [comment]
Agree completely - the direct show off of the lang is what caught me and kept me reading - very important indeed. And I also was annoyed to have it ripped from under my eyes while I was reading.

Slowed down would be enough, so one can 'grab it' with a mouse click. Also as mentioned, @kentonv, stopping when "picking a slide".

Optimally and bonus: some signal that it's starting to go (blinking position dot?) - it took me quite a while to see the selection dots too - since they're kind of "disconnected" from the slides...

**Comment by Yardanico** [comment]
@dom96 close? We have only one example at the main page now :)
Other examples are here - https://nim-lang.org/features.html, and they're separated from each other
