### ISSUE TITLE
parallel spawn deadlock

### ISSUE THREAD

**Issue by Xaseron** [nim-lang/Nim#2704]
I'm using the parallel spawn feature for parallelizing quicksort and this piece of code mostly deadlock. 

Edited: update to latest Nim version(Nim v 1.4)
``` nim
{.experimental.}

import threadpool
import sequtils
import times
import random

proc quickSort[T](a: var seq[T], lo, hi: int) =
    if hi <= lo: return
    let pivot = a[int((lo+hi)/2)]
    var (i, j) = (lo, hi)

    while i <= j:
        if a[i] < pivot:
            inc i
        elif a[j] > pivot:
            dec j
        elif i <= j:
            swap a[i], a[j]
            inc i
            dec j
    parallel:
        spawn quickSort(a, lo, j)
        spawn quickSort(a, i, hi)

proc quickSort*[T](a: var seq[T]) =
    quickSort(a, a.low, a.high)

randomize(int(epochTime()))
var a = newSeqWith(100, rand(100))


quickSort a
echo a
```

**Comment by kirbyfan64** [comment]
I can't help but wonder if you're incurring a data race by modifying the contents of the array that you're sorting...

**Comment by rbehrends** [comment]
You're probably running out of worker threads in the threadpool. As soon as you have as many threads waiting on the result of a `spawn` as there are worker thread (implicit in the end of the `parallel` block), the system will block because there are no more threads available to service remaining spawn requests. This is a common problem when you use recursive divide-and-conquer algorithms with threadpools.

**Comment by Araq** [comment]
on windows it even crashes, no deadlock.

**Comment by Araq** [comment]
Since 'parallel' is still experimental, I'm turning this into "normal" priority.

**Comment by Araq** [comment]
Still an issue with 0.18.

**Comment by Clyybber** [comment]
Still an issue

**Comment by Araq** [comment]
std / threadpool is moribund, use Malebolgia instead.
