### ISSUE TITLE
Ambiguous error message when C compiler cannot be found

### ISSUE THREAD

**Issue by sstirlin** [nim-lang/Nim#2770]
When the C compiler cannot be found the only error spit out is

Error: unhandled exception: The system cannot find the file specified [OSError]

This could refer to anything.  It would be great to have a message that is more clear here (this tripped me up for several minutes).  Thanks!

**Comment by kirbyfan64** [comment]
This is actually just the error that the system returns. It's actually quite hard to trap this effectively.

**Comment by dom96** [comment]
``OSError`` should contain a field describing the error code. Perhaps this could be checked in the compiler?

**Comment by kirbyfan64** [comment]
I guess...I just know that I tried that for Posix and Windows in Python once, and it did *not* end well...

**Comment by ozra** [comment]
Also in #2135

**Comment by couven92** [comment]
I am onto it... But I think this calls for a new error message instead of doing something with `OSError` as @dom96 suggested. After all the `The system cannot find the file specified` is the message that is coming from the OS and which is the exception message of the error message. Other than the actual OS error code (`ENOENT`), there is not much more to get out of the error.

I suggest introducing the following error message:
> Unable to locate compiler backend: $1

Where `$1` is the executable path that is invoked (without the arguments, since they are not of interest in this case). E.g.: `gcc`, `gcc.exe`, `cl.exe`, `vccexe.exe`, `some/path/to/compiler/gcc`, etc.

(ref.: #2135)

**Comment by dom96** [comment]
Sure, feel free to do what. I don't mind defining a new exception type for this but I know that @Araq dislikes that.
