### ISSUE TITLE
Feature request: pragma similar to Scala's sealed keyword

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#2826]
In Scala, it is possible to define a class or trait as `sealed`, meaning that such a class or trait cannot be inherited from outside the current package. Having a matching feature in Nim that disallows inheritance outside the current module would allow for the following things:
1. More efficient method dispatch, since all subtypes can be exhaustively enumerated.
2. Exhaustiveness checks for method dispatch.
3. Being able to reserve enough space for `object` types so that a variable of a supertype can actually contain values of all subtypes.

While `sealed` may not be the best choice of keyword, given that it means something different in C# already, having a pragma for `ref object` and `object` types with matching semantics should be beneficial.

**Comment by Varriount** [comment]
Can't all subtypes of methods already be exhaustively enumerated? All the types that are covered by a particular method are known at compile time. I don't see how merely limiting the pool of types allows for increased optimization.

How would you go about actually coding #3, without breaking garbage collection? (assuming you're using garbage collection)

Overall, I'm against any sort of 'final' type modifier for types. I've seen far too many instances where authors put 'sealed' or 'final' because they think no-one would ever need to subclass/borrow from their instances, and the users have to come up with hacky workarounds. If a type should be handled that carefully, put it in the documentation.

**Comment by rbehrends** [comment]
Subtypes can be enumerated at compile time, but (1) not in an efficient fashion while using DLLs – which is why method dispatch with lots of subclasses currently can have poor performance – and (2) not without breaking modularity. I'd like to make method dispatch more efficient in general, but this is a useful feature all the same.

GC shouldn't be affected at all. You can tell by the runtime type what fields are actually occupied. It's not as though currently the GC can actually tell where the object ends without checking the runtime type, either.

>  Overall, I'm against any sort of 'final' type modifier for types.

That would then also be an argument against variant object types. This essentially gives you variant types without the memory overhead for the `ref` variant.

**Comment by Varriount** [comment]
> This essentially gives you variant types without the memory overhead for the ref variant.

I don't quite follow, could you explain please?

**Comment by rbehrends** [comment]
A `ref object` variant type currently allocates as much memory as the largest alternative needs (as you can switch between variants). With inheritance, you need only to allocate as much memory as the specific subtype needs, and if you can enumerate subtypes exhaustively, you can dispatch between them as efficiently as for variant types.

**Comment by Araq** [comment]
We have the ``.final`` pragma for that nowadays.
