### ISSUE TITLE
unittest causes \27[0m\10 to be appended to output

### ISSUE THREAD

**Issue by fenekku** [nim-lang/Nim#2857]
How to reproduce:

test1.nim file
```nim
import unittest

quit "Hello World"
```

test2.nim file
```nim
import osproc

var exitTuple = execCmdEx("./test1")
echo "repr(exitTuple.output)"
echo repr(exitTuple.output)
```

On the command line:

```bash
nim c test1.nim
nim c test2.nim
./test2
repr(exitTuple.output)
0x7fa5900996d0"Hello World\10"
"\27[0m\10"
""
```

Comment out or remove `import unittest` from test1.nim and the ANSI escape sequence "attribute clear" (that's the \27[0m) is removed. This behaviour is new from 0.11.x over 0.10.2. This has been tested under the git repo i.e. Nim version 0.11.3.

The mere presence of unittest alters the output of the program.

**Comment by ozra** [comment]
Aha!! Discovered this when working on #2862, but found no obvious candidate in "unittest". But then it's confirmed to be there. The plot tightens... :)

**Comment by fenekku** [comment]
Oh I don't know if the plot is so tight :smile_cat: . The problem is here: https://github.com/Araq/Nim/blob/devel/lib/pure/unittest.nim#L42

`system.addQuitProc(resetAttributes)` is used as a convenience to reset the color scheme when `testDone` is well... done: https://github.com/Araq/Nim/blob/devel/lib/pure/unittest.nim#L84

The color reset should be handled by the code and not registered as a QuitProc. That registration is global and makes it dip its toes everywhere.

I was planning on giving unittest some :heart: soon given the documentation (#460) and all.

**Comment by ozra** [comment]
In a way, the automatic "clean up" is good, avoiding boilerplate in unit tests. But then it should only do it _iff_ any output has been generated at all by the test. Might be hard to catch.

Simpler alternative is to look for the case specifically in testament tester - I was considering doing it, but since I didn't know _why_ (accident? one-off?) the term-reset was ouput, I didn't want to add any ad-hoc stuff. 

But in this case it is actually a viable solution. Since it's only the tester that does output compares.

**Comment by ozra** [comment]
Woo, this was sooome goofy code! (I mean, working, but goofy). Yeah it needs love.

```nim
  if outputLevel != PRINT_NONE and (outputLevel == PRINT_ALL or s == FAILED):
    template rawPrint() = echo("[", $s, "] ", name)
    when not defined(ECMAScript):
      if colorOutput and not defined(ECMAScript):
```

Anyways, I think I'll implement above mentioned exception for "attribute clear" in #2862. The unittest mod needs clearing up obviously, but I think it's good if it does helpful clean ups so that it's dead easy, no boiler, to implement tests, thereby encouraging it. (Cater to the lazy)

**Comment by fenekku** [comment]
Oh yeah what I meant by "handled by the code" was "handled by `testDone` or something in the module (definitely not the code *using* unittest module!)

**Comment by ozra** [comment]
Silly me - my bad.

**Comment by Araq** [comment]
ozra, this was fixed, right?

**Comment by fenekku** [comment]
@Araq this was fixed. Thanks
