### ISSUE TITLE
Exponentiation operator

### ISSUE THREAD

**Issue by wild-billy** [nim-lang/Nim#2897]
So the math module has 2 different exponentiation functions, `pow(x,y)` and ``^`(x,y)`. The operator version (`^`) can't handle negative `y`, which is an unexpected limitation.

Since both are ostensibly supposed to represent the same operation ("x raised to the power of y"), I'd suggest making `^` an alias for `pow()` (least surprise, right?), and optimizing `pow()` if needed/desired.

This hopefully wouldn't break any existing code (exponentiation is exponentiation, in theory), and frankly it's probably best to end the opportunity for any code to depend on the difference.

**Comment by dom96** [comment]
``^`` has the advantage that it will work at compile-time.

**Comment by dom96** [comment]
@def- could we add support for negative ``y`` to ``^``?

**Comment by Araq** [comment]
@dom96 Both work at compile-time.

**Comment by BigBoneDaddy** [comment]
@Araq Why are there 2?

**Comment by dom96** [comment]
Legacy I presume.

**Comment by reactormonk** [comment]
Wanna deprecate one or are two fine?

**Comment by dom96** [comment]
no reason to deprecate.

**Comment by BigBoneDaddy** [comment]
@dom96 Confusion is a good reason to deprecate especially when one of them can't handle negatives! Get rid of the bad one and use just the good one!

**Comment by reactormonk** [comment]
Then switch `^` to call `pow`?

**Comment by BigBoneDaddy** [comment]
@reactormonk Yes please make the change

**Comment by dom96** [comment]
@reactormonk yes.

**Comment by reactormonk** [comment]
The documentation explicitly states that `x` must be non-negative and I assume it has a reason, because `pow` loses precision, where `^` does not. Maybe rename `^` to something else?

**Comment by BigBoneDaddy** [comment]
@reactormonk That is good point. Do you maybe have test case to prove if that true that precision loss can be happening?

**Comment by reactormonk** [comment]
@BigBoneDaddy Nope, that's from the concept. `^` can use ints, where `pow` uses floats by default. Nothing to test here.

**Comment by BigBoneDaddy** [comment]
@reactormonk What about one name for both using generic?

**Comment by BigBoneDaddy** [comment]
@reactormonk What I mean is that pow operation work on other types too beside int and float. Like in old code base I work on in past there was pow function and it took character or string. It would repeat string many time if necessary. It good for testing string processing functions that could be O(n^m).

**Comment by dom96** [comment]
I don't see why we would need two different versions of ``^`` with subtle differences. But this issue is low priority I guess anyway.

**Comment by dom96** [comment]
We should decide what to do about this.

Alias ``^`` to ``pow``? Note, ``pow`` only works on floats. Is it fine to just convert the type to a float?

**Comment by andreaferretti** [comment]
> Is it fine to just convert the type to a float and then back again?

No. In any case, I think there are two different implementations of exponentation: repeated multiplication, or some kind of approximate algorithm via Taylor series or whatever libc uses.

The two are different enough (and have different exactness requirements) that I don't mind using different symbols for them

**Comment by dom96** [comment]
Perhaps, but then I think that the operator should get the more powerful variant (i.e. one without the limitations that the current ``^`` has).

**Comment by andreaferretti** [comment]
What limitations exactly?

**Comment by bluenote10** [comment]
That the exponent cannot be negative (btw: the docstring is wrong, it says `x` can't be negative, but it should be `y`).

I also see `^` as "repeated multiplication" and this limitation makes sense to me. Otherwise the operator would need a type signature that changes the input type. Currently the signature ensures that a repeated multiplication of an `int` stays an `int`. Allowing "negative repeats" requires a float result, and achieving repeated multiplications of ints would require a type conversion back to int. So it would make sense to have both.

**Comment by dom96** [comment]
Okay, but then wouldn't it make sense to rename ``pow`` to ``^``?

**Comment by andreaferretti** [comment]
We can overload `pow` for `(int,int)` and `(float, float)` and make `^` an alias for `pow`. `pow` is kind of a standard name, so people will look for it, but `5^3` looks so much better than `pow(5, 3)`

**Comment by cooldome** [comment]
There should be at least three exponentiation functions `(int, int) -> int,` `(float, int) -> float`, `(float, float) -> float`. The last one is usually called `pow`.` (float, float) -> float` is the slowest, because handling of floating exponent VERY non trivial, it is at least `log(x)`, `exp(x)` and 500 lines of accuracy improvement with several polynomials. Please check libc code for `pow`, you will be horrified how complicated and hence slow it is. `(float, int) -> float` can be done using a simple loop and it should be done this way. 

You may also want `(float, static[int])-> float` and `(float, static[float])->float` to optimize loops away or call `sqrt` instead of `pow(x, ±0.5)`, this is well worth it optimizations. 
You do want x^0.5 to mean `sqrt(x)` it much more efficient then `pow`.

**Comment by Araq** [comment]
IMO ``^``  should cover (int, int) -> int and (float, int) -> float and ``pow`` the all float case. Which is exactly what ``math.nim`` already offers.

**Comment by dom96** [comment]
> IMO ^ should cover (int, int) -> int and (float, int) -> float and pow the all float case. Which is exactly what math.nim already offers.

Great, so no breaking changes needed.

My only problem with the current ``^`` is that it doesn't support a negative exponent, but we can fix that later. Removing high priority.

**Comment by andreaferretti** [comment]
It doesn't support negative exponent because it would not be repeated multiplication (you cannot repeat something -3 times). It does not even match the type (`(int, int) -> int`) as, say, 5^-1 = 1/5. This would only be relevant for (float, int) -> float

**Comment by dom96** [comment]
> It doesn't support negative exponent because it would not be repeated multiplication (you cannot repeat something -3 times).

Yes, I am aware. I'm arguing that the `(float, int) -> float` variant should support negative exponents (by using a different algorithm if required).

And actually, if we want to be super technical then ``(int, int) -> int`` should really be `(int, natural) -> int`.

**Comment by dom96** [comment]
So I created a PR to hopefully close this issue, it's fairly simple: https://github.com/nim-lang/Nim/pull/7234

**Comment by GULPF** [comment]
Oh, I just tried to fix it as well :P I'll submit it anyway, because your PR has a few errors. ``proc `^`*(x: float, y: int)`` is in conflict with ``proc `^`*[T](x: T, y: Natural)``. The compiler doesn't complain for some reason, but it means that 2^2 == 4.0. Also, you forgot to support float32 with `^`

#7235

**Comment by dom96** [comment]
and with your code my tests don't work :)

In practice I don't see the problem with explicitly casting the int to a Natural.

**Comment by GULPF** [comment]
Hmm ok now I understand your intention. It's fragile though. The test `5 * 10 ^ -9 ==~ 5e-9` only works because the compiler infers `5 * 10` as float. The reason that it doesn't work with my PR is because `^` has generic arguments, which apparently doesn't trigger the compilers magic for int literals. Here's an example that fail with both PRs:
```nim
let x = 5
discard x ^ -9
```

float32 works because of type promotion, but that means that `pow` will be used instead of `powf. No idea if that actually matters though.

**Comment by enormandeau** [comment]
Exponentiation with ints (eg `var a = 2 ^ 2`) gives 

```
Error: type mismatch: got <int literal(2), int literal(2)>
but expected one of: 
template `^`(x: int): BackwardsIndex

expression: 2 ^ 2
```
# Nim version
Nim Compiler Version 0.18.0 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 855956bf617f68ac0be3717329e9e1181e5dc0c6
active boot switches: -d:release
```

**Comment by andreaferretti** [comment]
@enormandeau You need to `import math`

**Comment by Araq** [comment]
Nothing to fix here, I like how it works today and others agreed with me. Closing.
