### ISSUE TITLE
Odd little pragma issue

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#2926]
While I was writing some documentation for `macros.nim`, I noticed the following:

``` nim
type # this works fine
  BObj[T] = object {.inheritable.} 
  CObj[T] = ref object of BObj[T]
```

``` nim
type # this, too
  BObj {.inheritable.} = object
  CObj = ref object of BObj
```

``` nim
type # this doesn't
  BObj {.inheritable.} [T] = object
  CObj[T] = ref object of BObj[T]
```

The error is `Error: inheritance only works with non-final objects`
The position of the last pragma is a little weird, but `BObj[T] {.inheritable.}` isn't allowed.

**Comment by narimiran** [comment]
> The position of the last pragma is a little weird, but `BObj[T] {.inheritable.}` isn't allowed.

This is now allowed and preferred way. `BObj {.inheritable.} [T]` now gives "Warning: pragma before generic parameter list is deprecated"

> The error is `Error: inheritance only works with non-final objects`

The last example now gives more detailed error message: "Error: inheritance only works with non-final objects; to enable inheritance write 'BObj[CObj.T] of RootObj'", which is fixed by using:

```nim
type
  BObj[T] {.inheritable.} = object of RootObj
  CObj[T] = ref object of BObj[T]
```
