### ISSUE TITLE
`notof` operator feature request

### ISSUE THREAD

**Issue by apense** [nim-lang/Nim#2991]
Where we have `is` and `isnot`, I think the addition of `notof` to complement `of` seems natural ("not" at the beginning to match natural English). That way, given:

``` nim
type
  Person {.inheritable.} = object
    name*: string
    age: int
  Student = ref object of Person
    id: int

var
  person: Person

var student = Student(name: "Anton", age: 5, id: 3)
```

then

``` nim
assert(not(person of Student))
```

can be rewritten as

``` nim
assert(person notof Student))
```

**Comment by Araq** [comment]
True but a new keyword-like infix operator requires to add this as a keyword, which I don't like.

**Comment by kirbyfan64** [comment]
@Araq I doubt anyone names their identifiers `notof`.

**Comment by apense** [comment]
If a new keyword isn't added, it would be nice if at least `person not of Student` would work, as a special case of `of` infix

**Comment by Araq** [comment]
Meh let's better add a keyword then :P

**Comment by dom96** [comment]
:\

**Comment by dom96** [comment]
I think that the likelihood of somebody naming their idents ``notof`` is not as unlikely as you may think.

**Comment by Varriount** [comment]
Google and GitHub searches don't reveal any use of  'notof' in Nim code (in fact, one of the first entries in  a Google search is this issue).

**Comment by dom96** [comment]
A lot of code is not open source.

**Comment by Varriount** [comment]
Yes, however there's no reason why the lack of frequency of a 'notof' identifier in open source code shouldn't reflect it's use in closed source software.

**Comment by BigBoneDaddy** [comment]
@kirbyfan64 I have 2 variables and 1 function named notof in my largest of Nim programs. It is only of 3000 lines but still that is 3 occurrences of notof. If it happen to me then it happen to others!

**Comment by BigBoneDaddy** [comment]
@Varriount Like @dom96 said there is so much code that lives not on the internet but it lives on private computers but it still uses variables named notof. It is not so simple to just change it because in my private code notof is a function that is part of stable API and this stable API can't just change! What am my team and I supposed to do not use newer Nim until we have to release new major version of our API? No we can't be doing that! Semver is important and this change will break semver.

**Comment by reactormonk** [comment]
@BigBoneDaddy does your code for `notof` do something different than the semantics explained here?

**Comment by BigBoneDaddy** [comment]
@reactormonk Yes my code has not to do with objects. I have three function actually. One is notof, one is noton and one is notor. They do complex string comparison checking for certain occurrence of words of, on and or in some complex string parameter.

**Comment by apense** [comment]
if everybody wants to avoid a keyword change, another option (admittedly
with its own issues) is to just support ``x not of y`` a little better, or
to allow something like

```nim
x is of y
x isnot of y
```
The latter doesn't introduce any keywords, at least, and it makes sense in
natural language.

**Comment by BigBoneDaddy** [comment]
@apense I think that good idea. :thumbsup:

**Comment by Varriount** [comment]
At some point, backwards incompatible changes will have to be made (if not over this, then over something else), otherwise you either end up with an enormous amount of cruft and peculiarities  (php) or have to apply them all at once (python). 

@BigBoneDaddy If we were to make `notof` a keyword, how hard would it be for you to fix your codebase?

**Comment by BigBoneDaddy** [comment]
@Varriount It would not be hard but I do not like precedent it sets. Breaking changes should only be done in very serious cases where there are no alternatives. When one breaking change is made then other breaking change becomes justifiable. The slope is too slippery! Nim is not 1.0 so maybe it okay and semver does not die but I think Nim is getting to be used for serious code so changes that break old code to add new keyword should be done as last resort!

**Comment by Varriount** [comment]
@apense, @BigBoneDaddy: Regarding precedents, allowing 'not of' sets a bad one as well - if we have a 'not of', then why not a 'not in' and so forth? Aside from that, I believe that allowing something like that is tricky for the compiler, hence @Araq's preference for the single keyword.

**Comment by BigBoneDaddy** [comment]
@Varriount Is is not the case that the in word is already a Nim keyword? So compiler hardness aside I do not see how it sets bad breaking precedent. The word is already reserved so nobody should be a user of it and so no code should break. @apense is that not the gist of your idea? I am against breaking code because I had to throw out so much of my Rust code because I write it one day and the next day they make massive changes and my code no longer work! I put more Rust code into garbage than I put into production! So I move to Nim. That has not been my problem with Nim and I hope it does not change. I can make my Nim code today and I know that my Nim code will work tomorrow and I know even with certainty that my Nim code will most probably still compile with no change even next month and maybe even the year after next! I hope that stay the case!

**Comment by Varriount** [comment]
@BigBoneDaddy I mean that it sets a precedent to allow 'not in' and similar, which creates possible ambiguity that the compiler must sort out. @Araq probably has a better idea of how challenging such a change would be. Though language changes are, in general, not something to be done lightly, in this case the fix wouldn't be terribly hard to implement, right? It would mainly be renaming your procedures/variables.

**Comment by Abrasax-** [comment]
I don't see the problem with introducing a non backwards compatible change in a language which has not reached yet `1.0`, in fact, it is the expected behavior in such cases. It can be seen in two ways:

1. Any product *before* `1.0` doesn't have a frozen api, and therefore, we should expect any changes any time
2. Release `1.0` is a major release, and it is expected that some changes won't be compatible with `<1.0`

Progress cannot be stopped at this point of the development. And `notof` is in fact a desired addition. Maybe it could be delayed until `1.0` is released (of course, in case this request is accepted).

**Comment by Araq** [comment]
@Varriount Well people coming from Python expect ``not in`` (with space) to work, so perhaps we should take this route. I don't like the special casing in the parser this implies but afaict at least it doesn't introduce any further lookahead.

**Comment by dom96** [comment]
I guess we need ``not is`` too... what else? But I guess for the sake of consistency we must yet again add all these things.

**Comment by BigBoneDaddy** [comment]
@Abrasax- The problem with too much change even before 1.0 is that it discourages people and drives them away. Too many change is why I do not use Rust any longer. For my problem domain Rust is better choice than Nim but before Rust 1 there was so much change that I would write my code and use it for a day maybe two then I had to make changes and recompile but by then Rust would hate my code! So into the garbage my code goes! Before 1.0 doesn't mean that breaking change is ok. It is still very bad it just is not absolutely prohibited in the most severe cases. But after 1.0 it means that change cannot happen even in serious case. It is permanently not changed at that point for any reason. That is the essence of semver.

**Comment by Xe** [comment]
Any time before 1.0 is a perfect time to make changes we want to stay through 1.0.

Regardless, I think the responsible way to do this would be to make `nofof` a reserved keyword in a future compiler version, and have a note on use of it asking for confirmation that `notof` is actually being used somewhere. Then we can implement the `notof` operator without risking breaking existing code.

**Comment by BigBoneDaddy** [comment]
@Xe That is good compromise. If we have time to fix existing code that is good help too. It just the surprise changes where it work one day and then it not work the next day that are soooooooo frustrating! They make me and my programmers so angry! :anger: :angry: :anger:

**Comment by dom96** [comment]
@BigBoneDaddy Unfortunately that may happen before 1.0. It's why you should wait for 1.0 to come out unless you are willing to live with these changes.

**Comment by BigBoneDaddy** [comment]
@dom96 Well in this case it is minor. Like I say earlier change before 1.0 is not bad if it is kept within reason. I and my team do need to use Nim now because we need a language like Nim. Rust did not work for us but so far Nim has been good to us. It is just a fear of mine that if there is one breaking change like this then the next breaking change, maybe even a bigger one, will be easy too. Then a bigger and bigger breaking change gets easier and soon Nim code even if it is pre 1.0 does not last long. I do not mind changing my code if it is just one minor change maybe every once now and then. But I do hope it is not like Rust where I had to change my code sometimes 3 or 4 times a day if I want to use latest compiler and in some cases my Rust code it was no good and needed full rewrite after just 1 week sometimes less! So if this change good for Nim community then I obvious support it but I hope that even pre Nim 1.0 is stable for use so we can get comfortable with it and give it more use and more testing before 1.0 and when things become frozen for good.

**Comment by Araq** [comment]
@dom96 Actually I disagree. The only reason we don't have 1.0 out for years already is bugs.

**Comment by Araq** [comment]
Not gonna happen soon, ``notof`` is just too rare.
