### ISSUE TITLE
Minimal code triggering endless system.- in macro using `varargs[untyped]`

### ISSUE THREAD

**Issue by oderwat** [nim-lang/Nim#3064]
I have some strange problem with the new `varags[untyped]` feature for macros which I could not reproduce until now in a short code fragment. I found it has to do with a proc type in an argument where the macro is used.

See this:

```nim
import macros

macro newButton(x: varargs[untyped]): int =
  echo repr(x)

# change `proc` to e.g. pointer and it will work as expected
proc makeButton(cb: proc): bool =
  result = newButton(-1)

proc callBack() = discard

discard makeButton(callBack)
```
Output:
```
[(system.-|system.-|system.-|system.-|system.-|system.-|system.-|system.-|system.-|system.-|system.-|system.-|system.-|system.-|system.-|...) 1]
```

**Comment by Araq** [comment]
Well that is no bug but there are a couple  of issues here:

* Your ``makeButton`` is a generic, use ``proc makeButton(cb: proc())`` instead to get a non-generic. I wanted to change this aspect so that ``proc`` is not a typeclass anymore and instead ``SomeProc`` has to be used but I never got around it. :-/
* In generics symbol lookup needs to be performed differently leading to the (foo|foo|...) "Sym Choice" construct. This too is not a bug but really required.
* The one thing we could do is to give ``repr`` a flag so that it transforms the sym choice back to a single identifier.

That said, you really shouldn't hack your macros together with string constructions. We have a real API to construct ASTs.

**Comment by oderwat** [comment]
I understand. Changed and works now. Thank you!

About hacking it together with string construction: I do not really see whats the problem here but consider to change that soon, because of your advise. So far I was happy that it works at all.
