### ISSUE TITLE
Is there a way to word wrap UTF-8?

### ISSUE THREAD

**Issue by scriptum** [nim-lang/Nim#3196]
### Nim

``` Nim
import strutils

echo wordwrap("Наши исследования позволяют сделать вывод о том, что субъект выбирает институциональный психоз. Важность этой функции подчеркивается тем фактом, что объект вызывает эгоцентризм. Самоактуализация аннигилирует генезис. Анима аннигилирует возрастной код. Закон просветляет аутотренинг. Наши исследования позволяют сделать вывод о том, что воспитание заметно осознаёт инсайт.")
```

Output:

```
Наши исследования позволяют сделать вывод
о том, что субъект выбирает
институциональный психоз. Важность этой
функции подчеркивается тем фактом, что
объект вызывает эгоцентризм.
Самоактуализация аннигилирует генезис.
Анима аннигилирует возрастной код. Закон
просветляет аутотренинг. Наши исследования
позволяют сделать вывод о том, что
воспитание заметно осознаёт инсайт.
```

:crying_cat_face: 
### Python

``` py
import textwrap

print '\n'.join(textwrap.wrap(u"Наши исследования позволяют сделать вывод о том, что субъект выбирает институциональный психоз. Важность этой функции подчеркивается тем фактом, что объект вызывает эгоцентризм. Самоактуализация аннигилирует генезис. Анима аннигилирует возрастной код. Закон просветляет аутотренинг. Наши исследования позволяют сделать вывод о том, что воспитание заметно осознаёт инсайт.", 80))
```

Output:

```
Наши исследования позволяют сделать вывод о том, что субъект выбирает
институциональный психоз. Важность этой функции подчеркивается тем фактом, что
объект вызывает эгоцентризм. Самоактуализация аннигилирует генезис. Анима
аннигилирует возрастной код. Закон просветляет аутотренинг. Наши исследования
позволяют сделать вывод о том, что воспитание заметно осознаёт инсайт.
```

:smile_cat:

**Comment by dom96** [comment]
So the question now becomes: should the ``strutils`` module support unicode, or should every procedure be cloned in the ``unicode`` module for unicode support?

@Araq thoughts?

**Comment by scriptum** [comment]
AFAIK all Python 2 functions can work with both Unicode and Utf-8, Python 3 - only Unicode. This is why you don't need to specify file encoding and add `u` character before strings in Python 3 and this is convenient. Some languages (Vala, C + GLib) assume that there is only Utf-8 strings.

This is why just cloning every function from `strutils` isn't enough. There are also other modules, regular expressions... 

Another issue - regular expressions. Without unicode support `"\w+"` matches only English words. E.g. in javascript I should use messy `(?:^|[^А-я\\w])` instead of just `\b`. I know that Nim also can compile to JS and using only unicode may lead to incompatibility.

Having only unicode strings (Qt, Python 3):
`+` speed (`str[i]` is O(1))
`+` easy to implement
`+` transparent for non-English developers, everything work from the box
`-` usage of memory (only in English, in Russian, Chinese and so on Utf-8 anyway consumes 2+ bytes per character)

Only Uft8 (GTK, Glib):
`-` access to random character is slow (fortunately this is rare)

Mixed encodings (Python 2) or only ACSII:
`-` coding hell

**Comment by Araq** [comment]
> So the question now becomes: should the strutils module support unicode, or should every procedure be cloned in the unicode module for unicode support?

No, no, no, that is not the question because that question has been answered already. Do you now start a general philosophical discussion for every bug that pops up?

The **real** question is why wordwrap doesn't work for you. Is it a simple bug that has nothing to do with Unicode? Or do you use Unicode-but-not-ASCII-whitespace?

**Comment by Araq** [comment]
> Having only unicode strings (Qt, Python 3):
> + speed (str[i] is O(1))

Wrong, Unicode effectively is a variable length encoding, even if you use UTF-32. Google "combining characters" if you don't believe me.

> + easy to implement

Wrong, requires every IO operation to perform a conversion to UTF-32 for very little gain.

> + transparent for non-English developers, everything work from the box

Wrong, just leads to more subtle bugs.

> - usage of memory (only in English, in Russian, Chinese and so on Utf-8 anyway consumes 2+ bytes per character)

Wrong, UTF-32 uses *4* bytes per character, not 2.

**Comment by dom96** [comment]
>> So the question now becomes: should the strutils module support unicode, or should every procedure be cloned in the unicode module for unicode support?

> No, no, no, that is not the question because that question has been answered already. Do you now start a general philosophical discussion for every bug that pops up?

"No" is not an answer to that question. But whatever. I'm just trying to help.

**Comment by scriptum** [comment]
@Araq the problem that I cannot find a way to make Nim understand that 80 bytes != 80 chars, and IIUC, there is no way to make correct word wrapping. But how regexp, toupper/tolower works with non-English? If Nim uses UTF-8 convention, shouldn't string functions work with UTF-8?

Btw I didn't find anything for i18n support (e.g. gettext).

```sh
$ wc -c <<< "Привет"
13
# But!
$ fold -w2 <<< "Привет"
Пр
ив
ет
```
And, Nim:
```Nim
echo wordwrap("Привет", 2)
П
�
�
�
�
�
```

**Comment by scriptum** [comment]
From unit tests:
```nim
    inp = """ this is a long text --  muchlongerthan10chars and here
               it goes"""
    outp = " this is a\nlong text\n--\nmuchlongerthan10chars\nand here\nit goes"
 this is a
long text
--muchlo
gerthan10c
hars and
here
it goes
```
Is it okay to lose a space after `--`?

I'm afraid that this is another bug.

**Comment by krux02** [comment]
So ``wordwrap`` thinks single byte. Cyrillic letters are two byte encoded. ``wordwrap`` thinks the words are much longer as they are on screen and the words are wrapped much earlier. Since strutils isn't unicode aware, there isn't much I can do about it. Since the current solution is by far not great, it isn't horrible. The text is readable and it is wrapped, even if it is too narrow.

For a correct word wrapping algorithm, the algorithm does not only need to know the individual characters, but also the relative width of the characters in the Font that is supposed to be used for rendering. This is something strutils will not be able to provide.

``wordwrap`` isn't a solution that fits everybody, it is and will always remain a quick and imprecise solution. The only question is, should ``strutils.wordwrap`` measure word with by counting the runes in a word? I personally think it is a better default, but ``strutils`` is not a unicode aware library.

**Comment by skilchen** [comment]
@araq wrote:
> Wrong, Unicode effectively is a variable length encoding, even if you use UTF-32. Google "combining characters" if you don't believe me.

Nim doesn't handle "combining characters" properly in its `unicode.nim` and also in the new `wordwrap.nim` proposed by @krux02:
```nim
import unicode, std/wordwrap
var a = "I\u0305V\u0305" # some people use this as roman numeral for 4000
echo len(a)
echo len(toRunes(a))
echo wordWrap(a, 2)
```
produces:
6
4
I̅
V̅

instead of:
6
4
I̅V̅

I admit that there are many languages having the same limitation, one notable exception is elixir (and its parent erlang). `String.length("I\u0305V\u0305")` in elixir returns 2 (as expected: I overlined and V overlined).

In a perfect world, `wordWrap` and the other unicode-aware functions would operate on `graphemes` (or `glyphs` or whatever they are called) and not on `codepoints`.

**Comment by krux02** [comment]
Editing unicode text is an art form of it's own. I would honestly prefer if the development of unicode aware functionality would be developed in a nimble package. Then word wrap can be developed in an arbitrary way without the deed to discuss it with anybody. The standard library would then just provide the bare bone basics, such as classification and iterators.

**Comment by Araq** [comment]
In the devel version of ``std / wordwrap`` it produces what you're after

```
6
4
I̅V̅
```

**Comment by skilchen** [comment]
excellent! thank you!
