### ISSUE TITLE
toPy converter in nimborg causes ICE

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#3529]
```
clone https://github.com/micklat/NimBorg.git
cd NimBorg/nimborg/py/test
nim c test_py.nim
```

Output:

```
/Users/yglukhov/Projects/NimBorg/nimborg/py/high_level.nim(107, 19) Error: internal error: metatype not eliminated
```

**Comment by dom96** [comment]
I've got a fork that should make reproduction easier, simply clone it and check out this commit https://github.com/dom96/NimBorg/commit/f730b4908128f541e5d038c2d90ab58050167535. Then compile the test that @yglukhov showed.

**Comment by Araq** [comment]
I forked NimBorg too to work around this bug which proved hard to fix.

**Comment by krux02** [comment]
I just tested it, this is the output:

```
../low_level.nim(1663, 5) Error: invalid expression: 
finally:
  lib = nil
```

I don't know if this qualifies as fixed, since I don't know what the expectation of the output is, but it is not a crash anymore. @yglukhov please provide some more details in the issue of what you expect so that this issue can either be closed or properly fixed.

**Comment by Araq** [comment]
Unclear and I'm sure the real problem is also reported somewhere else.
