### ISSUE TITLE
Add support for asm.js type annotations in the JS codegen

### ISSUE THREAD

**Issue by zah** [nim-lang/Nim#371]
There are number of efforts to make JavaScript a target run-time for statically typed languages (like Nimrod). We should provide options for exploiting these opportunities.
https://blog.mozilla.org/luke/2013/03/21/asm-js-in-firefox-nightly/

**Comment by ozra** [comment]
This would be an awesome feature. But it's a _very_ tricky road!

Current state:

For _V8 TurboFan_ (next-gen JIT after Crankshaft) (important for io/node.js) even partial asm.js would be beneficial (the type notation part) - _in the future_ - since they opt for benefiting from the general use patterns rather than the asm.js standard (possibly "not invented here" syndrome). But so far (it's still alpha) in my tests TurboFan yields slower code on most things, and only equal speed when doing the asm.js notation (manually in my test)

_Mozilla Odin_  ofcourse benefits greater (atm), but _only if the spec is followed full through_, and then you have to generate the closure with a de-facto heap passed in, since _garbage collection is turned off_ in "asm.js mode", which would mean implementing nim gc on a array-based heap, which would not work anyway, because as @reactormonk notes: anything but numbers throws off the opt-mode.

Anyways - _why doesn't Nim target **emscripten** and get all for free?_ - could reduce workload on JS backend greatly? _Qoute from site:_
> "Practically any portable C or C++ codebase can be compiled into JavaScript using Emscripten, ranging from high performance games that need to render graphics, play sounds, and load and process files, through to application frameworks like Qt."

**Comment by def-** [comment]
I think emscripten is the way to go. It works already, supports asm, has far fewer bugs than Nim's JS backend. The only thing missing is the GC. I've heard emscripten has a thin Boehm-like GC, so we should probably try to use that.

**Comment by kirbyfan64** [comment]
Interestingly, PyPy.js uses Emscripten and works perfectly.

**Comment by alehander42** [comment]
this doesn't seem to be too relevant these days, having a wasm backend seems to be a better long term solution: can we close this issue?

**Comment by krux02** [comment]
Well as long as the wasm isn't in the roadmap in favor of asm.js, this isn't a solved issue.

**Comment by alehander42** [comment]
is there a roadmap? wasm seems as a better target to focus on these days
