### ISSUE TITLE
install.sh does not copy compiler sources

### ISSUE THREAD

**Issue by Xe** [nim-lang/Nim#3737]

**Comment by dom96** [comment]
Question is: should the compiler sources be a part of the standard library or a Nimble package (like they are now).

Nimble assumes that they are in the ``$nim`` directory, which is the case when you simply clone the Nim git repository, bootstrap Nim and then add ``$nim/bin`` to your PATH. Unix people prefer to use install.sh though, which spreads the Nim files in a lovely way all over ``/usr/bin`` and ``/usr/lib`` without copying the compiler sources since they are technically not a part of the Nim standard library. This is a bit of a hack and I apologise for it.

Thankfully users of Nim who do that should now be able to install Nimble anyway, thanks to my brilliant new installation instructions which I just pushed to Nimble's repo ;)

All that remains is the all important decision from @Araq.

**Comment by Xe** [comment]
Once nimble is bootstrapped though you can just `nimble install compiler` and be done.

**Comment by Araq** [comment]
nimble is part of the core now.
