### ISSUE TITLE
Private field is not resolved properly in templates

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#3770]
``` nim
# a.nim
import b, c
var f: Foo
let nb = newBar(f.field)
```

``` nim
# b.nim
type Bar* = tuple[x: int]
template newBar*(b: int): Bar = (x: b).Bar
```

``` nim
# c.nim
type Foo* = object
    mField: int
template field*(f: Foo): int = f.mField
```

Error:

```
$ nim c a.nim
a.nim(4, 16) template/generic instantiation from here
c.nim(4, 33) Error: undeclared field: 'mField'
```

**Comment by Araq** [comment]
Symbol lookup in templates does not consider typing. That's not a bug but certainly something we could improve.

**Comment by yglukhov** [comment]
Hrm, well it surely seems like a pretty critical bug to me. Because of this bug you can't safely convert a proc to a template. Also consider the following modification of a.nim:
```nim
var f: Foo
let tempField = f.field # works
let nb = newBar(tempField) # works
let wtf = newBar(f.field) # wtf!
```
Nightmare to metaprogramming, really!

**Comment by Araq** [comment]
> Because of this bug you can't safely convert a proc to a template.

Well we never claimed that you can "safely" convert a proc to a template.

**Comment by Menduist** [comment]
Hit this today:
```nim
# moda.nim
type
  Noice* = object
    hidden: int
  
template jjj*: Noice =
  Noice(hidden: 15)

# modb.nim
import moda
echo jjj() # works

proc someGeneric(_: type) =
  echo jjj() # fails: "Error: the field 'hidden' is not accessible."

someGeneric(int)
```

It works if `jjj` takes a `typed` parameter. But in my full project, can't find a good workaround

My understanding from the manual is that this should work:
"The bind statement [...] can be used to explicitly declare identifiers that should be bound early (i.e. the identifiers should be looked up in the scope of the template/generic definition)
But a bind is rarely useful because symbol binding from the definition scope is the default"

Is this wrong? Should `hidden` be exported?

**Comment by Araq** [comment]
Object fields are not subject to "bind" or its rules but there is a different mechanism ("friend modules") that is supposed to deal with this case automatically.

**Comment by ringabout** [comment]
The original example seems to have been fixed? I didn't reproduce it on windows.
