### ISSUE TITLE
block as expression without parentheses

### ISSUE THREAD

**Issue by ephja** [nim-lang/Nim#3827]
``` nim
var i = (block: 1)
var j = if true: 1 else: 2
```

A parenthesis pair is necessary for the `block` expression, but not for the `if` expression. Is this intended?

**Comment by bluenote10** [comment]
+1 It would be much more idiomatic if it was possible to write:
```nimrod
let y = block:
  let x = 5
  echo "hi"
  x * x
```
instead of the currently required syntax:
```nimrod
let y = (block:
  let x = 5
  echo "hi"
  x * x
)
```
Because of the unexpected syntax, I though for a long time that `block` can't be an expression. And I'm not alone, see the forum thread [Why block is not an expression](https://forum.nim-lang.org/t/2201). The thread also contains some good ideas for workarounds.
