### ISSUE TITLE
Add `->` and `=>` syntax to the compiler

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3840]
These macros are very handy, so it's better to have them as a standard language constructions.

The discussion is here (from 10:00:33): http://irclogs.nim-lang.org/05-02-2016.html

**Comment by dom96** [comment]
:+1:

**Comment by Varriount** [comment]
Doesn't this essentially make '->' and '=>' useless for others though? The permissive nature of the 'expr' parameters means that the compiler will ignore other overloads:

test_other.nim
```
proc `->`*(a, b: int): int =
  result = (a+b) div 2
```

test.nim:
```
import future, test_other
echo(1 -> 2)
```

Running test.nim above gives me a compiler error, as the anonymous procedure macro is being used instead of the averaging procdure.

**Comment by JesseTG** [comment]
How the hell is `x -> y` supposed to connote the idea of an average?

**Comment by Araq** [comment]
@Varriount ``->`` only matches better because it's immediate. But when we move it into the compiler it would actually only match in a type context, so it would work better.

**Comment by Varriount** [comment]
@JesseTG It's an example? The code really doesn't matter. The purpose is to point out that the anonymous procedure macro overshadows other uses of the `->` operator.

**Comment by JesseTG** [comment]
Oh, ok, that makes sense.

**Comment by Araq** [comment]
Nowadays I think these arrows have been a mistake.
