### ISSUE TITLE
Compiler messages should include suggestions

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3914]
I saw somebody on IRC in #pony-lang write that "Elm pretty much sets the bar for compiler error messages.". I agree:

http://elm-lang.org/blog/compiler-errors-for-humans

Let's improve Nim's error messages to include helpful suggestions.

**Comment by abudden** [comment]
I couldn't agree more (see also #4210).  I've just read the elm blog and I'm very impressed - clear and explicit.  The json output they have could be really useful for IDEs as well.

**Comment by blaiseli** [comment]
May I suggest that compiler errors also include a link to documentation about the error? I'm trying to learn Nim (I was hoping to use it as a replacement for Python when speed matters), but I'm struggling doing the most basic things (well, "most basic" from my mostly Python background) for the moment, and part of the issue is that I have a hard time finding examples and explanations about how things work in Nim.

The "undeclared identifier" error message at first seemed obvious to me, but when I looked at my code, I was (and still am) puzzled, so I guess there's some subtlety about what an identifier is, and what "declaring" means:

```
  var outfiles = tbl.newTable[string, File]()
  if inFastqFilename != nil:
    var fh = open(inFastqFilename)
    var fs = newFileStream(fh)
    var inputFqs = toClosure(parseFastqs(fh))
  else:
    var inputFqs = toClosure(parseFastqs(stdin))
  demultiplex(inputFqs, outfiles)  # undeclared identifier: 'inputFqs'
```

The last line of the above piece of code results in `Error: undeclared identifier: 'inputFqs'`, but it seems to me that I "declared" `inputFqs` in every possible execution path preceding its usage. Same error if I use `let` instead of `var`. What is happening?

The code compile if I remove the branches:
```
  var outfiles = tbl.newTable[string, File]()
  # if inFastqFilename != nil:
  #   var fh = open(inFastqFilename)
  #   var fs = newFileStream(fh)
  #   let inputFqs = toClosure(parseFastqs(fh))
  # else:
  #   let inputFqs = toClosure(parseFastqs(stdin))
  let inputFqs = toClosure(parseFastqs(stdin))
  demultiplex(inputFqs, outfiles)
```
(Also compiles with a `var`.)

So I suppose that if I want to set the value of `inputFqs` in two different places in the execution path, I need to declare this as a `var` before (and only in one place). But then I get into other trouble involving `attempting to call undeclared routine: 'inputFqs'` inside the body of `demultiplex`:

```
# [...]
# https://stackoverflow.com/a/35697846
template toClosure(inlineIterator): auto =
  ## Wrap an inline iterator in a first-class closure iterator.
  iterator closureIterator: type(inlineIterator) {.closure.} =
    for elem in inlineIterator:
      yield elem
  closureIterator


proc demultiplex(inputFqs: iterator, outfiles: tbl.TableRef[string, File]) =
# [...]
   for fastq in inputFqs():  # attempting to call undeclared routine: 'inputFqs'
# [...]
when isMainModule:
# [...]
  var outfiles = tbl.newTable[string, File]()
  var inputFqs: iterator {.closure.}
  if inFastqFilename != nil:
    var fh = open(inFastqFilename)
    var fs = newFileStream(fh)
    inputFqs = toClosure(parseFastqs(fh))
  else:
    inputFqs = toClosure(parseFastqs(stdin))
  demultiplex(inputFqs, outfiles)
```

I'm confused again by this "declaring" notion. The argument of a procedure does not need to be "declared", does it? So what does "declaring" mean in this context?

I had encountered this same error message [previously](https://stackoverflow.com/q/48260487/1878788), on the same `parseFastqs` iterator, and the solution was the `toClosure` trick, but it is apparently not enough here.

Thanks for any help, here or on stackoverflow.

**Comment by Yardanico** [comment]
@blaiseli don't forget that you have a new scope in if body, you can read about that in manual or tutorial

**Comment by GULPF** [comment]
@blaiseli 
Like most other languages (but unlike Python), Nim is block scoped which is the cause of your first error. You can read about here: https://nim-lang.org/docs/manual.html#modules-scope-rules.

I am a bit surprised that `var inputFqs: iterator {.closure.}` compiles at all. For me it gives `internal error: getTypeDescAux(tyBuiltInTypeClass)`. I _think_ (it's not documented, so not sure) that `iterator` is a type class, not a concrete type that can be used for variables. Read about type classes here: https://nim-lang.org/docs/manual.html#generics-type-classes. That said, you shouldn't need to declare the type at all. Something like this should work:
```nim
  var inputFqs =
    if inFastqFilename != nil:
      var fh = open(inFastqFilename)
      var fs = newFileStream(fh)
      toClosure(parseFastqs(fh))
    else:
      toClosure(parseFastqs(stdin))
```

Btw, you can use ```nim when starting a code block on github to get proper syntax highlighting.

**Comment by blaiseli** [comment]
@Yardanico @GULPF Thanks. That explains the "undeclared identifier" error. This is what I got to suspect after experimenting more. I had forgotten about [the relevant passage of the tutorial](https://nim-lang.org/docs/tut1.html#control-flow-statements-scopes-and-the-block-statement), that I read a few weeks a go.

**Comment by blaiseli** [comment]
@GULPF Maybe the "attempting to call undeclared routine" error I get comes before the `getTypeDescAux(tyBuiltInTypeClass)` you observe.

Your suggestion indeed makes the code pass compilation. Good to know this kind of variable initialization is possible.

**Comment by dom96** [comment]
@blaiseli Thank you for sharing your problems. This is the sort of thing we need to make Nim's error messages better. I plan to spend some time going through these kinds of reports and making the errors better, sadly there are always [higher priority issues](https://github.com/nim-lang/Nim/issues?q=is%3Aopen+is%3Aissue+label%3A%22High+Priority%22) to take care of so it may be a while yet before I get a chance to do that.

**Comment by Araq** [comment]
This issue is way too broad. You might as well say "I just read that C++ produces good assembler code, so lets improve Nim's produced C++ code".

Also, there are plenty of more concrete issues open with the "error messages" tag and error messages are constantly improved.
