### ISSUE TITLE
Local packages like in Go

### ISSUE THREAD

**Issue by zzz125** [nim-lang/Nim#4059]
Can nim have (local) packages like in golang?

It helps greatly when you want to import anything from anything and work mostly inside one package ("package main" for instance).

Another benefit is what you don't have to export every function, method, type etc with asterisk.

Also I tried to emulate this with "include foo" derictive but it seems like it doesn't work with cyclic dependencies and in general feels like a hack (you have to "include" every file in your main.nim)

example how packages work in go: http://stackoverflow.com/a/28390584

**Comment by singularperturbation** [comment]
The forum might be a better place for this, since others might have different / better ideas.  

AFAIK, there isn't a one-to-one analog to package structure in Go, since in Nim modules are specific to a file.  However, if you wanted to recreate something like this in your own project, it's easily doable with a macro and a standard file in each "package" (like `__init__.py` in Python) that defines what modules should be exported from the "package" by default.

```nim
import strutils
from macros import nnkStrLit, strVal, quote, expectKind

macro importPkg(packageDir: string): stmt =
  packageDir.expectKind(nnkStrLit)
  # Can't do something like __init__.nim since not valid module name
  let modName = "$1/pkg_init".format(packageDir.strVal)
  result = quote do: import `modname`

importPkg "submod"

proc main() =
  echo foo
  echo bar
  doStuff()

when isMainModule:
  main()
```
Where we have:
```shell
~/p/n/modtest> ls submod
fileA.nim  fileB.nim  pkg_init.nim
~/p/n/modtest> cat submod/fileA.nim 
# Import messes up scope
include pkg_init

var foo* = "HEY"

proc doStuff*()= echo "Package value of bar is: " & bar

when isMainModule:
  doStuff()

~/p/n/modtest> cat submod/fileB.nim
include pkg_init 
var bar* = "YO"
~/p/n/modtest> cat submod/pkg_init.nim 
import fileA,fileB
export fileA,fileB
ssimmons@unfraggable3 ~/p/n/modtest> nim c -r main.nim 
Hint: system [Processing]
Hint: main [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: macros [Processing]
Hint: pkg_init [Processing]
Hint: fileA [Processing]
Hint: fileB [Processing]
Hint:  [Link]
Hint: operation successful (13343 lines compiled; 0.218 sec total; 18.184MB; Debug Build) [SuccessX]
HEY
YO
Package value of bar is: YO
~/p/n/modtest> 
```

Within the package itself, you would just do:
```nim
#fileA or fileB
include pkg_init
```
and everything should 'just work' as far as scope when doing things internal to the package.  You could use a macro to alias `pkgDef` or some other shorthand to `include pkg_init`, or create a build tool to build the `pkg_init` automatically based on the files in each directory.

This is pretty fragile/finicky as-is, but should give you a good place to start.

**Comment by Araq** [comment]
There are no plans to change/support this anytime soon.
