### ISSUE TITLE
times.initInterval is a bit broken

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4076]
``` nim
import times
type
  Human = object
    name: string
    age: int

proc initHuman(name: string, birthday: Time): Human =
  var age = initInterval(seconds = getTime() - birthday).years
  return Human(name: name, age: age)

var foo = initHuman("foo", parse("05/10/1987", "dd/MM/yyyy").toTimeInfo)
echo foo # Age is 0
```

@coffeepots maybe you could take a look at this?

**Comment by coffeepots** [comment]
@dom96 I think this is because initInterval mods it's parameters individually, so you're only getting the seconds mod 60. No other fields are set because, whilst it uses the carryO variable to carry over overflowing parameters, it resets this overflow variable for each parameter. So, if you pass in 2000 milliseconds, it would add 1 second to the 'seconds' parameter. However, then the carryO variable is reset to the div 60 of seconds. I'm not sure if this is intentional or not.

The end result is that when you get the years out, it's zero. If you echo the value of the initInterval call, you'll get zero for all fields except seconds.

To make initInterval smarter, the carrying mechanism should take into account the total summed value of the inputs and work with that. The trouble is, as always, months are a variable length so I don't know how you'd get an accurate figure out of this.

The real question is, should this be how initInterval works? Should it be - as it is now - a way to manually set the fields of a TimeInterval, or should it do the extra work so you can use it as you want?

Moving on, perhaps what you actually want to do is this?

```
  proc initHuman(name: string, birthday: Time): Human =
    var age = getTime().toTimeInterval - birthday.toTimeInterval
    return Human(name: name, age: age.years)  # returns age as 29
```

TimeInterval is interesting here. These are the values I get out from this calculation, using the current time.
`(milliseconds: 0, seconds: 16, minutes: 12, hours: 16, days: 2, months: -6, years: 29)`
So just glancing at it, it appears each element is calculated as a diff separately, hence the negative value for months.

Incidentally I just realised I missed off a depreciated from TimeToTimeInterval for the windows section.

**Comment by dom96** [comment]
Thank you for looking into it. The question of whether ``initInterval`` should be smart is a good one, I think it would be very handy if it was but it may be useful to look at what other language's provide. Please look into that if you've got some time :)

**Comment by GULPF** [comment]
This can be closed, it's the intended behaviour of `TimeInterval`. Conversion between different time units is now done with the proc `convert`, added #6978.
