### ISSUE TITLE
Cannot use emit for gensymed variables

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4202]
In both cases in the sample below Nim outputs `:tmp` instead of the actual name. Perhaps I'm doing something wrong and there is a correct way to do this?

``` nim
import macros, strutils

macro genTrue(): untyped =
  let sym = genSym(nskVar)
  result = quote do:
    var `sym`: bool
    {.emit: "`$#` = true;".format(astToStr(`sym`)).}
    `sym`

macro genTrueTwo(): untyped =
  let sym = genSym(nskVar)
  let symStr = $sym.symbol
  result = quote do:
    var `sym`: bool
    {.emit: "`$#` = true;".format(`symStr`).}
    `sym`

proc main() =
  var a = genTrue()
  echo a

  var b = genTrueTwo()
  echo b

main()
```

**Comment by andreaferretti** [comment]
I am not sure what you are trying to do. I offer some comments that my be of help:

* `:tmp` may very well be the gensymmed name. In fact, I think that `genSym` returns `:tmp` + an incrementing id, because it is a simple way to generate fresh names
* variable names are in general mangled when compiling to C. This is needed to support more than one instantiation for the same code (think macros, generics and so on). I think that Nim now does not mangle local variables, but I am not sure
* `:tmp` is certainly not a valid C identifier, so there is no chance that directly writing `:tmp = true` in the generated C would work - that is, Nim will need to mangle this variable to avoid generating invalid C code

It seems to me that you are using `emit` to generate C code that is not valid - maybe if you clairfy your intended use case, I can be of more help

**Comment by endragor** [comment]
Thanks for your comments, I'm well aware of all of that. As for your first comment, even if `:tmp` is the gensymmed name, the backtricks (`) within emit statement are supposed to transform the Nim name into its codegenerated counterpart (that is mangled).

The question is simple - how to use the gensymmed variable in emit pragma to output its codegenerated name.

This sample is a bit more correct by the way, but still doesn't work (Nim outputs `:tmp169015` instead of the codegenerated name, which is `colontmp_`):
```
import macros, strutils

macro genTrue(): untyped =
  let sym = genSym(nskVar)
  template gen(s): untyped =
    var s: bool
    {.emit: "`$#` = true;".format(astToStr(s)).}
    s
  result = getAst(gen(sym))

proc main() =
  let b = genTrue()
  echo b

main()
```

**Comment by zah** [comment]
@endragor, this is much easier than you think.

``` nim
proc codegenName(e: auto): cstring {.importcpp: "\"#\"".}

var y = 10

proc test =
  var x = 10
  echo x.codegenName
  echo y.codegenName

test()
```

Outputs:

```
x
y_M9ahA9cHr9cSM9bLXg6FI9csPlQ
```
`x` stays `x`, because it's a local variable.

**Comment by endragor** [comment]
Thanks @zah, I was interested in emitting the names produced by genSym specifically. But @Araq told me already that this is correct way:
```nim
import macros

macro genTrue(): untyped =
  let sym = genSym(nskVar)
  template gen(s): untyped =
    var s: bool
    {.emit: [s, " = true;"].}
    s
  result = getAst(gen(sym))

proc main() =
  let b = genTrue()
  echo b

main()
```
And this does work indeed. Thanks everyone :)

**Comment by zah** [comment]
if you want to have a "true" as a literal for some reason, here is an alternative way:

```
type cbool {.importcpp: "bool".} = object
var  ctrue {.importcpp: "true", nodecl.}: cbool
var  cfalse {.importcpp: "false", nodecl.}: cbool

proc test =
  var a: cbool
  a = ctrue
```

This produces the following code:

```
N_NIMCALL(void, test_uMRS7vA8aL25wlC9bTxtPQQ)(void) {
	bool a;
	nimfr_("test", "c1.nim")
	nimln_(16, "c1.nim");
	a = true;
	popFrame();
}
```

**Comment by endragor** [comment]
No, that was just a sample, the actual use case was more complex, and I don't remember which it was, to be honest. It occurred when implementing [nimue4](https://github.com/pragmagic/nimue4) and I probably workarounded it at that time.

**Comment by endragor** [comment]
Thanks for your support guys, it's very much appreciated!
