### ISSUE TITLE
strtabs.getOrDefault is inconsistent with tables.getOrDefault

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4265]
The former returns `""` when key is not found, latter returns `nil`.

**Comment by Araq** [comment]
I know. I like it this way. Changing it would break code. :P

**Comment by dom96** [comment]
Time to break this :)

**Comment by cooldome** [comment]
I am suggesting to change table signature from `proc getOrDefault[A, B](t: Table[A, B]; key: A): B` to `proc getOrDefault[A, B](t: Table[A, B]; key: A, value = default(B)): B`. In this way Table will  be generic enough replicate strtabs behavior if necessary. It was many cases that I wanted to return -1 when value not found and not 0, or particular string instead of null.

**Comment by dom96** [comment]
@cooldome that sounds like a good idea.

**Comment by dom96** [comment]
Seems that ``value = default(B)`` doesn't work. @Araq says it's a bug.

**Comment by dom96** [comment]
I've fixed the inconsistency in any case. We can add the ``default`` for ``tables`` later without breaking anything.

**Comment by dom96** [comment]
So after doing this the [bootstrapping broke](https://travis-ci.org/nim-lang/Nim/jobs/342858650#L1070). I think I'm inclined to agree with @Araq here, this consistency isn't necessary. I will revert it and keep this issue closed.
