### ISSUE TITLE
`times` doesn't seem to be able to handle colon-less offsets?

### ISSUE THREAD

**Issue by Gastove** [nim-lang/Nim#4347]
Hallo! I'm trying to parse times in RFC-822 format like `Thu, 16 Jun 2016 04:16:41 +0000`. As best as I can tell, the parse syntax in `times` can't handle the UTC offset not containing a colon:

```
var parsed = parse("Thu, 16 Jun 2016 04:16:41 -1100", "ddd, dd MMM yyyy hh:mm:ss zzzz")
echo format(parsed, "ZZZ") # prints "PDT", my local timezone

var parsed = parse("Thu, 16 Jun 2016 04:16:41 -0000", "ddd, dd MMM yyyy hh:mm:ss zzzz")
echo format(parsed, "ZZZ") # prints "PDT" again

var parsed = parse("Thu, 16 Jun 2016 04:16:41 +0700", "ddd, dd MMM yyyy hh:mm:ss zzzz")
echo format(parsed, "ZZZ") # still PDT
```

(The rest of the string is parsed correctly.)

Am I missing something? Derping? Found a bug?

**Comment by cheatfate** [comment]
Using this code:
import times

```
var parsed: TimeInfo
parsed = parse("Thu, 16 Jun 2016 04:16:41 -1100", "ddd, dd MMM yyyy hh:mm:ss zz")
echo("==========")
echo(repr(parsed))
echo format(parsed, "ZZZ")
parsed = parse("Thu, 16 Jun 2016 04:16:41 -0000", "ddd, dd MMM yyyy hh:mm:ss zz")
echo("==========")
echo(repr(parsed))
echo format(parsed, "ZZZ")
parsed = parse("Thu, 16 Jun 2016 04:16:41 +0700", "ddd, dd MMM yyyy hh:mm:ss zz")
echo("==========")
echo(repr(parsed))
echo format(parsed, "ZZZ")
```

and result is:

```
==========
[second = 41,
minute = 16,
hour = 4,
monthday = 16,
month = mJun,
year = 2016,
weekday = dThu,
yearday = 167,
isDST = true,
tzname = 00000000001801D8"FLE Daylight Time",
timezone = -11]

FLE Daylight Time
==========
[second = 41,
minute = 16,
hour = 4,
monthday = 16,
month = mJun,
year = 2016,
weekday = dThu,
yearday = 167,
isDST = true,
tzname = 00000000001804B0"FLE Daylight Time",
timezone = 0]

FLE Daylight Time
==========
[second = 41,
minute = 16,
hour = 4,
monthday = 16,
month = mJun,
year = 2016,
weekday = dThu,
yearday = 167,
isDST = true,
tzname = 0000000000180788"FLE Daylight Time",
timezone = 7]

FLE Daylight Time
```

So, looks like parsing UTC offset without colon is works properly, but format("ZZZ") is still wrong.

**Comment by cheatfate** [comment]
Fast looking on times.nim code reveal one more bug, `timezone` must be in seconds, but not in hours.
Because there are many UTC timezone offsets which are not only in hours..
[https://en.wikipedia.org/wiki/List_of_UTC_time_offsets](https://en.wikipedia.org/wiki/List_of_UTC_time_offsets)

Comment here looks correct.
[https://github.com/nim-lang/Nim/blob/devel/lib/pure/times.nim#L158-L159](https://github.com/nim-lang/Nim/blob/devel/lib/pure/times.nim#L158-L159)

But parse() code supports only first 2 symbols of timezone offset, and not converting it to seconds.

**Comment by samdmarshall** [comment]
I'm having this same problem, where i need to output an RFC822 valid date and the timezone formatting is not correct. the [specification](https://www.w3.org/Protocols/rfc822/#z28) outlines:

```
zone        =  "UT"  / "GMT"                ; Universal Time
                                            ; North American : UT
            /  "EST" / "EDT"                ;  Eastern:  - 5/ - 4
            /  "CST" / "CDT"                ;  Central:  - 6/ - 5
            /  "MST" / "MDT"                ;  Mountain: - 7/ - 6
            /  "PST" / "PDT"                ;  Pacific:  - 8/ - 7
            /  1ALPHA                       ; Military: Z = UT;
                                            ;  A:-1; (J not used)
                                            ;  M:-12; N:+1; Y:+12
            / ( ("+" / "-") 4DIGIT )        ; Local differential
                                            ;  hours+min. (HHMM)
```

that the formatting needs to be without the colon that gets added as a separator for the hours and minutes units of the digits. after looking over the source code for the `times` module, it looks like this should be fairly simple to accommodate using a single new format pattern that renders the abbreviated time zone name, or add capitalized versions of the existing `z`/`zz`/`zzz`/`zzzz` patterns that remove the colons.

(given the high prevalence of this particular RFC, i think this should be prioritized as it would be sufficient reason to pass over using the language. a quick look over existing nimble packages i don't see anything that solves this problem either; so i guess the community really doesn't do a lot of date-time programming.)

**Comment by narimiran** [comment]
> I'm having this same problem, where i need to output an RFC822 valid date and the timezone formatting is not correct.

Can you please show us your code, i.e. the example of incorrect formatting? Also the current output vs the desired output. (The original examples in this issue are outdated)

EDIT: Nevermind, I've made the original examples to work and/or to show the problem.

**Comment by samdmarshall** [comment]
> Can you please show us your code, i.e. the example of incorrect formatting? Also the current output vs the desired output. (The original examples in this issue are outdated)

sorry, i thought it was absolutely clear given i pasted the relevant part of the spec (in addition to the issue title): the incorrect formatting is the inclusion of the colon separators between the hour and minute digits (and between the minute and second digits where relevant). i've never seen an implementation that has included colons in the timezone offset, hence my surprise about this - but i realize that might not be apparent to people that haven't worked in this space before.

additionally the comments from cheatfate are all correct, thought i didn't check to see if they are still things that need to be fixed or not now. there are a few zones that have offsets that cannot be represented in whole hour or whole minute units, so that is why it be represented in seconds. you should be able to look at the code in ICU if you need a model to work from.

**Comment by narimiran** [comment]
@samdmarshall #17318 is now merged: if you're on Nim devel, you can use `ZZZ` and `ZZZZ` for `+0300` and `+030000`, respectively.

**Comment by Araq** [comment]
I consider this to be fixed.
