### ISSUE TITLE
Inconsistencies in httpclient, asynchttpserver

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4423]
Data types and field names should really be unified across http modules. Here are a couple of things that managed  to trip me up today, while I was trying to implement a simple http proxy (with httpclient and asynchttpserver):

Http headers are sometimes represented as `StringTableRef`, and sometimes as `HttpHeaders` (which is a wrapper for `TableRef[string, seq[string]]`). There is no nice way to convert between two. You can do this:
```nim
let strTable = newStringTable(
  seq[(string, string)](
    toSeq(pairs(httpHeaders))))
let httpHeaders = newHttpHeaders(
  seq[(string, string)](
    toSeq(pairs(strTable))))
```
Not only is this awful - the second part actually loses data, as far as I can tell.

httpclient returns HTTP status code/reason phrase as a string (`status` field in `Response` type), but asynchttpserver expects a `HttpCode` enum value. There is no proc to convert a `string` to `HttpCode`, however. One could use something like this, of course:
```nim
let httpCode = HttpCode(response.status)
```
and it would even work - unless the server attempts to return a code that is not in `HttpCode`, or with a non-standard or missing reason phrase (all perfectly valid use cases). Seems like a better solution would be something like this:
```nim
type
  HttpStatusCode = range[100..999]
  HttpReasonPhrase = string
  HttpStatus = tuple[code: HttpStatusCode, reason: HttpReasonPhrase]
```
with constants for oft-used statuses.

HTTP method handling takes the cake. asynchttpserver uses strings like `"put"` and `"get"` (yes, lowercase). There is a HttpMethod enum (it is not a valid representation - custom HTTP methods are allowed by RFC). And some procs in httpclient receive a `string` (as an escape hatch) - however, not something like `"GET"`, or even `"get"` - you are supposed to pass `"httpGET"` (first four chars actually don't matter - they are thrown out). Of course, this last bit is not documented anywhere (barring a closed year-old issue), and if you pass in something else (like `"GET"`) it does not throw an error.

**Comment by nigredo-tori** [comment]
Also, `HttpHeaders` stores header names as lowercase, which makes reusing headers way harder than it should be...

**Comment by nigredo-tori** [comment]
One more annoyance: Uri is an object (not a ref), meaning it has default `$` proc. So if you try to convert it to string without importing corresponding module, you don't get a compile-time error - instead you would have to debug your program.

**Comment by andreaferretti** [comment]
I can also add:

* synchronous HTTP client methods accept a parameter `extraHeaders`, which unfortunately is a `string` and not a `HttpHeaders`. Moreover, there is no obvious way procedure in the stdlib to convert `HttpHeaders` to their string representation for use here
* asynchronous HTTP client methods do not even have a parameter to set headers

What I am doing now is to add the following

```nim
proc `$`*(headers: HttpHeaders): string =
  result = ""
  for k, v in headers:
    result &= ("$1: $2\c\L" % [k, v])
```
 but this is of no help with asynchronous clients

**Comment by dom96** [comment]
> you are supposed to pass "httpGET" (first four chars actually don't matter - they are thrown out).

You make it seem as if this was by-design, this is most certainly a bug.

**Comment by dom96** [comment]
Hopefully I didn't miss anything.

**Comment by andreaferretti** [comment]
I quickly skimmed the new version of `httpclient`, and I have a few comments.

First, it seems that all old procedures are deprecated. There are now two type of clients with the same operations: `HttpClient` and `AsyncHttpClient`. So far, so good. But it seems that in both cases one gest a `Future`, which seems to defeat the purpose of having a synchronous client. Am I missing something?

Second, I see that the new procedures do not have any way to set headers at all, while the previous ones took a `extraheaders` string - it was inconvenient but one could at least set custom headers.

Third, it seems that GET and POST requests have a custom logic to follow redirects. Is there a reason why this does not happen for the more general `request` proc, so that all HTTP methods benefit from it? What if one wants to do PUT and needs to follow redirects?

In general, it seems to me that `httpclient` is getting better and more consistent, but there may still be some issues to iron out.

**Comment by nigredo-tori** [comment]
@andreaferretti , I didn't have the chance get deep into the new version yet, but, as far as I see:

1. There's the new `multisync` macro, which generates two procs (sync and async) from one definition. This strips `Future` from the result in sync version.
2. Seems like the headers are in the client now, in both versions.

**Comment by dom96** [comment]
> Third, it seems that GET and POST requests have a custom logic to follow redirects. Is there a reason why this does not happen for the more general request proc, so that all HTTP methods benefit from it? What if one wants to do PUT and needs to follow redirects?

The idea is that ``request`` performs a single request and gives the result. There may be cases where you do not want to follow redirects, or you may want some other custom logic for redirects.

For PUT requests we should introduce a ``put`` procedure, so that it's consistent with ``get`` and ``post``. For now you can easily follow redirects yourself.

As for your other points @nigredo-tori answered them well.

**Comment by andreaferretti** [comment]
Great, I did not know about the `multisync` macro! :-)

The only thing left that I don't find very nice is the fact that headers have to be set in the client, for two reasons. First, conceptually headers are something that belongs to the single request, not to the client - they are in effect part of the request. Second, there is no way to pass the headers when creating the client, so the only way to set them is to assign the client to a `var` and then manually mutate the headers, which is not great.

For the case where headers are the same for all requests, it is useful that one can set them once on the client, thereby decreasing the allocations, but there should be more control per request.

My proposal is:

* headers can be passed when making a request
* as an optimization, a default can be set on the client

This would amount to adding a `headers` parameter both when creating the client (with default `newHttpHeaders()`) and when making a request (with default `nil` - in which case, use the headers on the client).

What do you think?
