### ISSUE TITLE
JS codegen - indexing into cstring.

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#4470]
While poking around pegs for #4247 , I discovered that indexing into `cstring` is implemented incorrectly in JS. Take the following code:

``` nim
let s: cstring = "hello"
let c = s[0]
```

It is translated into something like this:

``` javascript
var s_123 = "hello";
var c_123 = s_123[0];
```

Notice that, even though in Nim code `c` is a char (represented internally as a number), `c_123` is now a `String` "h". Given the permissiveness of JS, this is bound to result in nasty bugs.

This behaviour seems to be relatively easy to fix (in proc `genArrayAccess` in jsgen - enough to use something like `charCodeAt`). However, there is a less clear-cut issue: `char` should not be used at all when indexing into cstring in JS! Since JS Strings use UTF-16, `charCodeAt` returns a value in `range[0..65535]`.

Actually, while writing this issue, I have found another bug, related to this problem: https://github.com/nim-lang/Nim/blob/ec7d556c208725f336ff626c7be299cc14638e92/lib/system/jssys.nim#L200 . Here the Nim `string` (internally an `Array` of numbers in `range[0..255]`) is filled with numbers that might be outside this range.

**Comment by yglukhov** [comment]
Regarding the first issue, I can see no 100% correct way of indexing `cstring` in JS. There's a note in the [tutorial](http://nim-lang.org/docs/tut2.html#compilation-to-javascript) that cstring is a JS string. Possible solutions:
1. Add a note to the tutorial that "indexing should be avoided unless you know what you're doing".
2. Disallow indexing operator, and thus produce a compile-time error.
3. Change indexing operator type to some 16-bit type and use `charCodeAt`.
I would say that the simplest is 1, and also the most reasonable, because when using "backend dependent types" you're supposed to know what you're doing.


Regarding the second issue. `makeNimstrLit` is intended to be called with a literal, processed by compiler in such a way that there should be no chars out of ASCII range. Please see https://github.com/nim-lang/Nim/blob/ec7d556c208725f336ff626c7be299cc14638e92/compiler/jsgen.nim#L1975

**Comment by nigredo-tori** [comment]
I'm sorry, but I don't see the first solution as anything other than a temporary measure. It should not really say "unless you know what you're doing" anyway - indexing into cstring in JS target as it is right now is never a good idea. The message should really be "Do not do that, ever". And in that case a compile-time error (solution 2) is preferable (I don't see it being particularly hard to implement, too).

**Comment by Araq** [comment]
This is more a design question than a bug.

**Comment by yglukhov** [comment]
I'd say it is a tiny design bug and agree with both of you =)

**Comment by Araq** [comment]
Sorry, I misunderstood the problem. Now that I myself got bitten by this, I will fix the codegen so that it's at least harder to write wrong code.
