### ISSUE TITLE
Unsigned division by zero doesn't throw exception

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#4543]
Unsigned division by zero doesn't throw exception, while signed division does. For example:

```
let a = 5.uint64
let b = 0.uint64
echo (a mod b)
echo (a div b)
```

(edited to compile)
raises SIGFPE (making it impossible to catch), instead of throwing DivByZero exception.

**Comment by krux02** [comment]
Ok, that's a valid point, but not a single line in you example code does actually compile.

**Comment by cheatfate** [comment]
Could not agree, because nim has many backends. So every backend must handle this type of error on its own way. SIGFPE its a C backend way.

**Comment by Araq** [comment]
Impossible to catch, sure, but ultimately you need to test != 0 on your own anyway. DivByZero is not catchable either as per the spec, iirc.

**Comment by Araq** [comment]
Operations with unsigned numbers are not checked.

**Comment by konsumlamm** [comment]
`DivByZeroDefect` may not be catchable, but `SIGFPE: Arithmetic error.` still is a really bad error message. You have to look at the line of code it shows and then guess that the issue is division by 0.

`div` for signed integers also throws an exception, so why not for unsigned integers too? The overhead of checking for 0 isn't too high apparently.

**Comment by Araq** [comment]
Unsigned numbers are for the people who think they qualify as "numbers" and so they are left as sharp tools that don't really work.
