### ISSUE TITLE
"{.global.}" doesn't work in generics embedded in templates

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#4596]
This prints T0 four times (should print T1, T0, T0, T1):

```nim
import typetraits, macros

type
 T0 = object
 T1 = object


macro printFuncs(): untyped =
 return quote do:
   proc getV[A](a: typedesc[A]): string =
     var s {.global.} = name(A)
     return s

printFuncs()
echo getV(T1)
echo getV(T0)
echo getV(T0)
echo getV(T1)
echo "ok"
```

IMHO, "quote do" is too buggy (I've seen other, less serious bugs), and should be marked experimental in docs.

**Comment by krux02** [comment]
I would like to comment, it has nothing to do with ``quote``, the ast generated by quote is perfectly fine. The problem even remains when I don't use ``quote`` at all, and use templates instead:

```
import typetraits, macros

type
 T0 = object
 T1 = object

template printFuncsT(): stmt =
  proc getV[A](a: typedesc[A]): string =
    var s {. global .} = name(A)
    return s
    
printFuncsT()

echo getV(T1)
echo getV(T0)
echo getV(T0)
echo getV(T1)
echo "ok"
```

The output is T0 four times

**Comment by krux02** [comment]
I tried to analyse where the error came from. I analyzed, wher wrong code could have ben generated, and this is what I found out. I analyzed where something might have gone wrong, and this is the code I used for analyzing:

```Nim
import typetraits, macros

type
 T0 = object
 T1 = object

proc myinit[T](str: string) : string = 
  result = name(T)
  debugEcho("init ", result, " in ", str, " context")

template printFuncsT(): stmt =
  proc getTemplated[A](a: typedesc[A]): string =
    let globalValTemplated {. global .} = myinit[A]("templated")
    return globalValTemplated

printFuncsT()

proc getNonTemplated[A](a: typedesc[A]): string =
  let globalVal {. global .} = myinit[A]("non templated")
  return globalVal

echo "templated"
echo getTemplated(T1)
echo getTemplated(T0)
echo getTemplated(T0)
echo getTemplated(T1)
echo "non templated"
echo getNonTemplated(T1)
echo getNonTemplated(T0)
echo getNonTemplated(T0)
echo getNonTemplated(T1)
```
and this is the output:

```
init T1 in templated context
init T0 in templated context
init T1 in non templated context
init T0 in non templated context
templated
T0
T0
T0
T0
non templated
T1
T0
T0
T1
```

clearly it's wrong output, but since the init output is all there, and it's all before the first echo, I know that all initialization is done properly. But then I looked into the generated C code. Here I show you the important parts reformated and with comments, so that they become somewhat readable.

```C
STRING_LITERAL(TMP155, "templated", 9);
STRING_LITERAL(TMP157, "T1", 2);
STRING_LITERAL(TMP162, "T0", 2);
STRING_LITERAL(TMP163, "non templated", 13);

// globalvaltemplated[???]
       NimStringDesc* globalvaltemplated_101024_4094436648;
extern TNimType NTI138; /* string */
extern TFrame* frameptr_19636_1689653243;
extern Gcheap50818 gch_50858_1689653243;
extern NimStringDesc* globalvaltemplated_101024_4094436648;
       NimStringDesc* globalvaltemplated_101024_4094436648;

// globalval[T1]
       NimStringDesc* globalval_101149_4094436648;
extern NimStringDesc* globalval_101149_4094436648;
// globalval[T0]
       NimStringDesc* globalval_101169_4094436648;
extern NimStringDesc* globalval_101169_4094436648;
```

The code for ``globalvaltemplated`` looks very suspicious. First of all it's very different from the ``globalval`` code, it has all these ``extern`` declarations in it, second of all, it's wrong, there is only one instance, even thouhg there should be 2, and the declaration ``NimStringDesc* globalvaltemplated_101024_4094436648;`` is twice in the code, I did not even know that this would be legal C code.

from the Init000 function:
```C  
  // line 13 globalvaltemplated[T1] = myinit[T1]("templated")
  asgnRefNoCycle((void**) (&globalvaltemplated_101024_4094436648), myinit_101057_4094436648(((NimStringDesc*) &TMP155)));
  // line 13 globalvaltemplated[T0] = myinit[T0]("templated")
  asgnRefNoCycle((void**) (&globalvaltemplated_101024_4094436648), myinit_101087_4094436648(((NimStringDesc*) &TMP155))); 
  // line 19 globalval[T1] = myinit[T1]("non templated")
  asgnRefNoCycle((void**) (&globalval_101149_4094436648), myinit_101057_4094436648(((NimStringDesc*) &TMP163)));
  // line 19 globalval[T0] = myinit[T0]("non templated")
  asgnRefNoCycle((void**) (&globalval_101169_4094436648), myinit_101087_4094436648(((NimStringDesc*) &TMP163)));
```
Here you can see, that the same globalvaltemplated instance is used for both initializatens. So the value is just overridden. Tha same also happens in the instances of the `get` functions, but I think you get the point here, so I leave the code out, unless you really want to have it.

**Comment by krux02** [comment]
While I don't have a solution for the bug, I have a workaround to make your code work what it is supposed to do:

```nim
import typetraits, macros

type
 T0 = object
 T1 = object

macro printFuncs(): stmt =
  let s = newIdentNode("s")
  return quote do:
    proc getV[A](a: typedesc[A]): string =
      var `s` {.global.} = name(A)
      return `s`

printFuncs()
echo getV(T1)
echo getV(T0)
echo getV(T0)
echo getV(T1)
echo "ok"
```

For some reason, the global val `s` is a symbol in the ast, but in non templated code, `s` stays an identifier for a reason I don't know. luckily you can force `s` to be an IdentNode with the code above.

**Comment by metagn** [comment]
In 2.0, both `quote` and `template` examples output:

```
T1
T0
T0
T1
ok
```
