### ISSUE TITLE
SSL handshake failure for cloudflare-based sites?

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4614]
```nim
import httpclient
echo get("https://pokemongostatus.org/status.jsonp").body
```

Results in:

```
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [SslError]
```

**Comment by cheatfate** [comment]
@dom96 could you please check version of `openssl`, because i have
> OpenSSL 1.0.2h  3 May 2016

and got this

`onStatus({"servers":{"Login Gateway":{"time":1471172088.933264,"error":"","loginTime":-1.0,"resp":"403 Forbidden","status":"Online","delay":0.0381309986114502},"PTC Login (US East)":{"time":1471172038.731526,"error":"","loginTime":-1.0,"resp":"","status":"Online","delay":0.1187829971313477},"PTC Login (Germany)":{"time":1471172068.424776,"error":"","loginTime":-1.0,"resp":"","status":"Online","delay":0.1705451011657715},"PTC Login (Japan)":{"time":1471172077.4186,"error":"","loginTime":-1.0,"resp":"","status":"Online","delay":0.2947947978973389},"Google Login (Germany)":{"time":1471172077.166641,"error":"Could not get Google token","loginTime":0.08471322059631348,"resp":"","status":"Offline","delay":0.08471322059631348},"Google Login (US East)":{"time":1471172088.051178,"error":"Could not get Google token","loginTime":0.1072788238525391,"resp":"","status":"Offline","delay":0.1072788238525391}},"status":"Offline","time":1471172088.977607,"reason":"The Google Login (Germany) server was offline in the past 5 minutes and \"Google Login (US East)\" was offline in the past 5 minutes"})`

**Comment by dom96** [comment]
okay, so it must be my OpenSSL version as I have ``OpenSSL 0.9.8zh 14 Jan 2016``

**Comment by cheatfate** [comment]
Solution is to upgrade your OpenSSL to version 1.0.1 at least.
