### ISSUE TITLE
Different proc type inferred from default parameter

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#4659]
``` nim
import os, unicode, future

let nothing = proc: bool {.closure.} = false

proc odd(prev = nothing): bool =
  let a = stdin.readChar()
  if not isAlpha(Rune(ord(a))):
    discard prev()
    stdout.write(a)
    return a != '.'

  # delay action until later, in the shape of a closure
  proc clos: bool =
    stdout.write(a)
    prev()

  return odd(clos)

proc even(): bool =
  while true:
    let c = stdin.readChar()
    stdout.write(c)
    if not isAlpha(Rune(ord(c))):
      return c != '.'

var e = false
while (if e: odd() else: even()):
  e = not e
```

This used to compile until a few commits ago, now it fails with:

```
oddword.nim(17, 13) Error: type mismatch: got (proc (): bool{.closure, gcsafe, locks: 0.})
but expected one of: 
proc odd(prev = nothing): bool
```

A workaround is to explicitly specify the type of the `prev` parameter:

``` nim
proc odd(prev: proc: bool {.closure.} = nothing): bool =
```

**Comment by Araq** [comment]
The problem is that the compiler now rightly infers that 'nothing' has noSideEffect and this is thus also the constraint of your parameter 'prev'. You can annotate the 'nothing' with .sideEffect or explicitly mention the type of the parameter, as you said. I don't think we should make the typing rules more complex for this case to work, but I'm open to suggestions.

**Comment by def-** [comment]
Your explanation makes sense, but I would not have guessed that. I guess a better error message would be a good enough solution.
