### ISSUE TITLE
Adding time interval to UTC TimeInfo is off by an hour or so

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4690]
``` nim
let gmt = getGMTime(fromSeconds(876124714)) # Mon  6 Oct 08:58:34 BST 1997
doAssert toSeconds(toTime(gmt + 30.minutes)) == toSeconds(gmt.toTime) + 30*60
```

This assert shouldn't fail. I think there may be something wrong with `toSeconds`.

**Comment by nigredo-tori** [comment]
Seems to be some problem with `toTime` implementation and DST:
```nim
var t: TimeInfo
t.year = 2001
t.month = mSep
t.monthDay = 9
t.hour = 1
t.minute = 46
t.second = 40

# this fails - left part is greater by 3600
assert t.toTime.int == 1_000_000_000
```

**Comment by nigredo-tori** [comment]
More precise description of the bug in `toTime`:
1. TimeInfo is received.
2. It is passed to `mktime`, which produces a corresponding local Time with **historical** timezone offset.
3. From this Time we substract the **current** timezone offset, and correct for initial timezone.

This implementation seems fragile around DST time changes, but that's not the worst of it. It assumes that historical and current timezone offsets match - and this is not always the case. For example, here in Novosibirsk we've changed our timezone this year, meaning that `toTime` is **wrong for all dates before July 2016**! Here's the test case for this exact problem:
```nim
import times

block:
  var timeInfo: TimeInfo
  timeInfo.year = 2016
  timeInfo.month = mJul
  timeInfo.monthDay = 24
  timeInfo.hour = 12

  let unixTime = timeInfo.toTime.int
  # works
  doAssert unixTime == 1469361600

block:
  var timeInfo: TimeInfo
  timeInfo.year = 2016
  timeInfo.month = mJul
  timeInfo.monthDay = 23
  timeInfo.hour = 12

  let unixTime = timeInfo.toTime.int
  # fails
  doAssert unixTime == 1469275200
```
Start it like this (linux):
```sh
TZ=Asia/Novosibirsk nim c -r test_totime.nim
```
As for the way to fix it: using `timegm` and `_makegmtime` seems to be by far the best solution wherever supported. Otherwise we would have to either rely on some even less standard API, or some library with historical timezone data.

**Comment by nigredo-tori** [comment]
It seems that my fix was rolled back in #5188, so all the examples are broken again. @Araq, should this be reopened?

Also, tests for the `times` module are failing in Novosibirsk:
```
> TZ=Asia/Novosibirsk nim c -r tests/stdlib/ttime.nim
...
Parsing failure!
expected: 2015-12-15T09:04:00+00:00
actual  : 2015-12-15T10:04:00+00:00
Traceback (most recent call last)
ttime.nim(65)            ttime
ttime.nim(57)            parseTest
system.nim(3546)         raiseAssert
system.nim(2656)         sysFatal
Error: unhandled exception: false  [AssertionError]
Error: execution of an external program failed: '/home/dmitry/work/nim/tests/stdlib/ttime '
```

**Comment by dom96** [comment]
We need to run the tests in multiple timezones at once somehow. :\

**Comment by GULPF** [comment]
All issues here are now fixed
