### ISSUE TITLE
logging lvl can't use.

### ISSUE THREAD

**Issue by Angluca** [nim-lang/Nim#4720]
Use log will lvlAll.

`
var L = newConsoleLogger(lvlInfo)
var fL = newFileLogger("test.log", levelThreshold = lvlInfo, fmtStr = verboseFmtStr)
var rL = newRollingFileLogger("test_rolling.log", fmtStr = verboseFmtStr)
addHandler(L)
addHandler(fL)
# setLogFilter(lvlInfo)

addHandler(rL)

info("920410:52 accepted")
info "111_920410:52 accepted"
warn("4 8 15 16 23 4-- Error")
error("922044:16 SYSTEM FAILURE")
fatal("SYSTEM FAILURE SYSTEM FAILURE")
`
test.log has all lvl message when u run it.

**Comment by Araq** [comment]
Why wouldn't it? you declare the file logger with lvlInfo which means 'info or worse'.

**Comment by Angluca** [comment]
I want use test.log save info and use rolling.log save error, But test.log has save all message, the same with rolling.log.

**Comment by andreaferretti** [comment]
If I understand correctly, this is a misunderstanding on the error levels. The logger follows the common convention of setting a threshold - every message having at least a certain severity gets written to the log. There is no way to filter message having exactly a certain severity, since, well, it is not a very common case.

It seems there is no bug here, @Angluca  can you clarify if you need further feedback or this can be closed?

**Comment by Yardanico** [comment]
@andreaferretti maybe close this? @Angluca has not left any feedback

**Comment by Yardanico** [comment]
@Araq close?
