### ISSUE TITLE
Recent changes to marshal module break old marshalled data

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#4779]
https://github.com/nim-lang/Nim/commit/6013240f5d4fcb48cf9dc30eb2addc78672b274b#commitcomment-19043239

Please be more careful next time.

**Comment by endragor** [comment]
I was aware of that. What do you suggest, exactly? marshal doesn't add a version tag, should we start doing that? One additional note I'd add to the module doc is that marshal is not supposed to be used in production, just for debugging/testing purposes, or is it not so? For example, it's dangerous to marshal `Table` from stdlib, because unmarshalling it on a different arch would produce incorrect table, because hash values are platform-dependent.
