### ISSUE TITLE
Timezone bug in "times" library

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#4804]
Sample program:

```
import times

echo "2016-01-01 00:00".parse("yyyy-MM-dd hh:mm").toTime.getGMTime.format("HH:mm")
echo "2016-08-01 00:00".parse("yyyy-MM-dd hh:mm").toTime.getGMTime.format("HH:mm")

echo "2016-01-01 00:00".parse("yyyy-MM-dd hh:mm").toTime.getLocalTime.format("HH:mm")
echo "2016-08-01 00:00".parse("yyyy-MM-dd hh:mm").toTime.getLocalTime.format("HH:mm")
```

Output on Windows (OK):
23:00
22:00
00:00
00:00

Output on Linux:
23:00
00:00
00:00
02:00

Expected output on Linux: same as on Windows.

Tested with:
Nim devel 2017-01-03, local timezone: UTC+1

**Comment by trustable-code** [comment]
I propose this fix:
in file times.nim:
in proc parse():
replace:
  var info = getGMTime(getTime())
with
  var info = getGMTime(getTime())

I have tested this fix with the master branch.

**Comment by Araq** [comment]
But this parses strings presumably coming from user input, and users refer to their local timezones, not to GMTime. If anything, ``parse`` can get a parameter which says how to interpret the string.

**Comment by FedericoCeratto** [comment]
According to the docs, parse() supports timezones, therefore it should have parsed "GMT"

**Comment by dom96** [comment]
> According to the docs, parse() supports timezones, therefore it should have parsed "GMT"

Indeed.

**Comment by jdbernard** [comment]
I was looking through the PRs and noticed this issue. I just submitted a PR (#4923) that addresses this issue from a different point of view. I do think we want to be able to parse dates and infer the timezone when not given, so I don't know if using `timegm()` is always the right answer. I have a feeling that just replacing `mktime` will lead to incorrect behavior when working with non-GMT times, but I'll test that and follow up.

As @dom96 said, we should support GMT. It looks like parse does not really respect the timezone provided by the user in many cases. My PR doesn't fix that so I'm sure there is more work to be done.

**Comment by FedericoCeratto** [comment]
Inferring timezones or other missing date components can lead to heisenbugs and code that is difficult to test and debug.
I would recommend disabling the guesswork by default and requiring some flags to specify what can be inferred.

An interesting read: http://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time
Related to #4922

**Comment by jdbernard** [comment]
You're right. As I mentioned in the thread you linked, there are definitely bugs around DST transition periods, and as you mention there are going to be a lot of other wierd and hard to find edge cases.

The patches I've submitted are just small changes that keep with the approach of the code that is already there. Creating a date and time library that is correct in the face of how humans keep track of time is a large undertaking. Just using GMT under the covers isn't enough to truly address all the issues you linked (great link, btw. Should be required reading for people writing these kinds of libraries).

I'm not one of the language maintainers, I'm just a random guy who is hitting some of the edge cases in the current implementation and trying to patch them. I think that Nim needs better support for time and date, but the current implementation rests on C's handling of date and time. What is there now will get you most of the way there most of the time.

In the short term we should fix `parse` so that the user can give a timezone and get back a date in that timezone. More generally I think it is not to hard to ensure that when given a fully specified date `parse` returns the correct value.

In the long term it would be nice to have a full featured date and time library that uses the [tzdata database](https://www.iana.org/time-zones) and handles things like alternate chronologies, etc. In fact, if this is something the community wants and the maintainers greenlight, when I free up a little more I was hoping to be involved in such an effort.

**Comment by FedericoCeratto** [comment]
Unfortunately timezone support has been removed in 170745eb39d8607004a6be8a9d8968137d99824d

**Comment by jdbernard** [comment]
It looks like it still has the timezone offset, just drops the name which wasn't consistently used anyway.

**Comment by trustable-code** [comment]
I have just updated this issue and created a new PR: https://github.com/nim-lang/Nim/pull/5188
