### ISSUE TITLE
Weird variable/proc name redefinition bug

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4971]
Apparently, Nim doesn't let you use variable names that are already used for some procs or templates, *but only if both the variable and proc/template definitions are in the same file!* The following example won't compile:

```
type Vec3 = object
  x, y, z: float

template r(v: Vec3): float = v.x
proc g(v: Vec3): float = v.y
proc b(v: Vec3): float = v.z

proc r() = discard    # note that this is allowed

#let g = 5     # FAILS TO COMPILE: naming.nim(8, 5) Error: redefinition of 'g'
#let b = 1     # FAILS TO COMPILE: naming.nim(9, 5) Error: redefinition of 'b'
```

But if you moved the proc/template definitions to a different module and then imported them, then everything would compile just fine:

**defs.nim**
```
type Vec3* = object
  x*, y*, z*: float

template r*(v: Vec3): float = v.x
proc g*(v: Vec3): float = v.y
proc b*(v: Vec3): float = v.z
```

**redef.nim**
```
import defs

proc r() = discard

let g = 5
let b = 1
```

**Comment by nigredo-tori** [comment]
Unless I'm missing something here, this is [intended behavior](http://nim-lang.org/docs/manual.html#modules-scope-rules). You can't define symbols with the same identifiers in one scope, unless they are all procs, templates and the like (in which case overloading kicks in). Since each module uses its own scope, this restriction does not apply. Any ensuing name collision has to be resolved wherever the identifier is used. In most modern languages modules work like this, as far as I can tell.

**Comment by johnnovak** [comment]
Yeah, I understand that and indeed, I just tested it with Scala and it works the same way. However, because the module variant in my example works fine, it is technically possible to allow the non-module version to compile too, I believe. Sure, it's not a top priority, but it would be nice if Nim could do better than other languages in this regard :)

**Comment by Araq** [comment]
We need less smart behaviour and more robstness. Sorry.
