### ISSUE TITLE
.this pragma doesn't work with generics

### ISSUE THREAD

**Issue by Swend5** [nim-lang/Nim#5053]
```nim
type
  A[T] = object
    x: T
{.this: self.}
proc testproc[T](self: A[T]) =
  echo x
```
```nim
type
  A = object
    x: int
{.this: self.}
proc testproc(self: A) =
  echo x
```
First example results in ` Error: undeclared identifier: 'x'`, second example compiles without issue.

**Comment by Swend5** [comment]
It works if the template is instantiated, maybe it has something to do with that.
```nim
type A[T] = object
  x: T
{.this: self.}
proc testproc[T](self: A[int]) =
  echo x
```

**Comment by brandonpickering** [comment]
The issue is that `x` is looked up before `testproc` is instantiated, and the existence of `x` can depend on `T`. For example:
```
type A[T] = object
  when T is int:
    x: T
```

The compiler also looks up symbols when it generates an instantiation, so removing the pre-instantiation lookup doesn't appear to break anything, and it fixes this issue. But maybe it's there for a reason.

**Comment by Araq** [comment]
The pre-instantiation lookup is required to implement the proper "open vs closed symbol lookup" rules.

http://nim-lang.org/docs/manual.html#generics-symbol-lookup-in-generics

**Comment by Swend5** [comment]
Is there some temporary workaround you can think of?

**Comment by nc-x** [comment]
{.this.} is deprecated. Can be closed?
