### ISSUE TITLE
GitHub community abuse

### ISSUE THREAD

**Issue by chbrown** [nim-lang/Nim#5082]
👑 Nim is cool.

This is not:

> [ You are receiving this email from Nim because you are a stargazer on GitHub. ]

_Edit:_ The email is signed "The Nim Team" — please forgive (and close) my interjection here if that's not actually you guys.

**Comment by dom96** [comment]
This email was sent through BountySource, and the reason you got it is because you list your email publicly on your GitHub page and you are a stargazer of the Nim repo. I understand that this might be annoying but it is a good way to reach more people than we would otherwise.

I believe the email should contain an unsubscribe link, so if you do not wish to receive such emails anymore you should be able to prevent that by unsubscribing.

But in any case, I apologise for the unwanted email.
