### ISSUE TITLE
RFC: unneeded (I guess) export of some symbols in asyncdispatch

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5162]
What's the reason of exporting these symbols?
* PDispatcher
* newDispatcher
* getGlobalDispatcher

I found no public operations for PDispatcher.

**Comment by cheatfate** [comment]
`getGlobalDispatcher` and `PDispatcher` needed to access `addRead`, `addWrite`, `register`, `unregister` procedures, they used in `asyncnet` and other async modules.

**Comment by vegansk** [comment]
@cheatfate , I don't get it. ``addRead``, ``addWrite``, ``register``, ``unregister`` uses these symbols internally and doesn't need for them to be exported, or did I miss something? 

Removed export markers from them and then called ``./koch tests c async``. Async tests are all green :-)

**Comment by cheatfate** [comment]
you are right, but only for posix branch, sometime ago i have tried to push PR with access to some members of `PDispatcher` object on Windows. And i still think its needed because in Windows you really need to have access to IOCP to implement some techniques with `RegisterWaitForSingleObject`.
So if you disable exports for `PDispatcher` and `getGlobalDispatcher` it will be much harder to me or somebody change this behavior in asyncdispatch.

**Comment by vegansk** [comment]
That's the reason for PDispatcher and for getGlobalDispatcher. What about newDispatcher?

**Comment by dom96** [comment]
At one point the idea was that you could create your own dispatcher, but later on I decided that it made more sense to have a global one.

**Comment by cheatfate** [comment]
Currently there no reasons to export `newDispatcher`.

**Comment by narimiran** [comment]
> Currently there no reasons to export `newDispatcher`.

Without it exported, `tasyncrecursion.nim` test fails. This means we have reasons to export all three symbols in the original post, and this can be closed.
