### ISSUE TITLE
Wrong overload resolution?

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#5164]
```nim
import htmlgen # Remove this line to make it work
discard 2 div 1
```
```
$ nim c test.nim
test.nim(2, 15) Error: type mismatch: got (int literal(1), string)
but expected one of:
proc `&`(x, y: char): string
proc `&`[T](x, y: seq[T]): seq[T]
proc `&`(x: string; y: char): string
proc `&`[T](x: seq[T]; y: T): seq[T]
proc `&`(x: char; y: string): string
proc `&`(x, y: string): string
proc `&`[T](x: T; y: seq[T]): seq[T]
```

**Comment by krux02** [comment]
from the documentation of htmlgen I got this quote:
> Warning: This module uses immediate macros which are known to cause problems. Do yourself a favor and import the module as from htmlgen import nil and then fully qualify the macros.

internally it uses ``expr`` instead of ``typed``/``untyped``, and as far as I know immediate macros are depricated, probably because they cause problems. So my suggestion is to port htmlgen to a more modern Nim, and see if this problem still exists.

**Comment by krux02** [comment]
I just made a test, and it is the immediate pragma that causes the problem:

```Nim
import macros

macro `div`(e: untyped): untyped #[{.immediate.}]# =
  result = newLit("WRONG")

echo 21 div 3
```
