### ISSUE TITLE
Feature request: More helpful error message when strutils is forgotten to be imported

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#5172]
In this example code, the user forgot to import strutils:
```nim
echo "foo".find("f")
```
Error message:
Error: type mismatch: got (char, string)
but expected one of:
proc `==`(x, y: bool): bool
proc `==`[T](x, y: ref T): bool
proc `==`(x, y: pointer): bool
[...]

This happens probably often, so it would be nice, if there would be a more helpful error message to the user. Understanding why the code does not compile, is important to be a user-friendly programming language I think.
I would expect a error message like:
Error: proc "find" is not declared for the given parameter types. 
(Maybe even add a hint, that "strutils" contains such a proc.)

**Comment by krux02** [comment]
To get  the behaviour you want, there are several things that need to be implemented. First of all when a function lookup fails, the entire standard library needs to be searched for an appropriate function to match the argument type, and then the function needs to suggested. This can be done and is often done in Java IDEs. I am just not sure if the command line compiler should do it by default.

Then `concept` not only needs to be finished and stabilized, it also needs to be used in system, so that system.find wont match the argument types `(string, string)`. `string` does not have an iterator items with the ityem type of `string`.

**Comment by alehander92** [comment]
i think some kind of hint can be still useful at least for stdlib

**Comment by Araq** [comment]
Nobody is working on this.
