### ISSUE TITLE
Detect iterator variables being modified inside loop body

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#525]
An iterator that works on a mutable variable like a string can be problematic for the user if he tries to modify it during the iteration. The following code is allowed now:

``` nimrod
  for match in dest.findAll(RE_UNICODE):
    var temporal: int
    if parseHex(match, temporal, 2) > 0:
      let u = toUTF8(TRune(temporal))
      dest = dest.replace(match, u)
```

The code won't produce the expected results with certain input strings (`dest`), it will work however if the findAll iterator is wrapped inside sequtils.toSeq. Maybe the compiler could detect this situation and at least issue a warning?

**Comment by narimiran** [comment]
> Notice that the `items` iterator will actually check that the length is not modified and throw an exception if this happens

...and one can include the same check in their own custom iterators, if they are afraid that some other code will mutate the iterable.

Here is the implementation, for the completeness sake:
```nim
iterator items*(a: string): char {.inline.} =
  ## iterates over each item of `a`.
  var i = 0
  let L = len(a)
  while i < L:
    yield a[i]
    inc(i)
    assert(len(a) == L, "string modified while iterating over it")
```

As for using the iterators which don't include this check, a general programming rule of thumb is: don't mutate what you're iterating over.

Adding a check to every iterator (in the stdlib) did not happen in the last 5 years (since this issue has been created) and I don't see it happening any time soon. Closing.
