### ISSUE TITLE
compiler reject to pass break statement of templated loop

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#5292]
```Nim
template doWhile*(a: typed, b: typed) =
  while true:
    b
    if not a:
      break

var 
  x = 100
  y = 10

doWhile x != 0:
  inc y
  dec x
  if y == 15: break #this line cause error
```

error message:
```text
dowhile.nim(14, 15) Error: invalid control flow: break
```
really doesn't make any sense

**Comment by stisa** [comment]
`b` should be `untyped`, otherwise, as I understand it, the compiler does not see the loop you want to break from because the code passed as `b` is parsed ( resolved? Not sure about the correct term ) before being passed to the template. See http://nim-lang.org/docs/manual.html#templates-typed-vs-untyped-parameters

```nim
template doWhile*(a: typed, b: untyped)
```

Maybe the compiler error could be improved, something like`no loop to break from`, but it would probably be just as puzzling.

**Comment by Araq** [comment]
Yup, no bug here, @stisa is correct.
