### ISSUE TITLE
Compiling in release mode prevents valid code execution.

### ISSUE THREAD

**Issue by myankles** [nim-lang/Nim#5296]
This snippet of code behaves differently depending on whether or not release mode is used for compilation:
```
proc bug() : void =
    var x = 0
    try:
        inc x
        raise new(Exception)
    except Exception:
        echo x

bug()
```
Here's what happens:
```
$ nim c bug.nim
...
$ ./bug
1
$ nim c -d:release bug.nim
...
$ ./bug
0
$ nim --version
Nim Compiler Version 0.16.0 (2017-01-08) [MacOSX: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 5947403e84ba44397b35f93f9d327c76e794210f
active boot switches: -d:release
```
Please observe that the code prints **1** when using normal compilation and **0** when using release mode.

**Comment by Parashurama** [comment]
Investigating the source code, this seems related to C compiler optimisation.
I can also reproduce the issue in full debug mode, but while passing -O3/-O2/-O1 level optimisation.
tested with GCC and clang x64 on linux.
Since 
Exceptions uses setjmp/longjmp, at least on C target.
I'm reasonably sure the problem is that the variable isn't declared as volatile.
In optimizing mode, compilers often discard the variable and keep them register.
which can mess up state restoration on longjmp.
