### ISSUE TITLE
Nim hangs forever in infinite loop in nre library

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#5444]
Short code example that hangs Nim:-

```
import httpclient
import nre

var http = newHttpClient()
var data = http.getContent("http://downloads.tomsguide.com/MusicBee,0301-27475.html")

echo data.findall(re"url.*? = &#39;(.*?)&#39;")
```

On pressing CTRL-C, following stack is printed:-

```
Traceback (most recent call last)
http.nim(7)              http
nre.nim(521)             findAll
nre.nim(452)             matchImpl
SIGINT: Interrupted by Ctrl-C.
SIGINT: Interrupted by Ctrl-C.
```

Replace URL with google.com and it works fine, try cnn.com, it hangs again. Not sure what about the content is confusing Nim or PCRE.

**Comment by napalu** [comment]
The problem is in nre.findIter which keeps on searching when it's never matched until it reaches the end of the input. The function keeps incrementing the offset by one and searches again until len of input is reached. The fix is simple: bail early when never matched instead of searching for the next match boundary.

**Comment by genotrance** [comment]
I just tried it out your change and it works great - in fact it probably greatly speeds up the search performance since searching in large files and strings was going through each offset.

Hope it gets accepted into the main branch soon.
