### ISSUE TITLE
Tester passes test although individual test in suite fails

### ISSUE THREAD

**Issue by napalu** [nim-lang/Nim#5472]
Related to #5469 - `tester` passes test although running the individual suite fails.

![screen shot 2017-03-02 at 21 00 57](https://cloud.githubusercontent.com/assets/6690378/23540143/da8baf36-ffdf-11e6-9fb0-7dbb63340f8a.png)
![pass](https://cloud.githubusercontent.com/assets/6690378/23540146/df204b88-ffdf-11e6-8135-7b3a5198148a.png)

**Comment by napalu** [comment]
Looking at the code, currently `tests/testament/tester.nim` is only testing the compiler, none of the tests are actually being run.  The action passed in `testspec` is 'compile' and the template command which is actually called is defined in `specs.nim` as:

```nim
const
  cmdTemplate* = r"compiler" / "nim $target --lib:lib --hints:on -d:testing $options $file"
```

What are the expectations? That tester should actually compile + run all files, or is the compiling only by design? I would personally expect tester to run which it actually would if it were passed the action `run` or `runNoSpec` but then the tests would need to be revised because we'd then get output like:

![screen shot 2017-03-03 at 12 00 30](https://cloud.githubusercontent.com/assets/6690378/23548716/275e3800-0009-11e7-9e8a-9129a2225903.png)

A cheap fix would be to just change  the default command template in `tests/testament/specs.nim` to:


```nim
const
  cmdTemplate* = r"compiler" / "nim $target --lib:lib --hints:on -d:testing $options -r $file"
```
Which would actually result in the desired behaviour of actually running the tests but there may well be cases where we want tests to be compile only and not compile and run. There's other options but I'd like to get some input before I start looking at them.

Feedback?

**Comment by Araq** [comment]
Then it works as expected and the test needs to be fixed. The default "only checks that it compiles" is correct. Use an 'output' spec to run the test and check for its output.

**Comment by napalu** [comment]
Changed the tnre test suite as suggested.

**Comment by bluenote10** [comment]
@dom96 Maybe this is the issue you are referring to in #5967? That's exactly the issue I encountered there as well, so it's probably good to discuss here.

My suggestion would be:
- Make "compile + run" the default, so we cannot miss a test suite again by accident.
- For those tests which must not run, mark them as `action: compile`.
- Make `output` matching optional, i.e., only check if it is specified (e.g. by making `spec.outp` nillable, or having a `spec.outpCheckRequired`). This makes the maintenance of tests suites like this much easier, because we don't have to touch the `output` on every added suite -- what really matters for them is the exit code.

The last point is the only critical, because I don't know if there are many tests which currently have `action: run` without specifying `output` and relying on the check of an empty output. But I would assume there aren't so many because most tests I have seen specify `output` anyway.

If @Araq likes the idea I could work on that.

**Comment by Araq** [comment]
Ugh, no. The tester is fine as it is. Tests that use ``unittest`` are confused anyway, IMO. We don't need "unittests" inside "tests", these are integration tests. How can you "unit test" for a decent compiler error message anyway.

**Comment by bluenote10** [comment]
Just a quick check (only in stdlib) for tests which are currently not run, but look like they should:

```
stdlib/tjsontestsuite.nim
stdlib/thttpcore.nim
stdlib/tnativesockets.nim
stdlib/thashes.nim
stdlib/tnet.nim
stdlib/trstgen.nim
```

**Comment by dom96** [comment]
> Maybe this is the issue you are referring to in #5967?

Yep. "compile + run" by default sounds like a good solution.

**Comment by dom96** [comment]
Also, if you're willing to fix this, any chance you could also write some documentation explaining the test suite and the different options supported (including ``action: compile``). It's an annoying guess game right now.

**Comment by napalu** [comment]
The problem with changing the default behaviour, is that many tests will fail because, although some seem to be setup to run+compile they've only ever been compiled and so errors and stuff (because of changes or whatever) have not been caught. It would require checking all current tests and possibly changing many of them.

But I agree that compile + run as default would make sense ;)

**Comment by bluenote10** [comment]
I had already enabled "compile + run" for a quick check, and there weren't too many tests that fail. Which is why I thought it's doable. But without Araq's approval I'll better hold my horses :-). I think his main concern is about `unittest` itself, and that it makes debugging compiler bugs more difficult. I can't really judge it, but I would encourage testing for runtime behavior in some way to ensure the quality of the standard library a bit more. Writing runtime tests without `unittest` and purely on the `spec.outp` matching basis feels a bit cumbersome, e.g. like in [this example](https://github.com/nim-lang/Nim/blob/devel/tests/js/tjsffi.nim).

**Comment by Araq** [comment]
@dom96 There is some sparse documentation here: https://github.com/nim-lang/Nim/blob/devel/doc/contributing.rst#compiler
