### ISSUE TITLE
Async writes are not queued up on Windows

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#5532]
The program below provides different outputs between Windows and nix systems:
```nim
import os, asyncfile, asyncdispatch

removeFile("test.txt")
let f = openAsync("test.txt", fmWrite)
var futs = newSeq[Future[void]]()
for i in 1..3:
  futs.add(f.write("string " & $i & "\n"))
waitFor(all(futs))
f.close()
echo readFile("test.txt")
```
On nix systems (tested on macOS, Linux) it prints 3 strings, as expected:
```
string 1
string 2
string 3
```
On Windows it prints only the last string:
```
string 3
```
Notice that on Windows it doesn't error out - all futures complete successfully, yet only the last write() actually does something.
I haven't tested if async sockets produce the same behaviour or if this is specific to async files.

Git hash: d59441340dcc3b131c984def530084da93796775

**Comment by cheatfate** [comment]
Ok, this happens because of direct manipulation of `OVERLAPPED` structure members to specify file offset.

Actually all 3 `WriteFile` calls were performed at file position `0`, and its why all 3 operations was completed successfully.

It will be hard to save *nix semantic without increasing number of syscalls for every read/write operation, for example:

1. Use `LockFileEx/UnlockFileEx` to lock regions in file, before actually reading/writing.
2. Store current read/write operation Future inside of `AsyncFile` object and perform operations sequentially, eg. waiting for current Future to be completed and run write/read operation after it. This will make `offset` field of `AsyncFile` more consistent.
3. Before actually perform read/write operation call to `SetFilePos` to obtain current offset in file, and do not use `offset` field of `AsyncFile` object anymore.

All this proposition will slowdown asynchronous operations on Windows.

**Comment by endragor** [comment]
Thank you for reviewing the issue.

I don't think that (2) is going to cause a noticeable slowdown when the app makes sequential writes. It will just add additional pointer comparison (or maybe queue length check). But it will result in a meaningful behaviour in the presented case. (1) and (3) are more scary as they result in more IO-related syscalls.

**Comment by dom96** [comment]
Unfortunately I cannot reproduce this in a Windows XP VM. I tried multiple runs, all give the correct result. Maybe I'm just getting lucky, but I cannot fix this without reproducing.
