### ISSUE TITLE
Doc suggestion: a Types Index page...

### ISSUE THREAD

**Issue by mark-summerfield** [nim-lang/Nim#5535]
I find the docs v. hard to navigate. The theindex.html is too big and even searching it results in too many hits. At the moment I navigate via the library modules.

What I'm suggestion is the addition of a new page (linked from every page just as theindex.html should be) called: Types Index. This page should list every type known to Nim (built-in and std. lib.) in symbols then alphabetical order and each type should be a link to a page called: *sometype* Type. And this page should have an alphabetically ordered list of every function/method that accepts the type (no matter in which position) or that returns the type (or both). That way people who know the type they're interested in could find every relevant function.

**Comment by zah** [comment]
Mark, since you seem to care a lot about documentation, I would suggest one project that you might find interesting. 

There are few documentation indexing systems, all sharing a common file format started by the popular [Dash](https://kapeli.com/dash) tool for macOS. Now, the family includes [Velocity](http://velocity.silverlakesoftware.com/) for Windows and [ZealDocs](https://zealdocs.org/) for Linux. There are also plugins for many editors using the same "docset" format.

There was an [effort](https://github.com/nim-lang/Nim/issues/1401) to create a docset file for Nim, but I'm not sure how up-to-date it is. Ideally, we would incorporate a docset generator as part of our build tools (e.g. `koch docset`).

**Comment by mark-summerfield** [comment]
I had never heard of those tools before; they look interesting.

However, my guess is that most people who come to Nim will work from the online docs so ISTM that improving the online docs would be more immediately beneficial, hence my suggestions to add a link to theindex.html above or below the Search on every page and to have the Types Index described, both of which I assume would involve adding to the doc generation tool.

Of course the docs also need a lot of filling out and more examples as last year's user survey indicated; I can fix typos and English here and there when I notice, but I don't know enough about Nim to be able to *originate* text or examples. (I plan to buy Nim in Action once it is available though, and I am continuing to learn Nim.)
