### ISSUE TITLE
Recursive function: Strange return type resolution

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#5708]
I'm trying to flatten nested sequences of any level with a recursive function:

```Nim
proc flatten*[T](a: seq[T]): seq[T] =
  return a
proc flatten*[T](a: seq[seq[T]]): seq[T] =
  return a.concat.flatten
```

The logic is, if I have a nested sequence `seq[seq[seq[int]]]`, T should match `seq[int]` and return value should be `seq[seq[int]]`but it seems in the following snippet that the return value is `seq[int]` and that the recursive call to flatten got optimized away and type matching fails:

```Nim
import math
import sequtils
import typetraits

######### No nesting
let p = @[1,2,3,4,5]

######### Nesting seq of seq
const
  a = @[1, 2, 3, 4, 5]
  b = @[1, 2, 3, 4, 5]

var
  vandermonde: seq[seq[int]]
  row: seq[int]

vandermonde = newSeq[seq[int]]()

for i, aa in a:
  row = newSeq[int]()
  vandermonde.add(row)
  for j, bb in b:
    vandermonde[i].add(aa^bb)

echo vandermonde
# @[@[1, 1, 1, 1, 1], @[2, 4, 8, 16, 32], @[3, 9, 27, 81, 243], @[4, 16, 64, 256, 1024], @[5, 25, 125, 625, 3125]]


######### Nesting seq of seq of seq
let t = @[
            @[
                @[1,2,3],
                @[1,2,3]
            ],
            @[
                @[3,2,1],
                @[3,2,1]
            ],
            @[
                @[4,4,5],
                @[4,4,4]
            ]
        ]
echo t
# @[@[@[1, 2, 3], @[1, 2, 3]], @[@[3, 2, 1], @[3, 2, 1]], @[@[4, 4, 5], @[4, 4, 4]]]


proc flatten*[T](a: seq[T]): seq[T] =
  static:
    echo "flatten*[T](a: seq[T]): seq[T]"
    echo T.name
  return a
proc flatten*[T](a: seq[seq[T]]): seq[T] = # auto works
  static:
    echo "flatten*[T](a: seq[seq[T]]): seq[T]"
    echo T.name
  return a.concat.flatten

echo p.flatten()
# @[1, 2, 3, 4, 5]

echo vandermonde.flatten()
# @[1, 1, 1, 1, 1, 2, 4, 8, 16, 32, 3, 9, 27, 81, 243, 4, 16, 64, 256, 1024, 5, 25, 125, 625, 3125]

echo t.flatten()
# Error: type mismatch: got (seq[int]) but expected 'seq[seq[int]]'
# Using auto signature works, but it doesn't look like anything else would
```

The static outputs with `auto` type signature are:
```Nim
flatten*[T](a: seq[T]): seq[T] #This is p
int
flatten*[T](a: seq[seq[T]]): seq[T] #This is vandermonde, there is no second static output
int
flatten*[T](a: seq[seq[T]]): seq[T] #This is t, there is no second nor third static output
seq[int]
```

**Comment by zah** [comment]
I took me a while to figure this out, but the signature of the second `flatten` proc is not correct. Using `auto` as the return type is the easiest way to fix the problem.

To understand the error, consider carefully what happens when `seq[seq[seq[int]]]` is passed to the `flatten` proc. The call to `concat` will turn this argument to `seq[seq[int]]` and the the the follow-up call to `flatten` with further turn this into `seq[int]`, thus skipping two-levels of sequence types instead of just one.

**Comment by zah** [comment]
I should also say that this is not the best possible way to implement such a `flatten` function, because the current approach performs more copies than necessary.

A better way would be to split the implementation in three parts:

1) a `flattenedCount` proc that computes the number of elements in the final flattened sequence (it will be implemented just like the current `flatten` proc)

2) a `flattenedItems` iterator or a `flattenedCopy` proc capable of traversing an arbitrary nested structure of sequences.

3) a `flatten` proc using 1) and 2) to compute the final result.
