### ISSUE TITLE
parseCookies is not handling HttpOnly and Secure

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#5716]
HttpOnly and Secure are flags often used in cookies. parseCookies is handling only key=value items:

``` 
parseCookies "user=XYZ; Expires=Sun, 17-Jan-2038 19:14:07 GMT; HttpOnly; Secure"
```

**Comment by FedericoCeratto** [comment]
Related to #5721

**Comment by JordanMajd** [comment]
I'm working on this along with unit tests, should PR'd in the next day.

**Comment by FedericoCeratto** [comment]
@JordanMajd me too, I have a parser for the Set-Cookie header ready.

**Comment by JordanMajd** [comment]
After some thought, I have a few genuine questions to which I'm not sure what the answer is.

1. Should `client->server` cookie code be separated from `server->client` cookie code?

The `Set-Cookie`  header is sent in a response from a server to a client; where the `Cookie` header is sent in a request from a client to the server. 

Generally, a server cookie package has the functionality to parse the `Cookie` header and also set the `Set-Cookie` header. A client cookie package has the functionality to parse the `Set-Cookie` header and also set the `Cookie` header.

It would seem a bit odd for a single package to have both feature sets. If I am developing client logic I would only want the client functionality, likewise if I am developing server logic I would only want the server functionality. Instead it would make sense for these to be two separate packages.

2. Should both client and server cookie parsing be a part of the Nim standard library?

Many languages don't have any cookie parsing in their standard libraries, other languages (Python) only have server side cookie parsing - but not client.  This isn't much of an issue for any of these languages, because outside packages can be installed for the desired functionality.

**Comment by FedericoCeratto** [comment]
The Cookie and Set-Cookie semantics are quite different. I'm implementing the Set-Cookie parser and a cookiejar at https://github.com/FedericoCeratto/nim-httpauth/blob/master/cookiejar.nim

**Comment by JordanMajd** [comment]
Yes, they are quite different. Which is why I asked the previous questions. It would seem that `parseCookie` should not parse `HttpOnly` and `Secure` because that is not part of the `Cookie` header but part of the `Set-Cookie` header.

**Comment by ringabout** [comment]
I also have a cookiejar library handling cookies

https://github.com/planety/cookiejar/blob/master/src/cookiejar/cookies.nim

It supports constructing Cookie object from string
https://github.com/planety/cookiejar/blob/aa96ca83a7c154f08803c7715f054d77f2d623cf/src/cookiejar/cookies.nim#L112

> Yes, they are quite different. Which is why I asked the previous questions. It would seem that parseCookie should not parse HttpOnly and Secure because that is not part of the Cookie header but part of the Set-Cookie header.

I agree. `cookies` module is really simple. There is no cookie object in cookies module. It is not the responsibility of `parseCookie` to handle `HttpOnly` attributes. `parseCookie` is used to parse Cookie headers from client.
