### ISSUE TITLE
[Regression] code no longer compiles

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#5733]
This code used to compile, but now it doesn't. I don't claim this code is valid, but some time ago it looked pretty valid to me :)

```nim
proc foo(a: int, b: int) = discard
proc bar(p: proc()) = discard

foo 5, bar do():
    echo 1
```
```
test.nim(4, 5) Error: type mismatch: got (int literal(5), void)
but expected one of:
proc foo(a: int; b: int)
```

**Comment by zah** [comment]
Yes, this is intentional change I recently introduced in the parser.

The foo call will be now parsed as `foo(5, bar, closure)` as this seemed to be a more natural interpretation of the do notation. You can introduce a variable for the result of the `bar` call or you can put it in brackets.

**Comment by yglukhov** [comment]
Ok, thanks for clarification. I don't really mind but note that `foo(5, bar(closure))` way of parsing can be controlled more easily (and looks nicer) when you add brackets.
Old way:
```nim
foo 5, bar do(): # parsed as foo(5, bar(closure))
  echo 1
# vs
foo(5, bar) do(): # parsed as foo(5, bar, closure)
  echo 1
```
New way:
```nim
foo 5, bar do(): # parsed as foo(5, bar, closure)
  echo 1
# vs
foo 5, (bar do(): # parsed as foo(5, bar(closure))
  echo 1
  )
# or
let tmp = bar do():
  echo 1
foo 5, tmp
```
As you can see the new grammar is a bit bulkier when you want to control `do` precedence.

**Comment by zah** [comment]
That's an interesting take on it, but I think code like this comes relatively rare in practice, while a much more common form that I appreciate is the following:

``` Nim
btn.on "click" do:
   ...
```

This is especially true with the JavaScript back-end. Since Nim's "command syntax" is equivalent to normal function calls in all other situations, it would be strange if the code above is parsed in a different way than `btn.on("click") do:`.

**Comment by yglukhov** [comment]
Well ok,  makes sense.
