### ISSUE TITLE
Move libsvm to an external nimble module

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#5786]
In its current state, it does not make much sense to keep the module `libsvm` in the standard library.

It seems abandoned (still refers to libsvm 3.12, while latest version is 3.22) and without tests. Moreover, it does not look like a core module for a stdlib, and it is a low level wrapper, so it is not very friendly anyway.

I think it would make more sense to move it to a nimble package (as I believe it happened to Redis)

**Comment by genotrance** [comment]
I've created a nimgen based wrapper for libsvm [here](https://github.com/genotrance/libsvm). Please evaluate and see if it is a sufficient replacement for the native version. You will need to install it in order to see the generated nim wrappers. Unlike the native version, this version compiles in svm.cpp rather than binding to a library. I can change it to the other method if that is preferred.

> git clone https://github.com/genotrance/libsvm
> cd libsvm
> nimble install

I don't have any good tests yet but if you have any known code using libsvm, I can verify that it continues to work.

**Comment by dom96** [comment]
Fixing this issue is just a case of removing the libsvm wrapper from the stdlib (and putting it in some nimble package in case anyone out there still depends on it).

Your wrapper is probably better, but it's existence isn't relevant to this issue :)

**Comment by genotrance** [comment]
Ya the idea was to get the wrapper reviewed before ripping it out. Considering it's in stdlib, I figured you would want to see it.

I'll submit a PR to remove libsvm.nim.

**Comment by dom96** [comment]
@genotrance your repo doesn't seem to contain the .nim file?

**Comment by genotrance** [comment]
This is because it uses nimgen to download libsvm from GitHub and generate the wrapper. This way the wrapper is in sync with the latest version. 

See libsvm.cfg for details.

**Comment by dom96** [comment]
I see :)
