### ISSUE TITLE
Infinite recursion in `hashType` with cyclic tuple types

### ISSUE THREAD

**Issue by zah** [nim-lang/Nim#5891]
``` nim
import asyncdispatch

type
  SomeTuple = ref tuple
    retFuture: Future[SomeTuple]
    
var x: SomeTuple
```
This results in a stack overflow, caused by an infinite recursion in `hashType`. Changing the `tuple` type to an `object` type fixes the problem.

**Comment by Araq** [comment]
Type recursions need to go through a nominal type. This code was never valid, the compiler needs to reject it.

**Comment by philip-wernersbach** [comment]
@zah @Araq What caused this regression? This used to work, [influx-mysql](https://github.com/philip-wernersbach/influx-mysql) uses this, and we use it in production at my company, so I question the assumption that this is not valid. This also makes sense logically, since `SomeTuple` is a `ref tuple`, `retFuture` is simply storing a reference, which is casted to `SomeTuple` at runtime.

**Comment by philip-wernersbach** [comment]
I just tried changing all of the `tuple`s in influx-mysql to `object`s, and this error still occurs.

**Comment by zah** [comment]
@philip-wernersbach, can you push the tuple-to-object change to your repo (possibly in a branch). I might have a chance to look at it this Friday.

**Comment by philip-wernersbach** [comment]
Nevermind, it was my fault. My reflists code used a cyclic tuple type as well. After updating that to use an object type, it worked.

**Comment by Yardanico** [comment]
Compiles fine in devel

**Comment by Araq** [comment]
But it shouldn't and we have an incomplete PR addressing this problem.

**Comment by Araq** [comment]
This now compiles.
