### ISSUE TITLE
Install script doesn't install the nimble binary

### ISSUE THREAD

**Issue by felixplesoianu** [nim-lang/Nim#5912]
After downloading the source tarball from <https://nim-lang.org/download/nim-0.17.0.tar.xz>, running the build commands and checking that the compiler and tools work, I decided to run `sh install.sh /opt`. After doing that, however, it turned out that the `/opt/nim/bin/` directory only contains the `nim` binary, and none of the other tools. Indeed, `nimble` and the rest aren't even mentioned in `install.sh`. I can of course copy them over manually, but doesn't that kind of defeat the point of having an install script?

By the same token, it would be nice if the install script also symlinked the tools into `/usr/local/bin`. Thank you.

Edit: on second thought, it occurs to me that `nimble` is meant to be installed and used locally by each user, e.g. in `~/bin`. But the documentation doesn't make that clear.

**Comment by dom96** [comment]
You're right, the ``install.sh`` script should install Nimble.

I don't think it should perform any symlinking. If you want it to it can install the binaries into /usr/local too.

**Comment by Araq** [comment]
The ``install.sh`` script is not supported anyway. Install by patching your PATH or via your package manager.

**Comment by dom96** [comment]
If it's not supported then it shouldn't be in the .tar.xz

On 31 May 2017 9:27 am, "Andreas Rumpf" <notifications@github.com> wrote:

Closed #5912 <https://github.com/nim-lang/Nim/issues/5912>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nim-lang/Nim/issues/5912#event-1103745645>, or mute the
thread
