### ISSUE TITLE
0.17.0 Regression: Statement macro from tutorial does not compile anymore

### ISSUE THREAD

**Issue by flyx** [nim-lang/Nim#5918]
From [here][1]:

```nim
macro case_token(n: typed): typed =
  # creates a lexical analyzer from regular expressions
  # ... (implementation is an exercise for the reader :-)
  discard

case_token: # this colon tells the parser it is a macro statement
of r"[A-Za-z_]+[A-Za-z_0-9]*":
  return tkIdentifier
of r"0-9+":
  return tkInteger
of r"[\+\-\*\?]+":
  return tkOperator
else:
  return tkUnknown
```

Compiler output:

```
test1.nim(7, 1) Error: invalid expression: '
of r"[A-Za-z_]+[A-Za-z_0-9]*":
  return tkIdentifier'
```

 [1]: https://nim-lang.org/docs/tut2.html#macros-statement-macros

**Comment by zah** [comment]
The parsing logic in the compiler has changed a little bit and now macros such as `case_token` will receive each of the `of` and `else` branches as separate parameters. This was decided in order to make the behavior more consistent with `do` blocks.

The fix is to turn the `n` parameter into `varargs[untyped]`. I'll push a commit that fixes the manual and improves the error message a bit.
