### ISSUE TITLE
listDirs ignores symbolic links to directories on Linux

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#5927]
Nim version: 0.17 stable
Operating system: Linux

The `listDirs` proc from the `nimscript` module omits symbolic links to directories from the seqence of directory names it returns. This could confuse devs because `listFiles` _does_ return symlinks to regular files.

**Comment by Parashurama** [comment]
This might be unexpected behavior on linux (and other platforms with symbolic links)
but it appear to be  deliberate choice to avoid cases of endless recursion.
see: https://github.com/nim-lang/Nim/blob/92c2a51bf763c16579/compiler/scriptconfig.nim#L53
```
  # Idea: Treat link to file as a file, but ignore link to directory to prevent
  # endless recursions out of the box.
```
EDIT: @Araq Actually I'm not sure it's relevant since listDirs doesn't walk recursively.
I think we can safely change 
```nim
listDirs(a, {pcDir})
```
to
```nim
listDirs(a, {pcDir, pcLinkToDir})
```

**Comment by Araq** [comment]
Yes, it doesn't recurse itself but it can be used in a recursion.

**Comment by noxpo** [comment]
If there is a recursion problem, it would have to be solved differently IMHO. Now, links to directories are "unlistable", which is really unintuitive.

**Comment by Araq** [comment]
I think the current solution is good enough.
