### ISSUE TITLE
Destructor declared with var param doesn't work with let variables

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#6112]
I think this is supposed to work, according to the manual:
```nim
type
  MyObj = object

proc `=destroy`(obj: var MyObj) =
  discard

proc someProc() =
  let o = MyObj()

someProc()
```
Error:
```
sample.nim(8, 7) Error: type mismatch: got (MyObj)
but expected one of:
proc `=destroy`(obj: var MyObj)
for a 'var' type a variable needs to be passed, but 'o' is immutable
```
Git hash: 4846ce0f4107746811da3f6a4b7b606ff1ba298d

The destructor signature can be changed not to use `var`, but in real case that makes you perform cast/unsafeAddr within the destructor which shouldn't be required.

**Comment by andreaferretti** [comment]
I am not sure what is the issue here. Is it that

* `=destroy` does not accept `o` (which is correct, since you explicitly ask for a `var` parameter), or
* `=destroy` in your particular case would require `casts?

If it is the second case, maybe you should port a bigger example of what you are trying to achieve with the destructor. There are many use cases (closing files, sockets and so on) that do not require casts at all.

**Comment by endragor** [comment]
I don't have a problem finding a workaround for what I want to achieve. It's just that the manual states the destructor should be declared with `var` type, which makes logical sense, but it doesn't work for one of the destructible contexts (let assignment) as described in the manual.
In my case specifically I'm calling a C library procedure that performs the destruction. The procedure is declared with `var` parameter because it modifies contents of the object in the process (e.g. sets pointers to nil so that they cannot be used again).

**Comment by andreaferretti** [comment]
I don't see where the manual states that the destructor should be declared with `var` type (although the example actually uses a `var`).

In your case, I guess that the C function takes a`* sometype` as argument - maybe in this case you could introduce another layer of indirection, for instance

```nim
type MyWrapperType = object
  content: ptr SomeType
```

and then  write a destructor for `MyWrapperType`, which could pass the inner pointer to the C function.

Just an idea. In general, I guess (but I am not sure) that variables defined with `let` may be optimized out, so that they are actually never materialized on the stack (just as expression that appear in intermediate computations may never be materialized outside of registers). In this case, there would not be an actual pointer to pass around, but one could still make use of destructors (say to close a file handle).

**Comment by dom96** [comment]
Can this be closed?

**Comment by Araq** [comment]
No.

**Comment by Araq** [comment]
Compiles with ``--newruntime``.
