### ISSUE TITLE
'discard getch' not working when called without brackets (0.17.0)

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#6140]
`discard getch()` work correctly,
`discard getch` gets skipped entirely.

**Comment by bluenote10** [comment]
I don't think this is a bug, because `getch` only references the proc and does not call it. You also cannot do: 

```nimrod
proc test() =
  echo "test"

test()
test
#  Error: expression 'test' is of type 'proc (){.gcsafe, locks: 0.}' and has to be discarded; for a function call use ()
```

This must be the case, otherwise you wouldn't be able to pass the proc `getch` as a parameter to another proc -- you would automatically call it (see Scala's `_` suffix for an alternative way of handling it). Note that omitting parentheses works in e.g. `o.getch` because `o` becomes a parameter.

**Comment by Araq** [comment]
bluenote10 is entirely correct. No bug here.
