### ISSUE TITLE
Async http client crashes after some time

### ISSUE THREAD

**Issue by Yardanico** [nim-lang/Nim#6155]
This program crashes after some time (like 5-10 minutes):
```nim
import asyncdispatch, httpclient

let client = newAsyncHttpClient()

proc doWork() {.async.} = 
  while true:
    discard await client.getContent("http://httpbin.org/get")
    await sleepAsync(2500)

waitFor doWork()
```
With error: https://gist.github.com/Yardanico/3e502d1f8215362159a95f2c9186e940

**Comment by dom96** [comment]
Here is the responsible code: https://github.com/nim-lang/Nim/blob/devel/lib/pure/httpclient.nim#L1021

My guess is that the remote server times you out because it thinks that you won't send any more requests. A good solution might be to fix httpclient so that it reconnects to the server if such a situation arises.

To do that I think we need to modify `parseResponse` a bit. It needs to take into account how much data was read:

* If some data has been read (but not all of it) and we get disconnected then fail with the same error.
* If no data has been read and we get disconnected then try reconnecting.

**Comment by dom96** [comment]
Looks like this was fixed here https://github.com/nim-lang/Nim/commit/ac67f5eda57a91e97d16b31dcdea65fb39de9fc5#diff-232b8586e82bf9dedf2b071ec6fd52aa

**Comment by yglukhov** [comment]
@Yardanico, any chance to publish the error from the gist to here? Because the gist is dead (

**Comment by Yardanico** [comment]
@yglukhov is it?
https://gist.githubusercontent.com/Yardanico/3e502d1f8215362159a95f2c9186e940/raw/519c0e4a2654ceb10386e7f3d558d22ebd83e97d/error

**Comment by yglukhov** [comment]
Ok, it works now. Strange.
