### ISSUE TITLE
Placement of the nimsuggest.log

### ISSUE THREAD

**Issue by samdmarshall** [nim-lang/Nim#6199]
When using nim-mode in emacs (with nimsuggest), a new log file gets created in my home directory (`nimsuggest.log`) which contains what i assume is debugging output from the `nimsuggest` tool. This default placement is really not ideal and was wondering if there was any way I could direct it to a more appropriate directory for writing a log to.

**Comment by dom96** [comment]
I noticed this myself for VS code. Strange that nimsuggest would create that, this clutter should definitely not be created by default.

**Comment by krux02** [comment]
I removed the "question" tag, because the question part is solved my now. The real issue is "nimsuggest.log shouldn't be created in home". I just checked it nimsuggest.log is still generated. My old log had the size of over 1 GB (that is a problem). But that file was really old I don't know if the same amount of spam is still being generated.

**Comment by Araq** [comment]
We should simply not generate this file unless nimsuggest is started in a debug/logging mode.

**Comment by samdmarshall** [comment]
did this ship in 0.19.4? or is it still not in a public release yet?
