### ISSUE TITLE
Specify Compile backend via pragma and/or in config file

### ISSUE THREAD

**Issue by couven92** [nim-lang/Nim#6201]
ref.: [Any method to set backend by configuration or nim code? - Nim Forum](https://forum.nim-lang.org/t/3089)

As suggested in the forums it would be nice to have a `backend` pragma and/or a backend config key to put into a `.cfg` file in your Nim project.

With this `nim compile` should use the config- or pragma-specified compile backend and only fall back to the default c backend if none is specified.

When explicitly specifying the backend (e.g. `nim compileToC`) and a different pragma or config is encountered we should either raise a warning or fail an error message that the wrong compile backend is used.

**Comment by krux02** [comment]
Yes, I agree. A particular use case would be write a wrapper for a c++ library that does not require the entire project to be compiled to c++. It could be a bit tough to implement though, because function ``foo`` in C cannot be linked together with function ``foo`` in C++, because of name mangeling.

**Comment by Araq** [comment]
Let's give it a shot for the upcoming release.

**Comment by Araq** [comment]
Use this in your Nimscript file:

```nim

if getCommand() == "c":
  setCommand("js")

```

Turns out this was implemted quite some time ago. :-)
