### ISSUE TITLE
Trouble with bound `char *` from C libraries.

### ISSUE THREAD

**Issue by define-private-public** [nim-lang/Nim#6324]
Coming in from this issue on my `stb_image` bindings: https://github.com/define-private-public/stb_image-Nim/issues/3

I sear when I updated the bindings last month my tests did work, though I think that machine might have been using Nim v0.16 or something like that.  Following the trace log, issue is coming from this chunk of code:

```nim
proc stbi_failure_reason(): cstring
  {.importc: "stbi_failure_reason", noDecl.}


## Get an error message for why a read might have failed.  This is not a
## threadsafe function.
proc failureReason*(): string =
  return $stbi_failure_reason()
```

`stbi_failure_reason()` is returning a `nil` type, thus making the `$` fail.  I then just had the proc return an empty string.

On top of that, the issues seems to be with any of the bound functions that return `char *` type.  E.g. `stbi_load()` returned a `nil`, though it's parameters are populated. (Source link: https://github.com/define-private-public/stb_image-Nim/blob/df9bd0f0327ef072aa22cdb110e6aeb850cc8441/stb_image/read.nim#L47).

I'm wondering if some oppsie happened recently in Nim.  Before anyone asks, stb should be good.

**Comment by edubart** [comment]
I've take a look into that, and the problem is using .noDecl

When .noDecl is used stbi_failure_reason() and stbi_load() will no be declared in the nim generated C code, as your's read.nim generated code does not include either a header with the stbi_load() and stbi_failure_reason() body declaration it's never declarated, thus its body will be implied from the call. 

GCC usually warns about this, as you can see if you compilewith GCC warnings on:
```
gcc -c  -Wall -I/usr/lib/nim -o /tmp/stb_image-Nim/nimcache/stb_image_read.o /tmp/stb_image-Nim/nimcache/stb_image_read.c

/tmp/stb_image-Nim/nimcache/stb_image_read.c: In function ‘failureReason_jGKpadXTf7KJCfBI03WXEg’:
/tmp/stb_image-Nim/nimcache/stb_image_read.c:325:8: warning: implicit declaration of function ‘stbi_failure_reason’ [-Wimplicit-function-declaration]
...
```

The problem is that when the body is implied gcc always treats the body return as an int.
Thus gcc thinks that stbi_load() and stbi_failure_reason() are returning ints, the code will compile and int will be cast to a pointer, but on x64 the pointer is a long, so it will be an invalid pointer.

To confirm I digged and printed out the pointer in nim and before stbi_load():

```
stdbi_load ptr: 0x55a46aecc8b0
read.c:load ptr: 0x6aecc8b0
```

As you can see half of the pointer is returned by the function.

Removing .noDecl from the procs made you library work again.

**Comment by define-private-public** [comment]
Hey, it works.  Thanks for the fix.  I think this might have happened because before I was embedding the .h file with the `.emit.` pragma instead of using `.compile.` (which I am right now).
