### ISSUE TITLE
stdout should be flushed by the compiler

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#635]
As discussed on IRC (http://build.nim-lang.org/irclogs/25-10-2013.html) there are problems caused by buffering when reading the output from the compiler using a separate application (e.g. babel). This is evident when GCC for example decides to write to stderr. The first lines of output may then contain the error which causes confusion.

The compiler should flush its stdout stream every time stdout is written to.

**Comment by BigBoneDaddy** [comment]
@dom96 The URL is dead!

**Comment by reactormonk** [comment]
@BigBoneDaddy should work again.

**Comment by dom96** [comment]
http://irclogs.nim-lang.org/25-10-2013.html

**Comment by nanoant** [comment]
@Araq @dom @reactormonk  FYI `stderr` is not buffered, where `stdout` is by default. I think the problem is not lack of `flush(...)`, but that Nim outputs diagnostics to `stdout` rather than `stderr` which outputs immediately, so 48036fa3d997e86c8f73738681ec12ea1fce8076 IMHO is not a correct solution.

Clang, GCC, Ruby, Python and numerous other tools output diagnostics to `stderr` and I think Nim should obey that standard too.

This is also especially important when you want to use the compiler via pipe, so diagnostics are not cluttering `stdout`, eg.:

    cc -c -S -o - source.c | as - -o source.o
