### ISSUE TITLE
range initialization: [ProveInit] hint: Cannot prove that

### ISSUE THREAD

**Issue by jlp765** [nim-lang/Nim#6474]
The following raises the [ProveInit] hint, when it has been initialized
```
var
  t: range['a'..'z'] = 'a'
```

I assume if it is initialized, the compiler should be able to prove it has been initialized :-)

**Comment by tawsi-melek** [comment]
I'm on Nim devel (0.18.1 says nim -v) and I have this problem.

Code example:
```nim
type
  Glyph = range['a'..'z']

type
  Cell = tuple
    g: Glyph
    fg, bg: int

var c: Cell
```

Last line is the problematic one: cannot prove init blah blah.

The program compiles and run fine though.

**Comment by andreaferretti** [comment]
In your case, the compiler does not know how to initialize `Cell`, which in turn is because of `g`. In general the compiler uses 0 as a default value, but the 0 of `char` is not in the range `'a' .. 'z'`, which would make the cell invalid. I am afraid you should actually initialize `c`, say

```
var c = Cell(g: 'a', fg: 0, bg: 0)
```

**Comment by tawsi-melek** [comment]
Yeah, GULPF on the Nim forum explained that to me. 

Question: are there any plans to update range types so that they're initialized to rangeType.low? From an end-user pov, I can't see why that shouldn't be the case; I mean, it's not like the compiler doesn't already have all the info it needs. Though I guess that would complicate the implementation a little bit.

**Comment by Araq** [comment]
> Question: are there any plans to update range types so that they're initialized to rangeType.low? 

Yes, in fact something like this is planned:

```nim

type
  Foo = object
    x: int = 1 # construct defaults with 1
```
