### ISSUE TITLE
Need support for Visual Studio 2017

### ISSUE THREAD

**Issue by GooRoo** [nim-lang/Nim#6540]
Just to make it clear from the very beginning: C++ compiler from Visual Studio 2017 is able to build Nim programs just fine. 

However, `vccenv` bundled with the latest Nim release is **not** able to find and run `vcvarsall.bat` because folder structure in VS2017 was changed comparing to VS2015 and previous versions. Moreover, it looks like the old approach with environment variables pointing to Visual Studio Tools folder won't work anymore and a special separate tool [`vswhere`](https://github.com/Microsoft/vswhere) should be used instead.

**Comment by dom96** [comment]
CC @couven92

**Comment by couven92** [comment]
@GooRoo yes, that is correct. I am working on `vccexe` to include VS2017 support, but in order to that properly I am doing sth. along the lines of the `vswhere` tool that is bundled with the Visual Studio Installer.

If you download https://github.com/couven92/Nim/archive/devel.zip from my Nim fork, you get a slightly enhanced version of `vccexe` that supports the `--vcvarsall` command-line flag which allows you to specify the location of the VS2017 `vcvarsall.bat`. Currently, while in development I use the `nim.cfg` in `%APPDATA%` to exand the following options with the `--vcvarsall` argument:
``` nim
cc = vcc
vcc.options.always %= "--vcvarsall: \"YOUR VS2017 VCVARSALL.BAT\" ${vcc.options.always}"
vcc.options.linker %= "--vcvarsall: \"YOUR VS2017 VCVARSALL.BAT\" ${vcc.options.linker}"
vcc.cpp.options.always %= "--vcvarsall: \"YOUR VS2017 VCVARSALL.BAT\" ${vcc.cpp.options.always}"
vcc.cpp.options.linker %= "--vcvarsall: \"YOUR VS2017 VCVARSALL.BAT\" ${vcc.cpp.options.linker}"
```

Sorry for the wonky temporary workaround, I am working on VS2017 support, but I am currently in Master-Thesis-Hand-in mode. So from November 2017 onwards I will have *more* time to finish this up.  
**Help is definitely welcome if you like to play with Nim and COM on Windows** :wink:

PR #5575 tracks my work on enhancing `vccexe`, but the PR is waiting for me to finish VS2017 support.

**Comment by GooRoo** [comment]
@couven92 I would help if I could. However, I hate COM :)

I resolved the problem with a dirty hack on my local PC, so it's not a blocker for me. Just created an issue 'cause it can be useful for someone else. Glad that you are working on it.

**Comment by nc-x** [comment]
This has been fixed and can be closed.
