### ISSUE TITLE
Assignment for strings inside a block doesn't has "copy semantic"?

### ISSUE THREAD

**Issue by kvinwang** [nim-lang/Nim#6541]
```nim
proc test() =
    var s0 = "a"
    block:
        let s: string = s0
        echo "==="
        echo s
        s0.add('b')
        echo s # should be "a" or "ab"?

    while true:
        let s: string = s0
        echo "==="
        echo s
        s0.add('c')
        echo s 
        break

    for i in 0..0:
        let s: string = s0
        echo "==="
        echo s
        s0.add('d')
        echo s

test()

```

output:
```
===
a
ab
===
ab
abc
===
abc
abcd
```

**Comment by andreaferretti** [comment]
It does work as you expect if you change all `let s` into `var s`. I am not sure whether this is expected or not (guess not)

**Comment by loongw** [comment]
Oh, just awared it's not the thing of *block*, but different sematic between proc and global code:
```nim
proc test() =
  var s0 = "a"
  let s = s0
  echo "===in proc=="
  echo s
  s0.add('b')
  echo s

test()

var s0 = "a"
let s = s0
echo "===global==="
echo s
s0.add('b')
echo s
```

output:
```
===in proc==
a
ab
===global===
a
a
```
It's weird.
Is there any document or comment for this behavior? or just a bug?

**Comment by Araq** [comment]
Just a bug.

**Comment by ibutra** [comment]
I have a question regarding this because I am currently working of fixing this:

Is the wanted behaviour to always copy strings i.e:
`
var s0 = "a"
var s = s0
s0.add('b')
echo s #this should give 'a'
`
or should it only be a copy if it is declared with 'let'?

I personally would think it is always a copy since it is not a ref type.

**Comment by Araq** [comment]
It needs to always copy unless it can be proven to be movable.

**Comment by timotheecour** [comment]
it's quite nasty, code below shows (with recent devel  64168d4aea282a82230cc41064890db8a51566d0):
```
===proc===
(a1: "foobarbaz", a2: "foobar", a3: 10, a4: @[1, 2])
(a1: "foobarbaz", a2: "foobarb", a3: 10, a4: @[1, 123])
===global===
(a1: "foobarbaz", a2: "foobar", a3: 10, a4: @[1, 2])
(a1: "foobarbaz", a2: "foobar", a3: 10, a4: @[1, 2])
```

* seq has same problem as string
* depending on string length (a1 vs a2) the string will be modified or not (because a reallocation happens or not). So any code that relies on existing broken behavior is buggy

```nim
  type Foo = object
    a1: string
    a2: string
    a3: int
    a4: seq[int]

  template fun()=
    var s0 = Foo(a1: "foobarbaz", a2: "foobar", a3: 10, a4: @[1,2])
    let s = s0
    echo s
    s0.a1.add 'b'
    s0.a2.add 'b'
    s0.a3.inc
    s0.a4[1] = 123
    echo s

  proc test() =
    fun()
  echo "===proc==="
  test()
  echo "===global==="
  fun()
```

**Comment by ringabout** [comment]
It works with ARC/ORC.
