### ISSUE TITLE
doc2 outputs in current work dir

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6583]
This isn't consistent with the way output binaries are generated. (This is possibly a duplicate).

**Comment by FedericoCeratto** [comment]
Confusingly, "nim doc" behaves like "nim c".

**Comment by narimiran** [comment]
Tested with v0.19.0:

Both `nim doc` and `nim doc2` create outputs in the subdirectory. E.g. `nim doc lib/pure/collections/sequtils.nim` produces `./lib/pure/collections/sequtils.html`.

**Comment by timotheecour** [comment]
this should be re-opened; a regression happened since 0.19.0 and it outputs again in $pwd.
see `getOutFile` (`result = conf.outDir / changeFileExt(filename, ext)` which resolves to `$pwd/changeFileExt(filename, ext)` when conf.outDir is empty)

the bug is that `"" / path` resolves to `path` instead of giving an error
