### ISSUE TITLE
Times cannot represent time before "1970-01-01T00:00:00+03:00" on windows

### ISSUE THREAD

**Issue by abijahm** [nim-lang/Nim#6668]
example code
```
import times
echo parse("1970-01-01T00:00:00+03:00","yyyy-MM-dd'T'HH-mm-sszzz")
echo getTime() - 48.years
#only works on js backend
```
stacktrace
```
Traceback (most recent call last)
nrpltmp.nim(2)           nrpltmp
times.nim(514)           -
times.nim(417)           -
times.nim(1258)          getLocalTime
system.nim(3613)         failedAssertImpl
system.nim(3605)         raiseAssert
system.nim(2724)         sysFatal
Error: unhandled exception: not isNil(lt)  [AssertionError]
Error: execution of an external program failed: 'bin\nrpltmp
```
```
C:\nrpl>nim -v
Nim Compiler Version 0.17.2 (2017-09-07) [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 811fbdafd958443ddac98ad58c77245860b38620
active boot switches: -d:release

```

**Comment by skilchen** [comment]
Nim inherits these limitations from the C runtime library in use. The Microsoft one indeed allows no dates earlier than 1970-01-01. We can extend the range of possible date values by using the date/time functions from the Win API. I made an experiment to do that. Please see my changed times.nim here: 
https://play.nim-lang.org/?gist=9dad1fd6a88986fc940272afd805c297 
This extends the range of possible dates on Windows from 1600-01-01 until somewhere after 30000-01-01 (it is not entirely clear, what the exact upper limit is, i didn't try to find out myself.)
I don't think that a PR with these changes would be accepted, because @GULPF is already on the way to make times.nim better. Unfortunately reimplementing C's localtime etc. in pure Nim requires a considerable effort.

**Comment by GULPF** [comment]
@skilchen Such a PR will be a lot easier to create after my PR is merged. The only change required is to supply Windows specific implementations of `zoneInfoFromTz` and `zoneInfoFromUtc` that uses the dreaded Win API.

Here is how phobos does it (with the year limits 1601 to 30827): https://github.com/dlang/phobos/blob/0308bd6b9a080501b931f43d1e39b1c3cf79c29a/std/datetime/timezone.d#L3005. Note that the year range be extended by using the same tz rules that are used at the limits (1601 and 30827), which I think is desired.

**Comment by treeform** [comment]
I wrote a time/timezone library: https://github.com/treeform/chrono
It supports times before 1970, maybe give it a try? Feature requests welcome.

**Comment by skilchen** [comment]
I would welcome it, if the timezone work from @treeform could be merged into stdlibs times module.

**Comment by GULPF** [comment]
For reference, this is partially fixed by #6978. There is no longer a crash, but timezone data older than `1970-01-01T00:00:00Z` is ignored.

**Comment by Araq** [comment]
@skilchen can you reapply your patch somehow? The refactorings for times.nim are complete as far as I know.

**Comment by skilchen** [comment]
The main issue raised here is solved by @GULPF. IMHO you can close this issue. I think its good enough to extrapolate to Timezone settings from 1970-01-01 backwards. The Win-Api isn't really better: it extrapolates the earliest available settings backwards. For you in the Windows timezone "W. Europe Standard Time" (which is not a `dynamic timezone` in windows speak) that means that the current DST settings are extrapolated backwards, which imho is even worse than extrapolating only the standard utcoffset backwards. Somebody in need of better timezone support, simply shouldn't use the stdlib.

Another issue with the Win-Api is that it only has millisecond resolution. And then: using the Win-Api would add a whole bunch of code to times.nim for relatively little benefit (see below).

The goal for Nim's times module should be to become mostly independent of what the runtime libraries or platform apis have to offer in the matter of date/time. Anything except reading the current clock should be implemented in pure Nim because the available runtime-library/api support for date/time is mostly rubbish left over from the stone-age. 

times.nim would be even better, if it had no calls to `localtime` and relatives. I am sure that @GULPF will eventually come up with such a beast. AFAIK he already has a timezones package that goes in this direction and could become part of the stdlib.

Just as a deterrent example, here is my `getLocalTime` using the Win Api and runnable using the current times.nim:
```nim
import times

when defined(windows):
  import winlean
  
  type 
    WCHAR = int16
    USHORT = uint16
    
    SYSTEMTIME* {.final, pure.} = object
      wYear*: int16
      wMonth*: int16
      wDayOfWeek*: int16
      wDay*: int16
      wHour*: int16
      wMinute*: int16
      wSecond*: int16
      wMilliseconds*: int16
  
    TIME_ZONE_INFORMATION* {.final, pure.} = object
      Bias*: LONG
      StandardName*: array[0..31, WCHAR]
      StandardDate*: SYSTEMTIME
      StandardBias*: LONG
      DaylightName*: array[0..31, WCHAR]
      DaylightDate*: SYSTEMTIME
      DaylightBias*: LONG

    DYNAMIC_TIME_ZONE_INFORMATION* {.final, pure.} = object
      Bias*: LONG
      StandardName*: array[0..31, WCHAR]
      StandardDate*: SYSTEMTIME
      StandardBias*: LONG
      DaylightName*: array[0..31, WCHAR]
      DaylightDate*: SYSTEMTIME
      DaylightBias*: LONG
      TimeZoneKeyName*: array[0..127, WCHAR]
      DynamicDaylightTimeDisabled*: WINBOOL 
    
    LARGEINT {.union.} = object
      val: int64
      ft: tuple[low: int32, high: int32]
    
  const rateDiff = 10000000'i64 # 100 nsecs
  
  proc fileTimeToSystemTime*(lpFileTime: ptr FILETIME, lpSystemTime: var SYSTEMTIME): bool {.
    importc: "FileTimeToSystemTime", dynlib: "kernel32", stdcall.}

  proc systemTimeToFileTime(lpSystemTime: ptr SYSTEMTIME, lpFileTime: var FILETIME): bool {.
    importc: "SystemTimeToFileTime", dynlib: "kernel32", stdcall.}

  proc systemTimeToTZSpecificLocalTime*(lpTimeZone: ptr TIME_ZONE_INFORMATION,
                                        lpFileTime: ptr SYSTEMTIME, 
                                        lpSystemTime: var SYSTEMTIME): bool {.
    importc: "SystemTimeToTzSpecificLocalTime", dynlib: "kernel32", stdcall.}

  proc getTimeZoneInformationForYear(wYear: USHORT,
                                     pdtzi: ptr DYNAMIC_TIMEZONE_INFORMATION,
                                     ptzi: ptr TIMEZONE_INFORMATION): bool {.
      importc: "GetTimeZoneInformationForYear", dynlib: "kernel32", stdcall.}
  
  proc getLocalTime*(t: Time): DateTime =
    result = DateTime(year: 0, month: Month(1), monthday: 1)
    var wt = toWinTime(initTime(unix = t.toUnix, nanosecond = 0))
    var lrgint: LARGEINT
    lrgint.val = wt
    var ft, lft: FILETIME
    ft.dwLowDateTime = lrgint.ft.low
    ft.dwHighDateTime = lrgint.ft.high
    
    var st: SYSTEMTIME
    var lst: SYSTEMTIME
    var tzinfo: TIME_ZONE_INFORMATION
    
    if fileTimeToSystemTime(addr(ft), st):
      if systemTimeToTZSpecificLocalTime(nil, addr(st), lst):
        if systemTimeToFileTime(addr(lst), lft):
          result.utcoffset = int((rdFileTime(ft) - rdFileTime(lft)) div rateDiff)
          if getTimeZoneInformationForYear(lst.wYear.USHORT, nil, addr tzinfo):
            if (tzinfo.Bias + tzinfo.DaylightBias) * 60 == result.utcoffset:
              result.isDst = true
          result.year = lst.wYear
          result.month = Month(lst.wMonth)
          result.monthday = lst.wDay
          result.hour = lst.wHour
          result.minute = lst.wMinute
          result.second = lst.wSecond
          result.nanosecond = t.nanosecond
          result.timezone = local()
          result.weekday = (if lst.wDayOfWeek == 0: dSun else: WeekDay(lst.wDayOfWeek - 1))
          result.yearday = getDayOfYear(year = result.year, 
                                        month = result.month, 
                                        monthday = result.monthday)
          
when isMainModule:
  const fmtStr = "uuuu-MM-dd HH:mm:ss'.'fffffffffzzz"
  var t = initDateTime(year = 1970, month = Month(1), monthday = 1,
                       hour = 0, minute = 0, second = 0, nanosecond = 0,
                       zone = local()).toTime()
  echo format(t, fmtStr)
  echo format(fromWinTime(toWinTime(t)), fmtStr)
  echo "---"

  var ldt = getLocalTime(t)
  echo repr(ldt)
  echo "==="
  echo format(ldt, fmtStr)
  echo "==="
  echo ""

  ldt = getLocalTime(initTime(unix = -2147483648, 0))
  echo format(ldt, fmtStr)
  
  echo "++++"
  var dt = initDateTime(year = 1900, month = Month(4), monthday = 1,
                        hour = 1, minute = 4, second = 5, nanosecond = 123456789,
                        zone = utc())
  echo "udt: ", format(dt, fmtStr)
  ldt = getLocalTime(dt.toTime())
  echo "ldt: ", format(ldt, fmtStr)
```

**Comment by Araq** [comment]
For me the primary benefit is that we get fewer dependencies to ``libc`` which is always worth it.

**Comment by narimiran** [comment]
> The main issue raised here is solved by @GULPF. IMHO you can close this issue.

Should this be closed?

**Comment by Araq** [comment]
Ok.
