### ISSUE TITLE
Tests which compare floats using == operation, fail on optimized builds (-O2)

### ISSUE THREAD

**Issue by avsej** [nim-lang/Nim#6747]
Tests compare floats with `==` when they should not. Optimization level (e.g. `-O2`) might break behaviour or some platforms (`x86_64` does not seem to be affected). Below is the minimal code, which demonstrates the issue
```nim
import math

proc clean(x: float): float =
  result = round(1.0e8*x).float * 1.0e-8

var x = 0.15 + 0.15
var y = 0.1 + 0.2

doAssert(clean(x) == 0.3)
doAssert(clean(y) == 0.3)
```

The list below shows tests, where such issues has been detected:
* [lib/pure/stats.nim](https://github.com/nim-lang/Nim/blob/v0.17.2/lib/pure/stats.nim#L313)
* [lib/pure/times.nim](https://github.com/nim-lang/Nim/blob/v0.17.2/lib/pure/times.nim#L1395)
* [lib/pure/complex.nim](https://github.com/nim-lang/Nim/blob/v0.17.2/lib/pure/complex.nim#L402)

As a solution, the tests probably should have different type of assertion when working with floats (some examples here: http://floating-point-gui.de/errors/comparison)

**Comment by timotheecour** [comment]
* we now have `almostEqual` for this
* the snippet works with both `nim r main`, or adding -d:danger, or `--passc:-ffasmtmath` or -O2 (but i haven't tried on i686, refs https://github.com/nim-lang/Nim/issues/11837)
* (unrelated but ffasmtmath used to be passed in some cases but not anymore; users can pass it by hand if they understand its semantics)

tests/stdlib/tstats.nim should probably use `almostEqual` instead of `clean` but that's tracked in https://github.com/nim-lang/Nim/issues/11837

I feel like this issue can be closed, given that we have `almostEqual` which can be used as needed

feel free to re-open if there's something more to this
