### ISSUE TITLE
Build and serve docs for PR's as part of CI

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#6781]
It would be useful to have the CI buildbots to generate docs for PRs and host them online (e.g. natively, like CircleCI does, or using S3 buckets)
Additionally add a link to the PR so that people can quickly check if docs looks good.

**Comment by timotheecour** [comment]
added "for PR's" in title since we now build devel docs regularly (daily?) and publish to https://nim-lang.github.io/Nim/lib.html

**Comment by kaushalmodi** [comment]
> devel docs are updated daily

No, they are updated each time Travis CI runs on a commit (so almost every commit). Sometimes a PR has multiple commits, but Travis would run only for the last commit of that PR.

**Comment by narimiran** [comment]
Since I'm now "the documentation guy", I usually review PRs which change the docs.

For smaller changes it is easy to tell if something will (continue) to look right, and for the larger changes I usually locally build the updated docs and visually inspect them.

The number of these docs-changing PRs is (unfortunately) quite low, so I think the effort involved in this (hosting online, disk space, marking PRs for which the docs should be built, etc.) is too high for too small benefit (we now have devel docs so if something breaks, it can be caught there relatively soon).
