### ISSUE TITLE
remove parseopt2 or parseopt

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6818]
Which one?

@zielmicha?

The primary difference seems to be:

https://github.com/nim-lang/Nim/blob/devel/tests/system/params.nim#L16

For parseopt2: ``f[2].key == "a=c"  and f[2].val == "d"``
For parseopt: ``f[2].key == "a" and f[2].val == "c:d"``

**Comment by zielmicha** [comment]
parseopt2 was meant to replace parseopt (parseopt also has problem with whitespace #726)

**Comment by dom96** [comment]
relevant https://github.com/nim-lang/Nim/issues/4620

**Comment by dom96** [comment]
For this example:

```nim
import os
import osproc
import parseopt2
import sequtils

let argv = commandLineParams()

if argv == @[]:
  # this won't work with spaces
  assert execShellCmd(getAppFilename() & " \"foo bar\" --path:\"/i like space/projects\" --aa:bar=a --a=c:d --ab -c --a[baz]:doo") == 0
else:
  let f = toSeq(getopt())
  for a in f:
    echo a
```

With ``parseopt``:

```
(kind: cmdArgument, key: foo bar, val: )
(kind: cmdLongOption, key: path, val: /i like space/projects)
(kind: cmdLongOption, key: aa, val: bar=a)
(kind: cmdLongOption, key: a, val: c:d) # difference here
(kind: cmdLongOption, key: ab, val: )
(kind: cmdShortOption, key: c, val: )
(kind: cmdLongOption, key: a[baz], val: doo)
```

With ``parseopt2``:

```
(kind: cmdArgument, key: foo bar, val: )
(kind: cmdLongOption, key: path, val: /i like space/projects)
(kind: cmdLongOption, key: aa, val: bar=a)
(kind: cmdLongOption, key: a=c, val: d) # difference here
(kind: cmdLongOption, key: ab, val: )
(kind: cmdShortOption, key: c, val: )
```

I don't see that whitespace issue, the only difference seems to be between handling of ``--a=c:d``. I personally think the way ``parseopt`` handles it makes more sense.

**Comment by zielmicha** [comment]
@dom96 Your example works, but you have yourself linked to issue demonstrating the problem: #4620.

I think the best way to solve this problem is to change parseopt2 to handle `--a=c:d` the same way as parseopt (the fact it behaves differently was probably my oversight).

**Comment by dom96** [comment]
Okay, so is #4620 the only issue that parseopt2 solves?

**Comment by zielmicha** [comment]
Most likely yes.

**Comment by c-blake** [comment]
I found it necessary for several reasons to do a ``parseopt3.nim`` when I did https://github.com/c-blake/cligen.  I'm happy to contribute that if people want it.  One thing Araq said in the #4620 was he would be ok with breaking changes if we got POSIX compatibility.  The approach I took is very gentle on end-user command typers, accepting both the ``-d:val`` type syntax as well as POSIX ``-dval``, or ``-d=val`` and so on.  I feel like the current command-line parsing syntax is far more rigid than Nim's actual language syntax.

**Comment by dom96** [comment]
But then how can you distinguish between ``-dval`` meaning ``(key: "d", value: "val")`` vs. ``(key: "dval", value: "")``?

**Comment by c-blake** [comment]
My API lets you/makes you tell the parser which long & short option keys take no arguments.  That is analogous to the getopt(3) API where you have to specify such.  I didn't see a way to break the ambiguity without that requirement.

**Comment by c-blake** [comment]
Admittedly, this puts slightly more work on command-authors to require slightly less work on command-typers, but that seems like a good trade off to me.

**Comment by c-blake** [comment]
Also, I chose the reverse of getopt(3) in having the command-author specify non-argument taking keys.  It would be trivial to reverse that logical sense of NoArg vs. some HasArg. It probably wouldn't be so hard to have the API take *either* NoArg or HasArg lists and let the caller choose the least onerous (but only one per parser object).  I'm all for flexibility wherever one can find it, and no other commands I use require me to type all those pesky ":"s.

**Comment by Araq** [comment]
>  I feel like the current command-line parsing syntax is far more rigid than Nim's actual language syntax.

Well as you noted, the reason for this is that I **love** to be able to parse command line arguments without a "symbol table" (without having to define the list of available options) just like Nim's actual language syntax. IMO the right tradeoff was made here and Posix's design is just wrong. If the machine cannot parse it without knowing the available options, neither can the programmer.

**Comment by c-blake** [comment]
Well, you seemed a lot more open to being POSIX-y a little over a year ago in #4620 than you do today.  If you see a way to be more POSIX-y without a symbol table, that would be cool, too.  It doesn't sound like you do, though.

I'm personally in favor of even less work on CLI authors (as per cligen).  It just feels wrong to me that CLI users/command-typers lose out.  Users probably type the options to commands many more times than CLI authors write parsers. Reasonable folks can differ, though.

In terms of this particular issue of removing one of parseopt and parsopt2, given that in the wider world there is an alternate CLI syntax, it might make sense for the stdlib to support both.  It might not, too.  I was just trying to be helpful if it was wanted, and #4620 made me think that it might be wanted.

**Comment by andreaferretti** [comment]
> But then how can you distinguish between -dval meaning (key: "d", value: "val") vs. (key: "dval", value: "")?

I would read `-dval` as `-d -v -a -l`, `--dval` as `key = dval`, and `-d val`, `--d=val`, `--d:val` as `key:d, value: val`

**Comment by c-blake** [comment]
Something to perhaps mention here is that regardless of syntax choices, the person entering a command is emitting symbols.  So, they *must* have at least a partial symbol table at least in their brain, no matter the syntax.  If the parser also knows the full set of option keys then it can provide more syntax flexibility and things like spell checking/suggestions (e.g., "No option 'missng' did you mean --missing?").  I absolutely agree that more points of edit when adding options is annoying, though.  That's why I wrote https://github.com/c-blake/cligen.

**Comment by andreaferretti** [comment]
@c-blake I love cligen! I just wanted to drop in and mention ho I have almost always seen interpreted CLI options

**Comment by c-blake** [comment]
Yeah.  No worries.  It's all good.  Glad you like cligen.  I don't take any of this personally, and I can always keep distributing my own parsing sub-engine.  I don't know there is a perfect trade-off that is easy on both command authors and easy on command-users.  Something like argh/cligen or docopt are the two closest I've seen (at opposite poles of the design space - one starting from just code, the other from documentation).

I do think the POSIX style is popular enough in the wider world to support in the stdlib, and I used to think (because #4620) Araq did, too, but that's ultimately the judgement call of others more on the hook to support the stdlib.  I'm just advancing various (perhaps overlooked) rationales.

What exactly "is" POSIX compliance is also a bit fuzzy.  It is not nearly as "strict" as a lot of POSIX, and surely not an exact parser spec.  There are mostly general guidelines, http://pubs.opengroup.org/onlinepubs/009604499/basedefs/xbd_chap12.html, but also a lot of exceptions for ancient commands like 'tar' and whatnot.  Anyway, the general guideline does include the ``-foption-argument`` form which I think we all think requires the parser knowing at least the set of possible short option keys that do (or do not) take arguments.

**Comment by dom96** [comment]
Don't know why you removed High Priority, but I think it's important enough to be called a Showstopper now.

**Comment by dom96** [comment]
**What needs to be done:**

1. Fix the quoting in parseopt
2. Remove parseopt2
3. Call it a day.

**Comment by c-blake** [comment]
Mentioning ``os.parseCmdLine`` in this thread seems prudent.  I haven't tested it myself, but it has what looks like a set of tokenization/quoting rules that is well documented and complete and perhaps even standard in the Microsoft world.  If there are corner cases to be fixed (as suggested by the comment for that routine suggesting instead using ``parseopt``) in that, we can fix them at that tokenization layer.

It seems like a not bad way to go is to have just two ``initOptParser`` and two ``getopt`` overloads -- one for ``string`` using ``os.parseCmdLine`` and one for ``seq[string]`` that assumes tokenization/de-quoting has already happened.  The ones that takes ``string`` can be simple wrappers around the ones that do not.

**Comment by Araq** [comment]
> Don't know why you removed High Priority, but I think it's important enough to be called a Showstopper now.

Because the bugs were fixed, as far as I could tell. The forum post showed us that is not the case.

**Comment by kaushalmodi** [comment]
This works great!! Thanks for fixing this @Araq!  👍 

My test: https://ptpb.pw/sYl0/nim

**Comment by greencardamom** [comment]
Agreed, thanks.
