### ISSUE TITLE
random crash caused by createThread

### ISSUE THREAD

**Issue by kvinwang** [nim-lang/Nim#6875]
```nim
proc testCreateThread(): Thread[int] =
  createThread(result, proc(a: int) = discard, 0)

let t = testCreateThread()
t.joinThread()
```
Crashes without any hint.

In threads.nim
```nim
    if pthread_create(t.sys, a, threadProcWrapper[TArg], addr(t)) != 0:
```
it use the addr(t) directly. so it has problem if t is on stack.

**Comment by genotrance** [comment]
Works fine on Windows, crashes on Linux.

**Comment by timotheecour** [comment]
so the problem is indeed that `pthread_create(t.sys, a, threadProcWrapper[TArg], addr(t)) != 0:` consumes a stack address that gets invalidated, and nim doesn't flag this as illegal. Thread already has `=copy` disabled with {.error.} but that's unrelated and doesn't prevent this.

possible solution: use escape analysis, refs https://github.com/nim-lang/Nim/pull/14976 to detect this and at least issue a warning.

**Comment by Varriount** [comment]
> 
> 
> so the problem is indeed that `pthread_create(t.sys, a, threadProcWrapper[TArg], addr(t)) != 0:` consumes a stack address that gets invalidated, and nim doesn't flag this as illegal. Thread already has `=copy` disabled with {.error.} but that's unrelated and doesn't prevent this.
> 
> possible solution: use escape analysis, refs #14976 to detect this and at least issue a warning.

Can you explain a bit more?

**Comment by Araq** [comment]
`createThread` is a sharp tool and you cannot use it in this way.

**Comment by kvinwang** [comment]
> `createThread` is a sharp tool and you cannot use it in this way.

I don't think this is a responsible answer.

**Comment by Araq** [comment]
Too bad.
