### ISSUE TITLE
GC crashes after a short while when using `-d:useNimRtl` and dynamic nim libraries

### ISSUE THREAD

**Issue by idlewan** [nim-lang/Nim#6886]
I've put the test case here to be able to clone it easily: https://github.com/idlewan/nimrtl_gc_issue_6717_testcase.

When loading a dynamic library, executing its function (which allocates memory), unloading the library, loading another dynamic library and executing its function (which also allocates memory), and so on, the program is going to crash with a SIGSEV.

This is the issue I unsuccessfully tried to fix in #6717, extracted in a minimal test case
(and simpler to reproduce than with https://github.com/Serenitor/hotnim).

[Nim#6717]: https://github.com/nim-lang/Nim/pull/6717

Here is the failing test program:
```nim
# loader.nim
import dynlib

var libnames = [
  "./liblib1.so",
  "./liblib2.so"
]

type Fn = proc () {.nimcall.}

var lib: pointer
var lib_main: Fn

proc load(index: int) =
  echo "loading ", libnames[index]
  lib = loadLib(libnames[index])
  var p = lib.symAddr("lib_main_fn")
  if cast[int](p) == 0:
    quit "Error loading proc in .so"

  lib_main = cast[Fn](p)

load(0)

var i = 0
var cur_index = 0
while true:
  if i mod 5 == 0:
    lib.unloadLib()
    cur_index = (cur_index + 1) mod 2
    load(cur_index)
  lib_main()
  i += 1
```
```nim
# lib1.nim
import times

var i = 0

proc lib_main_fn*() {.exportc.} =
  var t = getGmTime(getTime())
  echo "hello " & $i & "  ", format(t, "yyyy-MM-dd HH-mm")
  i += 1
```
```nim
# lib2.nim
import times

var i = 0

proc lib_main_fn*() {.exportc.} =
  var t = getGmTime(getTime())
  echo "hello " & $i & "  " & $t
  i += 1
```
Compile the loader program and the two dynamic libraries it uses with:
```
nim c -d:useNimRtl loader.nim
nim c -d:useNimRtl --app:lib lib1.nim
nim c -d:useNimRtl --app:lib lib2.nim
```
You should also compile `libnimrtl.so` and place it in this folder.
```bash
nim c --nimcache:nimcache_libnimrtl -o:./libnimrtl.so /path/to/Nimrepo/lib/nimrtl.nim
```
Now run the loader, paying careful attention to modify the `LD_LIBRARY_PATH` to use the newly-compiled `libnimrtl.so`.
```bash
LD_LIBRARY_PATH=`realpath ./` ./loader
```
The traceback points to GC functions.
```
Traceback (most recent call last)
loader.nim(30)           loader
loader.nim(14)           load
gc.nim(492)              newObjNoInit
gc_common.nim(360)       prepareDealloc
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by PMunch** [comment]
Been playing a bit more with this now, and the strangest bug I've had so far is that after a second or two of running the code terminates as it couldn't load the library "loading" I tried printing out the list of libraries and it told me it was `["./liblib1.so", "loading"]`.

**Comment by PMunch** [comment]
Okay, finally making some headway on this. I tracked the segfault back to the GC, the problem appears to be that the GC will register cells that originate in the libraries and then after the library is unloaded it goes to deallocate them. This causes the GC to try and look for information in memory that is no longer owned by the program (since the lib took that with it when it unloaded). Putting a `GC_fullcollect` right before the `unloadLib` call is enough in this case to clean up that memory before it's unloaded (but would probably not work if the library actually had some state it held). But that introduces another problem, for some reason `GC_fullcollect` does the weird thing I described above and adds the word "loading" in the array of libraries. Making that array a const however solves this, probably because the GC doesn't consider it. Whether or not the `GC_fullcollect` bug is there always or if it is related to dynlib or nimrtl I'm not entirely sure.

So to actually fix this it seems that when unloading a library the GC needs to be informed that all memory allocated from that library is now to be considered deallocated. How this can be done however I have no idea. Maybe @Araq has some idea on how that might be implemented?

**Comment by PMunch** [comment]
By enabling `--gc:boehm` for each part of the compilation on the latest devel (0.19.9) it seems to run without any strange crashes. Without it you either get the free-ing of memory in the loaded library that's already gone leading to the crash above, or it messes up some memory and swaps strings around so you end up with something like this:
```
loading ./liblib1.so
hello 0  2019-03-27 08-29
hello 1  2019-03-27 08-29
hello 2  2019-03-27 08-29
hello 3  2019-03-27 08-29
hello 4  2019-03-27 08-29
loading ./liblib2.so
hello 0  2019-03-27T08:29:04Z
hello 1  2019-03-27T08:29:04Z
hello 2  2019-03-27T08:29:04Z
hello 3  2019-03-27T08:29:04Z
hello 4  2019-03-27T08:29:04Z
loading 2019-03-27T08:
Error loading proc in .so
```

**Comment by yukari159** [comment]
Maybe, I've encountered a possibly related bug and will report it.
Create a nim DLL and use it in C.

- nim
```nim
# nim c --app:lib -d:useNimRtl nimdll.nim
# nim -v
# Nim Compiler Version 1.6.10 [Windows: amd64]
# Compiled at 2022-11-21
# cc = vcc

proc fn(p : pointer, n : cint) : void {.exportc, cdecl, dynlib.} =
    var a = cast[ptr UncheckedArray[cint]](p)
    var x : seq[int]
    
    for i in 0..<n:
        x.add(a[i])

    for i in 0..<n:
        echo x[i]
```

Visual Studio 2019 (v142)
- c 
```c
extern "C" __declspec(dllimport) void __cdecl fn(int* p, int n);
int main(void)
{
  int p[] = {0,1,2,3,4,5,6,7,8,9};
  while (1)
    fn(p, 10);
  return 0;
}
```

- file placement
  folder/
  nimdll.dll
  nimrtl.dll
  Project1.exe
  Project1.pdb

- output
A DLL function `fn` is called several times and an error occurs.
```
...
3
4
5
6
7
8
9
5
6
C:\Users\user\nim-1.6.10_x64\nim-1.6.10\lib\system\fatal.nim(54) sysFatal
Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]
```

**Comment by Araq** [comment]
The ORC memory management scheme does not have this problem.
