### ISSUE TITLE
osproc poUseShell doesn't make sense (at least on Posix)

### ISSUE THREAD

**Issue by zielmicha** [nim-lang/Nim#701]
I think that to goal of poUseShell was to allow PATH expansion. Right way to do this is to use execvp, not shell. While docs say that it is unsafe, even standard library doesn't respect that, i.e.:

```
import browsers
"http://$(echo HACKED > hacked; echo google).com".openDefaultBrowser
```

The only reasonable thing poUseShell could do is to `assert args == nil` and pass command straight to `/bin/sh`, so user can be blamed when he creates shell-injection using '&' operator. If we don't want to introduce backward incompatibility we may alias poUseShell to new flag poUsePath, which will use execvp instead of execv.

By the way, `quoteIfContainsWhite` also should be removed, because currently it just adds ", which is not safe. Theoretically it could be made to use proper quoting, but I don't think it's possible to do that on Windows.

If what I have written makes sense, I will investigate if secure `quoteIfContainsWhite` is possible on Windows. If it is I will change its implementation and keep poUseShell. If not `quoteIfContainsWhite` needs to be removed, because security is more important than backward compatibility.

**Comment by lee-b** [comment]
FWIW, I disagree that this is useless, or that "the goal was to allow PATH expansion".

In C, the `system(const char* command)` function is intended to execute the given command using "a *command-processor*", i.e., the actual system shell.  i.e., it would be expected that, with bash as `$SHELL` running "help" would output the bash builtin help, `alias` would output defined aliases, etc.

It's a rare usecase, and system() doesn't seem to work that way in GCC (at least now, probably because it's considered insecure: https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152177 ).

I'm not sure if nim should bother providing `poUseShell` at all, especially given the above security vuln.  I **think** people can resolve `$SHELL` and execute it directly, if necessary, assuming they know its argument syntax.

However, the `poUseShell` option should **NOT** be equated with `poUsePath`, imho. That just seems wrong.
