### ISSUE TITLE
Error when trying to iterate a distinct type based array

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#7167]
```nim
type Id = distinct range[0..1_000]

var xs: array[Id, bool]

for x in xs: discard # type mismatch: got (T) but expected 'bool'
```

**Comment by Araq** [comment]
Why should it work? The distinct type means arithmetic operations are not available.

**Comment by GULPF** [comment]
@Araq I disagree. Since all ordinal types are allowed as array indices, they should work with the items iterator even if they are distinct. Is there a reason why the iterator can't be implemented like this?
```nim
iterator items*[IX, T](a: array[IX, T]): T {.inline.} =
  ## iterates over each item of `a`.
  var i = low(IX).IX
  if ord(i) <= ord(high(IX)):
    while true:
      yield a[i]
      if ord(i) >= ord(high(IX)): break
      inc(i)
```

Having to borrow `>=` to use a distinct type as array indexer just seems like a leaky abstraction.

**Comment by Araq** [comment]
The real problem here is that ``distinct T`` is an ordinal if ``T`` is ordinal but that makes no sense. A distinct type should not be an ordinal. I tried to fix that in the compiler but ``times.nim`` now depends on it. -.-

**Comment by GULPF** [comment]
Agreed that `distinct T` shouldn't be automatically ordinal if `T` is ordinal, but imo there should be a way to explicitly inherit the "ordinalness" since it can be useful.  Fwiw I don't think `times` depends on it after #6978, since it changes the `Time` type to be an object (which will undoubtedly break a lot of code...).
