### ISSUE TITLE
Nim doesn't know which enum an identifier belongs to

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#7211]
```nim
type
    A {.pure.} = enum X
    B {.pure.} = enum X
    
    C = object
        case kind: B
        of X: discard #type mismatch: got (A) but expected 'B = enum'
```

**Comment by cooldome** [comment]
Yes, I have tried to fix it in the past it is quite nasty.
Use full qualifiers for now: A.X, B.X

**Comment by andreaferretti** [comment]
What is there to fix? The enum is pure, hence the need to qualify

**Comment by twetzel59** [comment]
I suppose there could be a more helpful error message. Without some more testing, I'm going to say this *isn't* a bug - **but**, sometimes these little examples point to deeper issues. However, I think that this isn't an actual malfunction, since each ``enum {.pure.}`` doesn't release it's variants into the namespace.

Essentially, the compiler is somewhat wrong to say that `X` is a variant of `A`, since both are ``{.pure.}``, but I don't yet know enough about the Nim compiler to say whether this has any real-world repercussins.

@cooldome, when you tried to fix this, what behavior did you try to change?

**Comment by cooldome** [comment]
Agree, it is not a bug but rather feature request to improve semantic of ``case`` statement.  In the example above case statement knows that values should be of enum `B` so it can use this knowledge to disambiguate ``X`` to correct type. 
I have tried to  to get closedSymChoice for node ``X`` and then make ``fitNode`` to select  ``B.X``.

I suggest changing title to: Improve handling of pure enums in case statements 
Label: feature request

**Comment by ringabout** [comment]
In devel, got a better error messages for pure enum: Error: ambiguous identifier: 'X'
```nim
type
    A {.pure.} = enum X
    B {.pure.} = enum X
    
    C = object
        case kind: B
        of X: discard
```

And this gives Error: type mismatch: got <A> but expected 'B = enum'

```nim
type
    A = enum X
    B {.pure.} = enum X

    C = object
        case kind: B
        of X: discard
```

**Comment by metagn** [comment]
This is fixed since overloadable enums are now default
