### ISSUE TITLE
gdb debug

### ISSUE THREAD

**Issue by r3d9u11** [nim-lang/Nim#7264]
Hi. Is it possible to integrate Nim's variables with gdb (now gdb [can't evaluate it](https://github.com/pragmagic/vscode-nim/issues/65) without [workarounds](https://github.com/pragmagic/vscode-nim/issues/65#issuecomment-367317736))?

**Comment by krux02** [comment]
I have some experience with debugging with the gdb command line tool. And I can write a bit about the experience.  First of all, use `--debugger:native`. Then when your program has debug information you can just debug it with gdb. you can inspect strings already, but it is kind of tedious, because gdb by defaults thinks they are just C structs. But it is possible. Then when you want to set breakpoints. You can use `rbreak` with the unmangled name in nim. The mangled function name will always contain the unmangled name in nim. Local variables work, too. Thanks to auto completion the mangleing of those names can be completed and is not really a problem.

**Comment by enthus1ast** [comment]
there is also this https://github.com/cooldome/Nim-gdb

**Comment by krux02** [comment]
well this is now fixed, there are now gdb pretty printers distributed with nim. Just make sure they are loaded (for example with the nim-gdb start script in the bin folder)
