### ISSUE TITLE
HttpClient crash inside {.exportc.} proc

### ISSUE THREAD

**Issue by Mnenmenth** [nim-lang/Nim#7290]
HttpClient causes the program to crash if it is created or accessed inside of a proc with {.exportc.}

C: 
```
extern "C" test();
int main() {
    test()
}
```
Nim Ex 1:
```
proc test*() {.exportc.} =
    let client = newHttpClient() <-- crash
```
Nim Ex 2:
```
let client = newHttpClient()
proc test*() {.exportc.} =
    client.onProgressChanged = nil <-- crash
```

**Comment by Yardanico** [comment]
You didn't initialise Nim's GC

**Comment by Mnenmenth** [comment]
How can I do that?

**Comment by krux02** [comment]
Chen you create a hello-world application in Nim, the generated C source file can be a starting point for 
a C program that needs to call Nim fucntions. But when you do this, do it with -d:release. The generated source us much better readable when you build in release mode. Then strip out everything you don't need.

**Comment by Mnenmenth** [comment]
Is that the only way to initialize the libraries and GC? I'd like to just define the procs through extern or something similar if possible, rather than using the generated source.

**Comment by krux02** [comment]
I don't mean you have to use the generated source, what I mean is that you use the generated source as a starting point to get to know how you initialize the Nim environment properly. I don't mean you should not change that source code, because you should. Take out everything that isn't needed and make it to hand crafted code.

By the way I needed to link the stdlib_system.o and dl to make dlopen work:

``cc scratch.o nimcache/stdlib_system.o -ldl``

**Comment by Mnenmenth** [comment]
Ah ok. I understand now. Thank you
