### ISSUE TITLE
newSeqWith is 3 times slower than fill

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7295]
Test case:

```Nim
import math, algorithm, sequtils, times

const
  dz = 0.01
  z = 100
  spaceSteps = int(z / dz)
  timeSteps = 50000

let start = cpuTime()

# var foo = newSeq[float](timeSteps * spaceSteps)
# foo.fill(1.0) # 3.629437

var foo = newSeqWith(timeSteps * spaceSteps, 1.0) # 10.429099

let stop = cpuTime()
echo stop - start
```
![2018-03-03_23-43-09](https://user-images.githubusercontent.com/22738317/36940084-a97a4ab0-1f3c-11e8-86df-c0b2402fd926.png)
![2018-03-03_23-45-25](https://user-images.githubusercontent.com/22738317/36940095-f902894e-1f3c-11e8-9ce1-c720d1a21a18.png)

cc @narimiran

**Comment by skilchen** [comment]
Its not `fill` that is that much faster. IMHO the slowness of `newSeqWith` is due to the fact that it is implemented as a template. This causes first an allocation of the sequence and then a copying assignment to the target value.
If `newSeqWith` is changed to a generic procedure, it is as fast as your version using `fill`:
```nim
proc newSeqWith*[T](len: int, init: T): seq[T] =
  result = newSeq[T](len)
  for i in 0 ..< len:
    result[i] = init
```
I don't know, why `newSeqWith` is implemented as a template and not as a generic procedure.

**Comment by mratsim** [comment]
It's implemented as a template to allow inline proc arguments like "rand" to fill a tensor with random values for example. In your case the whole seq will be filled with the same "init" value.

**Comment by cooldome** [comment]
New timings:
newSeqWith: 6.849931 sec
fill: 6.800397999999999 sec

**Comment by skilchen** [comment]
> mratsim wrote: 
It's implemented as a template to allow inline proc arguments like "rand" to fill a tensor with random values for example. In your case the whole seq will be filled with the same "init" value.

ah, i see. thanks @mratsim  for the explanation. this feature is too clever for me ...

**Comment by narimiran** [comment]
> New timings:
> newSeqWith: 6.849931 sec
> fill: 6.800397999999999 sec

I've just tried it on the latest Nim devel (0.19.9) and:

* in debug mode, `newSeqWith` is ~30% slower
* in release mode, `newSeqWith` is ~2x slower

**Comment by krux02** [comment]
``newSeqWith`` uses a for loop, where ``fill`` uses a while loop

**Comment by data-man** [comment]
Is time for #7572? ;-)

**Comment by krux02** [comment]
I think those optimizations should stay in the realm of the backend (C(++)) compiler. They do this for years now. But generating code that is suitable for loop unrolling is worth it.

**Comment by data-man** [comment]
I want to control the optimization of a particular loop, not rely on some strange heuristic.

**Comment by ringabout** [comment]
Tested on latest devel version on windows.

With ARC/ORC, I got the similar results for both operations(8.83 vs 8.225).

**Comment by timotheecour** [comment]
any of these changes would make it identical to fill:
* replacing newSeqWith with a proc 
* using --gc:arc|orc
* replacing result by move(result) in last line of the template

the last point is the most useful because it applies to other cases as well (where a template is needed) and doesn't require one to change the gc

=> https://github.com/nim-lang/Nim/pull/18168
