### ISSUE TITLE
confusing error messages when using lines + --debugger:on fails with: `error: expected expression`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7426]
D20180327T111559

nim wrongly accepts code where expression involves an undefined identifier (here, `lines`) that is later defined in statement LHS

nim c --debugger:on -o:app -r bugs/t02_debug_error.nim

```
import sequtils
const input = "/tmp/unexistant.txt"
let lines    = toSeq(input.lines) # Should be an error, lines is not yet defined
echo lines
```

Note: when adding `--debugger:on` it now errors:

```
Error: execution of an external compiler program 'clang -c  -w  -I/Users/timothee/homebrew/Cellar/nim/0.18.0_1/nim/lib -o /Users/timothee/git_clone/nim/timn/bugs/nimcache/t02_debug_error.o /Users/timothee/git_clone/nim/timn/bugs/nimcache/t02_debug_error.c' failed with exit code: 1

/Users/timothee/git_clone/nim/timn/bugs/nimcache/t02_debug_error.c:527:3: error: expected expression
                else {
                ^
```

**Comment by skilchen** [comment]
you miss that `lines` is defined in system.nim which is available automatically in every nim program.
https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L3308

the error with --debugger:on is another story that i don't understand.

**Comment by timotheecour** [comment]
> you miss that lines is defined in system.nim which is available automatically in every nim program.

are you sure? If I replace with:
```
let lines2    = input.lines
```
I get:
`Error: undeclared field: 'lines'`

**Comment by cabhishek** [comment]
@timotheecour this works fine for me on `0.18.0`
```
import sequtils
const input = "/tmp/unexistant.txt"
let lines2    = toSeq(input.lines) 
echo lines2  # @[]
```

**Comment by skilchen** [comment]
a quote from [(ENDB) User Guide](https://nim-lang.org/docs/endb.html):
> **WARNING**: ENDB is not maintained anymore! Please help if you're interested in this tool.

unfortunately i am unable to help because i have no idea, what `--debugger:on` really does...
It is clear that Nim produces invalid C code when compiling your example. It inserts an instrumenting statement for the debugger at the wrong place. This has something to do with the specifics (using `defer`) of the iterator `lines(filename: string)` in  lib/system.nim. I made the following test to illustrate the problem:
```nim
import sequtils

iterator mylines(fname: string): string =
  let fp = open(fname, fmRead)
  defer: fp.close()
  var result = newString(256)
  while fp.readLine(result):
    yield result

proc test() =
  const input = "/tmp/unexistant.txt"
  echo toSeq(mylines(input))
  
test() 
```
`nim c --debugger:on -r test.nim` gives the error reported by @timotheecour 
Now if you move the line `var res = newString(256)` above `defer: fp.close` the test works (i.e.: `nim c --debugger:on -r test.nim` starts the endb debugger):
```nim
import sequtils

iterator mylines(fname: string): string =
  let fp = open(fname, fmRead)
  var res = newString(256)
  defer: fp.close()
  while fp.readLine(res):
    yield res

proc test() =
  const input = "/tmp/unexistant.txt"
  echo toSeq(mylines(input))  

test()
```
or if you remove the `defer: fp.close()` and add `fp.close()` after the while loop, the test also works:
```nim
import sequtils

iterator mylines(fname: string): string =
  let fp = open(fname, fmRead)
  var res = newString(256)
  while fp.readLine(res):
    yield res
  fp.close()

proc test() =
  const input = "/tmp/unexistant.txt"
  echo toSeq(mylines(input))
  
test()
```

I have no idea why and how  Nim produces invalid C code for the first test, but valid code if we modify the test only slightly.

**Comment by timotheecour** [comment]
fixed https://github.com/nim-lang/Nim/issues/7426#issuecomment-376638432 via https://github.com/nim-lang/Nim/pull/8786 ; the rest now works
