### ISSUE TITLE
Concepts with generics: bug with int32 instantiation (works with int, ...)

### ISSUE THREAD

**Issue by vincentvidal** [nim-lang/Nim#7510]
The following code:
```
type
    A[T] = concept a
        a.x is T
    B[T] = object
        x: T
proc getx(v: A): v.T = v.x
var v = B[int32](x: 10)
echo v.getx
```

produces this error:

```
Error: internal error: invalid kind for first(tyInferred)
```

Instantiating B with int8 and int16 yields the same error.

However, it works well and prints 10 when B is instiantiated with all other integer types (byte, int, int64, uint, uint8, uint16, uint32, uint64).

**Comment by Araq** [comment]
We know ``concept`` is full of bugs, currently you have a better time ignoring this feature. But you don't have to ignore Nim completely because of that. :-)

**Comment by vincentvidal** [comment]
However concepts are a really appealing concept ;-), I would really love give them a try.. Do you think we are far from a relatively stable implementation?

**Comment by siliconvoodoo** [comment]
@Araq But of course, I wouldn't be exasperated by only that. It's a string of little things that accumulates.
Let's take one sample of the things that scare me:
https://github.com/flyx/emerald/issues/14
The author says
> pretty nice tech demo, it is not a great tool to tackle actual problems.
That is a huge downer, I intended to use this in production.

Since we're at it, let's go with a second sample: the legacy of the choice of distinct integers types not implicitly convertible to each other, but still initable with a special numeric literal called {int literal} that is not int, but numeral, and that has implicit capabilities at declaration site. Associated with strange choices of int/int64, causing this original mess: https://github.com/nim-lang/Nim/issues/936 which really, keeps coming back in different forms, even recently (but less severe than the original report).

Last sample for the day since it's totally off topic: the recurrent frustrations caused by not understanding the compiler, and finding no help on google. This thread puts the finger perfectly on it https://forum.nim-lang.org/t/3641

For the final word, this is going to get meta :) In the previous languages I've used: basic, C, C++, java, C# and python, I've never had to spend my life in the bugtracker.
I've filed once, a bug at microsoft for a C++11 feature that wasn't well supported, and I felt like a speleologist on Mars.

**Comment by dom96** [comment]
@siliconvoodoo I sense that there isn't much I can say to convince you to stick around. You have a lot of experience with languages that, let's face it, have thousands of developers using them every day. They are also much older than Nim. Because of that, the low hanging fruit issues have all been solved. 

Depending on what you're doing you may find that Nim is what Linux is to Windows: a powerful tool that doesn't always work perfectly, but if you're willing to get your hands dirty it can work perfectly. You'll also learn a hell of a lot by solving these issues.

**Comment by genotrance** [comment]
No longer crashes with #head. Please confirm if issue is fixed and if snippet should be added as a test case.

```
-------- SNIPPET --------
# Snippet not defined as ```nim

type
    A[T] = concept a
        a.x is T
    B[T] = object
        x: T
proc getx(v: A): v.T = v.x
var v = B[int32](x: 10)
echo v.getx
-------------------------

-------- OUTPUT --------
Hint: used config file 'c:\users\gt\Desktop\DL\programming\nimdevel\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: temp [Processing]
Hint:  [Link]
Hint: operation successful (12255 lines compiled; 0.281 sec total; 10.758MiB peakmem; Debug Build) [SuccessX]

10

Ran successfully
------------------------

-------- NIMTEMP --------
Hint: used config file 'c:\users\gt\Desktop\DL\programming\nimdevel\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: temp [Processing]
Hint:  [Link]
Hint: operation successful (12255 lines compiled; 1.016 sec total; 10.746MiB peakmem; Debug Build) [SuccessX]

10

Ran successfully
-------------------------

-------- VERSION --------
Nim Compiler Version 0.18.1 [Windows: i386]
Compiled at 2018-09-12
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 87955eaf3048bd6b69a988ac330f9d35b2cfa39e
active boot switches: -d:release
-------------------------
```
