### ISSUE TITLE
thread local variable `threadvar` not working as expected (differs from C++ thread_local and D static)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7565]
thread local variable `threadvar` not working as expected (differs from C++'s `thread_local` and D's `static`)

```nim
const mode=3

when mode==1:
  var count {.threadvar.}: int # works
when mode==2:
  var count {.global.}: int # works

proc fun() : auto =
  when mode==3:
    var count {.threadvar.}: int # doesn't work
  when mode==4:
    var count {.global.}: int # works

  count.inc
  return count

proc test_global_var() =
  doAssert fun()==1
  doAssert fun()==2

test_global_var()
```

* in D, the equivalent code would work, eg:

```
auto fun(){
  static int count=0;
  count++;
  return count;
}

void test(){
  assert(fun()==1);
  assert(fun()==2);
}
```
* likewise, in C++ (c++11) **EDIT for clarification**
```c++
int fun(T a){
  thread_local int count = 0;
  count++;
  return count;
}
//etc
```

the docs in https://nim-lang.org/docs/manual.html#threads-threadvar-pragma at least don't make nim's behavior clear.

What's a workaround?
**EDIT** especially in light of thread local variables in templates (see example in [comment](https://github.com/nim-lang/Nim/issues/7565#issuecomment-380363393))

## links
**EDIT**
* https://forum.nim-lang.org/t/2873/1 Thread-local persistence

**Comment by andreaferretti** [comment]
I copy from [the docs](https://nim-lang.org/docs/manual.html#threads-threadvar-pragma):

> A global variable can be marked with the threadvar pragma; it is a thread-local variable then

So, support for thread local variables exists only at the top level. Local variables are, well, local, so if you declare x0 locally in `fun` and then increase it, you will get the same result each time

**Comment by timotheecour** [comment]
so what's the difference between x0 and x1 below?
```
proc fun() : auto =
  var x0 {.threadvar.}: int
  var x1: int
```

if there's no difference, it should be disallowed.

However, I'd argue we'd want to be able to define static thread local variables inside procs, with same semantics as in D and C++:

- [ ] avoids polluting namespace
- [ ] not even sure what'd be workaround in case of templated procs, eg:

```nim
proc fun[T](a: T):auto=
  var x {.threadvar.} = 0
```
should match D:
```d
void fun(T)(T a){
  static int count = 0;
}
```
or similar C++ code

**Comment by zah** [comment]
Yes, this seems like a very easy fix. The use of `threadvar` can imply `global`.

**Comment by lightness1024** [comment]
in C++ the generated code for a `static` variable includes a mutex so that the first entry in the function initializes the variable. as you know, double checked locking is an antipattern if you forget the memfence, generated code therefore does not use either, just the mutex directly which is cleaner. a TLS variable at least would lift the need to lock, so it's not the same semantic as global. it's global+TLS which is a special combination by itself.

**Comment by zah** [comment]
The lack of any guarding mechanisms such as mutexes is intentional. The user can implement any kind of scheme by defining a template that uses `.global.` variables internally.

**Comment by lightness1024** [comment]
In nim `{.global.}` is not lazy, it initializes at module start if I'm not mistaken. In C++/D/C# function-scoped `static` variables, which is the semantic equivalent to Nim's global, are initialized once at first entry (lazily). Which poses the grave risk of being prone to race conditions since at this point of the program, the function may be entered from any thread. A problem Nim avoids by executing the initialization statement at startup. Which is what C++ calls "non-local static".
This behavior is described here : http://en.cppreference.com/w/cpp/language/storage_duration#Static_local_variables
Anecdotally & unfortunately just to make me look dumb, contradicting what I said in previous post about double check locking. But my recollection comes from inspecting disassembled code of that feature, so that just proves "implementation defined" more.

**Comment by timotheecour** [comment]
> Which poses the grave risk of being prone to race conditions since at this point of the program, the function may be entered from any thread

@lightness1024 @zah I'm not talking about shared static variables but about thread-local static variables. I've edited previous [comment](https://github.com/nim-lang/Nim/issues/7565#issuecomment-380363393) to make it clear with C++11 `thread_local int` (equivalent to D's `static int`). There is no race condition.

**Comment by lightness1024** [comment]
@timotheecour we know. but I was referring to this because the behavior is different. TLS, is not just global and TLS. The whole combination global+TLS becomes a thing with its own semantic.
