### ISSUE TITLE
nil.isNil doesn't build

### ISSUE THREAD

**Issue by lightness1024** [nim-lang/Nim#7647]
> echo nil.isNil
>         ^
> Error: ambiguous call; both system.isNil(x: ptr T)[declared in lib/system.nim(2332, 5)] and system.isNil(x: pointer)[declared in lib/system.nim(2333, 5)] match for: (nil)

lol

**Comment by Araq** [comment]
Seems ok to me? Give the ``nil`` a concrete type.

**Comment by siliconvoodoo** [comment]
Let's put ourselves from a newbie perspective, with naive eyes: `nil` is expected to be a value of 0, that can duck type against any ref/ptr for comparison or assignation.
On the other hand, `isNil` appears with a keyword color on my editor so it's supposedly a construct provided by the language. So first surprise here, is that it's in fact a `proc`. Which, with a second of thought, is fine. It is modern to alleviate constructs from the compiler to the stdlib, so all far so good.
But, second surprise, the current state of the provided stdlib makes it so that `nil.isNil` construct is refused.
But even after being shout at by the compiler, it still feels like it is a reasonable construct and that the compiler is being unreasonable. (well. the stdlib in this case)
But then, there is this https://github.com/nim-lang/Nim/issues/5976 which raises a whole new range of interesting questions, and maybe the doubt that providing a `isNil` override that can take `nil` is not going to be trivial as long as #5976 isn't implemented.
@Araq after almost two months of twiddling with Nim I am today capable to understand what you just said, but all honesty spoken, I felt this as a limitation while doing tests.
I've been forced to do:
```
let v: string
doAssert myDefensiveFunction(v)
```
I felt like I've been forced into this gymnastic, when if `nil` was ducktypable:
`doAssert myDefensiveFunction(nil)` a oneliner would have sufficed

**Comment by Araq** [comment]
> On the other hand, isNil appears with a keyword color on my editor so it's supposedly a construct provided by the language. So first surprise here, is that it's in fact a proc. 

I'm not responsible for the bad syntax highlighting rules people came up with. It annoys me very much too.

> But all this attention given to nil, and I can't help but to feel discomfort, Tony Hoare said it was a billion dollar mistake after all. This kind of make me want to shy away from giving it too much support.

Exactly.
