### ISSUE TITLE
Better compiler warning/error messages

### ISSUE THREAD

**Issue by jrenner** [nim-lang/Nim#7749]
Not to be cliche by comparing to Rust, but in learning some Rust recently I was blown away by how helpful the compiler error messages were.  I think Nim could improve a lot in this area, and I might be interested in helping out if the maintainers think it would be a good idea.

Here is one example I ran across recently:

```nim
import strformat

let x = "{t}"
let fmt_x = x.fmt
```
compiler message: `Error: & only works with string literals`

improvement: might also mention something about "fmt", & made me think of string concat at first
suggested new message: `Error: strformat module string formatting (fmt(), &) only works with string literals`

I'm curious what others think.

**Comment by data-man** [comment]
https://github.com/nim-lang/Nim/issues?q=is%3Aopen+is%3Aissue+label%3A"Error+messages"

**Comment by jrenner** [comment]
That search query doesn't seem to have any results for me.

**Comment by kaushalmodi** [comment]
@jrenner So how did you get around that limitation.. I have really long message formatting, and instead of copy/pasting the message, I wished I could store the string representing that format to a var and do `fmt(VAR)`.

Here's a simple case:

```nim
import strformat
let
  a = 100
  msg = "a = {a}"

echo fmt(msg)
```

But here's that actual `msg`: `"The '{argval}' value for ':{arg}' is invalid. The only valid values are 'yes' and 'no'."`.
