### ISSUE TITLE
'Block' doesn't generate new scope.

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#7784]
The following code gives error!
```nim
block:
   type
      Color = enum clrBlack, clrRed, clrGreen, clrBlue

   var color = clrRed
   assert(ord(color) == 1)   
   assert($color == "clrRed")

block:
   type
      Color = enum
         clrBlack = "Black",
         clrRed = "Red",
         clrGreen = "Green",
         clrBlue = "Blue"

   var color = clrRed
   assert(ord(color) == 1) 
   echo $color                   # clrRed !!!!!!
   assert($color == "Red")  
```

**Comment by krux02** [comment]
At least the compiler should complain about the type clash when the types are not properly scoped. Can also be a code generation related problem.

**Comment by LemonBoy** [comment]
This results in a codegen error:

```nim
block:
  type
    Foo = object
      discard

  echo Foo()

type
  Foo = object
    x: string

echo Foo(x: "super")
```

Also related to #7959.

The problem here is that we open a new scope but don't push a new owner on the stack. This way the types defined in `block`/`try`/`if`/etc are always attached to the parent scope via the `owner` chain even though they're in different scopes.

**Comment by ringabout** [comment]
The first example works with ARC.
The second example works.

**Comment by metagn** [comment]
Both of these work now, original issue because of #20457/#22606, the comment because of #23969
