### ISSUE TITLE
generics: error with multiple types and constraints

### ISSUE THREAD

**Issue by brentp** [nim-lang/Nim#7794]
> Update: @krux02 has found this happens when constraints are specified. When the constraints are removed the code will compile.

the code below fails with: ` Error: cannot instantiate Data got: <type int, type float64> but expected: <T: SomeNumber, U: SomeNumber>`
```Nim
type
  Element*[U:SomeNumber] = ref object
    value*: U

  Data*[T:SomeNumber, U:SomeNumber] = ref object
    xs*: seq[T]
    e*: Element[U]

var e = Element[float64](value:2'f64)
var xs = new_seq[int](10)
var d = Data[int, float64](xs:xs, e:e)
```

**Comment by narimiran** [comment]
Even this doesn't work:

```nim
type
  Element*[U: float64] = ref object
    value*: U

  Data*[T: int, U: float64] = ref object
    xs*: seq[T]
    e*: Element[U]

let e = Element[float64](value:2'f64)
let xs = new_seq[int](10)
var d = Data[int, float64](xs: xs, e: e)
```

**Comment by krux02** [comment]
well as close as I can get between working and non working with non-essential parts removed.

```Nim
type
  # this works
  DataA*[T, U] = object
    xs*: seq[T]
    e*: U

  # this doesn't
  DataB*[T:SomeNumber; U:SomeNumber] = object
    xs*: seq[T]
    e*: U

var a = DataA[int, float64](xs: @[1,2,3], e: 12.3)
var b = DataB[int, float64](xs: @[1,2,3], e: 12.3)
```

**Comment by zah** [comment]
`m.typedescMatched` is a very hacky work-around trying to compensate for one very old historic flaw of the compiler internal design. The generic params "signature" of a type is still consisting of `tyGenericParams` slots as formal requirement, while it should really be using `tyTypeDesc`. The meaning of `tyGenericParam` is "match any value", while `tyTypeDesc` has the proper meaning of "match any type". Unfortunately, fixing this has proven to be quite hard in the few times I've attempted to solve the problem, so the compiler is still relying on these subtly wrong `m.typedescMatched` hacks.

Regarding your point 2, you seem to be missing the fact that each named type class is a "bind once" type by default. This is briefly explained in the type classes section of the manual:
https://nim-lang.org/docs/manual.html#generics-type-classes

In this sense, Brent's example is the best when trying to solve this issue, because it doesn't invoke this extra complexity:

``` nim
type
  Data*[T:SomeNumber, U:SomeReal] = ref object
    x*: T
    value*: U

var d = Data[int, float64](x:10.int, value:2'f64)
```

With that said, I'll mention for completeness that there are indeed problems with the `or` handling in the compiler. Properly handling `or` types in all situations requires back-tracking in the type binding process. We'll eventually introduce some support for this in the compiler to deal with some more easily triggered cases involving concepts.

**Comment by LemonBoy** [comment]
There's definitely more than it meets the eye.

> very hacky work-around

Yeah, I noticed some comments about this in the compiler.

> Regarding your point 2, you seem to be missing the fact that each named type class is a "bind once" type by default.

Oh, I've completely missed that bit.

> In this sense, Brent's example is the best when trying to solve this issue, because it doesn't invoke this extra complexity:

Definitely

Resetting `m.typedescMatched` fixes the issue at hand, do you think it may have other unintended consequences?

**Comment by zah** [comment]
Sounds like a plausible solution, but as usual the test suite will tell you if there are problems.

**Comment by Araq** [comment]
> The generic params "signature" of a type is still consisting of tyGenericParams slots as formal requirement, while it should really be using tyTypeDesc.

That's not true, ``tyTypeDesc`` is just as flawed for this as typically you want to allow e.g. ``int`` but not ``typeDesc[int]`` in your generic.

**Comment by Araq** [comment]
No, it's not an implementation problem, it's language design / spec problem: ``type C[T]`` means ``type C[T: typedesc and not (typedesc of typedesc)]``.

**Comment by zah** [comment]
I don't disagree with this, but it doesn't contract anything I said. `[typedesc[int]]` wouldn't match `typedesc[typedesc[int]]` in sigmatch in the future I'm describing.
