### ISSUE TITLE
seq/string initialized with `add` or `setLen` being deallocated

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#7833]
```nim
var s: seq[int]
s.add(123)
for i in 0 .. 10000:
    var s = newString(10)
    s[i mod 9] = 'a'
```
```
nim c -r -d:useSysAssert -d:useGcAssert -d:smokeCycles ~/test.nim
```
```
[GCASSERT] markS: foreign heap root detected A!
Traceback (most recent call last)
test.nim(4)              test
gc.nim(475)              newObj
```

**Comment by Araq** [comment]
``--gc:markAndSweep`` is not affected.

**Comment by yglukhov** [comment]
The issue results in non-deterministic crashes some time after `s.add(123)`, which are hard to track down. Could we promote it to showstopper or smth?

**Comment by mratsim** [comment]
I don't know why but this doesn't affect me, and I did not get a report for Arraymancer as well which is using the following just about everywhere:

```Nim
func newSeqUninit*[T](len: Natural): seq[T] {.inline.} =
  ## Creates an uninitialzed seq.
  ## Contrary to newSequnitialized in system.nim this works for any subtype T
  result = newSeqOfCap[T](len)
  result.setLen(len)
```

Unfortunately my main test suite is down due to https://github.com/nim-lang/Nim/issues/8432, but my opencl test suite doesn't have corruption issues.

Note: @coffeepots and @cheatfate had issues with uninitialized seq altogether (`newSeqOfCap`), not just `add` or `setLen`.

I also suppose newSeqUnitialized is affected: https://github.com/nim-lang/Nim/blob/6a9b082b535c48b07c5713b33d0d0a3a784f7c73/lib/system.nim#L733-L743
