### ISSUE TITLE
net.acceptAddr "Client socket needs to be initialised with `new`" (even if it is)

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/Nim#7848]
please note the `new Socket`

```nim
import net # https://nim-lang.org/docs/net.html
var socket = newSocket()
socket.bindAddr(Port(1234))
socket.listen()

var client = new Socket
var address = ""
while true:
  socket.acceptAddr(client, address) #<---
  echo("Client connected from: ", address)


# Client connected from: 127.0.0.1
# btcp.nim(9)         btcp
# net.nim(793)             acceptAddr
# system.nim(3788)         failedAssertImpl
# system.nim(3781)         raiseAssert
# system.nim(2843)         sysFatal
# Error: unhandled exception: int(client.fd) <= 0 Client socket needs to be initialised with `new`, not `newSocket`. [AssertionError]
# Error: execution of an external program failed: '/home/david/nimPlayground/btcp '
```

**Comment by dom96** [comment]
So the reason this happens is because the `client` is reused. By the second loop the `client`'s fd will be set to the previous client's fd.

The intention for the assertion error is to detect someone accidentally writing ``newSocket`` instead of ``new Socket``. I'm out of ideas about how to detect this. Perhaps we should just get ``accept`` to auto-init the socket?

**Comment by dom96** [comment]
> this new working on typedesc just lures people into these wrong usages.

It does indeed. Makes you wonder about that RFC which wants ``typedesc`` for ``parseInt`` etc. :)

**Comment by Araq** [comment]
Not applicable though, ``new T`` circumvents the ``newT`` vs ``initT`` convention, ``parse(mystring, typeHere)`` seems to do no comparable harm.
