### ISSUE TITLE
Bad codegen (runtime crash) when catching exceptions in a proc with no stack trace

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#7982]
```nim
proc foo(recurse: int = 10) =
    assert(recurse != 0)
    foo(recurse - 1)

{.push stackTrace: off.}
proc bar() =
    try:
        foo()
    except:
        echo "exception caught"
{.pop.}

proc baz() =
    bar()

baz()
```
```
exception caught
No stack traceback available
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by Vindaar** [comment]
Just ran the code on current devel https://github.com/nim-lang/Nim/commit/e67eddc91b5e06039498b337763acf718d436aae. 

If I compile it without the `release` flag, it doesn't crash with a `SIGSEGV` for me. Compiling it with `release` simply results in the program never stopping, since the assertion is ignored. Replacing it with `doAssert` results in the correct behavior, too. So no crashes for me. Do you compile it in a specific way?

**Comment by yglukhov** [comment]
Well yes, this is actually an undefined behavior, not necessarily a crash, depending on your luck. The code is still wrong though as it doesn't restore the stack frame in `except` of `bar`. Relevant lines: https://github.com/nim-lang/Nim/blob/devel/compiler/ccgstmts.nim#L901-L902
