### ISSUE TITLE
Initializing seq empty without using newSeq causes SIGSEGV error

### ISSUE THREAD

**Issue by jimhavrilla** [nim-lang/Nim#8068]
Hey I'm pretty new to Nim (and I'm using version 0.18) but I was curious about something.

Is it the intended function that all new seq variables are set to nil?  

If you run
`var b = newSeq[int]()`
`b.add(1)`
you get no error.

But if you run
`var c: seq[int]`
`c.add(1)`
You get the error:
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

I'm wondering if seqs are intended to act similar to python lists and arrays are like tuples, why does this functionality exist?  Am I missing something?

**Comment by Vindaar** [comment]
Yes, it is intended. Or rather was. It was changed ~2 months ago on the devel branch. If I'm not mistaken this was the first commit related to that change:
https://github.com/nim-lang/Nim/commit/ef1b547f358ce610e8f728a05169a2ee434b8f87

A couple more commits followed shortly after this one.

So if you wish to use v0.18.0 you have to take care of that. However, you can simply assign an empty sequence like so:
```nim
var c: seq[int] = @[]
```
instead of `newSeq[T]` if you wish. In case of the `result` variable of a proc you can even just do
```nim
result = @[]
```
because it's type is known from the proc declaration.

**Comment by jimhavrilla** [comment]
Oh so 
`var c: newSeq[T]()`
basically implements 
`var c: seq[T] = @[]`

Thanks for the swift response.

So I guess that's something that will be dropped in 0.19 or some such future release?

**Comment by Yardanico** [comment]
@jimhavrilla clarification: it's `var c = newSeq[type]()`.
And yes, you can easily compile devel branch yourself (and no, it's not 'unstable' in terms of compilation, etc.).
Probably can be closed?

**Comment by jimhavrilla** [comment]
Yeah, I mean if you want to close it, go for it.  More of a curiosity, because it seemed unusual to me.
