### ISSUE TITLE
non-intuitive json '%*' macro behaviour

### ISSUE THREAD

**Issue by zevv** [nim-lang/Nim#8144]
I understand the two cases below result in a different way the `%*` macro is handled, but from a user view the result feels a bit odd: the first example works as expected, but the second fails at compile time.

```
import json


# This works

let a = %* { "cat": 23, "dog": [ 1, 2, 3 ] }
echo a.pretty

# This does not

let a = { "cat": 23, "dog": [ 1, 2, 3 ] }
let b = %* a
```

Resulting in

```
t.nim(11, 27) Error: type mismatch: got <tuple of (string, array[0..2, int])> but expected 'tuple of (string, int)'
```

**Comment by andreaferretti** [comment]
The error has nothing to do with the `%*` macro. The fact is that you cannot create the literal `a`, since it is not well typed. The whole point of the macro is to transform it into something valid.

I don't think there is anything we can do here: when `a` is created, there is no information that the user will want to pass it to `%*`, hence I do not see a way to improve the error message

**Comment by andreaferretti** [comment]
More generally, the point of macros is - often - to allow to do things that functions cannot do by working on the AST, so I don't think it is a reasonable expectation that they should work on a variable, because then they cannot see the AST at all.

For another example (using jester), the following works:

```nim
import jester, asyncdispatch, htmlgen

routes:
  get "/":
    resp h1("Hello world")

runForever()
```

but this doesn't

```nim
import jester, asyncdispatch, htmlgen

let x = get "/":
  resp h1("Hello world")
routes(x)

runForever()
```

**Comment by hlaaftana** [comment]
Nim is a statically typed language. Normally the {a: b} literals translate to [(a, b)], which is an array of 2 element tuples, and since arrays are homogenous it expects all the tuples to have the same type. The tuple ("cat", 23) has the type (string, int) and the tuple ("dog", [1, 2, 3]) has the type (string, array[0..2, int]). You can see how these types are not equal to each other.

However there is still a way to turn the expression {"cat": 23, "dog": [1, 2, 3]} into a type. In fact, it's what makes the %* macro and all of the Nim frontend language work: Nim's AST type, NimNode. This means that when {"cat": 23, "dog": [1, 2, 3]} is a NimNode, so is "cat", so is 23 and so is [1, 2, 3].

Since the compiler is written in Nim, you can know that Nim has a way of storing multiple values in a single type as the way of NimNode: [object variants](https://nim-lang.org/docs/manual.html#types-object-variants). Object variants allow for multiple descriptions of compound values in the same object type, while still being able to tell which description to use.

Macros are special procs that only run at compile time and manipulate Nim AST, aka NimNode, and %* is a macro. From this line of thinking, you can also check what %* does to learn more about how Nim is able to use the expression {"cat": 23, "dog": [1, 2, 3]} at runtime. Reading [the docs](https://nim-lang.org/docs/json.html#%*.m,untyped), we can find out that it "converts an expression" (NimNode) "to a JsonNode", and guess what? [JsonNode has object variants too](https://nim-lang.org/docs/json.html#JsonNodeObj)!

Now that you know %* takes Nim AST, you can understand that no matter what you give %* it will always treat it as fresh Nim AST. So if you gave it the identifier `a`, it would try to convert that to a JsonNode and inadvertently fail. However, there are procs that don't need Nim AST in the json package, but instead use the proper runtime type JsonNode. To learn more about them, [read the package docs](https://nim-lang.org/docs/json.html). More importantly, [read the manual](https://nim-lang.org/docs/manual.html) and immerse yourself in the world of static typing.

**Comment by Araq** [comment]
Well yes. No bug here.

**Comment by Araq** [comment]
Python has a similar "problem":

```
foo(a=3, b=3, c=5) # works

# doesn't work:
x = (a=3, b=3, c=5) 
foo x
```
