### ISSUE TITLE
Varargs with array ignores leading arguments.

### ISSUE THREAD

**Issue by Quelklef** [nim-lang/Nim#8172]
```
proc f(v: varargs[string]) =
    echo(v)

f("a", ["b", "c"])
```
Outputs `["b", "c"]`.

**Comment by Quelklef** [comment]
Possibly related to https://github.com/nim-lang/Nim/issues/7914

**Comment by LemonBoy** [comment]
The problem here is that `varargs[string]` and `array[2, string]` are linked by a `isConvertible` relationship and `matchesAux` is confused by this: it first creates a `nkBracket` with `"a"` in it and then overwrites it with the second argument.

I'll take care of this later if nobody else steps up.
