### ISSUE TITLE
Strange codegen ICE with importcpp

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#8241]
```nim
when defined(windows):
  const
    SoundTouchDLL* = "SoundTouchDLL.dll"
elif defined(macosx):
  const
    SoundTouchDLL* = "SoundTouchDLL.dylib"
else:
  const
    SoundTouchDLL* = "SoundTouchDLL.so"

proc soundtouch_getVersionString*(): cstring {.importcpp: "soundtouch_getVersionString()", dynlib: SoundTouchDLL.}

echo soundtouch_getVersionString()
```

```
Error: internal error: (filename: "ccgcalls.nim", line: 423)
```

**Comment by LemonBoy** [comment]
The problem lies in a optimization gone bad. The compiler assumes that once the nodes reach `genCall`  the symbol `sym.loc.r` points to a valid leafy rope but that's not the case when `mangleDynLibProc` is thrown in the mix. Using `$` is a (possibly costly) solution or, as an alternative, we could just make `mangleDynLibProc` always produce a single rope piece.

CC @Araq ?

**Comment by Araq** [comment]
Either solution is fine with me. Let's hope ``--incremental:on`` will work soon and optimizations like these are less important in the compiler.
