### ISSUE TITLE
[compiler bug] template redefinition silently accepted; should give `Error: redefinition` error

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8275]
```nim
# D20180710T212850

when false: # case1
  # OK: Error: redefinition of 'foo'
  proc foo(): int = 1
  # proc foo(): int = 2

when true: # case2
  # BUG: compiles but should not
  template foo(): int = 1
  template foo(): int = 2

when false:# case3
  # OK: Error: redefinition of 'foo'
  macro foo(): int = 1
  macro foo(): int = 2

when false: # case4
  # OK: Error: ambiguous call;
  proc foo(): int = 1
  template foo(): int = 2

echo foo() # compiles with case2 but should not
```

**Comment by Araq** [comment]
That's not a compiler bug, that's allowed, the spec needs to mention it.

**Comment by timotheecour** [comment]
what's the rationale for this special case? (or kindly just link to the place where it's described if it's described somwhere)

**Comment by andreaferretti** [comment]
I don't see a good reason to allow redefinition only for templates

**Comment by kaushalmodi** [comment]
@timotheecour Does the redefined template become the effective version? If so, this could be great for redefining templates from imported modules (that's very common in Emacs Lisp :), and probably other lisps too).

**Comment by timotheecour** [comment]
@kaushalmodi

> Does the redefined template become the effective version

yes

* What's a use case of redefinition within a single module? Can't think of any, and it's bug prone

* I understand there are valid use cases for this kind of `hijacking` across module boundary (see https://dlang.org/articles/hijack.html) however as it currently stand it's very bug prone.

How about making it a compiler error (`Error: redefinition`) unless a pragma (say, `{.redefinition.}`) is given for the redefining definition?

This would be the `template` analog of `override` keyword in C++11 for overriding methods.

**Comment by Araq** [comment]
Well the ``unittest`` module uses this feature to allow users to override something. But I don't like this feature either.

**Comment by zah** [comment]
Since templates are a term-rewriting/inlining mechanism, it's semantically sound to override them freely and keep the "latest" version as the active definition. 

This is usually used to create APIs where you store a piece of code as "handler" for something in the current scope. In the `unittest` module, these are the `setup` and `teardown` blocks, in `system.onFailedAssert`, you can specify what should happen when an assertion fails. In [nim-chronicles](https://github.com/status-im/nim-chronicles), this is used for the implementation of the `logScope` construct.

By now, you should be getting the pattern.

**Comment by timotheecour** [comment]
I understand the use cases; the problem (as always) is when user redefines a template without knowing it's a redefinition. Hence the `redefinition` pragma.

**Comment by Bulat-Ziganshin** [comment]
So, the proposal is:
- by default, fail to compile when const/template/macro is redefined
- allow to do it with {.redefinition.} pragma
- new definition applies only to the code below
- update manual sections on const/template/macro mentioning this all

Please vote with your thumbs :)

Follow-on question: are there alternative ideas on the pragma name?

**Comment by Bulat-Ziganshin** [comment]
```Nim
template foo(): int {.redefinition.} = 2 # error: this doesn't override anything
```
IMHO, redefinition of undefined thing should be allowed - the pragma utility is more "I don't care about any previous definitions" rather than "I know that there is previous definition". Of course, the pragma names looks more like the second case, but may be there are other ideas for this name?

**Comment by metagn** [comment]
It turns out a fair amount of packages rely on template redefinitions (tested in #20211). Likely because the implicit behavior of templates being injected and not gensyming inside other templates makes people forget about scoping. Sometimes it's desirable to not open a new scope (as in `await`).

The biggest issue is that this is really hard to detect. It's not easily searchable, and a lot of testing would be required to fix packages. Maybe redefinitions could be restricted to templates with any typed arguments or overloaded templates.

So I think the most we can do now is make template redefinition a warning, and add the `override`/`redefinition` pragma on top of it. (I vote the name `redefine` despite it not necessarily redefining)
