### ISSUE TITLE
Natural type weirdness

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#8292]
What's happening here?

```Nim
var i = 0
var n: Natural = 0

proc incNat(n: var Natural) = inc(n)

incNat(i)     # OK
incNat(n)     # doesn't compile
```

This is the error:

```
natural.nim(6, 8) Error: for a 'var' type a variable needs to be passed; but 'Natural(i)' is immutable
```

My theory is that `i` is inferred to an `int` and var arguments must be passed by pointer, so I guess the conversion cannot be made, but the error message is quite confusing. If this is the case, maybe there's nothing to do about the behaviour.

**Comment by skilchen** [comment]
Your problem is not related to the type `Natural` (and i think the comments in the code are the wrong way: it is line 6 `incNat(i)` that doesn't compile). 

The problem is that a type conversion can't produce a `var Natural` but only a new value of type Natural, because it has no address of a variable where it could store the converted value. Otherwise the type of variable `i` would change from `var int` to `var Natural` and that is not something that Nim allows you to do. Thats more or less what the error message is trying to tell you.
```nim
var i = 0
var i32: int32 = 0

proc incInt(n: var int) = inc(n)

incint(i)   # OK
incint(i32) # doesn't compile
```
fails for exactly the same reason.

**Comment by johnnovak** [comment]
Yes, my comment were the wrong way around. Thanks for the explanation, now it makes sense. I'm closing the issue.
