### ISSUE TITLE
Optimize string concatenation (was: [strutils] list of bugs and missing features)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8317]
in C++, `auto s = str1 + str2 + str3` is known to not be efficient, compared to: `string s = str1 ; s+= str2; s+=str3;` 
I wonder if `&` suffers from same issue: does `a & b & c` use any temporaries?

- [ ] SPEED: `append(a, b, c, ... ) : string` => returns`$a & $b & $c ...` but without using any temporaries instead of >= n-1 (n=nb args)
NOTE: should be smart enough to construct the $ai in place when possible instead of creating temporary strings for each $ai (something like https://dlang.org/changelog/2.079.0.html#toString would enable that)
NOTE: my attempt at it hit this bug: https://github.com/nim-lang/Nim/issues/8316

- [ ] SPEED: `appendTo(dst: string, a, b, ... ) : void` => returns`dst = dst & $a & $b & $c ...` but with a single allocation

**Comment by trustable-code** [comment]
Better use `add()` instead of `&`. 
`s.add(str1)` is much faster than `s = s & str1`. 
Maybe the Nim compiler should do this optimization.

**Comment by timotheecour** [comment]
I'm not intending to use `a & b` in an implementation of `append`, I'm just using `$a & $b & $c` above to illustrate what this function returns; 
btw wouldn't `&=` be the same as `add` ?

**Comment by timotheecour** [comment]
implementing `appendTo` gets me 10X speedups in some synthetic benchmark, stay tuned...

**Comment by Bennyelg** [comment]
Why not just do `+` like almost any language?

**Comment by GULPF** [comment]
This should be possible to optimize with [term rewriting macros](https://nim-lang.org/docs/manual.html#term-rewriting-macros), without having to call a seperate proc. One of the examples in the manual even implements this, not sure why it was never added to the stdlib.

**Comment by hlaaftana** [comment]
&= for strings uses the same magic as add, and is also defined as a generic template that calls an open symbol `add`.

https://github.com/nim-lang/Nim/blob/332469692d5053c6c935163e196b117b6979c8e7/lib/system.nim#L3695-L3701

And yes, `a & b & c` compiles to `var temp = newString(a.len + b.len + c.len); temp.add(a); temp.add(b); temp.add(c); temp`.

**Comment by krux02** [comment]
There are expression templates in nim that have the potential to optimize string concatenation. But the bigger problem not within string expressions, it is with a lot of intermediate strings that are created for a string representation. For example you have a tree, every node is converted to a a new string object and this is then copied into a new string object for the parent string representation. This has O(N²) time costs. Also for ``echo`` every argument is written into a new string object. That is neither good for GC nor for non GC languages because allocation is normally not the fasted thing in a language. Though for debug strings (most uses of $ operator) this is not a problem at all. If you plan to generate bigger files/strings don't rely on the $ operator.
