### ISSUE TITLE
we probably should forbid using parameter name that are equal to proc/template name

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8320]
this was the root cause of https://github.com/nim-lang/Nim/issues/8273

**Comment by GULPF** [comment]
I think it makes sense to allow it, since it's just a result of how scopes and shadowing works. The parameters are in a lower scope than the proc, so naturally they can shadow the proc name. I tried with a few different languages (JavaScript, Java, Python) and they all support it. The real bug in #8273 is the fact that it doesn't work with `static[T]`.

**Comment by GULPF** [comment]
[Even D supports it](https://run.dlang.io/?compiler=dmd&source=import%20std.stdio;%0Aimport%20std.algorithm;%0Aimport%20std.range;%0A%0Avoid%20foo(string%20foo)%0A%7B%0A%20%20%20%20writeln(foo);%0A%7D%0A%0Avoid%20main()%0A%7B%0A%09foo(%22Hello,%20World!%22);%0A%7D) ;)

**Comment by timotheecour** [comment]
=> filed https://github.com/nim-lang/Nim/issues/8324 to track that; I still think allowing this is error prone (makes code hard to read and can be a source of nasty bugs, eg code compiles but does the wrong thing that what user intended because (when, say, param refers to a proc itself)

**Comment by Araq** [comment]
I don't like special casing in Nim's scope handling. Scopes need to be simple in order for meta programming to work better. So, sorry, I'm closing this already.
