### ISSUE TITLE
Writing to readonly data gives SIGBUS error; should be CT error instead

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#8463]
While wrapping a C library and trying to understand why it could write to `ptr char` but segfaulted when I asked it to write to `(var) cstring`, I came upon the following issue:

```Nim
var x: cstring = "0123456789"
x[1] = 'A' # SIGBUS: Illegal storage access. (Attempt to read from nil?)

echo x

import typetraits
echo x.type.name
```

Note that this is a SIGBUS (accessing unaddressable memory) not a SIGSEGV (accessing unauthorized memory).

**Comment by mratsim** [comment]
Tagging @yglukhov, in C we can reproduce it with:

```C
int main(int argc, char **argv)
{
    char* s = "0123456789";
    s[0] = 'c';
    return 0;
}
```

which points to constant memory in the executable

and it can be fixed by using
```C
int main(int argc, char **argv)
{
    char s[10] = "0123456789";
    s[0] = 'c';
    return 0;
}
```

**Comment by Bulat-Ziganshin** [comment]
It may be related to https://github.com/nim-lang/Nim/issues/8370 - Nim doesn't distinguish "char *" and "const char *", so it can try to write into constant C strings. The "solution", indeed, is to make all Nim literal strings mutable, i.e. "123" Nim string constant should be declared as `char str[] = "123"` rather than erroneous `char* str = "123"` (modern C++ compilers complain here that you assign const char * to char*).

**Comment by Bulat-Ziganshin** [comment]
I don't have an idea whether and to which extent it's possible. I explained [here](https://github.com/nim-lang/Nim/issues/8370#issuecomment-406660961) that while we have let/const on higher level, we can't include such fields into structures, so the protection may be leaky. But it's just a wild assumption from general theoretical viewpoint :)

**Comment by Araq** [comment]
I don't think there is anything to fix here, ``cstring`` literals are read-only.

**Comment by BarelyMalicious** [comment]
@Araq Give a better error message than SIGBUS?

**Comment by timotheecour** [comment]
> I don't think there is anything to fix here, cstring literals are read-only.

there should be a CT error, it should be illegal to write to rodata

I was going to file an issue but I searched and found this. Here's another example, same root cause:
```nim
const a = "abc"
var x = a.cstring
x[0]='t' # SIGBUS: Illegal storage access.
```

This is related also to https://github.com/nim-lang/RFCs/issues/126#issuecomment-616306221: 
> D distinguishes between `enum a = expr;`: enum creates a compile-time only construct; it has no address; pretty close to nim's const a = expr
> static const a = new Foo(): this computes at CT as well but puts in the static data segment, and has an address you can access at runtime. in nim, that'd be the analog, for example, of let a = "foo".cstring, which puts "foo" in the data segment as readonly memory

and solving this issue properly would enable `default values for object properties` with safe semantics even for ptr-like types, among other things.

There should be a storage class to represent rodata, and prevent write access at CT. How exactly to do that needs to be determined but this problem is solvable (and other languages, eg D, handle this aspect well).

I have a concrete proposal in mind but no RFC yet, that would work not only for this problem but also for escape analysis (for first class openarrays)

## note
a simpler fix might be possible by using C arrays (char[]) instead of c string litterals in cgen, but this might have performance implications; EDIT: this would prevent returning a cstring from a proc, as it'd allocate on stack, so it's not a viable alternative in most cases

## related
* [[WIP] [RFC] Nim should have `immutable` type qualifier (`let` is more like C++'s const); it would enable a new string class design, etc · Issue #8370 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/8370)
* [Support default values for object properties · Issue #126 · nim-lang/RFCs](https://github.com/nim-lang/RFCs/issues/126)
* [Write tracking for Nim](https://nim-lang.org/araq/writetracking.html)
* [D enum vs static const](https://p0nce.github.io/d-idioms/#Precomputed-tables-at-compile-time-through-CTFE)

**Comment by Araq** [comment]
> there should be a CT error, it should be illegal to write to rodata

There is no bug here. Let's keep this closed please. If some RFC gets accepted that improves the situation, that's fine, but with the current spec it is not a bug the compiler needs to detect.

**Comment by timotheecour** [comment]
this could be fixed by https://github.com/timotheecour/Nim/issues/524
