### ISSUE TITLE
BUG: `case` inconsistently accepts set `of` argument

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8537]
BUG: the 1st `of {nnkIdent, nnkSym}:` is allowed
the 2nd one `of {nnkEmpty, nnkLiterals}:` is not allowed, giving compile error

seems like the 1st one should also give compiler error?
either way, it's inconsistent

```nim
import macros

proc replaceNodes(ast: NimNode): NimNode =
  proc inspect(node: NimNode): NimNode =
    case node.kind:
    of {nnkIdent, nnkSym}: #this set one is allowed, seems like a BUG
    # of nnkIdent, nnkSym:
      return ident($node)
    of {nnkEmpty, nnkLiterals}: # this one is not allowed, giving Error: type mismatch: got <set[NimNodeKind]> but expected 'NimNodeKind = enum'
    # of nnkEmpty, nnkLiterals: # this would work
      return ident($node)
    else:
      var rTree = node.kind.newTree()
      for child in node:
        rTree.add inspect(child)
      return rTree
  result = inspect(ast)
```

/cc @mratsim I extracted this from your answer in https://github.com/nim-lang/Nim/pull/8531#issuecomment-410436458

**Comment by GULPF** [comment]
The use case for allowing a set is to allow the case values to be defined in a `const` somewhere else. The reason that `{nnkEmpty, nnkLiterals}` doesn't work is because `nnkLiterals` isn't an enum value, it's a set: https://github.com/nim-lang/Nim/blob/96c6c82d5592a7a19006c0fb161a74178cea9700/lib/core/macros.nim#L131

**Comment by timotheecour** [comment]
gotcha thanks! closing
