### ISSUE TITLE
Cannot use `unsafeAddr` on an element from for loop 

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#8630]
Tested on devel 0.18.1
```nim
proc test(strings: seq[string]) =
  var p1 = unsafeAddr(strings) # works
  var i = 0
  while i < strings.len:
    var p2 = unsafeAddr(strings[i]) # works
    inc(i)
  for s in strings:
    var p3 = unsafeAddr(s) # doesnt work; instead proc test(strings: var seq[string]) =
    # and for s in mitems(strings) is needed
    # Note: the error says I should try `unsafeAddr` here but I already use it. 
```

**Comment by Clyybber** [comment]
Can confirm, this has also affected me.

**Comment by andreaferretti** [comment]
Kind of makes sense, right? You can have many aliases for a string (for instance `strings[i]` and a local variable defined by `let s = strings[i]`) and then the address of these things will be different (one is on the heap, the other on the stack). This is by the way a reason why `unsafeAddr` is unsafe.

The expression `for s in strings` does not specify what kind of alias `s` is, so it does not really make much sense to take its address (with `mitems` you are forced to point to `strings[i]` for modification). In other words, is your second loop equivalent to the first one or to the following?

```nim
while i < strings.len:
    let s = strings[i]
    var p2 = unsafeAddr(s) # works
    inc(i)
```

Remember that variables defined with `let` might not even be materialized on the stack, but compiled away via some optimization and you will see what the issue is

**Comment by awr1** [comment]
@andreaferretti "Remember that variables defined with let might not even be materialized on the stack" - isn't this somewhat different because `strings` is an argument? Similar to a variable declared by `let` (given the immutable nature of arguments in Nim), but not quite the same thing. Isn't the main reason `unsafeAddr` is around is for being able to plug proc arguments into C functions that read pointers?

**Comment by Araq** [comment]
@andreaferretti It's just a bug, this code should compile.
