### ISSUE TITLE
template in template scope issue

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8701]
- [ ] case1 fails, and seems buggy; shouldn't that either lead to a compile time error (redefinition of template) or use the redefined template `foo` (which would make the assert succeed)?
- [ ] is it possible to define a template whose definition is limited to the scope where it's defined? (without using a block statement as in `case2`)

```nim
when defined(case1):
  template bar(): auto =
    template foo(): untyped = "ok1"
    foo()
  doAssert bar() == "ok1"

  template bar2(): auto =
    template foo(): untyped = "ok2"
    foo()
  # BUG: this fails, returns "ok1" instead of ok2
  doAssert bar2() == "ok2"

when defined(case2):
  # ok
  template bar(): auto =
    block:
      template foo(): untyped = "ok1"
      foo()
  doAssert bar() == "ok1"

  template bar2(): auto =
    block:
      template foo(): untyped = "ok2"
      foo()
  doAssert bar2() == "ok2"
```

**Comment by jcosborn** [comment]
A workaround seems to be to explicitly declare the templates to be `gensym`.  Apparently issue #2465 is now fixed.  I think `gensym` should still be the default here though.
```nim
template bar(): untyped =
  template foo(): untyped {.gensym.} = "ok1"
  foo()
doAssert bar() == "ok1"

template bar2(): untyped =
  template foo(): untyped {.gensym.} = "ok2"
  foo()
doAssert bar2() == "ok2"
```

**Comment by timotheecour** [comment]
> I think gensym should still be the default here though.

no, see manual: https://nim-lang.github.io/Nim/manual.html#templates-hygiene-in-templates

> The default for symbols of entity type, var, let and const is gensym and for proc, iterator, converter, template, macro is inject. However, if the name of the entity is passed as a template parameter, it is an inject'ed symbol:


> Apparently issue #2465 is now fixed

partially, see https://github.com/nim-lang/Nim/issues/2465#issuecomment-643482519

> A workaround seems to be to explicitly declare the templates to be gensym

yes; but it's just a workaround indeed, bug still there

**Comment by jcosborn** [comment]
After some more testing, I think this behavior might be intended.  Since `foo` defaults to `{.inject.}`, the symbol isn't created when `bar2` is defined, but instead only when `bar2` is called.  However the call to `foo` inside `bar2` gets bound at definition time to the 1 existing symbol `foo`.  Adding a `mixin foo` to `bar2` produces the expected ambiguous call.  If the intent is to bind to the local definition regardless of any others, then `{.gensym.}` is required.

**Comment by metagn** [comment]
Original example works now because `doAssert` is a template that puts the argument in an `if` condition which creates a new scope (you cannot call `foo` outside for example). If you do:

```nim
when true:
  template bar(): auto =
    template foo(): untyped = "ok1"
    foo()
  let x = bar()
  doAssert x == "ok1"

  template bar2(): auto =
    template foo(): untyped = "ok2"
    foo()
  # BUG: this fails, returns "ok1" instead of ok2
  let y = bar2()
  doAssert y == "ok2"
  echo foo()
```

it compiles but the assertion fails as implied in the issue, but you do get a new warning (#20211):

```
(9, 5) Warning: template 'foo' is implicitly redefined; this is deprecated, add an explicit .redefine pragma [ImplicitTemplateRedefinition]
```

So the code here is undefined behavior that will become opt in eventually and error by default, as it does if you use anything but `template`.
