### ISSUE TITLE
scanf Invalid node kind nnkBracketExpr for macros.`$`

### ISSUE THREAD

**Issue by bung87** [nim-lang/Nim#8925]
Nim Compiler Version 0.18.1 [MacOSX: amd64]
Compiled at 2018-09-07
git hash: 91b37311d9974ae30745946a52c9a971da1616f4
``` 
lib/system.nim(2818, 7) Error: unhandled exception: /Users/bung/Nim/lib/core/macros.nim(1109, 17) `false` Invalid node kind nnkBracketExpr for macros.`$`
```
``` nim
import times
import strscans
var 
    hour:HourRange
    minute:MinuteRange
    time_str:string

if scanf(time_str, "$i:$i", hour,minute):
    discard

```

**Comment by Vindaar** [comment]
As you can see in https://github.com/nim-lang/Nim/pull/8937, the issue is that in principle the call to `scanf` tries to fail, but crashes when printing the error message.

I'm not sure why you'd want to use `scanf` for this in the first place (I'd use https://nim-lang.org/docs/times.html#parse,string,string,Timezone or rather the current version on devel, which was rewritten), but if you wanted to do it with `scanf` you could write your own matcher proc. Something like this:

```nim
proc matchRange[T: range](input: string, rangeVal: var T, start: int): int =
  var i = 0
  var strVal: string
  while i + start < input.len:
    case input[i + start]
    of {'0' .. '9'}:
      strVal.add input[i + start]
    else:
      break
    inc i
  rangeVal = parseInt(strVal)
  result = i
```
which you'd just use like
```nim
  if scanf(time_str, "${matchRange}:${matchRange}", hour, minute):
```

(this is the naive way and doesn't allow `_`, but should be enough to get you started).

**Comment by bung87** [comment]
thanks! good example of matcher, learned something, you're right,`parse` seems good enough to do this job. I also hope `scanf` can support range.
