### ISSUE TITLE
OrderedSet.items infinite loop

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#9005]
Code
```nim
import sets

proc test =
  var s = initOrderedSet[(int, int)]()
  for i in 0 .. 30: incl(s, (i, i))
  
  while len(s) > 0:
    var e: s.A
    for i in s:  # <- Here
      e = i
      break
    excl(s, e)
    # echo e # latest output: (Field0: 28, Field1: 28)
  
test()
```
***
```nim
>nim -v
Nim Compiler Version 0.18.1 [Linux: i386]
Compiled at 2018-09-15
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 4342b79a3c05fcfb1e6fc97152daa0075b0b9603
active boot switches: -d:release
```

**Comment by skilchen** [comment]
As a workaround, you can initialize the OrderedSet with a high enough number.
```nim
var s = initOrderedSet[(int, int)](512)
```
Interestingly the following modification of your example has the same issue:
```nim
# tOrderedSet.nim
import sets, strutils

proc test(n: int) =
  var s = initOrderedSet[string](n)
  for i in 0 .. 30: incl(s, $i)
  excl(s, "2")
  for i in s:
    echo i

when isMainModule:
  import os
  let n = parseInt(paramStr(1))
  test(n)
```
If you store this as `tOrderedSet.nim`, compile it as `nim c -d:release tOrderedSet` and then run it with some increasing powers of 2 as parameter you will also encounter the infinite loop.
`./tOrderedSet 1024`
is the first one not looping forever.

**Comment by LemonBoy** [comment]
The `exclImpl` implementation for `OrderedSet` is completely wrong, if you execute the following snippet it'll burst up in flames.

The problem derives from the collision cluster distribution mechanism that was designed without the extra bookkeeping introduced by the element chaining: once the elements are displaced we may have three dangling indices, namely `s.first`, `s.last` and `s.data[M].next` with `M` being a generic index.

```nim
var s = initOrderedSet[(int, int)]()
for i in 0 .. 30: incl(s, (i, 0))
for i in 0 .. 30: excl(s, (i, 0))
```

CC @GULPF since he introduced it in #6158
