### ISSUE TITLE
Static + zero-ed array optional param: compiler hangs

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9039]
The following leaves the compiler in an unending loop.
This detects the nesting of arrays of arrays of arrays of ...

The sequence version works fine and has been battle-tested in Arraymancer.
However the array version will never finish to compile.

```Nim
#### Compiler stuck in loop

func default(T: typedesc[array]): T = discard

echo default(array[3, int]) # [0, 0, 0]

func shape*[T: not char](s: openarray[T], rank: static[int], nesting = 0, parent_shape = default(array[rank, int])): array[rank, int] =
  result = parent_shape
  result[nesting] = s.len
  when (T is seq|array):
    result = shape(s[0], nesting + 1, result)

echo [1, 2, 3].shape(rank = 1)
echo [[1, 2, 3],
      [4, 5, 6]].shape(rank = 2)

#### Working

# func shape*[T: not char](s: openarray[T], parent_shape: seq[int] = @[]): seq[int] =
#   result = parent_shape & s.len
#   when (T is seq|array):
#     result = shape(s[0], result)

# echo [1, 2, 3].shape # @[3]
# echo [[1, 2, 3],
#       [4, 5, 6]].shape # @[2, 3]
```

**Comment by timotheecour** [comment]
@mratsim next time please show the git hash where you tested the code (as mentioned in issue template) ; in this case, i could reproduce the bug only in 0.19.0 (f6c5c636bb1a1f4e1301ae0ba5a8afecef439132)

closing this in https://github.com/nim-lang/Nim/pull/17983 which adds a test case

note that the code in top post is invalid, because nesting is not static so nesting+1 is not static, so it can't match the `rank: static int` param.

and if you change the code with `nesting: static int = 0`, it gives a different (legitimate IIRC) error because result in `esult = shape(s[0], nesting + 1, result)` can't match nesting param (`parent_shape = result` would also error)

**Comment by Clyybber** [comment]
> @mratsim next time please show the git hash where you tested the code (as mentioned in issue template) ; in this case, i could reproduce the bug only in 0.19.0 ([f6c5c63](https://github.com/nim-lang/Nim/commit/f6c5c636bb1a1f4e1301ae0ba5a8afecef439132))

I think this issue is older than the issue template :)
