### ISSUE TITLE
Troll problem

### ISSUE THREAD

**Issue by JoJoBro** [nim-lang/Nim#9047]
Can we do something to stop these trolls? Maybe adopting a CoC similar to the one ruby has:

-   Participants will be tolerant of opposing views.
-   Participants must ensure that their language and actions are free of personal attacks and disparaging personal remarks.
-   When interpreting the words and actions of others, participants should always assume good intentions.
-   Behaviour which can be reasonably considered harassment will not be tolerated.

Either that or possibly openly state that the project will not accept a CoC since the community is full of good people? :man_shrugging:

**Comment by TimothyBergher** [comment]
Cute, but the Ruby community is notoriously toxic (Google it) and it's probably due to their bad CoC. I suggest the Contributor Covenant, as it shows trans people that they are welcome. A project cannot survive long without a CoC, so the second option is immediately out, and I am sure that the devs agree
