### ISSUE TITLE
[docgen] Make the link text in the sidebar more descriptive.. add proc signature too

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#9102]
For example: https://nim-lang.org/docs/system.html

While scrolling through the sidebar, you see:

![image](https://user-images.githubusercontent.com/3578197/46216333-54d47100-c30d-11e8-97e8-ad13c96048b8.png)

The links to `high`, `low`, etc are not much useful. It would be better to include the signatures in there too. It will become a lot more verbose, but more useful too.

Or.. may be just collapse all `high` links into a single link pointing to the first of the `high` procs, and so on.

**Comment by awr1** [comment]
>Or.. may be just collapse all high links into a single link pointing to the first of the high procs, and so on.

Contingent on that the declarations/definitions are made in the correct order, I'm assuming? So that:
```nim
proc high..
proc low...
proc blah...
proc high...
proc low...
```
laid out in the nim file in that manner wouldn't collapse in the docs? (Or should there be some type of reordering involved?)

**Comment by kaushalmodi** [comment]
@awr1 I would certainly prefer having the signatures next to the proc names in the sidebar too. 

Collapsing all proc variants is just a last resort thing.

**Comment by awr1** [comment]
If we do that, instead of having the parameters on the same line, I think we should have it below each name in smaller, grayed out text, like so:
![image](https://user-images.githubusercontent.com/41453959/46265205-f2849780-c4e9-11e8-88cc-9e70ba173b6c.png)

**Comment by kaushalmodi** [comment]
@awr1 I think that looks great! Why don't you submit a PR?

**Comment by cup** [comment]
https://github.com/nim-lang/Nim/issues/12399

**Comment by cup** [comment]
Here is some JavaScript that improves it marginally:

~~~js
const list_old = document.querySelector('.simple-toc-section');
const a_old = list_old.querySelectorAll('a');
const list_new = [];

for (const e1 of a_old) {
   list_new.push([e1.title, e1.href]);
}

list_new.sort();
const n_max = 33;

for (const a1 of list_new) {
   const a_new = document.createElement('a');
   const p_new = document.createElement('p');
   if (a1[0].length > n_max) {
      a_new.textContent = a1[0].substring(0, n_max) + '…';
   } else {
      a_new.textContent = a1[0];
   }
   a_new.href = a1[1];
   p_new.append(a_new);
   list_old.parentNode.append(p_new);
}

list_old.remove();
document.querySelector('.nine.columns').style.width = '74%';
document.querySelector('.three.columns').style.width = '25%';
~~~

**Comment by kaushalmodi** [comment]
@cup Would it be possible to bake that into the JS that runs on the Nim doc site and submit that as a PR?

**Comment by cup** [comment]
@kaushalmodi better would be to modify the code that actually generates the site. In general, server side is better than client side. If someone can point me to where that code is, I can look into it.

**Comment by narimiran** [comment]
> If someone can point me to where that code is, I can look into it.

[This part of rstgen.nim](https://github.com/nim-lang/Nim/blob/devel/lib/packages/docutils/rstgen.nim#L774) seems to be what you're looking for.

**Comment by cup** [comment]
@narimiran thanks - here is a permalink for my own use:

https://github.com/nim-lang/Nim/blob/21ea1094ef0de2e0661835f9f8b56fa0b9eb4d17/lib/packages/docutils/rstgen.nim#L774-L777

**Comment by cup** [comment]
@narimiran ok I dont think thats quite right. If you look here:

https://nim-lang.github.io/Nim/os

The links look like this:

~~~html
<a class="reference" href="#joinPath,string,string"
title="joinPath(head, tail: string): string"><wbr>join<wbr>Path<span
class="attachedType"></span></a>
~~~

but the code you point to look like this:

https://github.com/nim-lang/Nim/blob/21ea1094ef0de2e0661835f9f8b56fa0b9eb4d17/lib/packages/docutils/rstgen.nim#L774-L777

Notice that the import attribute `title` is missing. Proper locations would be:

https://github.com/nim-lang/Nim/blob/21ea1094ef0de2e0661835f9f8b56fa0b9eb4d17/lib/packages/docutils/rstgen.nim#L1270-L1273

and:

https://github.com/nim-lang/Nim/blob/21ea1094ef0de2e0661835f9f8b56fa0b9eb4d17/config/nimdoc.cfg#L50-L55

it seems all that needs to be done is to use the `title` as the link text,
something like:

~~~html
<li><a class="reference" href="#$itemSymOrIDEnc"
title="$header_plain">$header_plain</a></li>
~~~

as this is a stylistic choice (but probably a warranted one), I think whoever
makes the decisions would need to ok it because I move forward with a patch.
Thanks!

**Comment by nu8** [comment]
I wrote a script that returns the Procs in a more digestable way:

https://github.com/nu8/cove/blob/master/match-links/nim-links.php

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/16857
