### ISSUE TITLE
Can't round floats at compile time

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#9113]
```nim
import math

static: 
  echo 2.1234.round(2)
```

> ../../.choosenim/toolchains/nim-0.19.0/lib/pure/math.nim(422, 14) Error: cannot 'importc' variable at compile time

**Comment by demotomohiro** [comment]
Nim VM cannot use FFI. In other words, Nim compiler cannot call a proc used in your code at compile time that call a function in C language using importc.
See:
https://forum.nim-lang.org/t/4249

Implimenting proc ``round`` without using C library might be possible.
But using ``round`` for printing a float nicely is a not a good idea.
https://github.com/nim-lang/Nim/issues/9082

See strformat module
https://nim-lang.github.io/Nim/strformat.html

```nim
  import strformat

  echo fmt"{2.12345:.0f}"
```
But fmt is also cannot be used at compile time because it use importc.

**Comment by skilchen** [comment]
Thanks to the merge of PR #9089, `round` is now available at compiletime. 

This issue can be closed.
