### ISSUE TITLE
nim doc adds strange numbers to variable names in templates

### ISSUE THREAD

**Issue by jabbalaci** [nim-lang/Nim#9143]
Consider the following program (example.nim):

```nim
# https://gitter.im/nim-lang/Nim?at=5bb238511e23486b9370cf48
template repeat*(times: static[Natural], body: untyped): untyped =
  ## Repeat a body N times.
  ##
  ## I saw it first in Kotlin.
  runnableExamples:
    var cnt = 0
    repeat(5):
      inc cnt
    doAssert cnt == 5

  for _ in 0 ..< times:
    body
```

Available at https://ptpb.pw/9N-t/nim. If you run `nim doc example.nim` , the variable `cnt` becomes `cnt224459` in the HTML. In the HTML source you have `...<span class="Identifier">cnt</span><span class="DecNumber">224459</span>...`. Here is a screenshot: https://i.imgur.com/MjwaeCA.png .

Nim version: 0.19.0. Tried it under Linux, 64 bit.

**Comment by LemonBoy** [comment]
> strange

The numbers are there because templates are hygienic.

The fix is pretty easy so I'm leaving some hints & tips here (this the spirit of the Hacktoberfest, isn't it?):
- A brief introduction to how this works: the semantic pass is a fundamental step where most of the work happens, the end result is then feed into the successive passes that may:
  - Perform further processing then sending the resulting AST to the codegen
  - Walk over the AST and generate the documentation as needed (that's `nim doc`)
  - Walk over the AST, fix it and spit it back as source code (that's `nimfix` or `nimpretty`)
- Templates are hygienic: that means that every instantiation will get its own set of locally declared identifiers so that there are no declaration clashes if the same template is instantiated twice (or with the already defined variables)
- The problem here is that when the template is analysed we shouldn't touch the `runnableExamples` body even though it is part of a template
- This happens in `semTemplBody`
- `runnableExamples` is a magic procedure, this means that its behaviour is implemented in the compiler and is defined as follows:
```nim
  proc runnableExamples*(body: untyped) {.magic: "RunnableExamples".}
```
 As a tip if you want to figure out where a given magic is handled in the compiler just grep the source code for `m + "magic string"`, eg. `"mRunnableExamples"` in this case.
- Since `runnableExamples` is a `proc` one should look at the `nkCallKinds` case
- The `nkCallKinds` nodes have the following form `<callee> <arg1> ... <argN>`
- To check whether the callee is the one we need have a look at `isRunnableExample` in `docgen.nim` (ideally one would move that function in a place where it can be imported when needed)
- `nkIdent` are turned into `nkSym` (or `nkSymChoice` if the symbol is ambiguous) by performing a lookup... if needed calling `semTemplBody` on the first son will do the trick.
- Have fun
