### ISSUE TITLE
Converter is applied to the first parameter of operator instead of last

### ISSUE THREAD

**Issue by rokups** [nim-lang/Nim#9165]
```nim
type ustring* = distinct string

converter toUString*(s: string): ustring = ustring(s)
converter toString*(s: ustring): string = string(s)

proc `[]=`*(s: var ustring, slice: Slice[int], replacement: ustring) {.inline.} =
    s = replacement

var s = ustring("123")
s[1..2] = "3"
doAssert s == "3"
```
Results in an error:

> test.nim(10, 1) Error: for a 'var' type a variable needs to be passed; but 'toString(s)' is immutable

I was informed on irc that last parameter should be converted instead of first.

**Comment by skilchen** [comment]
what happens, if you change:
```nim
proc `[]=`*(s: var ustring, slice: Slice[int], replacement: ustring) {.inline.} =
    s = replacement
```
to
```nim
proc `[]=`*[T,U](s: var ustring, slice: HSlice[T, U], replacement: ustring) {.inline.} =
  s = replacement
```
according to the new definition of this procedure in [lib/system.nim](https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L3573)?

**Comment by rokups** [comment]
That works. What is going on here though? `1..2` seems like it passes two integers to `..` operator, why `Slice[int]` isnt working here?

**Comment by skilchen** [comment]
My not very well informed guess:
- Your `[]=` definition doesn't overload the `[]=` from `lib/system.nim`. During the overload resolution the alias `Slice[int]` is not considered equivalent to `HSlice[int, int]`. I don't know if this is intended or not.
- Your `s[1..2] = "3"` matches the signature of `[]=` in `lib/system.nim` because you have the converter `toString` and  because `Slice[int`] is an alias for and therefore implicitly convertible to `HSlice[int, int]`. 
- But your `toString` returns an immutable value. 
- This causes the error message you are seeing.

**Comment by ringabout** [comment]
It works since Nim v0.20.0.
