### ISSUE TITLE
Type which followed by a function and generated by a template will not shown in docs generated by `nim doc`

### ISSUE THREAD

**Issue by 7sDream** [nim-lang/Nim#9235]
### def.nim

```nim
import macros

template aEnum*(): untyped = 
  type
    A* {.inject.} = enum
      aA

template bEnum*(): untyped = 
  type
    B* {.inject.} = enum
      bB
  
  func someFunc*() = discard
```

### doc.nim

```nim
import ./def

aEnum()
bEnum()
```

Then run `nim doc doc.nim` as usual, you can notice there is no enum `B` in generated html.

## Screenshot:

![image](https://user-images.githubusercontent.com/7822577/46579625-12670e80-ca48-11e8-9576-7c0b3ad646a1.png)

**Comment by LemonBoy** [comment]
The problem is that the second template is translated into a `nkStmtList` containing the type-section and the `proc` declaration and the compiler marks only the last statement as belonging to the place where the template is expanded (check `wrapInComesFrom` for more info). This means that `generateDoc` will happily skip all but the last expressions.

**Comment by 7sDream** [comment]
@LemonBoy 

The strange this is, if I merge the two files into one, it works as expected:

![image](https://user-images.githubusercontent.com/7822577/46583467-97731780-ca8a-11e8-819d-ee0af4666180.png)
