### ISSUE TITLE
C compiler error when casting proc to func.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#9251]
The following code raises a C compiler error about incompatible type casts. Nim doesn't recognize the issue.

```
var
    y = proc() {.closure.} =
        echo "Hi"
    z = cast[func()](y)
```

**Comment by kayabaNerve** [comment]
To be clear, my example code compiled fine. It was also written two months ago.

You also said it (X) was casted to (X). Did you mean to say a closure proc can be casted to a regular proc but shouldn't be allowed to?

**Comment by nc-x** [comment]
No I just meant to say that the C compiler error is not related to func  (The compiler/stdlib has places where proc is cast to proc {.nosideeffect.}).
I don't know where exactly the problem is in the compiler but in your example both `y` and `cast[func()](y)` are both `proc () {.closure.}`so the compiler should probably ignore the cast and set z = y. That should fix this issue.

**Comment by dom96** [comment]
Your original title implied that casting shouldn't be possible, it should be.

**Comment by narimiran** [comment]
WIth Nim devel 1.1.1, the original example produces:
```
Error: func keyword is not allowed in type descriptions, use proc with {.noSideEffect.} pragma instead
```

When you do what the error message says (`z = cast[proc() {.noSideEffect.}](y)`), it compiles fine.
