### ISSUE TITLE
testsuite silently ignores a number of tests

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9328]
- [ ] are isMainModule blocks run by CI or not?
if not, they either should, or its use should be discouraged for testing as it gives false sense of it working
**EDIT**: they're not, currently

- [ ] isMainModule block fails for ./lib/core/typeinfo.nim

nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r ./lib/core/typeinfo.nim

/Users/timothee/git_clone/nim/Nim/lib/core/typeinfo.nim(685) typeinfo
/Users/timothee/git_clone/nim/Nim/lib/system.nim(3876) failedAssertImpl
/Users/timothee/git_clone/nim/Nim/lib/system.nim(3869) raiseAssert
/Users/timothee/git_clone/nim/Nim/lib/system.nim(2916) sysFatal
Error: unhandled exception: /Users/timothee/git_clone/nim/Nim/lib/core/typeinfo.nim(685, 18) `n == "name" and $kind(a) == "akString"`  [AssertionError]

using echo shows "Field0" instead of "name"

Note:
git rev-parse HEAD
fde4a086c5be2140b3b39014b302f681c87cb33c

## proposal
* testament should list all files `foo.nim` with a `isMainModule` block (using maybe nimgrep)
* we maintain a (small) blacklist of files where we don't want to run `foo.nim` (or don't want to run in a particular platform)
* we run each of the resulting `foo.nim`

Note: it's important to keep a blacklist of files that we skip, as opposed to other way around (a whilelist) as it's much easier to maintain that way; so if someone adds a `isMainModule` in a file, it'll automatically be run by CI (except if added to blacklist)

**Comment by LemonBoy** [comment]
> are isMainModule blocks run by CI or not?

Not all of them, afair only a few selected stdlib modules are tested like this.

> isMainModule block fails for ./lib/core/typeinfo.nim

Sometimes the tests get out of sync with the implementation.
The problem here is that we must make sure that tuples are structurally equivalent despite them having field names or not and to do so we [strip the field names](https://github.com/nim-lang/Nim/blob/d2b04a8bc7a78845d25e8b789184ae54e98073ec/compiler/ccgtypes.nim#L1234,L1235).

And, for the love of whatever deity you believe in, can you please stop writing an essay in the ticket title?

**Comment by timotheecour** [comment]
=> my PR https://github.com/nim-lang/Nim/pull/10044 fixes it
