### ISSUE TITLE
newAsyncSmtp() raises exception with Nim 0.19.0

### ISSUE THREAD

**Issue by FedericoCeratto** [nim-lang/Nim#9358]
```
import smtp
newAsyncSmtp()
```
leads to:
```
Error: unhandled exception: /build/nim-UtAWG3/nim-0.19.0/compiler/suggest.nim(462, 12) `result == nil or result.kind == nkPragma`  [AssertionError]
```

Also see https://api.travis-ci.org/v3/job/441072469/log.txt

**Comment by skilchen** [comment]
There are two things:
- instead of raising a runtime exception when ssl is required, but the program was compiled without `-d:ssl`, `smtp.nim` now uses the error pragma to signal a missing `-d:ssl` at compiletime. This has the consequence that you now must compile with `-d:ssl` even if you pass `useSsl = false` to the constructors `newSmtp` or `newAsyncSmtp`.
- the error you are seeing is the current way, how Nim tells you that you compiled without `-d:ssl`

Before commit 548fc778 Nim would  tell you
```
Error: invalid pragma: error: "SMTP module compiled without SSL support"
```

**Comment by Araq** [comment]
That's a compiler bug, the ``.error`` statement must not be treated as an ``.error`` proc annotation.
