### ISSUE TITLE
Jsondoc0 doesn't output module comments.

### ISSUE THREAD

**Issue by flenniken** [nim-lang/Nim#9364]
https://nim-lang.org/docs/docgen.html

The docgen0 example from the documentation above shows the json output contains the module comment from the top of the sample source file.  Running the example in 0.19.0 this module comment does not appear in the json.

**Comment by PMunch** [comment]
Seems to have been a strange bug, essentially it was double checking if the comment started with `##` so the below example would work:

```
## ## This is a module description
```
There was also a bug were it used the `jsondoc` syntax for these comments (with line numbers etc.). All of this, along with some other things, have been fixed in #9396
