### ISSUE TITLE
We need better temporary file and dir API

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9372]
- [x] `getTempDir` ; EDIT: solved by #16914
`getTempDir` comes with a warning `Please do not use this` and indeed its implementation should be replaced (or alternatively, deprecated for another proc if backward compatibility is an issue) by something more robust.
* We can draw some inspiration from https://github.com/dlang/phobos/blob/v2.082.1/std/file.d#L5169 ; in particular on windows:
`calling the Windows API function GetTempPath.` (https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-gettemppatha) instead of `string(getEnv("TEMP")) & "\\"`
* on android, instead of `getHomeDir()`, https://stackoverflow.com/questions/2364740/where-is-the-temp-folder-in-android-device points to `/data/local/tmp` or `getCacheDir()`

- [x] temporary file and dir creation; EDIT: see https://github.com/nim-lang/Nim/pull/17361
There's, in posix, `proc mkstemp*(tmpl: cstring): cint` but that's posix only and too low-level (eg see accompanying warning to it)

Shopping around for alternatives, python has nice standard library [library](https://docs.python.org/3/library/tempfile.html) with low level and high level API around temp file/dir creation, including facilities for cleanup, and with epmhasis on security (eg see description around TemporaryFile).

We could start with porting these:
```py
tempfile.mkstemp(suffix=None, prefix=None, dir=None, text=False)
# returns a tuple containing an OS-level handle to an open file (as would be returned by os.open()) and the absolute pathname of that file, in that order.

tempfile.mkdtemp(suffix=None, prefix=None, dir=None)
```

Note: the D variant (https://dlang.org/library/std/stdio/file.tmpfile.html) is not as convenient as it returns a File object (and no way to access its name)

## links
* http://www.cplusplus.com/reference/cstdio/tmpfile/
* http://www.cplusplus.com/reference/cstdio/tmpnam/
* https://dlang.org/library/std/stdio/file.tmpfile.html
* https://dlang.org/library/std/file/temp_dir.html
* people requiring it on IRC: https://gitter.im/nim-lang/Nim?at=5bc394d482893a2f3bdfae3d 
> no direct cross-platform convenience mktemp-like method yet

* [OpenSystemsLab/tempfile.nim: This module contains basic procs for creating temporary files and directories](https://github.com/OpenSystemsLab/tempfile.nim)
* [temp file api · Issue #195 · timotheecour/Nim](https://github.com/timotheecour/Nim/issues/195)

**Comment by timotheecour** [comment]
ah, thanks! but definitely some points in this issue should be addressed. in the eternal debate of 'batteries included or not', I feel temp file creation should be part of stdlib because it's generally useful AND because it's likely to be used in Nim repo itself (eg a lot of tests should use tempfile creation instead of what's being done currently:

$nimc_D/tests/stdlib/tparsecfg.nim
config.writeConfig("test.ini")
which dumps to current working dir and complicates .gitignore

**Comment by timotheecour** [comment]
note: https://github.com/OpenSystemsLab/tempfile.nim has limitations, eg:
* it itself uses `getTempDir()` which is marked as "do not use"
* it can't be used at CT, see https://github.com/OpenSystemsLab/tempfile.nim/issues/9

**Comment by hyao** [comment]
Python tempfile implementation:
https://docs.python.org/3.7/library/tempfile.html

**Comment by pb-cdunn** [comment]
Ironically, **nimble** itself uses `getTempDir()`.

* https://github.com/nim-lang/nimble/issues/80

**Comment by cup** [comment]
These?

- https://nim-lang.github.io/Nim/posix_utils#mkstemp,string
- https://nim-lang.github.io/Nim/posix_utils#mkdtemp,string

**Comment by sschwarzer** [comment]
>     * https://nim-lang.github.io/Nim/posix_utils#mkstemp,string
>     * https://nim-lang.github.io/Nim/posix_utils#mkdtemp,string

Yes, these seem to be Posix-only. I just find myself in the situation where I want to adapt a program that I developed under Linux to Windows.

**Comment by cup** [comment]
@sschwarzer yeah ok, but `mkstemp` works fine even on Windows. and if youre going that route, then youll need to throw out PHP and other too, as they can only create temp files and not directories either.

**Comment by sschwarzer** [comment]
> @sschwarzer yeah ok, but `mkstemp` works fine even on Windows. and if youre going that route, then youll need to throw out PHP and other too, as they can only create temp files and not directories either.

That's interesting, thank you. I had assumed that things in the `posix` module would only work on Posix platforms. Anyway, I need `mkdtemp`.

I agree with @timotheecour that creating temporary directories and files should be in the Nim standard library. I'll probably go with the external [tempfile library](https://github.com/OpenSystemsLab/tempfile.nim) for now that was mentioned above. I had considered working on `mkdtemp` and `mkstemp` in the standard library, but at the moment I don't have the time. :-/

(Regarding PHP, I haven't used it in years, although not specifically because of the temp directory omission but because I didn't have a project where I'd use PHP.)

**Comment by maxgrenderjones** [comment]
I'm a git/github newbie so please be gentle, but have just opened nim-lang#14347 to get support for `mkstemps`.

```nim
template withTempFile(prefix: string, suffix: string, code: untyped): untyped =
    let (filename, tempfile {.inject.}) = mkstemp(prefix, suffix)
    let tempfilename {.inject.} = absolutePath(filename)
    try:
        code
    finally:
        removeFile(tempfilename)
```

Is the user-friendly version of the same, but I don't know if that has the cross-platform support it would need to go into `os`. (I'm on OSX where the temp file seems to get created in the current directory, so I'm not sure what happens if `TMPDIR` is set to something else - I'm not sure what you need to do to get the `absolutePath` in a way that works on all OSes - [generic way to get temp path](https://unix.stackexchange.com/questions/352107/generic-way-to-get-temp-path) suggests that you'd need to change the call to the posix `mkstemp` to ensure that the file is created a well-known place that honours `TMPDIR`. [tempfile.py](https://github.com/python/cpython/blob/3.8/Lib/tempfile.py) may be instructive (seems they just try a bunch of directories until one succeeds).

**Comment by kaushalmodi** [comment]
May be https://github.com/OpenSystemsLab/tempfile.nim should be made part of fusion ( https://github.com/nim-lang/fusion ) if the author allows? /cc @OpenSystemsLab @ba0f3

**Comment by ghost** [comment]
@kaushalmodi well with MIT you don't really need permission, just need to keep the license, but yeah, it would be a nice thing to ask :)

**Comment by ba0f3** [comment]
@kaushalmodi why not :grinning:

**Comment by kaushalmodi** [comment]
@ba0f3 Thanks. With your approval, now we need to figure out how to proceed. @Araq ?

**Comment by timotheecour** [comment]
just create a PR against fusion ?
