### ISSUE TITLE
Nim should be able to generate a theindex.json

### ISSUE THREAD

**Issue by rayman22201** [nim-lang/Nim#9462]
### Summary
This is to track this feature that I am working on with @timotheecour 
The discussion of this feature has been spread over a few places, so I'm using this issue as a centralized place to organize all the thoughts / progress.

### Description
* there is no theindex.json created currently. (The jsondoc doc command does not do this, and the idx data is not exposed in json format anywhere atm)
* This functionality needs to be added, and should be part of the core compiler.
* There is no reason jsondoc should not have this since regular doc has this, and they should probably mirror each other where reasonable.
* it's needed to fix issues with the doc search functionality.

My plan is to use the .idx files to generate a theindex.json file, using the same exact technique
used to generate theindex.html
This functionality can be exposed by a flag on `nim buildIndex`

### Alternatives
There are strong arguments to remove json output (and possibly doc generation as a whole) from the core compiler completely, and have doc generation be moved to an external nimble project or at least a separate module that is powered by the compiler api or the nimsuggest api.
@see https://github.com/nim-lang/Nim/issues/9431
 
But theindex.json is needed as a short term solution to some important doc search bugs, and it makes the current state of the compiler more complete imo. (It makes no sense that jsondoc doesn't have this feature when regular doc generation does)

### Additional Information
https://github.com/nim-lang/Nim/pull/9396 -> clarifying info from @PMunch who has done some work with maintaining jsondoc
https://github.com/nim-lang/Nim/issues/9431 -> discussion of doc search architecture
https://irclogs.nim-lang.org/20-10-2018.html#00:36:03 -> irc discussion with @timotheecour 

Bugs that would be fixed by this feature:
https://github.com/nim-lang/Nim/issues/9147
https://github.com/nim-lang/Nim/issues/9198
https://github.com/nim-lang/Nim/issues/9406

**Comment by PMunch** [comment]
I personally like the fact that documentation is available through the compiler, and that you can get a proper machine readable version of it as well. Would be a shame if this functionality moved into it's own package. That being said generation of theindex and similar derivatives of the compiler output I'd be fine with having in a separate package.

**Comment by rayman22201** [comment]
I think are good arguments on both sides.

It's nice to have documentation built in from a user perspective, it's the same reasoning behind arguments for a large standard library. It's user friendly and "batteries included".

The cost from the compiler perspective is more code to maintain along with the compiler itself, with disadvantages such as being tied to the release cadence of the main compiler. 
Araq always talks about making the compiler smaller where possible, and this would help in that regard. 

Separating doc generation would also be a good way to ensure that the compiler-api is well tested and documented, because it would have important consumers that rely on it. This is one way to encourage the compiler maintain more modular architecture. Of course, this same argument can be applied to other core tooling such as nimsuggest and nimpretty.

> That being said generation of theindex and similar derivatives of the compiler output I'd be fine with having in a separate package.

I think this is a weird place to draw the line.

From a user perspective, I expect to get some kind of index with my docs. That is a standard practice. Especially in machine readable form. If I want to make a tool based on the machine readable doc output, an index is extremely useful to me.

From a code architecture standpoint, an index is highly semantically coupled to code parsing and doc generation, so why would that be separated?

**Comment by PMunch** [comment]
Well, my reasoning is a such. The compiler knows best what is a documentation comment and what is not, it's a part of the compilation process to grab this information. Decoupling the documentation generation from the compiler would mean that a slight change in syntax of the language might break documentation generation. This is guaranteed to not be the case when it's coupled with the compiler.

Why I drew the line at the index is because running `nim doc` on a module will grab all the relevant documentation from the Nim file, and with `--index:on` will generate a computer-readable index file. All the `buildIndex` command does is read these files and generate a derivative product based on this output. The compiler no longer has an advantage over any other tool when it comes to doing this, as long as the output of the compiler is consistent, or at least backwards compatible.

> If I want to make a tool based on the machine readable doc output, an index is extremely useful to me.

And that index could just as easily be generated from what the compiler already outputs, it doesn't actually need to know anything about Nim at all (just try to copy the .html and .idx file to another directory and run `nim buildIndex .` in there, should give you exactly the same result). My point is that the Nim compiler should work with Nim code, documentation is part of the Nim syntax, so it makes sense that the compiler knows what to do with it. But the output .html and .idx files aren't Nim specific, so the Nim compiler doesn't really need to know anything about them.

But I do see how the index file can be useful (not that I've ever used it myself though), so I'm not saying we should remove it. But if we are to remove something, then the index generation should go before documentation in general.

**Comment by rayman22201** [comment]
> ll the buildIndex command does is read these files and generate a derivative product based on this output.

@PMunch ah, OK! I understand your reasoning now based on the output of the .idx files.

> The compiler knows best what is a documentation comment and what is not, it's a part of the compilation process to grab this information.

This is a good argument.

My counter argument is that keeping the doc generation internal allows doc generation to benefit (because it "cheats" by being intertwined with the compiler internals), while the compiler api can be left behind and not updated. 

Extracting doc generation could be used as incentive to keep the compiler api up to date, which benefits external tools in general, and acts as incentive to keep the compiler more modular.... in theory....

There are good arguments on both sides. I'm just playing devils advocate for discussion sake. You are being a good sport for arguing with me @PMunch :-)

This is all theoretical anyway. I'm not advocating any big changes at this point and I don't want to "beat a dead horse" so to speak.

@timotheecour I promise I am actually working on index.json generation and not just arguing with people on github. I should have a PR by the weekend.

**Comment by timotheecour** [comment]
lol haha ok awesome! thanks :)

**Comment by andrewbriggs** [comment]
@rayman22201 Oh you're a peach son.

**Comment by timotheecour** [comment]
@rayman22201 friendly ping
