### ISSUE TITLE
[WONTFIX] nimpretty infers wrong indentation

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9512]
```nim
proc foo_verylong_verylong_verylong_verylong_verylong_verylong_verylong(a1 = 1,
    a2 = "asdfasdf", a3 = "asdfasdf"): auto =
  discard
```
nimpretty indents as:
```nim
proc foo_verylong_verylong_verylong_verylong_verylong_verylong_verylong(
        a1 = 1,
    a2 = "asdfasdf", a3 = "asdfasdf"): auto =
    discard
```
(ie, it wrongly inferred indentation of 4, whereas it was 2)

EDIT: s/margin/indentation/ (was a typo)

**Comment by timotheecour** [comment]
it does:
this diff:
```
diff --git a/compiler/layouter.nim b/compiler/layouter.nim
index 9f9b6fc8e..fe6125d7e 100644
--- a/compiler/layouter.nim
+++ b/compiler/layouter.nim
@@ -43,6 +43,7 @@ proc openEmitter*(em: var Emitter, cache: IdentCache;
   let fullPath = Absolutefile config.toFullPath(fileIdx)
   em.indWidth = getIndentWidth(fileIdx, llStreamOpen(fullPath, fmRead),
                                cache, config)
+  echo ("em.indWidth:", em.indWidth)
   if em.indWidth == 0: em.indWidth = 2
   em.config = config
   em.fid = fileIdx
```

produces this output:

(Field0: "em.indWidth:", Field1: 4)

**Comment by Araq** [comment]
It infers the indentation, not the "margin".

**Comment by timotheecour** [comment]
duh... was a typo; i meant indentation

**Comment by dom96** [comment]
Why close this? It seems like a genuine bug

**Comment by timotheecour** [comment]
@dom96  because of this comment from @narimiran https://github.com/nim-lang/Nim/pull/10629#issuecomment-463124842

> Btw, sorry to be blunt, but I will not consider/review your PRs until the count of your open issues is above 150. Close some least important ones (which affect the least amount of Nim users), this will show some good will from your side, and then I'll change my mind.

I went through all my open issues and they're all valid (IMO), but I had to reduce to < 150 or to avoid this stalemate.

**Comment by krux02** [comment]
@timotheecour Please show some respect. You are supposed to reduce your issues to set priorities on them. They are not all valid. I am sure I can find some that are invalid or written in a very obscure way that I have no idea what the real problem is. But the point is, you should do it and don't continue to waste our time on it. Only keep the important and issues open and close the issues that are not important. Then it would be really nice of you, when from the other 144 issues if you would check if they conform the issues template and rework them to make them easier processable. You still have 144 issues from 1256 issues in total. That is more that 10% from you alone.
