### ISSUE TITLE
wrong error messages (undeclared identifier) on type mismatch of another error when untyped followed by typed params

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9620]
In the same vein as #9414, using a parameter constraint like {lvalue} does not work with identifier injection.

Test case:

```Nim
template forLoop*(index: untyped, length: int{lvalue}, body: untyped) =
  for `index`{.inject.} in 0 ..< length:
      body

var x = newSeq[int](10)

forLoop(i, x.len):
  x[i] = i
```

`Error: undeclared identifier: 'i'`

Removing the lvalue constraint makes the code compile.

**Comment by timotheecour** [comment]
`x.len` is not an lvalue so the code isn't valid; the problem here is that the error message is wrong.

reduced:
```nim
when true:
  # Error: undeclared identifier: 'i'
  template fn(index: untyped, length: int{lvalue}, body: untyped) = discard
  var x = @[1]
  fn(i, len(x)): discard
```

further reduced, which shows title is wrong:
```nim
when true:
  template fn(a: untyped, b: int) = discard
  fn(nonexistant, 1.0)
```

this is a consequence of current sigmatch implementation for untyped params, which trigger semcheck for untyped params when not all arguments are untyped (IIUC this used to be what immediate templates were).

see also: https://nim-lang.github.io/Nim/manual.html#overloading-resolution-lazy-type-resolution-for-untyped
and https://nim-lang.github.io/Nim/manual.html#templates-typed-vs-untyped-parameters

this is related to https://github.com/nim-lang/Nim/issues/14827 but definitely different
