### ISSUE TITLE
Searching for "File" class does not show up in results

### ISSUE THREAD

**Issue by accidentalrebel** [nim-lang/Nim#9621]
I tried searching for "File" using the search bar in the website. I was expecting it would return the file class and it's available functions but it returned this:

`FileMode.fmAppend
FileMode.fmRead
FileMode.fmReadWrite
FileMode.fmReadWriteExisting
FileMode.fmWrite
FilePermission.fpGroupExec
FilePermission.fpGroupRead
FilePermission.fpGroupWrite
FilePermission.fpOthersExec
FilePermission.fpOthersRead
FilePermission.fpOthersWrite
FilePermission.fpUserExec
FilePermission.fpUserRead
FilePermission.fpUserWrite
FileSeekPos.fspCur
FileSeekPos.fspEnd
FileSeekPos.fspSet
os: fileExists(filename: string): bool
os: FileId`

I had to go through The Index and search through it to learn that it's actually under 'system:File'.

I tried searching for "Document" and it was able to list it in the search results. So I'm not sure why it could not find File but it could find Document.

**Comment by narimiran** [comment]
I tried to reproduce and I get this:

![https://imgur.com/NdJEm6O.png](https://imgur.com/NdJEm6O.png)

It would be nice if it was at the top, but at least it is here (in Nim devel it is in `system/io.nim`).

I've tried other stuff from `system.nim` and I was able to see the results so it seems this has been fixed in the mean time.
