### ISSUE TITLE
+-*/ can not be applied to <int, float64>

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#9681]
I am using the lasted-cloned-build nim with MSYS2 on windows 64bits
```bash
$ nim --version
Nim Compiler Version 0.19.9 [Windows: amd64]
Compiled at 2018-11-11
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 37d88e5168508870d69a990e5002a9ea113843f9
active boot switches: -d:release
```

the following code
```nim
var
    a = 442
    b = 0.7

echo 442*0.7
```
can be compiled and run as expected

however, when I compile this one
```nim
var
    a = 442
    b = 0.7

echo a*b  # or echo b*a
```
I get
```bash
a.nim(5, 7) Error: type mismatch: got <int, float64>
but expected one of:
proc `*`(x, y: int64): int64
  first type mismatch at position: 2
  required type: int64
  but expression 'b' is of type: float64
proc `*`(x, y: int): int
  first type mismatch at position: 2
  required type: int
  but expression 'b' is of type: float64
7 other mismatching symbols have been  suppressed; compile with --showAllMismatches:on to see them

expression: a * b
```
yes, I do know we can use `float(a)*b`

**Comment by retsyo** [comment]
obviously, this will fail to be compiled too
```nim
var
    a:int = 442
    b:float64 = 0.7

#~ echo a*b
echo a/b
```

**Comment by alaviss** [comment]
This is to be expected afaik. We don't have operators for `+`, `-`, `*`, `/` between `int` and `float`. You can import [`lenientops`](https://nim-lang.github.io/Nim/lenientops.html) module to get those.

The reason why this:

```nim
echo 442*0.7
```

works is because the compiler automatically promotes `442` to `float`, which makes sense in the context. I believe it's documented somewhere within the Manual.

**Comment by narimiran** [comment]
This works as intended.

**Comment by dom96** [comment]
Yep. This is the expected behaviour. It is a little annoying but there are safety-related reasons for it.
