### ISSUE TITLE
Open the commented proc will refresh recv loop rapidly .

### ISSUE THREAD

**Issue by gogolxdong** [nim-lang/Nim#9705]
It's blocked until opening the commented proc .
```nim
import nativesockets, os

let sockfd = createNativeSocket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)
defer: sockfd.close()

var peer = getAddrInfo("0.0.0.0", Port 1234, sockType = SOCK_DGRAM, protocol = IPPROTO_UDP)
if sockfd.bindAddr(peer.ai_addr, SockLen peer.ai_addrlen) < 0i32:
    let err = osLastError()
    freeAddrInfo(peer)
    raiseOSError(err)

const cap = 10
var buf : array[10, byte]

# proc toStr*(a: openArray[byte]): string =
#     result = newString len a
#     for idx, val in a:
#       result[idx] = char val

while true:
    var bytes = recv(sockfd, addr buf , cap, 0)
    echo buf
```

**Comment by gogolxdong** [comment]
updated, can you reproduce?

**Comment by skilchen** [comment]
One could argue that it is your coding style causing troubles here. 
Mixing toplevel executable statements and procedure definitions is probably not a good idea.
Your mixed in definition of `toStr` triggers the `defer` (which IMHO shouldn't be allowed at the toplevel).
The `defer` closes the socket and you are therefore `recv`ing nothing indefinitely.
(On an UDP socket it would be better to use `recvFrom`, but that is not the problem here.)

Wrapping your toplevel statements in a main procedure solves your problem:
```nim
import nativesockets, os

proc toStr*(a: openArray[byte]): string =
  result = newString len a
  for idx, val in a:
    result[idx] = char val

proc main() =
  let sockfd = createNativeSocket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)
  defer: sockfd.close()

  var peer = getAddrInfo("0.0.0.0", Port 1234, sockType = SOCK_DGRAM, protocol = IPPROTO_UDP)
  if sockfd.bindAddr(peer.ai_addr, SockLen peer.ai_addrlen) < 0i32:
    let err = osLastError()
    freeAddrInfo(peer)
    raiseOSError(err)

  const cap = 10
  var buf : array[10, byte]

  while true:
    var bytes = recv(sockfd, addr buf , cap, 0)
    echo "buf: ", buf
    echo "str: ", toStr(buf)
    
main() 
```

**Comment by gogolxdong** [comment]
Yes, wrapping in a proc works, but it doesn't prevent what I wrote from happening. Tried any proc instead of toStr,  refreshing essentially lies in toplevel defer .

**Comment by skilchen** [comment]
>The defer closes the socket and you are therefore recving nothing indefinitely.

Actually calling `recv` on a closed datagram socket immediately returns -1 to signal an error. I should have written: the `defer` closes the socket and you will therefore get an error forever.

In the [manual](https://nim-lang.org/docs/manual.html#exception-handling-defer-statement) we have:
Top level **defer** statements are not supported since it's unclear what such a statement should refer to.

**Comment by ringabout** [comment]
Now `defer: sockfd.close()` gives CT error: Error: defer statement not supported at top level which works as expected.

Moving `defer` statement to procs does work.
