### ISSUE TITLE
Early block returns

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#9711]
It would be nice if you could return values from expression blocks early. Currently, because only the last statement inside a block can be the result value some patterns are more verbose than they need to be.

A silly example of what it could look like:
```nim
let x = block:
  while true:
    break "foo"
```
Instead of this:
```nim
let x = block:
  var result: string
  while true:
    result = "foo"
    break
  result
```

**Comment by mratsim** [comment]
How often would this be used, is there a niche that would use this a lot?

Because you can already break to named blocks:

```Nim
var a = 1
block myblock:
  block foo:
    break myblock
  a = 2
echo a
```

If there are conflict between variable names and block names your proposition will cause confusion. That means that the compiler will need to add block namespaces into normal identifiers namespaces. I'm not sure it's done this way currently.

**Comment by Araq** [comment]
Instead of more ``break``, we need more structured programming.
