### ISSUE TITLE
` Warning: fun is deprecated` doesn't check whether deprecated overload is actually used

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9759]
```nim
#[
code below give ` Warning: fun is deprecated` but shouldn't, since we're using
the non-deprecated overload
]#

proc fun(a: string) {.deprecated.} = echo "ok1"
proc fun(a: int) = echo "ok2"

proc bar(fun: proc(a:int):void)=
  fun(1)

# Warning: fun is deprecated
bar(fun)
```

**Comment by krux02** [comment]
Well I found where the bug is introduced:
https://github.com/nim-lang/Nim/blob/f8fa94cb20672fc517d2621bbe3fce622ae76bce/compiler/semexprs.nim#L2347

qualifiedLookup returns a symbol of the first symbol with that name "fun". 

https://github.com/nim-lang/Nim/blob/f8fa94cb20672fc517d2621bbe3fce622ae76bce/compiler/semexprs.nim#L2349
This symbol then gets a sem check, where the deprecartion warning is created. Only afterwards the symbol is actually transformed into a sym choice:
https://github.com/nim-lang/Nim/blob/f8fa94cb20672fc517d2621bbe3fce622ae76bce/compiler/semexprs.nim#L2352

I don't know what to do about it.
