### ISSUE TITLE
unicode.nim Error: type mismatch: got <seq[char]> but expected 'string'

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#9762]
Happens with `--os:standalone --gc:none` flags.
```nim
# test.nim
import unicode
```
```nim
# panicoverride.nim
proc rawoutput(s: string) = discard
proc panic(s: string) = rawoutput(s)
```
```
nim c --os:standalone --gc:none test.nim
```
```
Hint: used config file '/home/yglukhov/Projects/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
Hint: unicode [Processing]
Projects/nim/lib/pure/unicode.nim(255, 3) Error: type mismatch: got <seq[char]> but expected 'string'
```

**Comment by deech** [comment]
I wanted to take a stab at this issue to get my feet wet with the Nim codebase.

The reason this compiler error is occurring is that when `--gc:none` is passed in [`string` slice operations in `unicode.nim`](https://github.com/nim-lang/Nim/blob/devel/lib/pure/unicode.nim#L261) resolve to [the `openarray` implementation of slicing](https://github.com/nim-lang/Nim/blob/devel/lib/system.nim#L3748) which returns a `seq[char]`. The typechecker cannot unify `seq[char]` with `string` and fails.

I had a hard time figuring out why `string` was being coerced `openarray` but it seems to be happening [in `sigmatch.nim`](https://github.com/nim-lang/Nim/blob/devel/compiler/sigmatch.nim#L1239).

So I have some idea why this issue is happening but no idea how to go about fixing it so if someone can offer some guidance I'm happy to work on a PR.

**Comment by exelotl** [comment]
Hey, has anyone made any progress with this? It's rendering large portions of the standard library unusable for embedded programming, when they really should be usable 😅

**Comment by Araq** [comment]
Don't use ``--os:standalone --gc:none``, use instead ``--os:standalone --gc:regions`` or whatever. Embedded programming has nothing to do with gc:none (which is misdesigned and needs to die).

**Comment by exelotl** [comment]
@Araq Currently `--gc:none` is the only option that works for me, because every other GC option results in large quantities of TNimNode being created in stdlib_system.c (even when my source program is totally empty). I'm dealing with just 32k RAM. Under `--gc:regions` my program won't even link because the toolchain recognises that its static memory requirements would be too high.

Should I file an issue for this? Or am I missing some option that would fix everything?

**Comment by Araq** [comment]
Yup, these should be optimized out.
