### ISSUE TITLE
odbcsql module has some wrong integer types

### ISSUE THREAD

**Issue by gpdnet** [nim-lang/Nim#9771]
In the odbcsql module the type of TSqlInteger and SqlUinteger seems to be wrong. Both are defined as type int, but with nim on 64 bit systems this is 64 bits. In C this is also defined as int, but in C, int is still 32 bits even on 64 bit systems (normally). This causes alignment problems in some struct definitions, particularly SQL_TIMESTAMP_STRUCT where the Fraction member is defined as SqlUInteger and doesn't get populated properly as it's the wrong size and possibly the wrong alignment. I think that TSqlInteger and SqlUInteger, perhaps others also, need redefining to specify int32 to match the C definitions.

**Comment by coffeepots** [comment]
Just wanted to add that this issue was stopping me fetch the nanosecond portion of datetimes in the odbc library.

Sure enough, in `SQL_TIMESTAMP_STRUCT`, using `int32` instead of `int` for the `Fraction` field fixes the problem in x64.

However reworking `odbcsql` might not be so straightforward, as on x64 systems simply replacing the definition of `TSqlInteger` with `int32` means every `odbcsql` proc that takes that type will no longer work with `int` without specifying as `myParam.int32`, which is somewhat onerous.

**Comment by gpdnet** [comment]
Hmm, maybe it's only necessary to sort out any structs that use TSqlInteger or SqlUInteger? I'm not sure how the nim->C interface behaves with ordinary (ordinal) parameters if C is expecting a 32 bit int, but gets passed a 64 bit int. It *seems* to work with this, but I'm not sure if there will be other subtle issues elsewhere.

**Comment by Araq** [comment]
No, the types need to reflect what C does. Let's just fix it.
