### ISSUE TITLE
Suggestion: rename "User defined type classes"

### ISSUE THREAD

**Issue by exetoc** [nim-lang/Nim#990]
We already have "type classes", so I suggest that we rename the "user defined type classes" feature. Someone suggested "traits", which I do like for these reasons:

+ It accurately describes the feature
+ It's common
+ It's not ambiguous
+ It's short

Also, I suggest that we then rename the "generic" keyword to "trait".

**Comment by filcuc** [comment]
I like contract

**Comment by Araq** [comment]
I think it should be 'concept':

 

Firstly, C++'s influence on this feature is undeniable.

Secondly, I think the term leaves the door open for more dynamic behaviour. (Litmus test: Does it allow heterogenous containers as in 'sequence of Concepts'?)

Thirdly, it is not a compound noun; these are IMHO nicer as keywords (as opposed to "typeclass")

 

Gesendet: Donnerstag, 05. Februar 2015 um 10:00 Uhr
Von: "Filippo Cucchetto" <notifications@github.com>
An: Araq/Nim <Nim@noreply.github.com>
Betreff: Re: [Nim] Suggestion: rename "User defined type classes" (#990)


I like contract

**Comment by reactormonk** [comment]
I vote for typeclass.You can implement heterogeneous lists with them. http://hackage.haskell.org/package/HList https://github.com/milessabin/shapeless/wiki/Feature-overview:-shapeless-2.0.0#heterogenous-lists

**Comment by dustinlacewell** [comment]
I think 'constraint' is also pertinent. But I do think that 'typeclass' is
perfectly cromulent.

**Comment by kirbyfan64** [comment]
Well...

- *contract* sounds a lot like D's completely unrelated feature.
- Nim's type classes seem a bit different from Haskell's, so I vote against that.
- *contraint* is usually used to refer to the required protocol/type class/whatever on a variable, so another -1.
- *generic* sounds like you're created a templated type. -1.
- *interface* sounds more like Java's cheap alternative to multiple inheritance.
- *trait* probably would confuse newcomers, as @fowlmouth said.

I think the best choices would be *concept* and *spec*. *Concept* does make sense, since Nim's type classes currently remind me of a mix of C++11's proposed concepts and axioms (which are part of concepts anyway). *Spec* sounds neat, but it would introduce technical words that nobody else uses.

+1 for concept, +0.5 for spec.

**Comment by reactormonk** [comment]
We're calling them concepts now.
