### ISSUE TITLE
`inc` and `+=` have inconsistent function signatures

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#9931]
https://github.com/nim-lang/Nim/blob/a8b53c97ee041bc02862b17a6b7cf70546979a6e/lib/system.nim#L3836

https://github.com/nim-lang/Nim/blob/a8b53c97ee041bc02862b17a6b7cf70546979a6e/lib/system.nim#L724

Not sure which one is the right one, but this causes several problems when trying to figure out which one to use:

* semantics are confusing - I could not find a description of integer handling assumptions in the manual or elsewhere (two, one complement.. or "whatever c does"?)
* `inc`, as specified, requires that 'y' is an `int` even when `T` is something else - from what I remember of the `C` gen it just sprinkles `NI` casts liberally which might be surprising if you want to `inc` a `uint8`
* the difference in documentation is also hard to explain
* what's an `Ordinal` actually and why doesn't it include `uint64`? why does `+=` include `uint64` but `Ordinal` does not?

**Comment by arnetheduck** [comment]
* what's `SomeOrdinal` and how is it different from `Ordinal`?

**Comment by Clyybber** [comment]
@arnetheduck It is the same, except that it includes enums with holes.

**Comment by dom96** [comment]
I really really wish `+=` (et al) would work for any type that has a `+` operation defined. I really really don't want to define `inc`, `+=`, `+`, and the same for `*`, `-`, `/` every time I create a new type.

I feel like I've mentioned this multiple times now. Can we please fix this in a generic way once and for all?

**Comment by arnetheduck** [comment]
@Clyybber yeah, I know what the definitions in Nim are - by _why_ do both exist / what's the intent?

**Comment by Araq** [comment]
@dom96 That's a different issue and the reply still is "it's way more efficient to express ``+`` in terms of ``+=`` rather the other way round".

**Comment by Araq** [comment]
To answer the question, ``inc`` is for incrementing an ordinal with an integer, for example ``var x = january; inc x, 2; assert x == march``

``x += y`` is the usual shortcut for ``x = x + y``

**Comment by GULPF** [comment]
> @dom96 That's a different issue and the reply still is "it's way more efficient to express + in terms of += than the other way round".

With concepts couldn't it be done both ways? Implement `+` using `+=` if only `+=` exists, implement `+=` using `+` if only `+` exists, implement nothing if neither or both exists.

**Comment by Clyybber** [comment]
@GULPF I think thats the best way, a `+=` that leverages internal optimizations, as we have now, and a generic `+=` that uses `+`.
AFAIK the overloading resolution is smart enough to choose the former over the latter where appropriate, so we don't have to use concepts either.

**Comment by Clyybber** [comment]
@dom96 @GULPF Placing this in system.nim works perfectly, as far as my testing goes:
```
type
  Addable = concept x, y
    (x + y) is x.type
  Subtractable = concept x, y
    (x - y) is x.type
  Multipliable = concept x, y
    (x * y) is x.type
  Dividable = concept x, y
    (x / y) is x.type

proc `+=`*(x: var Addable, y: Addable) {.noSideEffect.} =
  ## Increments anything
  x = x + y

proc `-=`*(x: var Subtractable, y: Subtractable) {.noSideEffect.} =
  ## Increments anything
  x = x - y

proc `*=`*(x: var Multipliable, y: Multipliable) {.noSideEffect.} =
  ## Increments anything
  x = x * y

proc `/=`*(x: var Dividable, y: Dividable) {.noSideEffect.} =
  ## Increments anything
  x = x / y
```
@Araq Are we ready to use concepts in the stdlib/system.nim?

**Comment by Clyybber** [comment]
@andreaferretti Yeah, I left out the viceversa part, because I'm not sure if "it's way more efficient to express + in terms of += than the other way round" applies to types not supplied by the compiler.

**Comment by dom96** [comment]
You don't even need concepts here as far as I can tell. Concepts are just a refinement of generics, you can easily create a generic proc for this:

```nim
proc `+=`*[T, Y](x: var T, y: Y) =
  x = x + y
```

And it will work as long as there is a `+` defined on the type.

Personally I'm still not comfortable having concepts in the stdlib and they don't really add that much here IMO.


----

> @dom96 That's a different issue and the reply still is "it's way more efficient to express + in terms of += than the other way round".

It's way more efficient to just get the "good enough" solution which is what I've suggested above, than to make everything efficient. Having hundreds PRs which add these noisy procedures is a waste of time.

Also, I think the ship to get people to define `+=` instead of `+` has sailed by now.

**Comment by narimiran** [comment]
Related: https://github.com/nim-lang/Nim/issues/7173

**Comment by krux02** [comment]
It took me a while as well to understand the difference. In my code I always used `+=` while the standard library really prefers `inc` over `+=`. 

Even though both `inc` and `+=` do practically exactly the same, the concept is a bit different. The idea behind ``inc`` is to increment anything. This includes enum values. The offset is then specified by an integer, but it thas the default to 1. So ``inc`` is really made for while loops and iterators, while ``+=`` is really meant for addition where both argument types are the same. This won't work for enums as adding two enum values doesn't really work.

I hope I could clear the question. I am closing this issue now though as it is more a question rather than a real issue description.
